### ISSUE TITLE
Better error for config type mistake

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1012]
When first learning how instantiating a solid definition works, it's easy to write something like the following, forgetting to wrap your config `Dict` instance in a `Field`: 

```
config = Dict(fields={ ... })
SolidDefinition(..., config_field = config)
```

This results in the stack trace:

```
Traceback (most recent call last):
...
  File "/Users/nate/src/dagster/python_modules/dagster/dagster/core/definitions/solid.py", line 76, in __init__
    self.config_field = check_opt_field_param(config_field, 'config_field')
  File "/Users/nate/src/dagster/python_modules/dagster/dagster/core/types/field_utils.py", line 36, in check_opt_field_param
    return check.opt_inst_param(obj, param_name, FieldImpl)
  File "/Users/nate/src/dagster/python_modules/dagster/dagster/check/__init__.py", line 163, in opt_inst_param
    raise_with_traceback(_param_type_mismatch_exception(obj, ttype, param_name))
  File "/Users/nate/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
dagster.check.ParameterCheckError: Param "config_field" is not a FieldImpl. Got <class 'dagster.core.types.field_utils.Selector.<locals>._Selector'> which is type <class 'type'>.
```

Which leaks the internal `FieldImpl`. Might be good to replace this stack trace with a more helpful error message to the user, e.g. "config_field is a `Dict`, not a `Field`. Did you forget to enclose the config in a `Field`? See <<docs link here>>"

**Comment by schrockn** [comment]
Fixed in https://github.com/dagster-io/dagster/pull/1086
