### ISSUE TITLE
Improve end-user type system documentation

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1013]
When I was first learning how to write my own `SolidDefinition`, I didn't have a good idea of what built-in types already existed, e.g. `Path`.

We should flush out this page further: https://dagster.readthedocs.io/en/0.3.5/apidocs/types.html with more information about what the built-in dagster types are and how to use them.

One example of this: I didn't have a good idea of what the different types were, and wanted to use an enumeration in my config specification. grepped the codebase, saw `ConfigEnum`, and used that, resulting in 

```
Traceback (most recent call last):
...
  File "/Users/nate/src/dagster/python_modules/dagster/dagster/core/types/field.py", line 48, in Field
    res = resolve_to_config_type(dagster_type)
  File "/Users/nate/src/dagster/python_modules/dagster/dagster/core/types/field.py", line 29, in resolve_to_config_type
    if issubclass(dagster_type, ConfigType):
TypeError: issubclass() arg 1 must be a class
```

because I should've been using an `Enum`, not a `ConfigEnum` 

(arguably the error message around these kinds of mistakes should be improved also)

**Comment by natekupp** [comment]
@schrockn related to our conversation this AM

**Comment by natekupp** [comment]
The current version of this page is much improved: https://dagster.readthedocs.io/en/master/sections/api/apidocs/types.html but still could use a little more polish

**Comment by natekupp** [comment]
Punting from 0.5.0
