### ISSUE TITLE
build_asset_reconciliation_sensor always fails because "__ASSET_JOB" is hardcoded into the Sensor Definition

### ISSUE THREAD

**Issue by yeachan153** [dagster-io/dagster#10370]
### Dagster version

1.0.12

### What's the issue?

`build_asset_reconciliation_sensor` returns an instance of `_make_sensor`:
https://github.com/dagster-io/dagster/blob/b2b1cb14c1c27e9288239a171ab182f17eb30ee6/python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py#L418-L426

`_make_sensor` returns an instance of `MultiAssetSensorDefinition `, but the `job_name` is hard-coded to `__ASSET_JOB`:
https://github.com/dagster-io/dagster/blob/b2b1cb14c1c27e9288239a171ab182f17eb30ee6/python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py#L295-L304

`MultiAssetSensorDefinition` inherits from `SensorDefinition`, which then ends up targeting the job that doesn't exist:
https://github.com/dagster-io/dagster/blob/b2b1cb14c1c27e9288239a171ab182f17eb30ee6/python_modules/dagster/dagster/_core/definitions/sensor_definition.py#L796-L803

Attached the traceback below:

```bash
 Traceback (most recent call last):
  File "/usr/local/bin/dagster", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/dagster/_cli/__init__.py", line 48, in main
    cli(auto_envvar_prefix=ENV_PREFIX)  # pylint:disable=E1123
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dagster/_cli/api.py", line 638, in grpc_command
    container_context=json.loads(container_context) if container_context != None else None,
  File "/usr/local/lib/python3.7/site-packages/dagster/_grpc/server.py", line 864, in __init__
    container_context=container_context,
  File "/usr/local/lib/python3.7/site-packages/dagster/_grpc/server.py", line 233, in __init__
    self._container_image,
  File "/usr/local/lib/python3.7/site-packages/dagster/_grpc/server.py", line 109, in __init__
    loadable_target_origin.attribute,
  File "/usr/local/lib/python3.7/site-packages/dagster/_grpc/utils.py", line 33, in get_loadable_targets
    else loadable_targets_from_python_file(python_file, working_directory)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/workspace/autodiscovery.py", line 27, in loadable_targets_from_python_file
    loaded_module = load_python_file(python_file, working_directory)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/code_pointer.py", line 86, in load_python_file
    return import_module_from_path(module_name, python_file)
  File "/usr/local/lib/python3.7/site-packages/dagster/_seven/__init__.py", line 51, in import_module_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "repo.py", line 559, in <module>
    @repository
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/decorators/repository_decorator.py", line 308, in repository
    return _Repository()(definitions_fn)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/decorators/repository_decorator.py", line 108, in __call__
    default_logger_defs=self.default_logger_defs,
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/repository_definition.py", line 881, in from_list
    assets_defs_by_key=assets_defs_by_key,
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/repository_definition.py", line 617, in __init__
    self._sensors.get_all_definitions()
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/repository_definition.py", line 195, in get_all_definitions
    key=lambda definition: definition.name,
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/repository_definition.py", line 224, in get_definition
    self._definition_cache[definition_name] = self._validation_fn(definition_source)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/repository_definition.py", line 1159, in _validate_sensor
    f'SensorDefinition "{sensor.name}" targets job/pipeline "{sensor.job_name}" '
dagster._core.errors.DagsterInvalidDefinitionError: SensorDefinition "asset_reconciliation_sensor" targets job/pipeline "__ASSET_JOB" which was not found in this repository.
```

### What did you expect to happen?

For the sensor to function without requiring an explicit job.

### How to reproduce?

1. Create some assets
2. Create a sensor with build_asset_reconciliation_sensor

### Deployment type

Other Docker-based deployment

### Deployment details

Running 1.22.12-gke.2300.

Deployments of:

- Dagit
- Daemon
- Repository

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
I'm working on this one
