### ISSUE TITLE
graphql.error.located_error.GraphQLLocatedError: (psycopg2.DatabaseError) could not receive data from server: Connection timed out

### ISSUE THREAD

**Issue by 123mw123** [dagster-io/dagster#10396]
### Dagster version

0.12.5

### What's the issue?

```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.8/dist-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dagster_graphql/schema/external.py", line 183, in resolve_schedules
    [GrapheneSchedule(graphene_info, schedule) for schedule in schedules],
  File "/usr/local/lib/python3.8/dist-packages/dagster_graphql/schema/external.py", line 183, in <listcomp>
    [GrapheneSchedule(graphene_info, schedule) for schedule in schedules],
  File "/usr/local/lib/python3.8/dist-packages/dagster_graphql/schema/schedules/schedules.py", line 44, in __init__
    self._schedule_state = graphene_info.context.instance.get_job_state(
  File "/usr/local/lib/python3.8/dist-packages/dagster/core/instance/__init__.py", line 1507, in get_job_state
    return self._schedule_storage.get_job_state(job_origin_id)
  File "/usr/local/lib/python3.8/dist-packages/dagster/core/storage/schedules/sql_schedule_storage.py", line 65, in get_job_state
    rows = self.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/dagster/core/storage/schedules/sql_schedule_storage.py", line 30, in execute
    result_proxy = conn.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
graphql.error.located_error.GraphQLLocatedError: (psycopg2.DatabaseError) could not receive data from server: Connection timed out
```
dagster verison: 0.12.5

Dagser is getting stuck after this error. Any idea on how to resolve this?

Restarting dagster solving the issue but is there any permanent fix without human intervention? 

### What did you expect to happen?

Ideally database timeout errors should be handled with retries

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
Hi @123mw123, thanks for the report. it's hard to offer any advice here without more context, but I notice that you are using a very old version of dagster. Have you considered upgrading? There's a good chance whatever bug you're encountering has been fixed.

**Comment by 123mw123** [comment]
Hi @smackesey, Thanks for the reply. I don't think I can upgrade dagster in near future, since we have lot of pipelines and not sure if they will be compatible with latest version. I don't think there is any proper context or event triggering this issue. I am getting this error in random manner
