### ISSUE TITLE
GraphQL import errors encountered on Gitpod

### ISSUE THREAD

**Issue by Yathushan** [dagster-io/dagster#10872]
### Dagster version

version 1.1.4

### What's the issue?

I was following the instruction in the following [blog post](https://dagster.io/blog/duckdb-data-lake) to get Dagster and DuckDB setup.

When I tried to execute initial pipeline with the `dagit` command I got the following error:

```bash
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/3.8.13/bin/dagit", line 5, in <module>
    from dagit.cli import main
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagit/cli.py", line 21, in <module>
    from .app import create_app_from_workspace_process_context
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagit/app.py", line 11, in <module>
    from .webserver import DagitWebserver
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagit/webserver.py", line 7, in <module>
    from dagster_graphql import __version__ as dagster_graphql_version
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster_graphql/__init__.py", line 3, in <module>
    from .client import (
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster_graphql/client/__init__.py", line 1, in <module>
    from .client import DagsterGraphQLClient
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster_graphql/client/client.py", line 5, in <module>
    from gql import Client, gql
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/gql/__init__.py", line 2, in <module>
    from .client import Client
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/gql/client.py", line 3, in <module>
    from graphql import parse, introspection_query, build_ast_schema, build_client_schema
ImportError: cannot import name 'introspection_query' from 'graphql' (/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/graphql/__init__.py)
```

### What did you expect to happen?

According to the [blog post](https://dagster.io/blog/duckdb-data-lake), I should have seen a webpage appear where I would be able to click a Materialize All button.

### How to reproduce?

Follow the instructions in the [blog post](https://dagster.io/blog/duckdb-data-lake)

### Deployment type

Local

### Deployment details

Used [Gitpod](https://www.gitpod.new/) to deploy the code

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dpeng817** [comment]
what version of graphql do you have installed here?

**Comment by Yathushan** [comment]
I have graphql-core Version: 3.2.3 installed

**Comment by gibsondan** [comment]
Hi @Yathushan - try running `pip install gql\>=3.0.` - that should resolve this.
