### ISSUE TITLE
Dagit with dagster-postgres not working with default search schema

### ISSUE THREAD

**Issue by daglob** [dagster-io/dagster#10913]
### Dagster version

version 1.1.5

### What's the issue?

Dagit with dagster-postgres not working with default search schema.

@alangenfeld prompted in slack that parameters are not being used intentionally now:
https://github.com/dagster-io/dagster/blame/master/python_modules/libraries/dagster-postgres/dagster_postgres/run_storage/run_storage.py#L97-L105

### What did you expect to happen?

There was a need to raise dagster using dagster -postgres. A feature of the configuration was the use of a pre-created database schema. The following configuration was used for this:

```
storage:
  postgres:
    postgres_db:
      db_name: database
      hostname: localhost
      params: {
        options: "-csearch_path=snbx_dagster",
        application_name: "dagster"
      }
      scheme: postgresql+psycopg2
      username: postgres
      password: password
      port: 5432
```
When I run `dagster-daemon run`, the storage configuration is used correctly, migration is performed in the correct schema, and tables are created.
But when I run dagit I get an error:
```
(venv) PS C:\dagster> dagit -p 3030
2022-12-06 14:00:25 +0300 - dagster - INFO - Loaded environment variables from .env file: 
2022-12-06 14:00:28 +0300 - dagster - INFO - Started Dagster code server for package domrf on port 64972 in process 19216
2022-12-06 14:00:30 +0300 - dagster - INFO - Loaded environment variables from .env file: 
2022-12-06 14:00:30 +0300 - dagster - INFO - Started Dagster code server for package tech on port 63042 in process 22012
2022-12-06 14:00:31 +0300 - dagster - INFO - Loaded environment variables from .env file: 
2022-12-06 14:00:33 +0300 - dagster - INFO - Started Dagster code server for package alerts on port 57537 in process 6400
2022-12-06 14:00:34 +0300 - dagit - INFO - Serving dagit on http://127.0.0.1:3030 in process 18756
Traceback (most recent call last):
  File "C:\dagster\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\dagster\venv\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: ╬╪╚┴╩└:  юЄэю°хэшх "instance_info" эх ёє∙хёЄтєхЄ
LINE 2: FROM instance_info
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\dagster\venv\Scripts\dagit.exe\__main__.py", line 7, in <module>
  File "C:\dagster\venv\lib\site-packages\dagit\cli.py", line 190, in main
    cli(auto_envvar_prefix="DAGIT")  # pylint:disable=E1120
  File "C:\dagster\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\dagster\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\dagster\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\dagster\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\dagster\venv\lib\site-packages\dagit\cli.py", line 142, in dagit
    host_dagit_ui_with_workspace_process_context(
  File "C:\dagster\venv\lib\site-packages\dagit\cli.py", line 175, in host_dagit_ui_with_workspace_process_context
    log_action(workspace_process_context.instance, START_DAGIT_WEBSERVER)
  File "C:\dagster\venv\lib\site-packages\dagster\_core\telemetry.py", line 494, in log_action
    (dagster_telemetry_enabled, instance_id, run_storage_id) = _get_instance_telemetry_info(
  File "C:\dagster\venv\lib\site-packages\dagster\_core\telemetry.py", line 333, in _get_instance_telemetry_info
    run_storage_id = instance.run_storage.get_run_storage_id()
  File "C:\dagster\venv\lib\site-packages\dagster\_core\storage\runs\sql_run_storage.py", line 778, in get_run_storage_id
    row = self.fetchone(query)
  File "C:\dagster\venv\lib\site-packages\dagster\_core\storage\runs\sql_run_storage.py", line 96, in fetchone
    result_proxy = conn.execute(query)
  File "C:\dagster\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "C:\dagster\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\dagster\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\dagster\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\dagster\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\dagster\venv\lib\site-packages\sqlalchemy\util\compat.py", line 210, in raise_
    raise exception
  File "C:\dagster\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\dagster\venv\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) ╬╪╚┴╩└:  юЄэю°хэшх "instance_info" эх ёє∙хёЄтєхЄ
LINE 2: FROM instance_info
             ^

[SQL: SELECT instance_info.run_storage_id
FROM instance_info]
(Background on this error at: https://sqlalche.me/e/14/f405)
2022-12-06 14:00:34 +0300 - dagster - INFO - Shutting down Dagster code server for package alerts on port 57537 in process 6400
2022-12-06 14:00:34 +03002022-12-06 14:00:34 +0300 - dagster -  - dagster - INFOINFO - Shutting down Dagster code server for package tech on port 63042 in process 22012
 - Shutting down Dagster code server for package domrf on port 64972 in process 19216

```

### How to reproduce?

1. `pip install dagit dagster dagster-postgres`
2. run postgresql server (ex., localhost:5432)
3. create database `database`, create schema `snbx_dagster`
4. create a `dagster.yaml` file and enter the configuration into it:
```storage:
  postgres:
    postgres_db:
      db_name: database
      hostname: localhost
      params: {
        options: "-csearch_path=snbx_dagster",
        application_name: "dagster"
      }
      scheme: postgresql+psycopg2
      username: postgres
      password: password
      port: 5432
```
5.  run `dagster-daemon run`, and wait for the full launch and execution of migrations to the database
6. run `dagit`, and get an error on startup

### Deployment type

Local

### Deployment details

OS: windows 11

(venv) PS C:\dagster> python --version
Python 3.10.4

(venv) PS C:\dagster> pip --version   
pip 22.3.1 from C:\dagster\venv\lib\site-packages\pip (python 3.10)

Requirements:
dagit==1.1.5
dagster==1.1.5
dagster-postgres==0.17.5

DB server:
"PostgreSQL 13.3, compiled by Visual C++ build 1914, 64-bit"

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by pdavidsonFIA** [comment]
Thanks @daglob @alangenfeld this is great, was just trying to figure out how to use non-default schema, you've already fixed it! awsome! 🥇
