### ISSUE TITLE
Daemon scheduler stopping sometimes

### ISSUE THREAD

**Issue by cci-ykula** [dagster-io/dagster#11408]
### Dagster version

1.0.4

### What's the issue?

Deamon scheduler are stopping after some days. My workflows not triggered after deamon scheduler stopping.  When I look at logs , I get error like that:

`sqlite3.IntegrityError: UNIQUE constraint failed: alembic_version.version_num

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/dagit", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/dagit/cli.py", line 181, in main
    cli(auto_envvar_prefix="DAGIT")  # pylint:disable=E1120
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dagit/cli.py", line 123, in dagit
    with get_instance_for_service("dagit") as instance:
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/dagster/_cli/utils.py", line 13, in get_instance_for_service
    with DagsterInstance.get() as instance:
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/instance/__init__.py", line 427, in get
    return DagsterInstance.from_config(dagster_home_path)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/instance/__init__.py", line 443, in from_config
    return DagsterInstance.from_ref(instance_ref)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/instance/__init__.py", line 455, in from_ref
    unified_storage = instance_ref.storage
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/instance/ref.py", line 413, in storage
    return self.storage_data.rehydrate() if self.storage_data else None
  File "/usr/local/lib/python3.7/site-packages/dagster/_serdes/config_class.py", line 98, in rehydrate
    return klass.from_config_value(self, result.value)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/storage/sqlite_storage.py", line 70, in from_config_value
    return DagsterSqliteStorage.from_local(inst_data=inst_data, **config_value)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/storage/sqlite_storage.py", line 76, in from_local
    return cls(base_dir, inst_data=inst_data)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/storage/sqlite_storage.py", line 56, in __init__
    self._schedule_storage = SqliteScheduleStorage.from_local(_schedule_directory(base_dir))
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/storage/schedules/sqlite/sqlite_schedule_storage.py", line 61, in from_local
    stamp_alembic_rev(alembic_config, connection)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/storage/sql.py", line 50, in stamp_alembic_rev
    stamp(alembic_config, rev)
  File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 570, in stamp
    script.run_env()
  File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
(Background on this error at: https://sqlalche.me/e/14/gkpj)39331e376')]t failed: alembic_version.version_numion
`

### How to reproduce?

I could not reproduce directly. 

### Deployment type

Other Docker-based deployment

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @cci-ykula - is it possible to share your dagster.yaml file? 

Can you share more about your docker deployment setup - Are you running dagit and the daemon in separate containers? If you're running in docker you may have better results using postgres rather than sqlite, like in our deploy_docker example here which includes a postgres container: https://github.com/dagster-io/dagster/tree/master/examples/deploy_docker -

sqlite is great for getting started but since it just stores your data on the filesystem and has no real concurrency support you often quickly run into its limitations if you try to use it for a production deployment.

**Comment by cci-ykula** [comment]
Actually,
Hi @gibsondan dagit and deamon is in same container. we can try to separate them. Also we are using sqllite but it is madantory for us. we could not use postgres for now.

**Comment by gibsondan** [comment]
I see - our recommendation is to use postgres or some other more production-ready database like MySQL once you start running into concurrency issues with sqlite, which appears to be the case here.

**Comment by gibsondan** [comment]
Is this issue happening every time you start dagit?

**Comment by cci-ykula** [comment]
not just after starting. After some day, it happens

**Comment by sryza** [comment]
I'm going to close this because some time has passed and there's a recommendation on how to address. Feel free to reopen if you think this merits further attention.
