### ISSUE TITLE
nux enabled false not working as release notes says

### ISSUE THREAD

**Issue by AntonFriberg** [dagster-io/dagster#11852]
### Dagster version

1.1.11

### What's the issue?

According to the release notes on https://github.com/dagster-io/dagster/releases/tag/1.1.11 I should be able to add 

```yaml
nux:
  enabled: false
```
To the `dagster.yaml` file to disable the prompt about subscribing to Dagster newsletter. However, that does not work.

### What did you expect to happen?

That is would disable the prompt about newsletter and security changes.

### How to reproduce?

Install the following dependencies on Python 3.10
```
dagit==1.1.11
dagster-postgres==0.17.11
dagster==1.1.11
```

Create a file called `dagster.yaml` with the telemetry and nux disabled

```yaml
telemetry:
  enabled: false
nux:
  enabled: false
```

Run dagit from terminal
```
$ pip install -r requirements.txt
$ dagit
2023-01-24 14:04:22 +0100 - dagit - INFO - Using temporary directory /home/antonfr/Git/github/dagster-project-example/tmpq2rgfbs7 for storage. This will be removed when dagit exits.
2023-01-24 14:04:22 +0100 - dagit - INFO - To persist information across sessions, set the environment variable DAGSTER_HOME to a directory to use.
Traceback (most recent call last):
  File "/home/antonfr/Git/github/dagster-project-example/.venv/bin/dagit", line 8, in <module>
    sys.exit(main())
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagit/cli.py", line 225, in main
    cli(auto_envvar_prefix="DAGIT")  # pylint:disable=E1120
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagit/cli.py", line 160, in dagit
    with get_instance_for_service(
  File "/nix/store/al6g1zbk8li6p8mcyp0h60d08jaahf8c-python3-3.10.9/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagster/_cli/utils.py", line 36, in get_instance_for_service
    InstanceRef.from_dir(tempdir, config_dir=os.getcwd())
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagster/_core/instance/ref.py", line 320, in from_dir
    config_value, custom_instance_class = dagster_instance_config(
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagster/_core/instance/config.py", line 108, in dagster_instance_config
    raise DagsterInvalidConfigError(
dagster._core.errors.DagsterInvalidConfigError: Errors whilst loading dagster instance config at dagster.yaml.
    Error 1: Received unexpected config entry "nux" at the root. Expected: "{ code_servers?: { local_startup_timeout?: Int } compute_logs?: { class: String config?: { } module: String } event_log_storage?: { class: String config?: { } module: String } instance_class?: { class: String config?: { } module: String } local_artifact_storage?: { class: String config?: { } module: String } python_logs?: { dagster_handler_config?: { formatters?: { } handlers?: { } } managed_python_loggers?: [String] python_log_level?: String } retention?: { schedule?: { purge_after_days: (Int | { failure?: Int skipped?: Int started?: Int success?: Int }) } sensor?: { purge_after_days: (Int | { failure?: Int skipped?: Int started?: Int success?: Int }) } } run_coordinator?: { class: String config?: { } module: String } run_launcher?: { class: String config?: { } module: String } run_monitoring?: { cancellation_thread_poll_interval_seconds?: Int enabled?: Bool max_resume_run_attempts?: Int poll_interval_seconds?: Int start_timeout_seconds?: Int } run_retries?: { enabled?: Bool max_retries?: Int } run_storage?: { class: String config?: { } module: String } schedule_storage?: { class: String config?: { } module: String } scheduler?: { class: String config?: { } module: String } schedules?: { num_workers?: Int use_threads?: Bool } secrets?: { custom: { class: String config?: { } module: String } } sensors?: { num_workers?: Int use_threads?: Bool } storage?: { custom: { class: String config?: { } module: String } mysql: { mysql_db: { db_name: (String | { env: String }) hostname: (String | { env: String }) password: (String | { env: String }) port?: (Int | { env: String }) username: (String | { env: String }) } mysql_url: (String | { env: String }) } postgres?: { postgres_db?: { db_name: (String | { env: String }) hostname: (String | { env: String }) params?: { } password: (String | { env: String }) port?: (Int | { env: String }) scheme?: (String | { env: String }) username: (String | { env: String }) } postgres_url?: (String | { env: String }) should_autocreate_tables?: Bool } sqlite: { base_dir: (String | { env: String }) } } telemetry?: { enabled?: Bool } }".
```

### Deployment type

Local

### Deployment details

Python 3.10.9
Dagster 1.1.11

Also tested on python:3.10-slim docker container and same behavior.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by cmpadden** [comment]
Marking as closed.
