### ISSUE TITLE
Unpinned dependecies on dagster python module

### ISSUE THREAD

**Issue by menecio** [dagster-io/dagster#11882]
### Dagster version

latest

### What's the issue?

There are multiple dependencies that aren't pinned to specific versions or they don't have any limits, this causes issues like having SQLAlchemy==2.0.0 installed and breaking compatibility.

All python dependencies should be pinned at least defining a minimum and maximum versions to avoid unwanted versions.

### What did you expect to happen?

To have all dependencies versions pinned at setup.py

### How to reproduce?

Check the code

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by AntonFriberg** [comment]
This breaks even the simple getting started guide with a confusing error message.

```
$ pip install dagster dagit
...
$ pip freeze | grep dag
dagit==1.1.13
dagster==1.1.13
dagster-graphql==1.1.13
$ dagster dev -m dagster_example
2023-01-27 16:33:14 +0100 - dagster - INFO - Using temporary directory /home/antonfr/Git/github/dagster-project-example/tmpw9kazjkq for storage. This will be removed when dagster dev exits.
2023-01-27 16:33:14 +0100 - dagster - INFO - To persist information across sessions, set the environment variable DAGSTER_HOME to a directory to use.
Traceback (most recent call last):
  File "/home/antonfr/Git/github/dagster-project-example/.venv/bin/dagster", line 8, in <module>
    sys.exit(main())
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagster/_cli/__init__.py", line 46, in main
    cli(auto_envvar_prefix=ENV_PREFIX)  # pylint:disable=E1123
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagster/_cli/dev.py", line 86, in dev_command
    with get_instance_for_service("dagster dev", logger_fn=logger.info) as instance:
  File "/nix/store/al6g1zbk8li6p8mcyp0h60d08jaahf8c-python3-3.10.9/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagster/_cli/utils.py", line 35, in get_instance_for_service
    with DagsterInstance.from_ref(
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagster/_core/instance/__init__.py", line 491, in from_ref
    unified_storage = instance_ref.storage
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagster/_core/instance/ref.py", line 463, in storage
    return self.storage_data.rehydrate() if self.storage_data else None
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagster/_serdes/config_class.py", line 101, in rehydrate
    return klass.from_config_value(self, check.not_none(result.value))
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagster/_core/storage/sqlite_storage.py", line 70, in from_config_value
    return DagsterSqliteStorage.from_local(inst_data=inst_data, **config_value)
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagster/_core/storage/sqlite_storage.py", line 76, in from_local
    return cls(base_dir, inst_data=inst_data)
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagster/_core/storage/sqlite_storage.py", line 54, in __init__
    self._run_storage = SqliteRunStorage.from_local(_runs_directory(base_dir))
  File "/home/antonfr/Git/github/dagster-project-example/.venv/lib/python3.10/site-packages/dagster/_core/storage/runs/sqlite/sqlite_run_storage.py", line 84, in from_local
    engine.execute("PRAGMA journal_mode=WAL;")
AttributeError: 'Engine' object has no attribute 'execute'
```

Seems to be caused by sqlalchemy `2.0.0`. A simple workaround is to install the latest <2 version.
```
pip install 'sqlalchemy==1.4.46'
```

```
$ pip freeze | grep -i sql
SQLAlchemy==2.0.0
$ pip install 'sqlalchemy==1.4.46'
$ dagster dev -m dagster_example
2023-01-27 16:35:15 +0100 - dagster - INFO - Using temporary directory /home/antonfr/Git/github/dagster-project-example/tmp8quybj4l for storage. This will be removed when dagster dev exits.
2023-01-27 16:35:15 +0100 - dagster - INFO - To persist information across sessions, set the environment variable DAGSTER_HOME to a directory to use.
2023-01-27 16:35:16 +0100 - dagster - INFO - Launching Dagster services...
2023-01-27 16:35:18 +0100 - dagster.daemon - INFO - Instance is configured with the following daemons: ['BackfillDaemon', 'SchedulerDaemon', 'SensorDaemon']
2023-01-27 16:35:18 +0100 - dagster.daemon.SensorDaemon - INFO - Not checking for any runs since no sensors have been started.
2023-01-27 16:35:18 +0100 - dagit - INFO - Serving dagit on http://127.0.0.1:3000 in process 463594
```

**Comment by AntonFriberg** [comment]
Already been fixed so it just needs to be released.
#11871

**Comment by menecio** [comment]
@AntonFriberg that only fixes it for SQLAlchemy, other dependecies that are on the way of releasing major changes (like Pydantic) are still unpinned and it leaves the door open for having this issue again.

Here is the list of unpinned dependencies in the python module:

- Jinja2
- pendulum
- python-dateutil
- python-dotenv
- pytz
- requests
- tabulate
- tomli
- tqdm
- docstring-parser
- universal_pathlib
- pydantic

**Comment by ei-grad** [comment]
Here is a useful piece of experience - https://github.com/apache/airflow#approach-for-dependencies-for-airflow-core (maybe sqlalchemy should not be `<2.0` but `<1.5`).

Actually, Airflow team didn't follow their own rules having `sqlalchemy>1.4` in the `setup.cfg` - https://github.com/apache/airflow/pull/28725. But they found the problem by CI failures before sqlalchemy-2.0 has been released. I don't know how exactly, maybe by using the `--pre` flag, but wouldn't it cause too many false positives?..
