### ISSUE TITLE
make quick_pyright reports error with new file in dagster_tests

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#12317]
### Dagster version

master

### What's the issue?

`make quick_pyright` errored and it wasn't clear what the resolution was

```
(dagster-x86-3.10.3) elementl-13in-m1-mbppro-2021:dagster schrockn$ git diff origin/master --name-only
pending_job_test.py
python_modules/dagster/dagster/_core/definitions/decorators/job_decorator.py
python_modules/dagster/dagster/_core/definitions/definitions_class.py
python_modules/dagster/dagster/_core/definitions/pipeline_definition.py
python_modules/dagster/dagster/_core/definitions/repository_definition.py
python_modules/dagster/dagster/_core/definitions/schedule_definition.py
python_modules/dagster/dagster/_core/definitions/sensor_definition.py
python_modules/dagster/dagster/_core/definitions/target.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_pending_job.py
(dagster-x86-3.10.3) elementl-13in-m1-mbppro-2021:dagster schrockn$ make quick_pyright
python scripts/run-pyright.py --diff
Traceback (most recent call last):
  File "/Users/schrockn/code/dagster/scripts/run-pyright.py", line 224, in map_paths_to_envs
    env = next(
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schrockn/code/dagster/scripts/run-pyright.py", line 396, in <module>
    env_path_map = map_paths_to_envs(params["targets"])
  File "/Users/schrockn/code/dagster/scripts/run-pyright.py", line 232, in map_paths_to_envs
    raise Exception(f"Could not find environment that matched path: {path}.")
Exception: Could not find environment that matched path: pending_job_test.py.
make: *** [quick_pyright] Error 1
(dagster-x86-3.10.3) elementl-13in-m1-mbppro-2021:dagster schrockn$
```

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by cmpadden** [comment]
This is now resolved.
