### ISSUE TITLE
Issues with grpc on dagster poetry install on M2 macbook

### ISSUE THREAD

**Issue by amardeep** [dagster-io/dagster#12655]
### Dagster version

1.1.20

### What's the issue?

Using the poetry installation instructions on https://docs.dagster.io/getting-started/install
```shell
python -m grpc
```
fails with
```
Traceback (most recent call last):
  File "/Users/asingh/temp/dagster-test/env/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/asingh/temp/dagster-test/env/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/asingh/temp/dagster-test/env/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Users/asingh/temp/dagster-test/env/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/asingh/temp/dagster-test/env/lib/python3.10/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/asingh/temp/dagster-test/env/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (_CFRelease)
```

This also causes dagster commands including `dagster --version` to fail

### What did you expect to happen?

`python -m grpc` should not throw `symbol not found` error

### How to reproduce?

1. Create and activate conda environment with python3.10
```
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
```

2. Create a poetry project
```
poetry init -q
```

3. Follow poetry installation instructions:
```
poetry source add grpcio https://github.com/dagster-io/build-grpcio/wiki/Wheels
poetry add dagster dagit
```

4. Run `python -m grpc`  or `dagster --version`

### Deployment type

None

### Additional information

pip list:

```
Package                Version
---------------------- ---------
alembic                1.9.4
aniso8601              9.0.1
anyio                  3.6.2
backoff                2.2.1
certifi                2022.12.7
charset-normalizer     3.0.1
click                  8.1.3
coloredlogs            14.0
croniter               1.3.8
dagit                  1.1.20
dagster                1.1.20
dagster-graphql        1.1.20
docstring-parser       0.15
fsspec                 2023.1.0
gql                    3.4.0
graphene               3.2.1
graphql-core           3.2.3
graphql-relay          3.2.0
grpcio                 1.47.5
grpcio-health-checking 1.43.0
h11                    0.14.0
httptools              0.5.0
humanfriendly          10.0
idna                   3.4
Jinja2                 3.1.2
Mako                   1.2.4
MarkupSafe             2.1.2
multidict              6.0.4
packaging              23.0
pendulum               2.1.2
pip                    23.0.1
protobuf               3.20.3
pydantic               1.10.5
python-dateutil        2.8.2
python-dotenv          1.0.0
pytz                   2022.7.1
pytzdata               2020.1
PyYAML                 6.0
requests               2.28.2
requests-toolbelt      0.10.1
setuptools             67.4.0
six                    1.16.0
sniffio                1.3.0
SQLAlchemy             1.4.46
starlette              0.25.0
tabulate               0.9.0
tomli                  2.0.1
toposort               1.10
tqdm                   4.64.1
typing_extensions      4.5.0
universal_pathlib      0.0.21
urllib3                1.26.14
uvicorn                0.20.0
uvloop                 0.17.0
watchdog               2.3.1
watchfiles             0.18.1
websockets             10.4
wheel                  0.38.4
yarl                   1.8.2
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @amardeep - thanks for the report and sorry for the trouble here, I have two things for you to try here:

- Can you actually try installing *without* that special "poetry source add" command? grpcio just released a new version (1.47.5) yesterday that I would expect to work without needing to run that command (and it's actually possible that it's incompatible with that command). If that's the case, we'll take that out of the docs. You should be able to run `poetry source remove grpcio` to undo it.
- If that doesn't work, can you try installing with grpcio 1.47.2 instead of 1.47.5 and see if that works better?

**Comment by amardeep** [comment]
- Recreating env without `poetry source add` didn't work
- Adding `grpcio@1.47.2` without `poetry source add` didn't work
- Recreating env with `poetry source add` and `grpcio@1.47.2` worked

Thank you

**Comment by gibsondan** [comment]
Hmm, OK, we'll look into that - glad you're unblocked and thank you for the report

**Comment by gibsondan** [comment]
When you recreated the env without poetry source add, were the symptoms the same? It installed fine but then "python -m grpc" failed?

**Comment by gibsondan** [comment]
If there's any chance you'd be able to include the install logs from that install attempt that failed (without pinning grpcio@1.47.2) that would be helpful for us to get to the bottom of the problem here.

**Comment by gibsondan** [comment]
Sorry for all the questions, one last one - what version of poetry are you using?

**Comment by amardeep** [comment]
> When you recreated the env without poetry source add, were the symptoms the same? It installed fine but then "python -m grpc" failed?

Yes

>  what version of poetry are you using?

Poetry (version 1.4.0)

**Comment by amardeep** [comment]
> If there's any chance you'd be able to include the install logs from that install attempt that failed (without pinning grpcio@1.47.2) that would be helpful for us to get to the bottom of the problem here.

```shell
$ mkdir dagster-test
$ cd dagster-test
$ conda create --prefix ./env python=3.10
$ conda activate ./env
$ poetry --version
Poetry (version 1.4.0)
$ poetry init -q
$ poetry add dagster dagit
Using version ^1.1.20 for dagster
Using version ^1.1.20 for dagit

Updating dependencies
Resolving dependencies... (6.7s)

Writing lock file

Package operations: 56 installs, 0 updates, 0 removals

  • Installing certifi (2022.12.7)
  • Installing charset-normalizer (3.0.1)
  • Installing idna (3.4)
  • Installing markupsafe (2.1.2)
  • Installing six (1.16.0)
  • Installing urllib3 (1.26.14)
  • Installing fsspec (2023.1.0)
  • Installing graphql-core (3.2.3)
  • Installing grpcio (1.47.5)
  • Installing humanfriendly (10.0)
  • Installing mako (1.2.4)
  • Installing multidict (6.0.4)
  • Installing protobuf (3.20.3)
  • Installing python-dateutil (2.8.2)
  • Installing pytzdata (2020.1)
  • Installing requests (2.28.2)
  • Installing sniffio (1.3.0)
  • Installing sqlalchemy (1.4.46)
  • Installing typing-extensions (4.5.0)
  • Installing alembic (1.9.4)
  • Installing aniso8601 (9.0.1)
  • Installing anyio (3.6.2)
  • Installing backoff (2.2.1)
  • Installing click (8.1.3)
  • Installing coloredlogs (14.0)
  • Installing croniter (1.3.8)
  • Installing docstring-parser (0.15)
  • Installing graphql-relay (3.2.0)
  • Installing grpcio-health-checking (1.43.0)
  • Installing jinja2 (3.1.2)
  • Installing packaging (23.0)
  • Installing pendulum (2.1.2)
  • Installing pydantic (1.10.5)
  • Installing python-dotenv (1.0.0)
  • Installing pytz (2022.7.1)
  • Installing pyyaml (6.0)
  • Installing requests-toolbelt (0.10.1)
  • Installing tabulate (0.9.0)
  • Installing tomli (2.0.1)
  • Installing toposort (1.10)
  • Installing tqdm (4.64.1)
  • Installing universal-pathlib (0.0.21)
  • Installing watchdog (2.3.1)
  • Installing yarl (1.8.2)
  • Installing dagster (1.1.20)
  • Installing gql (3.4.0)
  • Installing graphene (3.2.1)
  • Installing h11 (0.14.0)
  • Installing httptools (0.5.0)
  • Installing starlette (0.25.0)
  • Installing uvloop (0.17.0)
  • Installing watchfiles (0.18.1)
  • Installing websockets (10.4)
  • Installing dagster-graphql (1.1.20)
  • Installing uvicorn (0.20.0)
  • Installing dagit (1.1.20)
```

```shell
$ python -m grpc
Traceback (most recent call last):
  File "/Users/asingh/temp/dagster-test/env/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/asingh/temp/dagster-test/env/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/asingh/temp/dagster-test/env/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Users/asingh/temp/dagster-test/env/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/asingh/temp/dagster-test/env/lib/python3.10/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/asingh/temp/dagster-test/env/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (_CFRelease)
```

```shell
$ pip list
Package                Version
---------------------- ---------
alembic                1.9.4
aniso8601              9.0.1
anyio                  3.6.2
backoff                2.2.1
certifi                2022.12.7
charset-normalizer     3.0.1
click                  8.1.3
coloredlogs            14.0
croniter               1.3.8
dagit                  1.1.20
dagster                1.1.20
dagster-graphql        1.1.20
docstring-parser       0.15
fsspec                 2023.1.0
gql                    3.4.0
graphene               3.2.1
graphql-core           3.2.3
graphql-relay          3.2.0
grpcio                 1.47.5
grpcio-health-checking 1.43.0
h11                    0.14.0
httptools              0.5.0
humanfriendly          10.0
idna                   3.4
Jinja2                 3.1.2
Mako                   1.2.4
MarkupSafe             2.1.2
multidict              6.0.4
packaging              23.0
pendulum               2.1.2
pip                    23.0.1
protobuf               3.20.3
pydantic               1.10.5
python-dateutil        2.8.2
python-dotenv          1.0.0
pytz                   2022.7.1
pytzdata               2020.1
PyYAML                 6.0
requests               2.28.2
requests-toolbelt      0.10.1
setuptools             67.4.0
six                    1.16.0
sniffio                1.3.0
SQLAlchemy             1.4.46
starlette              0.25.0
tabulate               0.9.0
tomli                  2.0.1
toposort               1.10
tqdm                   4.64.1
typing_extensions      4.5.0
universal_pathlib      0.0.21
urllib3                1.26.14
uvicorn                0.20.0
uvloop                 0.17.0
watchdog               2.3.1
watchfiles             0.18.1
websockets             10.4
wheel                  0.38.4
yarl                   1.8.2

```

**Comment by jayhale** [comment]
This issue has been impacting `grpcio` for all of Apple silicon.  Solution is a few flags:

See StackOverflow answer: https://stackoverflow.com/a/68205585

Export or set these environment variables when installing:
```
CFLAGS="-I /opt/homebrew/opt/openssl/include"
LDFLAGS="-L /opt/homebrew/opt/openssl/lib"\
GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
```

```
$ CFLAGS="-I /opt/homebrew/opt/openssl/include" LDFLAGS="-L /opt/homebrew/opt/openssl/lib" GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1 pip install grpcio

Collecting grpcio
  Downloading grpcio-1.51.3-cp310-cp310-macosx_12_0_universal2.whl (8.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 67.1 MB/s eta 0:00:00
Installing collected packages: grpcio
Successfully installed grpcio-1.51.3
```

**Comment by gibsondan** [comment]
Closing this out for now but will continue to track conda-forge related grpcio issues
