### ISSUE TITLE
devcontainer fails to build

### ISSUE THREAD

**Issue by jayhale** [dagster-io/dagster#12686]
### Dagster version

1!0+dev (main branch)

### What's the issue?

Attempting to launch a codespace in GitHub for the repository fails:

```

=================================================================================
2023-03-03 15:56:30.339Z: Configuration starting...
2023-03-03 15:56:30.387Z: Cloning...
2023-03-03 15:56:30.421Z: $ git -C "/var/lib/docker/codespacemount/workspace" clone --branch 12684-dagster-dbt-cli-options --depth 1 https://github.com/jayhale/dagster "/var/lib/docker/codespacemount/workspace/dagster"
2023-03-03 15:56:30.426Z: Cloning into '/var/lib/docker/codespacemount/workspace/dagster'...
2023-03-03 15:56:36.885Z: Checking out files:  71% (4281/6019)   
2023-03-03 15:56:36.902Z: Checking out files:  72% (4334/6019)   
2023-03-03 15:56:36.910Z: Checking out files:  73% (4394/6019)   
2023-03-03 15:56:36.913Z: Checking out files:  74% (4455/6019)   
2023-03-03 15:56:36.940Z: Checking out files:  75% (4515/6019)   
2023-03-03 15:56:37.009Z: Checking out files:  76% (4575/6019)   
2023-03-03 15:56:37.114Z: Checking out files:  77% (4635/6019)   
2023-03-03 15:56:37.233Z: Checking out files:  78% (4695/6019)   
2023-03-03 15:56:37.243Z: Checking out files:  79% (4756/6019)   
2023-03-03 15:56:37.266Z: Checking out files:  80% (4816/6019)   
2023-03-03 15:56:37.302Z: Checking out files:  81% (4876/6019)   
2023-03-03 15:56:37.357Z: Checking out files:  82% (4936/6019)   
2023-03-03 15:56:37.458Z: Checking out files:  83% (4996/6019)   
2023-03-03 15:56:37.473Z: Checking out files:  84% (5056/6019)   
2023-03-03 15:56:37.486Z: Checking out files:  85% (5117/6019)   
2023-03-03 15:56:37.495Z: Checking out files:  86% (5177/6019)   
2023-03-03 15:56:37.497Z: Checking out files:  87% (5237/6019)   
2023-03-03 15:56:37.519Z: Checking out files:  88% (5297/6019)   
2023-03-03 15:56:37.529Z: Checking out files:  89% (5357/6019)   
2023-03-03 15:56:37.531Z: Checking out files:  90% (5418/6019)   
2023-03-03 15:56:37.542Z: Checking out files:  91% (5478/6019)   
2023-03-03 15:56:37.557Z: Checking out files:  92% (5538/6019)   
2023-03-03 15:56:37.611Z: Checking out files:  93% (5598/6019)   
2023-03-03 15:56:37.640Z: Checking out files:  94% (5658/6019)   
2023-03-03 15:56:37.700Z: Checking out files:  95% (5719/6019)   
2023-03-03 15:56:37.710Z: Checking out files:  96% (5779/6019)   
2023-03-03 15:56:37.718Z: Checking out files:  97% (5839/6019)   
2023-03-03 15:56:37.726Z: Checking out files:  98% (5899/6019)   
2023-03-03 15:56:37.735Z: Checking out files:  99% (5959/6019)   
2023-03-03 15:56:37.741Z: Checking out files: 100% (6019/6019)   
2023-03-03 15:56:37.743Z: Checking out files: 100% (6019/6019), done.
2023-03-03 15:56:37.763Z: git process exited with exit code 0
2023-03-03 15:56:37.773Z: $ git -C "/var/lib/docker/codespacemount/workspace/dagster" config --local remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
2023-03-03 15:56:37.777Z: git process exited with exit code 0

=================================================================================
2023-03-03 15:56:39.146Z: Creating container...
2023-03-03 15:56:39.150Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/dagster --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --skip-non-blocking-commands --skip-post-create --config "/var/lib/docker/codespacemount/workspace/dagster/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache
2023-03-03 15:56:39.488Z: @devcontainers/cli 0.28.0. Node.js v14.21.3. linux 5.4.0-1103-azure x64.
2023-03-03 15:59:31.858Z: Error: Command failed: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/universal:linux
2023-03-03 15:59:31.887Z:     at fie (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1915:1355)
2023-03-03 15:59:31.891Z:     at P7 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1915:1291)
2023-03-03 15:59:31.892Z:     at runMicrotasks (<anonymous>)
2023-03-03 15:59:31.893Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2023-03-03 15:59:31.893Z:     at async Fie (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1921:2093)
2023-03-03 15:59:31.906Z:     at async $f (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1921:3239)
2023-03-03 15:59:31.908Z:     at async eoe (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:2045:17247)
2023-03-03 15:59:31.910Z:     at async Qse (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:2045:16993)
2023-03-03 15:59:31.913Z: {"outcome":"error","message":"Command failed: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/universal:linux","description":"An error occurred setting up the container."}
2023-03-03 15:59:31.917Z: devcontainer process exited with exit code 1

====================================== ERROR ====================================
2023-03-03 15:59:31.923Z: Failed to create container.
=================================================================================
2023-03-03 15:59:31.927Z: Error: Command failed: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/universal:linux
2023-03-03 15:59:31.936Z: Error Code: 1302

====================================== ERROR ====================================
2023-03-03 15:59:31.970Z: Container creation failed.
=================================================================================
2023-03-03 15:59:31.998Z: 

===================================== WARNING ===================================
2023-03-03 15:59:32.004Z: Creating recovery container.
=================================================================================

=================================================================================
2023-03-03 16:00:12.957Z: Creating container...
2023-03-03 16:00:12.961Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/dagster --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --skip-non-blocking-commands --skip-post-create --config "/var/lib/docker/codespacemount/workspace/dagster/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache
2023-03-03 16:00:13.232Z: @devcontainers/cli 0.28.0. Node.js v14.21.3. linux 5.4.0-1103-azure x64.
2023-03-03 16:00:29.088Z: $alpine -c echo Container started
2023-03-03 16:00:29.457Z: Container started
2023-03-03 16:00:29.753Z: Outcome: success User: vscode WorkspaceFolder: /workspaces/dagster
2023-03-03 16:00:29.761Z: devcontainer process exited with exit code 0

=================================================================================
2023-03-03 16:00:32.513Z: Running blocking commands...
2023-03-03 16:00:32.516Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/dagster --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --skip-non-blocking-commands --expect-existing-container --config "/var/lib/docker/codespacemount/workspace/dagster/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache
2023-03-03 16:00:32.719Z: @devcontainers/cli 0.28.0. Node.js v14.21.3. linux 5.4.0-1103-azure x64.
2023-03-03 16:00:33.014Z: Outcome: success User: vscode WorkspaceFolder: /workspaces/dagster
2023-03-03 16:00:33.020Z: devcontainer process exited with exit code 0

=================================================================================
2023-03-03 16:00:33.032Z: Configuring codespace...

=================================================================================
2023-03-03 16:00:33.073Z: Finished configuring codespace.
```

### How to reproduce?

Launch a codespace from `main`

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
We've removed support for this.
