### ISSUE TITLE
Re-execute op PapermillExecutionError

### ISSUE THREAD

**Issue by motuzov** [dagster-io/dagster#13013]
### Dagster version

1.2.2

### What's the issue?

Hi!
Working with pipelines consisting of dagstermill operations(a notebook is operation), I came across that `papermill.exceptions.PapermillExecutionError` raise when I try to re-execute operation.

>papermill.__version__
'2.4.0

Re-execute an operation created by `define_dagstermill_op` calls function ` reconstitute_pipeline_context` in  `dagstermill/manager.py`, `class Manager` :

```python
    # in dagstermill/manager.py
    ....
    with scoped_pipeline_context(
                execution_plan,
                pipeline,
                run_config,
                pipeline_run,
                instance,
                scoped_resources_builder_cm=self._setup_resources,
                # Set this flag even though we're not in test for clearer error reporting
                raise_on_error=True,
            ) as pipeline_context:
                self.context = DagstermillRuntimeExecutionContext(
                    pipeline_context=pipeline_context,
                    pipeline_def=pipeline_def,
                    op_config=run_config.get("ops", {}).get(op.name, {}).get("config"),
                    resource_keys_to_init=get_required_resource_keys_to_init(
                        execution_plan,
                        pipeline_def,
                        resolved_run_config,
                    ),
                    op_name=op.name,
                    node_handle=node_handle,
                    step_context=cast(
                        StepExecutionContext,
                        pipeline_context.for_step(
                            cast(ExecutionStep, execution_plan.get_step_by_key(step_key))
                        ),
                    ),
                )
```

In this case `get_step_by_key` pipeline_context.for_step always gets only one parameter(`step: ExecutionStep`) and always sets the second parameter `known_state` to `None ` (`known_state: Optional["KnownExecutionState"] = None`):

```python
    def for_step(
        self,
        step: ExecutionStep,
        known_state: Optional["KnownExecutionState"] = None,
    ) -> IStepContext:
        return StepExecutionContext(
            plan_data=self.plan_data,
            execution_data=self._execution_data,
            log_manager=self._log_manager.with_tags(**step.logging_tags),
            step=step,
            output_capture=self.output_capture,
            known_state=known_state,
        )
```

As a result, in `_get_source_run_id_from_logs` rises an exception:

```python
    dagster/_core/execution/context/system.py
    def _get_source_run_id_from_logs(self, step_output_handle: StepOutputHandle) -> Optional[str]:
        # walk through event logs to find the right run_id based on the run lineage

        parent_state = self.get_known_state().parent_state
        while parent_state:
            # if the parent run has yielded an StepOutput event for the given step output,
            # we find the source run id
            if step_output_handle in parent_state.produced_outputs:
                return parent_state.run_id

            # else, keep looking backwards
            parent_state = parent_state.get_parent_state()
```

### What did you expect to happen?

The possible solution would be to use  `KnownExecutionState`  to  `known_state` in `dagstermill/manager.py` :

```
 known_state  = KnownExecutionState.build_for_reexecution(
                 instance=instance,
                 parent_run=instance.get_run_by_id(pipeline_run.parent_run_id)
             )
```

The full patch could be found here: https://github.com/dsml4/dagster_patches/blob/main/18e7eb6551/manager.py.patch

### How to reproduce?

Demo project with a simple two-step pipeline to reproduce the issue:
https://github.com/dsml4/dagster_patches

Re-execute second op:

<img width="1227" alt="Re-execute" src="https://user-images.githubusercontent.com/1010096/225909282-9cc9028b-dc82-4323-86f1-1a31eab9895c.png">

<img width="1335" alt="Re-execute_Failure" src="https://user-images.githubusercontent.com/1010096/225909433-a8d7450a-d004-4ff4-966e-969adc38f5d4.png">

## Log

```

Error when attempting to materialize executed notebook: papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [2]":
---------------------------------------------------------------------------
CheckError                                Traceback (most recent call last)
Cell In[2], line 11
      3 import dagstermill as __dm_dagstermill
      4 context = __dm_dagstermill._reconstitute_pipeline_context(
      5     **{
      6         key: __dm_seven.json.loads(value)
   (...)
      9     }
     10 )
---> 11 val = __dm_dagstermill._load_input_parameter('val')

File /usr/local/lib/python3.10/site-packages/dagstermill/manager.py:414, in Manager.load_input_parameter(self, input_name)
    412 step_input = step_context.step.step_input_named(input_name)
    413 input_def = step_context.op_def.input_def_named(input_name)
--> 414 for event_or_input_value in step_input.source.load_input_object(step_context, input_def):
    415     if isinstance(event_or_input_value, DagsterEvent):
    416         continue

File /usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/inputs.py:518, in FromStepOutput.load_input_object(self, step_context, input_def)
    507     input_manager = step_context.get_io_manager(source_handle)
    508     check.invariant(
    509         isinstance(input_manager, IOManager),
    510         (
   (...)
    516         ),
    517     )
--> 518 load_input_context = self.get_load_context(
    519     step_context, input_def, io_manager_key=manager_key
    520 )
    521 yield from _load_input_with_input_manager(input_manager, load_input_context)
    523 metadata_entries = load_input_context.consume_metadata_entries()

File /usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/inputs.py:471, in FromStepOutput.get_load_context(self, step_context, input_def, io_manager_key)
    468 solid_config = step_context.resolved_run_config.ops.get(str(step_context.node_handle))
    469 config_data = solid_config.inputs.get(input_def.name) if solid_config else None
--> 471 return step_context.for_input_manager(
    472     input_def.name,
    473     config_data,
    474     input_def.metadata,
    475     input_def.dagster_type,
    476     self.step_output_handle,
    477     resource_config,
    478     resources,
    479 )

File /usr/local/lib/python3.10/site-packages/dagster/_core/execution/context/system.py:631, in StepExecutionContext.for_input_manager(self, name, config, metadata, dagster_type, source_handle, resource_config, resources, artificial_output_context)
    622     version = self.execution_plan.get_version_for_step_output_handle(source_handle)
    624     # NOTE: this is using downstream step_context for upstream OutputContext. step_context
    625     # will be set to None for 0.15 release.
    626     upstream_output = get_output_context(
    627         self.execution_plan,
    628         self.pipeline_def,
    629         self.resolved_run_config,
    630         source_handle,
--> 631         self._get_source_run_id(source_handle),
    632         log_manager=self.log,
    633         step_context=self,
    634         resources=None,
    635         version=version,
    636         warn_on_step_context_use=True,
    637     )
    638 else:
    639     upstream_output = artificial_output_context

File /usr/local/lib/python3.10/site-packages/dagster/_core/execution/context/system.py:824, in StepExecutionContext._get_source_run_id(self, step_output_handle)
    822 def _get_source_run_id(self, step_output_handle: StepOutputHandle) -> Optional[str]:
    823     if self._should_load_from_previous_runs(step_output_handle):
--> 824         return self._get_source_run_id_from_logs(step_output_handle)
    825     else:
    826         return self.dagster_run.run_id

File /usr/local/lib/python3.10/site-packages/dagster/_core/execution/context/system.py:777, in StepExecutionContext._get_source_run_id_from_logs(self, step_output_handle)
    774 def _get_source_run_id_from_logs(self, step_output_handle: StepOutputHandle) -> Optional[str]:
    775     # walk through event logs to find the right run_id based on the run lineage
--> 777     parent_state = self.get_known_state().parent_state
    778     while parent_state:
    779         # if the parent run has yielded an StepOutput event for the given step output,
    780         # we find the source run id
    781         if step_output_handle in parent_state.produced_outputs:

File /usr/local/lib/python3.10/site-packages/dagster/_core/execution/context/system.py:678, in StepExecutionContext.get_known_state(self)
    676 def get_known_state(self) -> "KnownExecutionState":
    677     if not self._known_state:
--> 678         check.failed(
    679             "Attempted to access KnownExecutionState but it was not provided at context"
    680             " creation"
    681         )
    682     return self._known_state

File /usr/local/lib/python3.10/site-packages/dagster/_check/__init__.py:1699, in failed(desc)
   1696 if not isinstance(desc, str):
   1697     raise CheckError("desc argument must be a string")
-> 1699 raise CheckError(f"Failure condition: {desc}")

CheckError: Failure condition: Attempted to access KnownExecutionState but it was not provided at context creation


Stack Trace:
  File "/usr/local/lib/python3.10/site-packages/dagstermill/factory.py", line 191, in execute_notebook
    papermill.execute_notebook(
  File "/usr/local/lib/python3.10/site-packages/papermill/execute.py", line 128, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/usr/local/lib/python3.10/site-packages/papermill/execute.py", line 232, in raise_for_execution_errors
    raise error
```

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by ei-grad** [comment]
Hit this problem too using `define_dagstermill_asset` with `ins` parameter. Failure occurs on loading the input value. Applying the patch like @motuzov provides fixes the issue.

@motuzov could you make a PR for this issue?

**Comment by motuzov** [comment]
Yes, I'll make a PR for the issue this week.

**Comment by motuzov** [comment]
PR:
https://github.com/dagster-io/dagster/pull/14947

**Comment by cmpadden** [comment]
That PR has since been merged, thank you.
