### ISSUE TITLE
FileNotFoundError with load_asset_value

### ISSUE THREAD

**Issue by GH-maggio** [dagster-io/dagster#13074]
### Dagster version

1.1.21

### What's the issue?

The following fails to materialize if run from the python API, but will materialize successfully in `dagit -f test_dagster.py`

```
from dagster import asset, AssetKey, Definitions

@asset
def test_asset():
    return {"Hello":"world"}

defs = Definitions(assets=[test_asset])

if __name__ == "__main__":

    content = defs.load_asset_value(AssetKey("test_asset")
    print(content)
```
```
python test_dagster.py &> test_dagster.log
```

```
2023-03-21 17:27:20 -0700 - dagster - DEBUG - system - Loading file from: /tmp/tmpqbz9j14q/storage/test_asset
Traceback (most recent call last):
  File "/home/cmaggio/repos/ebinder/ebinder/test_dagster.py", line 13, in <module>
    content = loader.load_asset_value(AssetKey("test_asset"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/storage/asset_value_loader.py", line 166, in load_asset_value
    return io_manager.load_input(input_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/storage/upath_io_manager.py", line 200, in load_input
    return self._load_single_input(path, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/storage/upath_io_manager.py", line 150, in _load_single_input
    raise e
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/storage/upath_io_manager.py", line 138, in _load_single_input
    obj = self.load_from_path(context=context, path=path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/storage/fs_io_manager.py", line 172, in load_from_path
    with path.open("rb") as file:
         ^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/3.11.2/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpqbz9j14q/storage/test_asset'
Exception ignored in: <generator object build_resources at 0x7f950b604ca0>
Traceback (most recent call last):
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/execution/build_resources.py", line 112, in build_resources
    list(resources_manager.generate_teardown_events())
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 558, in generate_teardown_events
    yield from self.generator
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/execution/resources_init.py", line 282, in resource_initialization_event_generator
    yield from manager.generate_teardown_events()
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 558, in generate_teardown_events
    yield from self.generator
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/execution/resources_init.py", line 354, in single_resource_event_generator
    with user_code_error_boundary(DagsterResourceFunctionError, msg_fn, log_manager=context.log):
  File "/home/cmaggio/.pyenv/versions/3.11.2/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/errors.py", line 202, in user_code_error_boundary
    with raise_execution_interrupts():
  File "/home/cmaggio/.pyenv/versions/3.11.2/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/errors.py", line 168, in raise_execution_interrupts
    with raise_interrupts_as(DagsterExecutionInterruptedError):
  File "/home/cmaggio/.pyenv/versions/3.11.2/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_utils/interrupts.py", line 98, in raise_interrupts_as
    _replace_interrupt_signal(original_signal_handler)
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_utils/interrupts.py", line 27, in _replace_interrupt_signal
    signal.signal(signal.SIGINT, new_signal_handler)
  File "/home/cmaggio/.pyenv/versions/3.11.2/lib/python3.11/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

```

### What did you expect to happen?

run successfully.

### How to reproduce?

python 3.11.2 venv 
dagster 1.1.21

python test_dagster.py 

### Deployment type

Local

### Deployment details

venv, python 3.11.2

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hi @GH-maggio - `load_asset_value` is meant to load an already-materialized asset. Are you saying that you materialized the asset from the UI?

If so, do the paths match between the location written by the UI (you can see this in the asset metadata) and the location that `load_asset_value` is trying to load from (you can see this in your logs)?

If not, the most likely cause is that you need to set DAGSTER_HOME so that it's in the environment of both the notebook and `dagster dev`.

**Comment by sryza** [comment]
@GH-maggio yes - you can use https://docs.dagster.io/_apidocs/execution#dagster.materialize.

You can also use `dagster asset materialize` from the CLI.

**Comment by GH-maggio** [comment]
Thanks, the following worked:

```
from dagster import asset, materialize, materialize_to_memory, Definitions, AssetKey

@asset
def upstream_asset():
    return [1, 2, 3]


@asset
def downstream_asset(upstream_asset):
    return upstream_asset + [4]

defs = Definitions(assets=[upstream_asset, downstream_asset])

if __name__ == "__main__":

    materialize([upstream_asset, downstream_asset])

    upstream_content = defs.load_asset_value(AssetKey("upstream_asset"))
    downstream_content = defs.load_asset_value(AssetKey("downstream_asset"))
    print("Upstream asset: ", upstream_content)
    print("Downstream asset: ", downstream_content)
```

```
Upstream asset:  [1, 2, 3]
Downstream asset:  [1, 2, 3, 4]
```

using `materialize_to_memory` had an error

```
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - RUN_START - Started execution of run for "__ephemeral_asset_job__".
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - ENGINE_EVENT - Executing steps in process (pid: 14869)
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - RESOURCE_INIT_STARTED - Starting initialization of resources [io_manager].
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - RESOURCE_INIT_SUCCESS - Finished initialization of resources [io_manager].
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - LOGS_CAPTURED - Started capturing logs in process (pid: 14869).
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - upstream_asset - STEP_START - Started execution of step "upstream_asset".
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - upstream_asset - STEP_OUTPUT - Yielded output "result" of type "Any". (Type check passed).
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - upstream_asset - ASSET_MATERIALIZATION - Materialized value upstream_asset.
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - upstream_asset - HANDLED_OUTPUT - Handled output "result" using IO manager "io_manager"
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - upstream_asset - STEP_SUCCESS - Finished execution of step "upstream_asset" in 4.6ms.
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - downstream_asset - STEP_START - Started execution of step "downstream_asset".
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - downstream_asset - LOADED_INPUT - Loaded input "upstream_asset" using input manager "io_manager", from output "result" of step "upstream_asset"
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - downstream_asset - STEP_INPUT - Got input "upstream_asset" of type "Any". (Type check passed).
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - downstream_asset - STEP_OUTPUT - Yielded output "result" of type "Any". (Type check passed).
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - downstream_asset - ASSET_MATERIALIZATION - Materialized value downstream_asset.
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - downstream_asset - HANDLED_OUTPUT - Handled output "result" using IO manager "io_manager"
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - downstream_asset - STEP_SUCCESS - Finished execution of step "downstream_asset" in 3.69ms.
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - ENGINE_EVENT - Finished steps in process (pid: 14869) in 19ms
2023-03-22 11:10:32 -0700 - dagster - DEBUG - __ephemeral_asset_job__ - bb590ea2-1310-4cba-9fd9-d5f787b892ba - 14869 - RUN_SUCCESS - Finished execution of run for "__ephemeral_asset_job__".
2023-03-22 11:10:32 -0700 - dagster - DEBUG - system - Loading file from: /tmp/tmpxohc0vug/storage/upstream_asset
Traceback (most recent call last):
  File "/home/cmaggio/repos/ebinder/ebinder/test_dagster.py", line 18, in <module>
    upstream_content = defs.load_asset_value(AssetKey("upstream_asset"))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/definitions/definitions_class.py", line 457, in load_asset_value
    return self.get_repository_def().load_asset_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/definitions/repository_definition/repository_definition.py", line 361, in load_asset_value
    return loader.load_asset_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/storage/asset_value_loader.py", line 166, in load_asset_value
    return io_manager.load_input(input_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/storage/upath_io_manager.py", line 200, in load_input
    return self._load_single_input(path, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/storage/upath_io_manager.py", line 150, in _load_single_input
    raise e
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/storage/upath_io_manager.py", line 138, in _load_single_input
    obj = self.load_from_path(context=context, path=path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/storage/fs_io_manager.py", line 172, in load_from_path
    with path.open("rb") as file:
         ^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/3.11.2/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxohc0vug/storage/upstream_asset'
Exception ignored in: <generator object build_resources at 0x7f1cdce2d900>
Traceback (most recent call last):
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/execution/build_resources.py", line 112, in build_resources
    list(resources_manager.generate_teardown_events())
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 558, in generate_teardown_events
    yield from self.generator
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/execution/resources_init.py", line 282, in resource_initialization_event_generator
    yield from manager.generate_teardown_events()
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 558, in generate_teardown_events
    yield from self.generator
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/execution/resources_init.py", line 354, in single_resource_event_generator
    with user_code_error_boundary(DagsterResourceFunctionError, msg_fn, log_manager=context.log):
  File "/home/cmaggio/.pyenv/versions/3.11.2/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/errors.py", line 202, in user_code_error_boundary
    with raise_execution_interrupts():
  File "/home/cmaggio/.pyenv/versions/3.11.2/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_core/errors.py", line 168, in raise_execution_interrupts
    with raise_interrupts_as(DagsterExecutionInterruptedError):
  File "/home/cmaggio/.pyenv/versions/3.11.2/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_utils/interrupts.py", line 98, in raise_interrupts_as
    _replace_interrupt_signal(original_signal_handler)
  File "/home/cmaggio/.pyenv/versions/ebinder/lib/python3.11/site-packages/dagster/_utils/interrupts.py", line 27, in _replace_interrupt_signal
    signal.signal(signal.SIGINT, new_signal_handler)
  File "/home/cmaggio/.pyenv/versions/3.11.2/lib/python3.11/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

```

**Comment by sryza** [comment]
Great. I'm going to close this in that case. Feel free to reopen if you think that is in error.
