### ISSUE TITLE
Direct asset invocation with config does not work with only config

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#13420]
### Dagster version

master

### What's the issue?

```
from dagster import Config, asset
from dagster._core.execution.context.compute import OpExecutionContext
from dagster._core.execution.context.invocation import build_op_context


@asset(config_schema={"a_string": str, "an_int": int})
def before(context: OpExecutionContext) -> None:
    assert context.op_config["a_string"] == "foo"
    assert context.op_config["an_int"] == 2


class AnAssetConfig(Config):
    a_string: str
    an_int: int


@asset
def after(config: AnAssetConfig):
    assert config.a_string == "foo"
    assert config.an_int == 2


before(build_op_context(op_config={"a_string": "foo", "an_int": 2}))
after(config=AnAssetConfig(a_string="foo", an_int=2))

```

Results in

```
(dagster-x86-3.10.3) elementl-13in-m1-mbppro-2021:dagster schrockn$ python asset_invocation.py
/Users/schrockn/code/dagster/asset_invocation.py:26: ExperimentalWarning: "Config" is an experimental class. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  after(config=AnAssetConfig(a_string="foo", an_int=2))
Traceback (most recent call last):
  File "/Users/schrockn/code/dagster/asset_invocation.py", line 26, in <module>
    after(config=AnAssetConfig(a_string="foo", an_int=2))
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/_core/definitions/assets.py", line 267, in __call__
    return solid_def(*args, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/_core/definitions/op_definition.py", line 437, in __call__
    return op_invocation_result(self, context, *args, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/_core/definitions/op_invocation.py", line 49, in op_invocation_result
    _check_invocation_requirements(op_def, context)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/_core/definitions/op_invocation.py", line 125, in _check_invocation_requirements
    raise DagsterInvalidInvocationError(
dagster._core.errors.DagsterInvalidInvocationError: op "after" has required config schema, but no context was provided. Use the `build_op_context` function to create a context with config.
(dagster-x86-3.10.3) elementl-13in-m1-mbppro-2021:dagster schrockn$
```

I shouldn't have to construct a context. I should be able to just pass config directly.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by cmpadden** [comment]
The reported direct-invocation config bug is no longer reproducible.
