### ISSUE TITLE
FileNotFoundError with dagster.materialize and dagster.materialize_to_memory

### ISSUE THREAD

**Issue by GH-maggio** [dagster-io/dagster#13487]
### Dagster version

1.1.21

### What's the issue?

dagster==1.2.6
Getting an FileNotFoundError with materialize and materialize_to_memory
This worked in dagster==1.2.3, does not work in 1.2.4 or 1.2.6.

```
from dagster import (
    AssetKey,
    Definitions,
    asset,
    materialize,
    materialize_to_memory
)

@asset
def test_asset():
    return "test_asset"

defs = Definitions(assets=[test_asset])

materialize([test_asset])
print(defs.load_asset_value(AssetKey("test_asset")))
``` 

```
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - c069846d-8932-4d3b-995d-243770b89123 - 363 - RUN_START - Started execution of run for "__ephemeral_asset_job__".
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - c069846d-8932-4d3b-995d-243770b89123 - 363 - ENGINE_EVENT - Executing steps in process (pid: 363)
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - c069846d-8932-4d3b-995d-243770b89123 - 363 - test_asset - RESOURCE_INIT_STARTED - Starting initialization of resources [io_manager].
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - c069846d-8932-4d3b-995d-243770b89123 - 363 - test_asset - RESOURCE_INIT_SUCCESS - Finished initialization of resources [io_manager].
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - c069846d-8932-4d3b-995d-243770b89123 - 363 - LOGS_CAPTURED - Started capturing logs in process (pid: 363).
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - c069846d-8932-4d3b-995d-243770b89123 - 363 - test_asset - STEP_START - Started execution of step "test_asset".
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - c069846d-8932-4d3b-995d-243770b89123 - 363 - test_asset - STEP_OUTPUT - Yielded output "result" of type "Any". (Type check passed).
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - c069846d-8932-4d3b-995d-243770b89123 - test_asset - Writing file at: /tmp/tmpkot093n6/storage/test_asset
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - c069846d-8932-4d3b-995d-243770b89123 - 363 - test_asset - ASSET_MATERIALIZATION - Materialized value test_asset.
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - c069846d-8932-4d3b-995d-243770b89123 - 363 - test_asset - HANDLED_OUTPUT - Handled output "result" using IO manager "io_manager"
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - c069846d-8932-4d3b-995d-243770b89123 - 363 - test_asset - STEP_SUCCESS - Finished execution of step "test_asset" in 9.3ms.
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - c069846d-8932-4d3b-995d-243770b89123 - 363 - ENGINE_EVENT - Finished steps in process (pid: 363) in 24ms
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - __ephemeral_asset_job__ - c069846d-8932-4d3b-995d-243770b89123 - 363 - RUN_SUCCESS - Finished execution of run for "__ephemeral_asset_job__".
[32m2023-04-10 11:25:56 -0700[0m - dagster - [34mDEBUG[0m - system - Loading file from: /tmp/tmpnbji1l7l/storage/test_asset
Traceback (most recent call last):
  File "/home/cmaggio/repos/dagster_materialize/assets.py", line 16, in <module>
    print(defs.load_asset_value(AssetKey("test_asset")))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_core/definitions/definitions_class.py", line 453, in load_asset_value
    return self.get_repository_def().load_asset_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_core/definitions/repository_definition/repository_definition.py", line 365, in load_asset_value
    return loader.load_asset_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_core/storage/asset_value_loader.py", line 165, in load_asset_value
    return io_manager.load_input(input_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_core/storage/upath_io_manager.py", line 196, in load_input
    return self._load_single_input(path, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_core/storage/upath_io_manager.py", line 146, in _load_single_input
    raise e
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_core/storage/upath_io_manager.py", line 134, in _load_single_input
    obj = self.load_from_path(context=context, path=path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_core/storage/fs_io_manager.py", line 172, in load_from_path
    with path.open("rb") as file:
         ^^^^^^^^^^^^^^^
  File "/home/cmaggio/.pyenv/versions/3.11.3/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpnbji1l7l/storage/test_asset'
Exception ignored in: <generator object build_resources at 0x7f573e1c8f60>
Traceback (most recent call last):
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_core/execution/build_resources.py", line 112, in build_resources
    list(resources_manager.generate_teardown_events())
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 511, in generate_teardown_events
    yield from self.generator
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_core/execution/resources_init.py", line 282, in resource_initialization_event_generator
    yield from manager.generate_teardown_events()
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 511, in generate_teardown_events
    yield from self.generator
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_core/execution/resources_init.py", line 352, in single_resource_event_generator
    with user_code_error_boundary(DagsterResourceFunctionError, msg_fn, log_manager=context.log):
  File "/home/cmaggio/.pyenv/versions/3.11.3/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_core/errors.py", line 200, in user_code_error_boundary
    with raise_execution_interrupts():
  File "/home/cmaggio/.pyenv/versions/3.11.3/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_core/errors.py", line 167, in raise_execution_interrupts
    with raise_interrupts_as(DagsterExecutionInterruptedError):
  File "/home/cmaggio/.pyenv/versions/3.11.3/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_utils/interrupts.py", line 98, in raise_interrupts_as
    _replace_interrupt_signal(original_signal_handler)
  File "/home/cmaggio/.pyenv/versions/dagster_materialize/lib/python3.11/site-packages/dagster/_utils/interrupts.py", line 27, in _replace_interrupt_signal
    signal.signal(signal.SIGINT, new_signal_handler)
  File "/home/cmaggio/.pyenv/versions/3.11.3/lib/python3.11/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

```
`inotifywait -r -m /tmp`
```
/tmp/ CREATE,ISDIR tmpj8yw4iwf
/tmp/ OPEN,ISDIR tmpj8yw4iwf
/tmp/ ACCESS,ISDIR tmpj8yw4iwf
/tmp/ CLOSE_NOWRITE,CLOSE,ISDIR tmpj8yw4iwf
/tmp/ OPEN,ISDIR tmpj8yw4iwf
/tmp/tmpj8yw4iwf/ OPEN,ISDIR
/tmp/ ACCESS,ISDIR tmpj8yw4iwf
/tmp/tmpj8yw4iwf/ ACCESS,ISDIR
/tmp/ ACCESS,ISDIR tmpj8yw4iwf
/tmp/tmpj8yw4iwf/ ACCESS,ISDIR
/tmp/ CLOSE_NOWRITE,CLOSE,ISDIR tmpj8yw4iwf
/tmp/tmpj8yw4iwf/ CLOSE_NOWRITE,CLOSE,ISDIR
/tmp/tmpj8yw4iwf/ DELETE_SELF
/tmp/ DELETE,ISDIR tmpj8yw4iwf
```

### What did you expect to happen?

retrieve the python object, str: `test_asset`

### How to reproduce?

environment:
venv, python 3.11.2
pip install dagster==1.2.6

`python assets.py`

### Deployment type

Local

### Deployment details

venv, python 3.11.2

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Hi @GH-maggio. By default, if your local dagster instance isn't passed into the `materialize` call, then `materialize` will create an ephemeral dagster instance where the contents are stored in a temp dir.

`load_asset_value` reads from your dagster instance to fetch the materialized value, not the ephemeral instance created in the `materialize` call. This is why you're seeing the "file not found" error.

Instead, you can call materialize like this if you want to persist the materialization with your other data:
```
materialize([your_asset], instance=DagsterInstance.get())
```

Or you can create a test instance, which will store your data in a temporary directory:
```
with instance_for_test() as instance:
    materialize([your_asset], instance=instance)
    defs.load_asset_value(AssetKey("your_asset"), instance=instance)
```
