### ISSUE TITLE
Fresh install has flask dependency issue

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1360]
Got this after fresh install:

```
(dagster-dev-3.7.1) [schrockn@mbp ~/code/dagster/examples/toys (master)]$ dagit
Traceback (most recent call last):
  File "/Users/schrockn/venvs/dagster-dev-3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/Users/schrockn/venvs/dagster-dev-3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/schrockn/venvs/dagster-dev-3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Flask 1.0.2 (/Users/schrockn/venvs/dagster-dev-3.7.1/lib/python3.7/site-packages), Requirement.parse('Flask==0.12.4'), {'dagit'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schrockn/venvs/dagster-dev-3.7.1/bin/dagit", line 4, in <module>
    __import__('pkg_resources').require('dagit==0.4.3.post4')
  File "/Users/schrockn/venvs/dagster-dev-3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/Users/schrockn/venvs/dagster-dev-3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/Users/schrockn/venvs/dagster-dev-3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/schrockn/venvs/dagster-dev-3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/schrockn/venvs/dagster-dev-3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/schrockn/venvs/dagster-dev-3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Flask==0.12.4' distribution was not found and is required by dagit
(dagster-dev-3.7.1) [schrockn@mbp ~/code/dagster/examples/toys (master)]$
```

**Comment by natekupp** [comment]
FWIW on this, I've been working locally on a more recent airflow version which requires a 1.x release of Flask. 

Would be nice to relax our constraint if possible so that we can accommodate users with different airflow/flask versions
