### ISSUE TITLE
not able to load dagit

### ISSUE THREAD

**Issue by saravananravi08** [dagster-io/dagster#14380]
### Dagster version

dagster, version 1.1.18

### What's the issue?

Sorry, page can't be displayed.
Please report this error to the Dagster team via GitHub or Slack. Refresh the page to try again.
Loading chunk 42 failed.
(error: http://0.0.0.0:9000/static/js/42.525c0d7e.chunk.js)

ChunkLoadError: Loading chunk 42 failed.
(error: http://0.0.0.0:9000/static/js/42.525c0d7e.chunk.js)
    at n.f.j (http://0.0.0.0:9000/dagster/static/js/main.c36a4e69.js:2:1851674)
    at http://0.0.0.0:9000/dagster/static/js/main.c36a4e69.js:2:1847932
    at Array.reduce (<anonymous>)
    at n.e (http://0.0.0.0:9000/dagster/static/js/main.c36a4e69.js:2:1847897)
    at http://0.0.0.0:9000/dagster/static/js/main.c36a4e69.js:2:2193292
    at _ (http://0.0.0.0:9000/dagster/static/js/main.c36a4e69.js:2:1570090)
    at wc (http://0.0.0.0:9000/dagster/static/js/main.c36a4e69.js:2:1423602)
    at Ds (http://0.0.0.0:9000/dagster/static/js/main.c36a4e69.js:2:1412234)
    at ys (http://0.0.0.0:9000/dagster/static/js/main.c36a4e69.js:2:1412162)
    at gs (http://0.0.0.0:9000/dagster/static/js/main.c36a4e69.js:2:1412025)

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tfederman** [comment]
FYI caused by: https://github.com/dagster-io/dagster/issues/14310
