### ISSUE TITLE
Support Pydantic V2 and/or peg it to V1 for now

### ISSUE THREAD

**Issue by zubakskees** [dagster-io/dagster#14647]
### What's the use case?

Pydantic is beta testing a V2 version, which replaces the core of the library with Rust and overhauls the API. I'd like to use it in a pre-release project, however, Dagster now bundles Pydantic V1 and hasn't yet capped the version. This is what I get when I try to upgrade:
```
Traceback (most recent call last):
  File "/Users/admin/Desktop/hello-dagster/venv/bin/dagster", line 5, in <module>
    from dagster.cli import main
  File "/Users/admin/Desktop/hello-dagster/venv/lib/python3.10/site-packages/dagster/__init__.py", line 100, in <module>
    from dagster._config.pythonic_config import (
  File "/Users/admin/Desktop/hello-dagster/venv/lib/python3.10/site-packages/dagster/_config/pythonic_config/__init__.py", line 22, in <module>
    from pydantic import ConstrainedFloat, ConstrainedInt, ConstrainedStr
  File "/Users/admin/Desktop/hello-dagster/venv/lib/python3.10/site-packages/pydantic/_migration.py", line 279, in wrapper
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
pydantic.errors.PydanticImportError: `pydantic:ConstrainedFloat` has been removed in V2.

For further information visit https://errors.pydantic.dev/2.0b2/u/import-error
```

### Ideas of implementation

I think as a pre-release this won't cause problems for anyone except people like me who want to use the new version, but a) Dagster should probably change requirements.text to reflect `pydantic<2` and b) maybe support it when it's no longer a pre-release. The V2 does include some V1 shims, so it shouldn't be too bad, but some parts of the API did change in breaking ways.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@benpankow - thoughts on this one?

**Comment by mjclarke94** [comment]
Pydantic V2 is now out of beta.
