### ISSUE TITLE
`1.4.5` raises an error when contexts arguments aren't passed around

### ISSUE THREAD

**Issue by honno** [dagster-io/dagster#15859]
### Dagster version

dagster, version 1.4.5

### What's the issue?

In 1.4.5, when invoking an asset that takes a context but not passing one, `DagsterInvalidInvocationError` is raised with the message "Decorated function <your_asset> has context argument, but no context was provided when invoking." Versions previous (at least `1.3.9` and `1.4.4`) this instead works fine.

### What did you expect to happen?

I'm not sure where I learnt this tbf, but I've been working under the assumption that we didn't need to pass around `context` around, because before `1.4.5` that has worked fine (i.e. resources from a `config.yaml` can be accessed in assets which didn't have `context` passed around). So I assume no error should be getting raised here—let me know if I've been doing it wrong all this time!

### How to reproduce?

```python
# pipeline.py
from dagster import asset, graph

@asset()
def data(context) -> int:
    return 42

@graph
def graph():
    data()
```

```console
$ dagster execute -f pipeline.py
```

<details><summary><code>1.4.5</code> traceback</summary>

```python
Traceback (most recent call last):
  File "<env>/bin/dagster", line 8, in <module>
    sys.exit(main())
  File "<env>/lib/python3.10/site-packages/dagster/_cli/__init__.py", line 48, in main
    cli(auto_envvar_prefix=ENV_PREFIX)  # pylint:disable=E1123
  File "<env>/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "<env>/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "<env>/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<env>/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<env>/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<env>/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "<env>/lib/python3.10/site-packages/dagster/_cli/job.py", line 317, in job_execute_command
    execute_execute_command(instance, kwargs)
  File "<env>/lib/python3.10/site-packages/dagster/_core/telemetry.py", line 170, in wrap
    result = f(*args, **kwargs)
  File "<env>/lib/python3.10/site-packages/dagster/_cli/job.py", line 330, in execute_execute_command
    job_origin = get_job_python_origin_from_kwargs(kwargs)
  File "<env>/lib/python3.10/site-packages/dagster/_cli/workspace/cli_target.py", line 531, in get_job_python_origin_from_kwargs
    repository_origin = get_repository_python_origin_from_kwargs(kwargs)
  File "<env>/lib/python3.10/site-packages/dagster/_cli/workspace/cli_target.py", line 652, in get_repository_python_origin_from_kwargs
    code_pointer_dict = _get_code_pointer_dict_from_kwargs(kwargs)
  File "<env>/lib/python3.10/site-packages/dagster/_cli/workspace/cli_target.py", line 572, in _get_code_pointer_dict_from_kwargs
    for loadable_target in get_loadable_targets(
  File "<env>/lib/python3.10/site-packages/dagster/_grpc/utils.py", line 37, in get_loadable_targets
    else loadable_targets_from_python_file(python_file, working_directory)
  File "<env>/lib/python3.10/site-packages/dagster/_core/workspace/autodiscovery.py", line 26, in loadable_targets_from_python_file
    loaded_module = load_python_file(python_file, working_directory)
  File "<env>/lib/python3.10/site-packages/dagster/_core/code_pointer.py", line 83, in load_python_file
    return import_module_from_path(module_name, python_file)
  File "<env>/lib/python3.10/site-packages/dagster/_seven/__init__.py", line 49, in import_module_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "pipeline.py", line 9, in <module>
    def graph():
  File "<env>/lib/python3.10/site-packages/dagster/_core/definitions/decorators/graph_decorator.py", line 196, in graph
    return _Graph()(compose_fn)
  File "<env>/lib/python3.10/site-packages/dagster/_core/definitions/decorators/graph_decorator.py", line 79, in __call__
    ) = do_composition(
  File "<env>/lib/python3.10/site-packages/dagster/_core/definitions/composition.py", line 1035, in do_composition
    output = fn(**kwargs)
  File "pipeline.py", line 10, in graph
    data()
  File "<env>/lib/python3.10/site-packages/dagster/_core/definitions/assets.py", line 299, in __call__
    return direct_invocation_result(self, *args, **kwargs)
  File "<env>/lib/python3.10/site-packages/dagster/_core/definitions/op_invocation.py", line 145, in direct_invocation_result
    raise DagsterInvalidInvocationError(
dagster._core.errors.DagsterInvalidInvocationError: Decorated function 'data' has context argument, but no context was provided when invoking.
```
</details>

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tacastillo** [comment]
Hi!

Assets aren't executable from `graphs`.

Pipelines in Dagster are made automatically by making assets and defining their dependencies on other assets.

Graphs are an advanced Dagster feature that is made to be used with Dagster's underlying way of executing assets (Ops).

If you'd like to execute a series of assets in sequence, you can group them into a job with `define_asset_job`.

**Comment by honno** [comment]
Makes sense!

> Assets aren't executable from `graphs`.

To clarify, they were executable before `1.4.5`, which I assume is an oversight.
