### ISSUE TITLE
Custom StepLauncher can't be used as a ConfigurableResource

### ISSUE THREAD

**Issue by zyd14** [dagster-io/dagster#15943]
### Dagster version

v1.4.7

### What's the issue?

It appears that passing a custom step launcher as a ConfigurableResource does not currently work. This prevents any jobs that use a custom step launcher from leveraging ConfigurableResources.

### What did you expect to happen?

I was hoping that I could create a StepLauncher which subclasses from both StepLauncher and ConfigurableResource, then pass it into an op the same way ConfigurableResources are usually passed, avoiding the context and `required_resource_keys`. While working through it I realized that this would still be a bit clunky, as the step launcher resource wouldn't actually be used by the op. So it feels like maybe a different means by which to pass the step launcher / associate it with an op might be necessary - maybe as part of the `@op` arguments? Like
```
@op(step_launcher=CustomStepLauncher)
def custom_step_launcher_op():
  pass
```
although you'd still need to be able to allow for configuring the step launcher at run time

### How to reproduce?

Running the following code does not trigger the `sleep()` call made within `NewStepLauncher.launch_step()`

```
from time import sleep
from dagster import ConfigurableResource, StepLauncher, job, op


class NewStepLauncher(StepLauncher, ConfigurableResource):
    def launch_step(self, step_context):
        step_context.log.info("Launching step from custom StepLauncher")
        sleep(10)


@op()
def my_custom_step(context, step_launcher: NewStepLauncher):
    pass


@job(resource_defs={"step_launcher": NewStepLauncher})
def my_custom_job():
    my_custom_step()
```

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
cc @benpankow

**Comment by PadenZach** [comment]
+1 My team would also love to be able to create step launchers that are Configurable Resources. 

We get this error from python 1.4.12
```
2023-09-28 18:01:21 -0400 - dagster.code_server - ERROR - Error while importing code
Traceback (most recent call last):
  File "/Users/zpaden/Workspace/locallogic-dagster/.venv/lib/python3.10/site-packages/dagster/_grpc/server.py", line 295, in __init__
    self._loaded_repositories: Optional[LoadedRepositories] = LoadedRepositories(
  File "/Users/zpaden/Workspace/locallogic-dagster/.venv/lib/python3.10/site-packages/dagster/_grpc/server.py", line 139, in __init__
    loadable_targets = get_loadable_targets(
  File "/Users/zpaden/Workspace/locallogic-dagster/.venv/lib/python3.10/site-packages/dagster/_grpc/utils.py", line 37, in get_loadable_targets
    else loadable_targets_from_python_file(python_file, working_directory)
  File "/Users/zpaden/Workspace/locallogic-dagster/.venv/lib/python3.10/site-packages/dagster/_core/workspace/autodiscovery.py", line 26, in loadable_targets_from_python_file
    loaded_module = load_python_file(python_file, working_directory)
  File "/Users/zpaden/Workspace/locallogic-dagster/.venv/lib/python3.10/site-packages/dagster/_core/code_pointer.py", line 83, in load_python_file
    return import_module_from_path(module_name, python_file)
  File "/Users/zpaden/Workspace/locallogic-dagster/.venv/lib/python3.10/site-packages/dagster/_seven/__init__.py", line 49, in import_module_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/zpaden/Workspace/locallogic-dagster/test_step_and_config.py", line 12, in <module>
    def my_custom_step(context, step_launcher: NewStepLauncher):
  File "/Users/zpaden/Workspace/locallogic-dagster/.venv/lib/python3.10/site-packages/dagster/_core/definitions/decorators/op_decorator.py", line 118, in __call__
    check.param_invariant(
  File "/Users/zpaden/Workspace/locallogic-dagster/.venv/lib/python3.10/site-packages/dagster/_check/__init__.py", line 1583, in param_invariant
    raise _param_invariant_exception(param_name, desc)
dagster._check.ParameterCheckError: Invariant violation for parameter Cannot specify resource requirements in both @op decorator and as arguments to the decorated function. Description: None
```

I also checked the @asset decorator and got pretty much the same errors.

**Comment by garethbrickman** [comment]
Step launchers were [superseded by Dagster Pipes](https://github.com/dagster-io/dagster/discussions/25685) and are not under development anymore.
