### ISSUE TITLE
Raising in the event-handling dagster_graphql code doesn't lead to a good user-facing error message

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1595]
raising in the event builders doesn't give a good user-visible error message
e.g. in pipeline_execution_manager.py:build_process_started_event

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/Users/max/dev/dagster/python_modules/dagster-graphql/dagster_graphql/implementation/pipeline_execution_manager.py", line 177, in _start_polling
    self._poll()
  File "/Users/max/dev/dagster/python_modules/dagster-graphql/dagster_graphql/implementation/pipeline_execution_manager.py", line 192, in _poll
    done = self._consume_process_queue(process)
  File "/Users/max/dev/dagster/python_modules/dagster-graphql/dagster_graphql/implementation/pipeline_execution_manager.py", line 237, in _consume_process_queue
    message.process_id,
  File "/Users/max/dev/dagster/python_modules/dagster-graphql/dagster_graphql/implementation/pipeline_execution_manager.py", line 113, in build_process_started_event
    metadata_entries=[EventMetadataEntry.text(process_id, 'pid')],
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/events.py", line 38, in text
    return EventMetadataEntry(label, description, TextMetadataEntryData(text))
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/events.py", line 64, in __new__
    return super(TextMetadataEntryData, cls).__new__(cls, check.str_param(text, 'text'))
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/check/__init__.py", line 219, in str_param
    raise_with_traceback(_param_type_mismatch_exception(obj, str, param_name))
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
dagster.check.ParameterCheckError: Param "text" is not a str. Got 10016 which is type <class 'int'>.
2019-07-22T23:29:49Z <Greenlet "Greenlet-0" at 0x107e10548: <bound method MultiprocessingExecutionManager._start_polling of <dagster_graphql.implementation.pipeline_execution_manager.MultiprocessingExecutionManager object at 0x107def0f0>>> failed with ParameterCheckError
```
but nothing in console or UX

**Comment by mgasner** [comment]
cc @prha

**Comment by natekupp** [comment]
No longer an issue, closing
