### ISSUE TITLE
`dagit` not working immediately after install

### ISSUE THREAD

**Issue by abegong** [dagster-io/dagster#162]
@schrockn, I'm guessing this is the same issue that's affecting the dagster CLI. Posting tracebacks in the hope that this will help make dagster installation (esp on Mac OS) more idiot-proof.

Installation traceback:
```
$ pip install .
Processing /Users/abe/Documents/superconductive/tools/dagster/python_modules/dagit
Requirement already satisfied: enum34>=1.1.6 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagit==0.2.0.dev3)
Requirement already satisfied: future>=0.16.0 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagit==0.2.0.dev3)
Requirement already satisfied: pyyaml>=3.12 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagit==0.2.0.dev3)
Requirement already satisfied: six>=1.11.0 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagit==0.2.0.dev3)
Requirement already satisfied: click>=6.7 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagit==0.2.0.dev3)
Requirement already satisfied: dagster>=0.2.0.dev3 in /Users/abe/Documents/superconductive/tools/dagster/python_modules/dagster (from dagit==0.2.0.dev3)
Collecting graphql-core>=2.1 (from dagit==0.2.0.dev3)
  Downloading https://files.pythonhosted.org/packages/35/dd/2dff553c929d059e53a95a8bcff66f6a3930d736dfea17f88d16229eaf84/graphql_core-2.1-py2.py3-none-any.whl (249kB)
    100% |████████████████████████████████| 256kB 2.9MB/s 
Collecting graphene>=2.1.3 (from dagit==0.2.0.dev3)
  Downloading https://files.pythonhosted.org/packages/a6/75/73bec3147071034ba73fad9aa2a8f4a41910a93b2cba1bc579420752aa3b/graphene-2.1.3-py2.py3-none-any.whl (95kB)
    100% |████████████████████████████████| 102kB 9.6MB/s 
Collecting Flask>=1.0.2 (from dagit==0.2.0.dev3)
  Downloading https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 7.5MB/s 
Collecting Flask-GraphQL>=2.0.0 (from dagit==0.2.0.dev3)
  Downloading https://files.pythonhosted.org/packages/d6/8c/043bd1deec422d33c31961dd93d952236326b1e5bbca6d3479383360ac42/Flask-GraphQL-2.0.0.tar.gz
Collecting flask-cors>=3.0.6 (from dagit==0.2.0.dev3)
  Downloading https://files.pythonhosted.org/packages/d1/db/f3495569d5c3e2bdb9fb8a66c54503364abb6f35a9da2227cf5c9c50dc42/Flask_Cors-3.0.6-py2.py3-none-any.whl
Collecting waitress>=1.1.0 (from dagit==0.2.0.dev3)
  Downloading https://files.pythonhosted.org/packages/ee/af/ac32a716d64e56561ee9c23ce45ee2865d7ac4e0678b737d2f5ee49b5fd6/waitress-1.1.0-py2.py3-none-any.whl (114kB)
    100% |████████████████████████████████| 122kB 7.6MB/s 
Requirement already satisfied: watchdog>=0.8.3 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagit==0.2.0.dev3)
Requirement already satisfied: funcsigs>=1.0.2 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagster>=0.2.0.dev3->dagit==0.2.0.dev3)
Requirement already satisfied: coloredlogs>=10.0 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagster>=0.2.0.dev3->dagit==0.2.0.dev3)
Requirement already satisfied: graphviz>=0.8.3 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagster>=0.2.0.dev3->dagit==0.2.0.dev3)
Requirement already satisfied: toposort>=1.5 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagster>=0.2.0.dev3->dagit==0.2.0.dev3)
Requirement already satisfied: pandas>=0.22.0 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagster>=0.2.0.dev3->dagit==0.2.0.dev3)
Requirement already satisfied: pyarrow>=0.8.0 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagster>=0.2.0.dev3->dagit==0.2.0.dev3)
Requirement already satisfied: sqlalchemy>=1.2.7 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagster>=0.2.0.dev3->dagit==0.2.0.dev3)
Requirement already satisfied: jinja2>=2.8 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from dagster>=0.2.0.dev3->dagit==0.2.0.dev3)
Requirement already satisfied: rx>=1.6.0 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from graphql-core>=2.1->dagit==0.2.0.dev3)
Requirement already satisfied: promise>=2.1 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from graphql-core>=2.1->dagit==0.2.0.dev3)
Requirement already satisfied: graphql-relay<1,>=0.4.5 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from graphene>=2.1.3->dagit==0.2.0.dev3)
Requirement already satisfied: aniso8601<4,>=3 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from graphene>=2.1.3->dagit==0.2.0.dev3)
Requirement already satisfied: itsdangerous>=0.24 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from Flask>=1.0.2->dagit==0.2.0.dev3)
Requirement already satisfied: Werkzeug>=0.14 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from Flask>=1.0.2->dagit==0.2.0.dev3)
Collecting graphql-server-core>=1.1 (from Flask-GraphQL>=2.0.0->dagit==0.2.0.dev3)
  Downloading https://files.pythonhosted.org/packages/48/36/9593c2922d2592c175f3c4e3e9c44dcc55560a6284abfeda907be7ae16bf/graphql-server-core-1.1.1.tar.gz
Requirement already satisfied: pathtools>=0.1.1 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from watchdog>=0.8.3->dagit==0.2.0.dev3)
Requirement already satisfied: argh>=0.24.1 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from watchdog>=0.8.3->dagit==0.2.0.dev3)
Requirement already satisfied: humanfriendly>=4.7 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from coloredlogs>=10.0->dagster>=0.2.0.dev3->dagit==0.2.0.dev3)
Requirement already satisfied: numpy>=1.9.0 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from pandas>=0.22.0->dagster>=0.2.0.dev3->dagit==0.2.0.dev3)
Requirement already satisfied: pytz>=2011k in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from pandas>=0.22.0->dagster>=0.2.0.dev3->dagit==0.2.0.dev3)
Requirement already satisfied: python-dateutil>=2 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from pandas>=0.22.0->dagster>=0.2.0.dev3->dagit==0.2.0.dev3)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from jinja2>=2.8->dagster>=0.2.0.dev3->dagit==0.2.0.dev3)
Requirement already satisfied: typing in /Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages (from promise>=2.1->graphql-core>=2.1->dagit==0.2.0.dev3)
Building wheels for collected packages: Flask-GraphQL, graphql-server-core
  Running setup.py bdist_wheel for Flask-GraphQL ... done
  Stored in directory: /Users/abe/Library/Caches/pip/wheels/c1/ec/ad/43a74080626a1eacdd27759b171f53c533900751c744239799
  Running setup.py bdist_wheel for graphql-server-core ... done
  Stored in directory: /Users/abe/Library/Caches/pip/wheels/55/b5/29/abc45da84f48540af1dff3fad1c3556d78cd3c04d206d5e80b
Successfully built Flask-GraphQL graphql-server-core
Installing collected packages: graphql-core, graphene, Flask, graphql-server-core, Flask-GraphQL, flask-cors, waitress, dagit
  Found existing installation: graphql-core 2.0
    Uninstalling graphql-core-2.0:
      Successfully uninstalled graphql-core-2.0
  Found existing installation: graphene 2.1
    Uninstalling graphene-2.1:
      Successfully uninstalled graphene-2.1
  Found existing installation: Flask 0.11.1
    Uninstalling Flask-0.11.1:
      Successfully uninstalled Flask-0.11.1
  Found existing installation: Flask-GraphQL 1.4.1
    Uninstalling Flask-GraphQL-1.4.1:
      Successfully uninstalled Flask-GraphQL-1.4.1
  Found existing installation: Flask-Cors 3.0.4
    Uninstalling Flask-Cors-3.0.4:
      Successfully uninstalled Flask-Cors-3.0.4
  Running setup.py install for dagit ... done
Successfully installed Flask-1.0.2 Flask-GraphQL-2.0.0 dagit-0.2.0.dev3 flask-cors-3.0.6 graphene-2.1.3 graphql-core-2.1 graphql-server-core-1.1.1 waitress-1.1.0
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Dagit launch traceback:
```
dagit 
Serving on http://localhost:3000
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/dagit/app.py", line 57, in index_view
    return send_file(os.path.join(os.path.dirname(__file__), './webapp/build/index.html'))
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/helpers.py", line 588, in send_file
    file = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/dagit/./webapp/build/index.html'
ERROR:flask.app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/dagit/app.py", line 57, in index_view
    return send_file(os.path.join(os.path.dirname(__file__), './webapp/build/index.html'))
  File "/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/flask/helpers.py", line 588, in send_file
    file = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/abe/anaconda2/envs/py36/lib/python3.6/site-packages/dagit/./webapp/build/index.html'
```

**Comment by schrockn** [comment]
Yeah this could be way better.

If you are installing it locally you need to do `yarn install` and `yarn build` in the webapp directly manually.

**Comment by schrockn** [comment]
So no, this is a different issue from the environmental stuff you are seeing.
