### ISSUE TITLE
Dagster stuck in crash loop: Thread for BACKFILL did not shutdown gracefully

### ISSUE THREAD

**Issue by mvanaltvorst** [dagster-io/dagster#16304]
### Dagster version

1.4.11

### What's the issue?

```
2023-09-04 08:13:16 +0000 - dagster - INFO - Launching Dagster services...                                                                             
2023-09-04 08:13:17 +0000 - dagster.daemon - ERROR - Thread for BACKFILL did not shut down gracefully.                                                 
2023-09-04 08:13:17 +0000 - dagster.daemon - INFO - Daemon threads shut down.                                                                          
Traceback (most recent call last):                                                                                                                     
  File "<frozen runpy>", line 198, in _run_module_as_main                                                                                              
  File "<frozen runpy>", line 88, in _run_code                                                                                                         
  File "/home/maurits/miniconda3/envs/develop/lib/python3.11/site-packages/dagster/_daemon/__main__.py", line 3, in <module>                           
    main()                                                                                                                                             
  File "/home/maurits/miniconda3/envs/develop/lib/python3.11/site-packages/dagster/_daemon/cli/__init__.py", line 154, in main                         
    cli(obj={})                                                                                                                                        
  File "/home/maurits/miniconda3/envs/develop/lib/python3.11/site-packages/click/core.py", line 1157, in __call__                                      
    return self.main(*args, **kwargs)                                                                                                                  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                  
  File "/home/maurits/miniconda3/envs/develop/lib/python3.11/site-packages/click/core.py", line 1078, in main                                          
    rv = self.invoke(ctx)                                                                                                                              
         ^^^^^^^^^^^^^^^^                                                                                                                              
  File "/home/maurits/miniconda3/envs/develop/lib/python3.11/site-packages/click/core.py", line 1688, in invoke                                        
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                            
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                             
  File "/home/maurits/miniconda3/envs/develop/lib/python3.11/site-packages/click/core.py", line 1434, in invoke                                        
    return ctx.invoke(self.callback, **ctx.params)                                                                                                     
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                     
  File "/home/maurits/miniconda3/envs/develop/lib/python3.11/site-packages/click/core.py", line 783, in invoke                                         
    return __callback(*args, **kwargs)                                                                                                                 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                 
  File "/home/maurits/miniconda3/envs/develop/lib/python3.11/site-packages/dagster/_daemon/cli/__init__.py", line 65, in run_command                   
    _daemon_run_command(instance, code_server_log_level, kwargs)                                                                                                                                                                          
  File "/home/maurits/miniconda3/envs/develop/lib/python3.11/site-packages/dagster/_core/telemetry.py", line 170, in wrap                              
    result = f(*args, **kwargs)                                                                                                                        
             ^^^^^^^^^^^^^^^^^^                                                                                                                        
  File "/home/maurits/miniconda3/envs/develop/lib/python3.11/site-packages/dagster/_daemon/cli/__init__.py", line 82, in _daemon_run_command           
    controller.check_daemon_loop()                                                                                                                     
  File "/home/maurits/miniconda3/envs/develop/lib/python3.11/site-packages/dagster/_daemon/controller.py", line 296, in check_daemon_loop              
    self.check_daemon_heartbeats()                                                                                                                     
  File "/home/maurits/miniconda3/envs/develop/lib/python3.11/site-packages/dagster/_daemon/controller.py", line 265, in check_daemon_heartbeats        
    raise Exception("Stopped dagster-daemon process due to thread heartbeat failure")
Exception: Stopped dagster-daemon process due to thread heartbeat failure
2023-09-04 08:13:17 +0000 - dagster.daemon - INFO - Instance is configured with the following daemons: ['AssetDaemon', 'BackfillDaemon', 'QueuedRunCoor
dinatorDaemon', 'SchedulerDaemon', 'SensorDaemon']
2023-09-04 08:13:18 +0000 - dagster-webserver - INFO - Serving dagster-webserver on http://0.0.0.0:3000 in process 2245886
2023-09-04 08:18:53 +0000 - dagster.daemon - ERROR - Stopping dagster-daemon process since the following threads are no longer sending heartbeats: ['BA
CKFILL']
2023-09-04 08:18:53 +0000 - dagster.daemon - WARNING - Shutting down daemon threads due to Exception...

```

When I run dagster dev, I get an error that the BACKFILL thread is not sending heartbeats anymore. I do not have any backfill jobs running. I suspect that the queue got corrupted somehow, which means that one part of dagster is not spawning jobs anymore whereas the other part is expecting heartbeats.

I get that it is impossible to catch all of these bugs. But it would be nice if Dagster provided some functionality to reset its thread list and other essential components that might break over time. Unresolvable issues like these make it difficult to adopt Dagster in a professional environment.

### How to reproduce?

Likely very difficult, I think it happened because I shutdown dagster dev right as it was writing something to its state sqlite. 

### Deployment type

Local

### Deployment details

Local deployment, very basic. I wrote my own PostgreSQL IO manager because of [previous data corruption issues](https://github.com/dagster-io/dagster/issues/16248) which were dismissed, but I do not think that could have caused this issue. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by mvanaltvorst** [comment]
I believe I fixed it by executing `DELETE FROM bulk_actions` in the SQLite. The table `daemon_heartbeats` was helpful for troubleshooting this issue. I'll leave this issue open because I believe the main issue of lack of documentation regarding troubleshooting Dagster internals still holds.

**Comment by mvanaltvorst** [comment]
I just managed to reproduce the issue. Attached you can see the multi assets I'm materialising. Whenever I try to materialise the latest partition, this asset materialises successfully. If I try to backfill approximately 2k partitions instead, the backfill daemon silently crashes and stops giving heartbeats (it doesn't spawn any runs so I assume it crashed)

<img width="532" alt="Screenshot 2023-09-04 at 12 30 01" src="https://github.com/dagster-io/dagster/assets/42608623/9248811b-a948-4fdd-bd6b-a24e8dd4ff5b">

**Comment by mvanaltvorst** [comment]
```
2023-09-04 10:59:58 +0000 - dagster.daemon - ERROR - Stopping dagster-daemon process since the following threads are no longer sending heartbeats: ['ASSET']                                      
```

About 1/10th into my backfill, this error occured. Again, there are no other log messages that can help me pinpoint down any specific issues.

I really like the concepts behind Dagster, but I think it is simply not built for moving around the terabytes of data I want it to, so I will be looking for another orchestrator.

**Comment by gibsondan** [comment]
@mvanaltvorst can you try setting the DAGSTER_DAEMON_HEARTBEAT_TOLERANCE environment variable to some larger value that's greater than the default of 300 seconds?

e.g.

DAGSTER_DAEMON_HEARTBEAT_TOLERANCE=7200

That should give the daemon more time to process your partitions during the backfill.

We have a PR out to increase this default that we'll prioritize getting out very soon.

**Comment by mvanaltvorst** [comment]
Thanks. I think this will definitely help the crashed ASSET daemon issue, given that the backfill had already started there. I will let you know whether the multi asset works using this relaxation of the heartbeat tolerance, because in 5 minutes I did not get a single queued job there.

**Comment by gibsondan** [comment]
If you're seeing the asset daemon run slower than you expect then a speedscope profile (see https://github.com/dagster-io/dagster/discussions/14771) would be very helpful for us to diagnose - we've observed that sometimes the first tick takes longer than normal as it does some initial book-keeping, but ideally ticks after that are faster. 

Note that auto-materializations is currently an experimental feature, so it's possible that there are still some kinks that need to be worked out on larger data sets - we'd welcome any perf data that you're seeing as you use it as we work to make it ready to remove the experimental label.
