### ISSUE TITLE
RangeError: Maximum call stack size exceeded on asset lineage page

### ISSUE THREAD

**Issue by tomasz-maj-bp** [dagster-io/dagster#16307]
### Dagster version

1.3.13

### What's the issue?

Dagit is not able to draw asset lineage, for two assets dependent on each other via partitions.

I'm attempting to present lineage between list of assets, that undergo daily processing, where they are sometimes used as an input (or as a group of assets taken as input) and sometimes as an output (or in output group). Processing happens outside of dagster and I'm trying to have a representation of it in dagit.

As an example:
assets = [a, b, c]

day1: a -> c # c for this day is created out of a partition 
day2: c+b -> a  # this day a's partition is created from combination of c and b for this day

While attempting that with time-based partitions I got circular dependency error.
With custom partitions, such correlation is visible on asset's definition tab (asset mentioned in upstream as well as downstream) but lineage page is filled with error:
```
Sorry, page can't be displayed.
Please report this error to the Dagster team via GitHub or Slack. Refresh the page to try again.
Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at http://localhost:3000/static/js/129.72133081.chunk.js:1:29283
    at Array.flatMap (<anonymous>)
    at e (http://localhost:3000/static/js/129.72133081.chunk.js:1:29266)
    at http://localhost:3000/static/js/129.72133081.chunk.js:1:29457
    at Array.map (<anonymous>)
    at e (http://localhost:3000/static/js/129.72133081.chunk.js:1:29433)
    at http://localhost:3000/static/js/129.72133081.chunk.js:1:29457
    at Array.map (<anonymous>)
    at e (http://localhost:3000/static/js/129.72133081.chunk.js:1:29433)
    at http://localhost:3000/static/js/129.72133081.chunk.js:1:29457
```

Is this concept (of inter-dependant partitions, in both ins and outs for same group of assets) not available in dagster as of now?

### What did you expect to happen?

Lineage being drawn.

### How to reproduce?

This code snippet can be used to illustrate the issue:
```
partitions_def = StaticPartitionsDefinition(["a", "b", "c"])
partitions_def2 = StaticPartitionsDefinition(["d", "e", "f"])

@asset(
    partitions_def=partitions_def,
    ins={
        "upstream": AssetIn(
            key=["second_asset"],
            partition_mapping=SpecificPartitionsPartitionMapping(["d"])
        ),
    }
)
def first_asset(upstream):
    pass


@asset(
    partitions_def=partitions_def2,
    ins={
        "upstream": AssetIn(
            key=["first_asset"],
            partition_mapping=SpecificPartitionsPartitionMapping(["c"])
        ),
    }
)
def second_asset(upstream):
    pass


defs = Definitions(assets=[first_asset, second_asset])
``` 

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tomasz-maj-bp** [comment]
Closing the issue as there's no interest in it.
