### ISSUE TITLE
Improve error message when dagit is started without a repository.yaml

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1647]
```14:57 $ dagit -p 3334 --log
Will be watching for file changes...
Traceback (most recent call last):
  File "/Users/max/.virtualenvs/dagster/bin/dagit-cli", line 11, in <module>
    load_entry_point('dagit', 'console_scripts', 'dagit-cli')()
  File "/Users/max/dev/dagster/python_modules/dagit/dagit/cli.py", line 120, in main
    cli = create_dagit_cli()
  File "/Users/max/dev/dagster/python_modules/dagit/dagit/cli.py", line 25, in create_dagit_cli
    return ui(auto_envvar_prefix='DAGIT')  # pylint: disable=no-value-for-parameter
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/max/dev/dagster/python_modules/dagit/dagit/cli.py", line 79, in ui
    log_dir = dagster_logs_dir_for_handle(handle)
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/utils/__init__.py", line 251, in dagster_logs_dir_for_handle
    repository_name = handle.build_repository_definition().name
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/handle.py", line 292, in build_repository_definition
    obj = self.entrypoint.perform_load()
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/handle.py", line 341, in entrypoint
    return self.data.get_repository_entrypoint(from_handle=self)
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/handle.py", line 412, in get_repository_entrypoint
    return LoaderEntrypoint.from_yaml(self.repository_yaml, from_handle=from_handle)
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/handle.py", line 80, in from_yaml
    config = load_yaml_from_path(file_path)
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/utils/yaml_utils.py", line 36, in load_yaml_from_path
    with open(path, 'r') as ff:
FileNotFoundError: [Errno 2] No such file or directory: 'repository.yaml'```

**Comment by mgasner** [comment]
We now have:
```
(dagster) ➜  dagster git:(master) dagit
Usage: dagit-cli [OPTIONS]

Error: Expected to use file "repository.yaml" to load repository but it does not exist. Verify your current working directory or CLI arguments.```
