### ISSUE TITLE
Fix error when loading large number of runs

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#1652]
When trying to load a large number of runs from the filesystem, dagit throws a websocket error.

![image](https://user-images.githubusercontent.com/3893054/62745740-36490700-ba01-11e9-8845-cc32cf7a14a5.png)

Error:

```
Traceback (most recent call last):
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BlockingIOError: [Errno 35] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/geventwebsocket/websocket.py", line 328, in send_frame
    self.raw_write(header + message)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/gevent/_socketcommon.py", line 355, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/gevent/_socketcommon.py", line 284, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/gevent/_socket3.py", line 445, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/geventwebsocket/websocket.py", line 344, in send
    self.send_frame(message, opcode)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/geventwebsocket/websocket.py", line 330, in send_frame
    raise WebSocketError(MSG_SOCKET_DEAD)
geventwebsocket.exceptions.WebSocketError: Socket is dead

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sashankthupukari/projects/dagster/python_modules/dagit/dagit/subscription_server.py", line 40, in on_start
    self.on_close,
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/rx/core/observablebase.py", line 83, in subscribe
    current_thread_scheduler.schedule(set_disposable)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/rx/concurrency/currentthreadscheduler.py", line 50, in schedule
    return self.schedule_relative(timedelta(0), action, state)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/rx/concurrency/currentthreadscheduler.py", line 67, in schedule_relative
    Trampoline.run(queue)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/rx/concurrency/currentthreadscheduler.py", line 31, in run
    item.invoke()
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/rx/concurrency/scheduleditem.py", line 17, in invoke
    ret = self.scheduler.invoke_action(self.action, self.state)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/rx/concurrency/schedulerbase.py", line 14, in invoke_action
    ret = action(self, state)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/rx/linq/observable/fromiterable.py", line 41, in action
    observer.on_next(item)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/graphql_ws/gevent.py", line 108, in on_next
    self.send_execution_result(self.connection_context, self.op_id, value)
  File "/Users/sashankthupukari/projects/dagster/python_modules/dagit/dagit/subscription_server.py", line 24, in send_execution_result
    return self.send_message(connection_context, op_id, GQL_DATA, result)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/graphql_ws/base.py", line 137, in send_message
    return connection_context.send(json_message)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/graphql_ws/gevent.py", line 28, in send
    self.ws.send(data)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/geventwebsocket/websocket.py", line 347, in send
    raise WebSocketError(MSG_SOCKET_DEAD)
geventwebsocket.exceptions.WebSocketError: Socket is dead

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/geventwebsocket/websocket.py", line 328, in send_frame
    self.raw_write(header + message)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/gevent/_socketcommon.py", line 355, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/gevent/_socketcommon.py", line 284, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/geventwebsocket/websocket.py", line 344, in send
    self.send_frame(message, opcode)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/geventwebsocket/websocket.py", line 330, in send_frame
    raise WebSocketError(MSG_SOCKET_DEAD)
geventwebsocket.exceptions.WebSocketError: Socket is dead

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/geventwebsocket/handler.py", line 75, in run_application
    self.run_websocket()
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/flask_sockets.py", line 45, in __call__
    handler(environment, **values)
  File "/Users/sashankthupukari/projects/dagster/python_modules/dagit/dagit/app.py", line 74, in view
    subscription_server.handle(ws, request_context=context)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/graphql_ws/gevent.py", line 56, in handle
    self.on_message(connection_context, message)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/graphql_ws/base.py", line 191, in on_message
    return self.process_message(connection_context, parsed_message)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/graphql_ws/base.py", line 104, in process_message
    return self.on_start(connection_context, op_id, params)
  File "/Users/sashankthupukari/projects/dagster/python_modules/dagit/dagit/subscription_server.py", line 45, in on_start
    self.send_error(connection_context, op_id, str(e))
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/graphql_ws/base.py", line 156, in send_error
    error_payload
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/graphql_ws/base.py", line 137, in send_message
    return connection_context.send(json_message)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/graphql_ws/gevent.py", line 28, in send
    self.ws.send(data)
  File "/Users/sashankthupukari/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/geventwebsocket/websocket.py", line 347, in send
    raise WebSocketError(MSG_SOCKET_DEAD)
geventwebsocket.exceptions.WebSocketError: Socket is dead
2019-08-09T00:22:14Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '59378', 'HTTP_HOST': 'localhost:3333', (hidden keys: 32)} failed with WebSocketError
```

**Comment by Jaikant** [comment]
I am seeing a similar error `BrokenPipeError: [Errno 32] Broken pipe` , while trying to run pipelines with sensors. It could probably be an error on my side - but since I stumbled on this issue, commenting here.

```
BrokenPipeError: [Errno 32] Broken pipe
  File "/Users/jai/work/automations_ai/env/lib/python3.8/site-packages/dagster/core/execution/api.py", line 722, in pipeline_execution_iterator
    for event in pipeline_context.executor.execute(pipeline_context, execution_plan):
  File "/Users/jai/work/automations_ai/env/lib/python3.8/site-packages/dagster/core/executor/in_process.py", line 36, in execute
    yield from inner_plan_execution_iterator(pipeline_context, execution_plan)
  File "/Users/jai/work/automations_ai/env/lib/python3.8/site-packages/dagster/core/execution/plan/execute_plan.py", line 55, in inner_plan_execution_iterator
    with pipeline_context.instance.compute_log_manager.watch(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/jai/work/automations_ai/env/lib/python3.8/site-packages/dagster/core/storage/compute_log_manager.py", line 55, in watch
    with self._watch_logs(pipeline_run, step_key):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/jai/work/automations_ai/env/lib/python3.8/site-packages/dagster/core/storage/local_compute_log_manager.py", line 47, in _watch_logs
    with mirror_stream_to_file(sys.stderr, errpath):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/jai/work/automations_ai/env/lib/python3.8/site-packages/dagster/core/execution/compute_logs.py", line 30, in mirror_stream_to_file
    with redirect_to_file(stream, filepath):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/jai/work/automations_ai/env/lib/python3.8/site-packages/dagster/core/execution/compute_logs.py", line 22, in redirect_to_file
    with redirect_stream(file_stream, stream):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/jai/work/automations_ai/env/lib/python3.8/site-packages/dagster/core/execution/compute_logs.py", line 57, in redirect_stream
    from_stream.flush()


```
