### ISSUE TITLE
PYTHONPATH no longer being used when loading repositories in dagster-webserver

### ISSUE THREAD

**Issue by freewilll** [dagster-io/dagster#16648]
### Dagster version

1.4.11

### What's the issue?

With `dagit`, I used to be able to set `PYTHONPATH` when loading repositories. This no longer appears to work with `dagster-webserver`. I can use `--working-directory` to get as far as loading my `main.py`, but then imports fail further down the line.

### What did you expect to happen?

I expect code to be able to load modules in directories that are in the `PYTHONPATH`.

### How to reproduce?

Create the following files:

`test.py`
```
from dagster import job
from my_module import foo

@job()
def test_job():
    pass
```

`external/my_module.py`
```
def foo():
    pass
```

Previously, I could do this:
```
PYTHONPATH=external dagit -f test.py
```

But with 1.4.x I get:
```
$ PYTHONPATH=external dagster-webserver -f test.py
Python-dotenv could not parse statement starting at line 27
2023-09-20 13:41:30 +0000 - dagster-webserver - INFO - Loaded environment variables from .env file: OFFLINE_PERCEPTION_CUSTOMER,OFFLINE_PERCEPTION_TIER,OFFLINE_PERCEPTION_BUCKETS_PREFIX,PYTHONPATH,LD_LIBRARY_PATH,DAGSTER_HOME,FLOG_LOGGER
2023-09-20 13:41:30 +0000 - dagster - WARNING - No dagster instance configuration file (dagster.yaml) found at /home/vagrant/point-cloud-processing/refinement/dagster/. Defaulting to loading and storing all metadata with /home/vagrant/point-cloud-processing/refinement/dagster/. If this is the desired behavior, create an empty dagster.yaml file in /home/vagrant/point-cloud-processing/refinement/dagster/.
Python-dotenv could not parse statement starting at line 27
2023-09-20 13:41:31 +0000 - dagster - INFO - Loaded environment variables from .env file: OFFLINE_PERCEPTION_CUSTOMER,OFFLINE_PERCEPTION_TIER,OFFLINE_PERCEPTION_BUCKETS_PREFIX,PYTHONPATH,LD_LIBRARY_PATH,DAGSTER_HOME,FLOG_LOGGER
2023-09-20 13:41:31 +0000 - dagster.code_server - ERROR - Error while importing code
Traceback (most recent call last):
  File "/home/vagrant/pcp-venv/lib/python3.8/site-packages/dagster/_core/code_pointer.py", line 83, in load_python_file
    return import_module_from_path(module_name, python_file)
  File "/home/vagrant/pcp-venv/lib/python3.8/site-packages/dagster/_seven/__init__.py", line 49, in import_module_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "test.py", line 2, in <module>
    from my_module import foo
ModuleNotFoundError: No module named 'my_module'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/pcp-venv/lib/python3.8/site-packages/dagster/_grpc/server.py", line 295, in __init__
    self._loaded_repositories: Optional[LoadedRepositories] = LoadedRepositories(
  File "/home/vagrant/pcp-venv/lib/python3.8/site-packages/dagster/_grpc/server.py", line 139, in __init__
    loadable_targets = get_loadable_targets(
  File "/home/vagrant/pcp-venv/lib/python3.8/site-packages/dagster/_grpc/utils.py", line 37, in get_loadable_targets
    else loadable_targets_from_python_file(python_file, working_directory)
  File "/home/vagrant/pcp-venv/lib/python3.8/site-packages/dagster/_core/workspace/autodiscovery.py", line 26, in loadable_targets_from_python_file
    loaded_module = load_python_file(python_file, working_directory)
  File "/home/vagrant/pcp-venv/lib/python3.8/site-packages/dagster/_core/code_pointer.py", line 97, in load_python_file
    raise DagsterImportError(
dagster._core.errors.DagsterImportError: Encountered ImportError: `No module named 'my_module'` while importing module test from file /home/vagrant/point-cloud-processing/test.py. Local modules were resolved using the working directory `/home/vagrant/point-cloud-processing`. If another working directory should be used, please explicitly specify the appropriate path using the `-d` or `--working-directory` for CLI based targets or the `working_directory` configuration option for `python_file`-based workspace targets.
```

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @freewilll - one line that jumps out from the logs that you shared is:

2023-09-20 13:41:31 +0000 - dagster - INFO - Loaded environment variables from .env file: OFFLINE_PERCEPTION_CUSTOMER,OFFLINE_PERCEPTION_TIER,OFFLINE_PERCEPTION_BUCKETS_PREFIX,PYTHONPATH,LD_LIBRARY_PATH,DAGSTER_HOME,FLOG_LOGGER

It looks like you also have PYTHONPATH set in a local .env file, is it possible that it's overwriting the PYTHONPATH that you're setting in the command line before starting the UI?

**Comment by freewilll** [comment]
Well done, that was it! Cheers.
