### ISSUE TITLE
UI error when adding a new partition to DynamicPartitionsDefinition inside a MultiPartitionsDefinition

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#17380]
### Dagster version

1.5.2

### What's the issue?

This error was displayed when I added a new partition:

```
Sorry, dialog can't be displayed.
This error has been reported to the Dagster team.
Attempting to show unified asset health for assets with dimension of different lengths

Error: Attempting to show unified asset health for assets with dimension of different lengths
    at mergedAssetHealth (https://sanas.dagster.cloud/_next/static/chunks/3364.02419e260e316a21.js:1:964614)
    at https://sanas.dagster.cloud/_next/static/chunks/3364.02419e260e316a21.js:1:928763
    at Object.Ci [as useMemo] (https://sanas.dagster.cloud/_next/static/chunks/framework-3d9f6d0c03981be1.js:9:65365)
    at t.useMemo (https://sanas.dagster.cloud/_next/static/chunks/framework-3d9f6d0c03981be1.js:25:6000)
    at LaunchAssetChoosePartitionsDialogBody (https://sanas.dagster.cloud/_next/static/chunks/3364.02419e260e316a21.js:1:928677)
    at Xh (https://sanas.dagster.cloud/_next/static/chunks/framework-3d9f6d0c03981be1.js:9:60992)
    at dj (https://sanas.dagster.cloud/_next/static/chunks/framework-3d9f6d0c03981be1.js:9:72859)
    at x (https://sanas.dagster.cloud/_next/static/chunks/framework-3d9f6d0c03981be1.js:9:120346)
    at Vk (https://sanas.dagster.cloud/_next/static/chunks/framework-3d9f6d0c03981be1.js:9:99132)
    at https://sanas.dagster.cloud/_next/static/chunks/framework-3d9f6d0c03981be1.js:9:98999
```

But the partition was successfully created. No other errors were displayed. 

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by danielgafni** [comment]
@sryza this one

**Comment by the4thamigo-uk** [comment]
I am seeing this also, any workaround?

**Comment by clairelin135** [comment]
@salazarm and I looked into this -- looks like the error is occurring in [these lines in the choose partitions dialog](https://github.com/dagster-io/dagster/blob/master/js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx#L164-L177) after a partition is added.

The `usePartitionHealthData` query makes a separate request for partitions per asset, updating the state after each asset's request. When 2 assets are selected, the first request returns a response including the new partition, causing the error because the second asset's request has not returned yet.

Tagging @bengotow because of your context on this query -- what are your thoughts how to handle? 

One possibility Marco and I discussed is adding a flag to the query that forces the state to only be updated after all asset partitions are returned.

**Comment by clairelin135** [comment]
Repro code:
```python
from dagster import (
    asset,
    DynamicPartitionsDefinition,
    MultiPartitionsDefinition,
    DailyPartitionsDefinition,
)


@asset(
    partitions_def=MultiPartitionsDefinition(
        {
            "a": DynamicPartitionsDefinition(name="a"),
            "b": DailyPartitionsDefinition("2024-01-01"),
        }
    )
)
def asset_a(_):
    return 1


@asset(
    partitions_def=MultiPartitionsDefinition(
        {
            "a": DynamicPartitionsDefinition(name="a"),
            "b": DailyPartitionsDefinition("2024-01-01"),
        }
    )
)
def asset_b(_):
    return 1

```
Steps to repro:
1. Select both assets in the UI
2. Add a dynamic partition

**Comment by salazarm** [comment]
Another option would be to just skip this check in this particular UI since there's already a check when you first open the dialog.

**Comment by kornerc** [comment]
The same issue can also be triggered just with `DynamicPartitionsDefinition` and without `MultiPartitionsDefinition`:

```python
from dagster import (
    DynamicPartitionsDefinition,
    asset,
)

partitions_def = DynamicPartitionsDefinition(name="split")


@asset(partitions_def=partitions_def)
def step_1(context):
    ...


@asset(partitions_def=partitions_def)
def step_2(context, step_1):
    ...
```

Then use the UI to manually add partitions.

This will trigger the UI error:

```
Sorry, dialog can't be displayed.

Please report this error to the Dagster team via GitHub or Slack. Refresh the page to try again.
Attempting to show unified asset health for assets with dimension of different lengths

mergedAssetHealth@http://127.0.0.1:3000/_next/static/chunks/818.18a7859d742baacc.js:1:635706
185/LaunchAssetChoosePartitionsDialogBody/eO<@http://127.0.0.1:3000/_next/static/chunks/818.18a7859d742baacc.js:1:602766
Ci@http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js:9:65364
83426/t.useMemo@http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js:25:6000
LaunchAssetChoosePartitionsDialogBody@http://127.0.0.1:3000/_next/static/chunks/818.18a7859d742baacc.js:1:602680
Xh@http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js:9:60991
dj@http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js:9:72858
x@http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js:9:120345
Vk@http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js:9:99132
52967/Jk/<@http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js:9:99000
Jk@http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js:9:99005
Ok@http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js:9:95761
Hk@http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js:9:94317
J@http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js:33:1365
R@http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js:33:1894
```
