### ISSUE TITLE
Direct invocation does not work when returning `AssetCheckResult`

### ISSUE THREAD

**Issue by jamiedemaria** [dagster-io/dagster#17454]
### Dagster version

1.15.5

### What's the issue?

reported here https://github.com/dagster-io/dagster/issues/16921#issuecomment-1782811167  `@asset_check` that returns `AssetCheckResult` doesn't work with direct invocation

### How to reproduce?

```python
dataframe_storage = {}

@asset
def orders():
    orders_df = pd.DataFrame({"order_id": [1, 2], "item_id": [432, 878]})
    dataframe_storage["orders"] = orders_df


@asset_check(asset=orders)
def orders_id_has_no_nulls():
    orders_df = dataframe_storage["orders"]
    num_null_order_ids = orders_df["order_id"].isna().sum()
    return AssetCheckResult(
        passed=bool(num_null_order_ids == 0),
    )

orders()
res = orders_id_has_no_nulls()
```

errors with this stack trace 
```
/usr/bin/env /Users/jamie/.pyenv/versions/dagster-3.9.10/bin/python /Users/jamie/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/la
uncher 55945 -- /Users/jamie/dev/jamie_examples/sandbox.py 
/Users/jamie/dev/jamie_examples/sandbox.py:12: ExperimentalWarning: Function `asset_check` is experimental. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  @asset_check(asset=orders)
/Users/jamie/dev/dagster/python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py:148: ExperimentalWarning: Class `AssetCheckSpec` is experimental. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  spec = AssetCheckSpec(
/Users/jamie/dev/dagster/python_modules/dagster/dagster/_core/definitions/asset_check_spec.py:101: ExperimentalWarning: Class `AssetCheckKey` is experimental. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  return AssetCheckKey(self.asset_key, self.name)
/Users/jamie/dev/dagster/python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py:173: ExperimentalWarning: Class `AssetChecksDefinitionInputOutputProps` is experimental. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  input_output_props=AssetChecksDefinitionInputOutputProps(
/Users/jamie/dev/dagster/python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py:169: ExperimentalWarning: Class `AssetChecksDefinition` is experimental. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  checks_def = AssetChecksDefinition(
Traceback (most recent call last):
  File "/Users/jamie/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jamie/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jamie/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/jamie/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/jamie/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/jamie/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/jamie/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/jamie/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/jamie/dev/jamie_examples/sandbox.py", line 21, in <module>
    res = orders_id_has_no_nulls()
TypeError: 'AssetChecksDefinition' object is not callable
```

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
I think this might be a duplicate of https://github.com/dagster-io/dagster/issues/17454

**Comment by jamiedemaria** [comment]
closing as duplicate of https://github.com/dagster-io/dagster/issues/17453
