### ISSUE TITLE
cant load dyn

### ISSUE THREAD

**Issue by nickvazz** [dagster-io/dagster#17664]
### Dagster version

dagster, version 1.5.5

### What's the issue?

When trying to load an asset partition, it says that my dagster is out of date although I am currently running 1.5.5

```python
import dagster

from data_platform import data_platform

data_platform.defs.load_asset_value(dagster.AssetKey(['57d2e9_e2a0','effmap']), partition_key='config_02a4d7f9')
```

### output
```python
---------------------------------------------------------------------------
CheckError                                Traceback (most recent call last)
Cell In[22], line 1
----> 1 data_platform.defs.load_asset_value(dagster.AssetKey(['57d2e9_e2a0','effmap']), partition_key='config_02a4d7f9')

File ~/anaconda3/envs/tau_env/lib/python3.9/site-packages/dagster/_core/definitions/definitions_class.py:495, in Definitions.load_asset_value(self, asset_key, python_type, instance, partition_key, metadata)
    466 @public
    467 def load_asset_value(
    468     self,
   (...)
    474     metadata: Optional[Dict[str, Any]] = None,
    475 ) -> object:
    476     """Load the contents of an asset as a Python object.
    477 
    478     Invokes `load_input` on the :py:class:`IOManager` associated with the asset.
   (...)
    493         The contents of an asset as a Python object.
    494     """
--> 495     return self.get_repository_def().load_asset_value(
    496         asset_key=asset_key,
    497         python_type=python_type,
    498         instance=instance,
    499         partition_key=partition_key,
    500         metadata=metadata,
    501     )

File ~/anaconda3/envs/tau_env/lib/python3.9/site-packages/dagster/_core/definitions/repository_definition/repository_definition.py:355, in RepositoryDefinition.load_asset_value(self, asset_key, python_type, instance, partition_key, metadata, resource_config)
    350 from dagster._core.storage.asset_value_loader import AssetValueLoader
    352 with AssetValueLoader(
    353     self.assets_defs_by_key, self.source_assets_by_key, instance=instance
    354 ) as loader:
--> 355     return loader.load_asset_value(
    356         asset_key,
    357         python_type=python_type,
    358         partition_key=partition_key,
    359         metadata=metadata,
    360         resource_config=resource_config,
    361     )

File ~/anaconda3/envs/tau_env/lib/python3.9/site-packages/dagster/_core/storage/asset_value_loader.py:148, in AssetValueLoader.load_asset_value(self, asset_key, python_type, partition_key, metadata, resource_config)
    142 io_resource_config = {io_manager_key: io_config} if io_config else {}
    144 io_manager_config = get_mapped_resource_config(
    145     {io_manager_key: io_manager_def}, io_resource_config
    146 )
--> 148 input_context = build_input_context(
    149     name=None,
    150     asset_key=asset_key,
    151     dagster_type=resolve_dagster_type(python_type),
    152     upstream_output=build_output_context(
    153         name=name,
    154         metadata=output_metadata,
    155         asset_key=asset_key,
    156         op_def=op_def,
    157         resource_config=resource_config,
    158     ),
    159     resources=self._resource_instance_cache,
    160     resource_config=io_manager_config[io_manager_key].config,
    161     partition_key=partition_key,
    162     asset_partition_key_range=(
    163         PartitionKeyRange(partition_key, partition_key)
    164         if partition_key is not None
    165         else None
    166     ),
    167     asset_partitions_def=asset_partitions_def,
    168     instance=self._instance,
    169     metadata=metadata,
    170 )
    172 return io_manager.load_input(input_context)

File ~/anaconda3/envs/tau_env/lib/python3.9/site-packages/dagster/_core/execution/context/input.py:607, in build_input_context(name, config, metadata, upstream_output, dagster_type, resource_config, resources, op_def, step_context, asset_key, partition_key, asset_partition_key_range, asset_partitions_def, instance)
    603 asset_partitions_def = check.opt_inst_param(
    604     asset_partitions_def, "asset_partitions_def", PartitionsDefinition
    605 )
    606 if asset_partitions_def and asset_partition_key_range:
--> 607     asset_partitions_subset = asset_partitions_def.empty_subset().with_partition_key_range(
    608         asset_partition_key_range, dynamic_partitions_store=instance
    609     )
    610 elif asset_partition_key_range:
    611     asset_partitions_subset = KeyRangeNoPartitionsDefPartitionsSubset(asset_partition_key_range)

File ~/anaconda3/envs/tau_env/lib/python3.9/site-packages/dagster/_core/definitions/partition.py:980, in PartitionsSubset.with_partition_key_range(self, partition_key_range, dynamic_partitions_store)
    974 def with_partition_key_range(
    975     self,
    976     partition_key_range: PartitionKeyRange,
    977     dynamic_partitions_store: Optional[DynamicPartitionsStore] = None,
    978 ) -> "PartitionsSubset[T_str]":
    979     return self.with_partition_keys(
--> 980         self.partitions_def.get_partition_keys_in_range(
    981             partition_key_range, dynamic_partitions_store=dynamic_partitions_store
    982         )
    983     )

File ~/anaconda3/envs/tau_env/lib/python3.9/site-packages/dagster/_core/definitions/partition.py:193, in PartitionsDefinition.get_partition_keys_in_range(self, partition_key_range, dynamic_partitions_store)
    187 def get_partition_keys_in_range(
    188     self,
    189     partition_key_range: PartitionKeyRange,
    190     dynamic_partitions_store: Optional[DynamicPartitionsStore] = None,
    191 ) -> Sequence[T_str]:
    192     keys_exist = {
--> 193         partition_key_range.start: self.has_partition_key(
    194             partition_key_range.start, dynamic_partitions_store=dynamic_partitions_store
    195         ),
    196         partition_key_range.end: self.has_partition_key(
    197             partition_key_range.end, dynamic_partitions_store=dynamic_partitions_store
    198         ),
    199     }
    200     if not all(keys_exist.values()):
    201         raise DagsterInvalidInvocationError(
    202             f"""Partition range {partition_key_range.start} to {partition_key_range.end} is
    203             not a valid range. Nonexistent partition keys:
    204             {list(key for key in keys_exist if keys_exist[key] is False)}"""
    205         )

File ~/anaconda3/envs/tau_env/lib/python3.9/site-packages/dagster/_core/definitions/partition.py:558, in DynamicPartitionsDefinition.has_partition_key(self, partition_key, current_time, dynamic_partitions_store)
    556 else:
    557     if dynamic_partitions_store is None:
--> 558         check.failed(
    559             "The instance is not available to load partitions. You may be seeing this error"
    560             " when using dynamic partitions with a version of dagster-webserver or"
    561             " dagster-cloud that is older than 1.1.18."
    562         )
    564     return dynamic_partitions_store.has_dynamic_partition(
    565         partitions_def_name=self._validated_name(), partition_key=partition_key
    566     )

File ~/anaconda3/envs/tau_env/lib/python3.9/site-packages/dagster/_check/__init__.py:1627, in failed(desc)
   1624 if not isinstance(desc, str):
   1625     raise CheckError("desc argument must be a string")
-> 1627 raise CheckError(f"Failure condition: {desc}")

CheckError: Failure condition: The instance is not available to load partitions. You may be seeing this error when using dynamic partitions with a version of dagster-webserver or dagster-cloud that is older than 1.1.18.
```

### What did you expect to happen?

I think it should be able to load a specific partition of an asset knowing the definition like in the [docs](https://docs.dagster.io/concepts/assets/software-defined-assets#loading-asset-values-outside-of-dagster-runs)

### How to reproduce?

I currently have an asset [factory](https://dagster.io/blog/python-factory-patterns) that has partitioned dynamic assets. Additional partitions are added using a sensor similar to [the docs](https://docs.dagster.io/concepts/partitions-schedules-sensors/partitioning-assets#dynamically-partitioned-assets).

```python
name = 'category'
group_name = 'sub_category'
glob_str = '*'

specs = [
    {'name': name, 'group_name': group_name, 'glob_str': glob_str},
]

dynamic_partition_def_dict = {
    f"{spec['group_name']}/{spec['name']}": DynamicPartitionsDefinition(name=f"{spec['group_name']}/{spec['name']}")
    for spec in specs
}

def generate_asset(spec, dynamic_partition_def_dict):
    @asset(
        key_prefix=[spec['group_name']],
        group_name=spec['group_name'],
        name=spec['name'],
        partitions_def=dynamic_partition_def_dict[f'{spec["group_name"]}/{spec["name"]}'],
    )
    def _asset(context):
        ...
        return df

all_assets = [generate_asset(spec, dynamic_partition_def_dict) for spec in specs]


defs = Definitions(
    assets=all_assets,
)
```

### Deployment type

Local

### Deployment details

```bash
python -m pip list | grep -e "dagster"
```

```bash
dagster                   1.5.5
dagster-dask              0.21.5
dagster-graphql           1.5.5
dagster-pipes             1.5.5
dagster-slack             0.21.5
dagster-webserver         1.5.5
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
As a short-term fix, I think setting DAGSTER_HOME will address this issue.

**Comment by sryza** [comment]
Here's a PR that will improve the error message: https://github.com/dagster-io/dagster/pull/17694.

The issue is caused by the fact that `load_asset_value` isn't aware of the instance that holds your dynamic partitions. To tell it, you need to set the DAGSTER_HOME environment variable or explicitly pass a `DagsterInstance` object in to its `instance` param.

**Comment by nickvazz** [comment]
Can confirm that this works! 🕺🏾

**Comment by SpencerSharp** [comment]
I previously fixed this by passing in the instance parameter to get_partition_keys_in_range. However, I saw that in https://github.com/dagster-io/dagster/pull/31012 the function no longer takes instance as a parameter. As such, I removed the argument from the places where I was using it, but now I am running into this error again.

It seemed like the fix to the function signature was working in some places, but not in others.

```
dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "normalized_game_box_2020s":
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 246, in dagster_event_sequence_for_step
    yield from check.generator(step_events)
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 504, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 183, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
                      ^^^^^^^^^^^^^^^^^^^
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 88, in _process_asset_results_to_events
    for user_event in user_event_sequence:
                      ^^^^^^^^^^^^^^^^^^^
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 190, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 159, in _yield_compute_results
    for event in iterate_with_context(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 390, in iterate_with_context
    with context_fn():
         ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.11/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 87, in op_execution_error_boundary
    raise error_cls(
The above exception was caused by the following exception:
dagster_shared.check.functions.CheckError: Failure condition: The instance is not available to load partitions. You may be seeing this error when using dynamic partitions with a version of dagster-webserver or dagster-cloud that is older than 1.1.18. The other possibility is that an internal framework error where a dynamic partitions store was not properly threaded down a call stack.
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 57, in op_execution_error_boundary
    yield
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 137, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/sbb/assets/utils/custom_decorators.py", line 384, in _asset
    return compute_fn(context, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/sbb/assets/utils/custom_decorators.py", line 183, in _asset
    return compute_fn(context)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/sbb/assets/normalize/nba/game/box/normalized_game_box.py", line 59, in normalized_game_box
    all_keys = partition_def.get_partition_keys_in_range(range)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_core/definitions/partitions/definition/partitions_definition.py", line 100, in get_partition_keys_in_range
    partition_key_range.start: self.has_partition_key(partition_key_range.start),
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster/_core/definitions/partitions/definition/dynamic.py", line 201, in has_partition_key
    check.failed(
  File "/Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages/dagster_shared/check/functions.py", line 1712, in failed
    raise CheckError(f"Failure condition: {desc}")
```

Here are my current dagster package versions:

```
~/.../Coding/Active/bball-stats$ py -m pip show dagster
Name: dagster
Version: 1.11.3
Summary: Dagster is an orchestration platform for the development, production, and observation of data assets.
Home-page: https://dagster.io
Author: Dagster Labs
Author-email: hello@dagsterlabs.com
License: Apache-2.0
Location: /Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages
Requires: alembic, antlr4-python3-runtime, click, coloredlogs, dagster-pipes, dagster-shared, docstring-parser, filelock, grpcio, grpcio-health-checking, Jinja2, protobuf, python-dotenv, pytz, requests, rich, setuptools, six, sqlalchemy, structlog, tabulate, tomli, toposort, tqdm, universal_pathlib, watchdog
Required-by: dagster-duckdb, dagster-duckdb-pandas, dagster-graphql, dagster-postgres, dagster-webserver
~/.../Coding/Active/bball-stats$ py -m pip show dagster-webserver
Name: dagster-webserver
Version: 1.11.3
Summary: Web UI for dagster.
Home-page: https://github.com/dagster-io/dagster
Author: Dagster Labs
Author-email: hello@dagsterlabs.com
License: Apache-2.0
Location: /Users/spencersharp/Documents/Coding/Active/bball-stats/venv_arm/lib/python3.12/site-packages
Requires: click, dagster, dagster-graphql, starlette, uvicorn
Required-by: 
```

Wondering what the intended fix is to this now. I also checked that DAGSTER_HOME was set by printing os.environ, and it is.
