### ISSUE TITLE
cannot start dagit with scheduler flag on, but no scheduler defined

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#1787]
```
$ DAGSTER_HOME=/tmp/prha dagit -p 3333
Loading repository...
Traceback (most recent call last):
  File "/Users/prha/.pyenv/versions/dagster-3.6.8/bin/dagit-cli", line 11, in <module>
    load_entry_point('dagit', 'console_scripts', 'dagit-cli')()
  File "/Users/prha/code/dagster/python_modules/dagit/dagit/cli.py", line 106, in main
    cli = create_dagit_cli()
  File "/Users/prha/code/dagster/python_modules/dagit/dagit/cli.py", line 21, in create_dagit_cli
    return ui(auto_envvar_prefix='DAGIT')  # pylint: disable=no-value-for-parameter
  File "/Users/prha/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/prha/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/prha/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/prha/.pyenv/versions/3.6.8/envs/dagster-3.6.8/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/prha/code/dagster/python_modules/dagit/dagit/cli.py", line 72, in ui
    host_dagit_ui(handle, host, port, storage_fallback, reload_trigger)
  File "/Users/prha/code/dagster/python_modules/dagit/dagit/cli.py", line 81, in host_dagit_ui
    app = create_app(handle, instance, reloader)
  File "/Users/prha/code/dagster/python_modules/dagit/dagit/app.py", line 179, in create_app
    scheduler_handle.up(python_path, repository_path)
AttributeError: 'NoneType' object has no attribute 'up'
```

**Comment by prha** [comment]
not sure if this is intended, known behavior, but thought i would flag that it seemed a little off...

**Comment by schrockn** [comment]
https://dagster.phacility.com/D1162
