### ISSUE TITLE
dagster-aws delete issues

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1795]
1) Security groups still have dependant resources:

```
(fresh-dagster-oct-2) [schrockn@mbp ~/code/playground/spinup]$ dagster-aws delete
ℹ️  Found DAGSTER_HOME in environment at: /Users/schrockn/.dagster
⚠️  This will terminate the following:
	i-09f0caff80a442b76 dagit-ec2-schrockn t3.medium

This step cannot be undone. Continue? [y/N]: y
⌛ Terminating...
Do you also want to remove the key pair dagster-keypair-schrockn-20191002T211351? [y/N]: y
Do you also want to remove the security group sg-0093e36cc597dd35a? [y/N]: y
Traceback (most recent call last):
  File "/Users/schrockn/venvs/fresh-dagster-oct-2/bin/dagster-aws", line 11, in <module>
    load_entry_point('dagster-aws', 'console_scripts', 'dagster-aws')()
  File "/Users/schrockn/venvs/fresh-dagster-oct-2/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/schrockn/venvs/fresh-dagster-oct-2/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/schrockn/venvs/fresh-dagster-oct-2/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/schrockn/venvs/fresh-dagster-oct-2/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/schrockn/venvs/fresh-dagster-oct-2/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/libraries/dagster-aws/dagster_aws/cli/cli.py", line 319, in delete
    client.delete_security_group(GroupId=cfg.security_group_id)
  File "/Users/schrockn/venvs/fresh-dagster-oct-2/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/schrockn/venvs/fresh-dagster-oct-2/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (DependencyViolation) when calling the DeleteSecurityGroup operation: resource sg-0093e36cc597dd35a has a dependent object
```

2) /Users/schrockn/.dagster/.dagit-aws-config remains

Therefore a new call to dagster-aws init spits warning:

```
(fresh-dagster-oct-2) [schrockn@mbp ~/code/playground/spinup]$ dagster-aws init

🌈 Welcome to Dagit + AWS quickstart cloud init!

ℹ️  Found DAGSTER_HOME in environment at: /Users/schrockn/.dagster
dagster-aws has already been initialized! Continue? [y/N]: ^

```

**Comment by natekupp** [comment]
This was a real issue, because we weren't waiting for the EC2 instance to terminate before trying to remove the security group.

In https://dagster.phacility.com/D1177 I've added a wait for the EC2 instance to go down, which addresses (1).

Aside from this specific case, (2) is interesting because it's entirely possible for people to get into a bad state. I think we should point them to the state file so that they can manually recover—I'll open a diff for that

**Comment by natekupp** [comment]
https://dagster.phacility.com/D1181
