### ISSUE TITLE
dbt werkzeug incompatability issue

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1807]
Right now we have some sort of conflict between flask and dbt requiring different werkzeug versions. 

```
ERROR: flask 1.1.1 has requirement Werkzeug>=0.15, but you'll have werkzeug 0.14.1 which is incompatible.
Installing collected packages: werkzeug, dbt-core
  Found existing installation: Werkzeug 0.16.0
    Uninstalling Werkzeug-0.16.0:
      Successfully uninstalled Werkzeug-0.16.0
  Running setup.py install for dbt-core ... done
Successfully installed dbt-core-0.14.2 werkzeug-0.14.1
(fresh-oct-3) [schrockn@mbp ~/code/dagster/examples (master *)]$ dagit
Traceback (most recent call last):
  File "/Users/schrockn/venvs/fresh-oct-3/bin/dagit-cli", line 6, in <module>
    from dagit.cli import main
  File "/Users/schrockn/venvs/fresh-oct-3/lib/python3.7/site-packages/dagit/cli.py", line 15, in <module>
    from .app import create_app
  File "/Users/schrockn/venvs/fresh-oct-3/lib/python3.7/site-packages/dagit/app.py", line 13, in <module>
    from flask import Flask, request, send_file, send_from_directory
  File "/Users/schrockn/venvs/fresh-oct-3/lib/python3.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask
  File "/Users/schrockn/venvs/fresh-oct-3/lib/python3.7/site-packages/flask/app.py", line 69, in <module>
    from .wrappers import Request
  File "/Users/schrockn/venvs/fresh-oct-3/lib/python3.7/site-packages/flask/wrappers.py", line 14, in <module>
    from werkzeug.wrappers.json import JSONMixin as _JSONMixin
ModuleNotFoundError: No module named 'werkzeug.wrappers.json'; 'werkzeug.wrappers' is not a package
```

**Comment by mgasner** [comment]
We're going to prioritize Flask over dbt for this and pin to `werkzeug>=0.15.0` explicitly in examples.  Ultimately, we can probably eliminate `dbt-core` from setup.py for both the examples and for dagster-dbt -- we don't call the dbt Python APIs at all, just shell out to `dbt`. Making this invocation configurable will allow dbt to be installed in a separate virtualenv. See for discussion in the dbt Slack: https://getdbt.slack.com/archives/C2JRRQDTL/p1570473192496400

**Comment by mgasner** [comment]
There is an open issue to upgrade dbt's dependency. https://github.com/fishtown-analytics/dbt/issues/1697
