### ISSUE TITLE
Dagster's `ConfigurableResource` uses deprecated Pydantic `config` 

### ISSUE THREAD

**Issue by ImadYIdrissi** [dagster-io/dagster#18296]
### Dagster version

dagster, version 1.5.6

### What's the issue?

When running some basic unittests (`pytest`) I keep getting those warnings :

```
<REDACTED_PERSONAL_DIRECTORY>/lib/python3.9/site-packages/pydantic/_internal/_config.py:267
<REDACTED_PERSONAL_DIRECTORY>/lib/python3.9/site-packages/pydantic/_internal/_config.py:267
<REDACTED_PERSONAL_DIRECTORY>/lib/python3.9/site-packages/pydantic/_internal/_config.py:267
<REDACTED_PERSONAL_DIRECTORY>/lib/python3.9/site-packages/pydantic/_internal/_config.py:267: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
    warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
```

So I converted the deprecation warnings into errors and got this stacktrace : 

```
pytest -vv -o log_cli=true -W error::DeprecationWarning <REDACTED_PERSONAL_DIRECTORY>/test_cnty_pipeline/resources/utils/test_resources.py 
```

Which returns :
```
ImportError while loading conftest '<REDACTED_PERSONAL_DIRECTORY>/test_cnty_pipeline/conftest.py'.
test_cnty_pipeline/conftest.py:4: in <module>
    from dagster._core.execution.context.invocation import BoundOpExecutionContext
<REDACTED_PERSONAL_DIRECTORY>/lib/python3.9/site-packages/dagster/__init__.py:98: in <module>
    from dagster._config.pythonic_config import (
<REDACTED_PERSONAL_DIRECTORY>/lib/python3.9/site-packages/dagster/_config/pythonic_config/__init__.py:1: in <module>
    from .config import (
<REDACTED_PERSONAL_DIRECTORY>/lib/python3.9/site-packages/dagster/_config/pythonic_config/config.py:82: in <module>
    class MakeConfigCacheable(BaseModel):
<REDACTED_PERSONAL_DIRECTORY>/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py:102: in __new__
    config_wrapper = ConfigWrapper.for_model(bases, namespace, kwargs)
<REDACTED_PERSONAL_DIRECTORY>/lib/python3.9/site-packages/pydantic/_internal/_config.py:119: in for_model
    config_from_namespace = config_dict_from_namespace or prepare_config(config_class_from_namespace)
<REDACTED_PERSONAL_DIRECTORY>/lib/python3.9/site-packages/pydantic/_internal/_config.py:267: in prepare_config
    warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
E   pydantic.warnings.PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
```

This must mean the class `class BoundOpExecutionContext(OpExecutionContext):` is using the deprecated pydantic configuration mode... probably `_op_config`..? i'm not certain.

NB : May be related to this issue : https://github.com/dagster-io/dagster/issues/16195

### What did you expect to happen?

No warnings.

### How to reproduce?

In a `test_sample.py` file:

```
import pytest
import mock
from dagster._core.execution.context.invocation import BoundOpExecutionContext


@pytest.fixture
def mock_resources(monkeypatch):
    # Patching job_name because Dagster doesn't provide dummy values when op is invoked directly
    # cf. issue: https://github.com/dagster-io/dagster/issues/16195
    monkeypatch.setattr(BoundOpExecutionContext, "job_name", "mock_job")

    mock_resources = {
        "some_resource": mock.MagicMock(),
    }
    yield mock_resources


def test_sample(mock_resource):
    assert True

```

```
pytest -vv -o log_cli=true -W error::DeprecationWarning test_sample.py 
```

### Deployment type

None

### Deployment details

Used python v 3.6.9

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
cc @benpankow

**Comment by edgarrmondragon** [comment]
I'm seeing the same warning for `SqlComponent`:

```console
$ PYTHONWARNINGS=error uv run python -c 'from dagster import SqlComponent'     
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/repro/.venv/lib/python3.12/site-packages/dagster/__init__.py", line 82, in <module>
    import dagster.components as components  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/repro/.venv/lib/python3.12/site-packages/dagster/components/__init__.py", line 28, in <module>
    from dagster.components.lib.sql_component.sql_component import (
  File "/repro/.venv/lib/python3.12/site-packages/dagster/components/lib/sql_component/sql_component.py", line 22, in <module>
    class SqlComponent(ExecutableComponent, ABC):
  File "/repro/.venv/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 110, in __new__
    config_wrapper = ConfigWrapper.for_model(bases, namespace, kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/repro/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py", line 136, in for_model
    config_from_namespace = config_dict_from_namespace or prepare_config(config_class_from_namespace)
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/repro/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py", line 323, in prepare_config
    warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
pydantic.warnings.PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/
```

https://github.com/dagster-io/dagster/blob/f24dc2802b9913cb98147b070064d1f8b46aa8e8/python_modules/dagster/dagster/components/lib/sql_component/sql_component.py#L20-L29

Let me know if a new issue is preferred.

**Comment by cmpadden** [comment]
Closing as the reported ConfigurableResource deprecation path looks fixed. Thank you.
