### ISSUE TITLE
Robustness pass on Postgres-backed storages

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1833]
Probably just need some retry logic, occasionally see:

`[GraphQL error] (psycopg2.DatabaseError) SSL SYSCALL error: Operation timed out [SQL: SELECT runs.run_body FROM runs WHERE runs.run_id = %(run_id_1)s] [parameters: {'run_id_1': '25471d57-e7c3-4aa9-b083-17fdd95cf317'}] (Background on this error at: http://sqlalche.me/e/4xp6)`

**Comment by mgasner** [comment]
Also need a friendlier error message if the storage can't connect on startup and probably some init logging -- right now, dagit startup hangs mysteriously.

**Comment by mgasner** [comment]
#1326

**Comment by natekupp** [comment]
See also #2482

**Comment by catherinewu** [comment]
going to close for now as we don't have a repro and our users haven't reported hitting this

**Comment by 123mw123** [comment]
```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.8/dist-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dagster_graphql/schema/external.py", line 183, in resolve_schedules
    [GrapheneSchedule(graphene_info, schedule) for schedule in schedules],
  File "/usr/local/lib/python3.8/dist-packages/dagster_graphql/schema/external.py", line 183, in <listcomp>
    [GrapheneSchedule(graphene_info, schedule) for schedule in schedules],
  File "/usr/local/lib/python3.8/dist-packages/dagster_graphql/schema/schedules/schedules.py", line 44, in __init__
    self._schedule_state = graphene_info.context.instance.get_job_state(
  File "/usr/local/lib/python3.8/dist-packages/dagster/core/instance/__init__.py", line 1507, in get_job_state
    return self._schedule_storage.get_job_state(job_origin_id)
  File "/usr/local/lib/python3.8/dist-packages/dagster/core/storage/schedules/sql_schedule_storage.py", line 65, in get_job_state
    rows = self.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/dagster/core/storage/schedules/sql_schedule_storage.py", line 30, in execute
    result_proxy = conn.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
graphql.error.located_error.GraphQLLocatedError: (psycopg2.DatabaseError) could not receive data from server: Connection timed out
```

@mgasner  @natekupp @catherinewu   I am using dagster=0.12.5 and getting the similar error. Any idea on how to resolve this?
