### ISSUE TITLE
Lacking example of testing partitioned IO Manager

### ISSUE THREAD

**Issue by C0DK** [dagster-io/dagster#18556]
### What's the issue or suggestion?

I was looking at [this](https://docs.dagster.io/concepts/io-management/io-managers#testing-an-io-manager) and trying to figure out how to test a partitioned io-manager.

My assumption would be something like this:

```python
def test_get_correct_partition():
    start_date = datetime(2000, 5, 1)

    partition_def = MonthlyPartitionsDefinition(start_date=datetime(2000, 1, 1))
    context = build_input_context(
        asset_key=SOME_ASSET_KEY,
        asset_partitions_def=partition_def,
        partition_key=partition_def.get_partition_keys(start_date)[0],
    )
```

however, in the IOManager, where I utilize a time window, I get the exception:

```
dagster._check.CheckError: Failure condition: Tried to access asset_partitions_time_window, but the asset is not partitioned.
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by ShootingStarD** [comment]
> I ended up creating my own hacky MockContext class to work around the issue, see:
> 
> ```python
>         class MockContext:
>             def __init__(self, asset_key: AssetKey, asset_partitions_time_window: TimeWindow):
>                 self.asset_key = asset_key
>                 self.asset_partitions_time_window = asset_partitions_time_window
> 
>         mock_input_context = MockContext(
>             asset_key=sample_asset.key,
>             asset_partitions_time_window=TimeWindow(
>                 start=datetime.datetime(2023, 10, 1),
>                 end=datetime.datetime(2023, 10, 8),
>             )
>         )
> 
>         loaded_input = io_manager.load_input(
>             mock_input_context
>         )
> ```

Did you tried providing an empty OutputContext to the upstream_output argument? 

I think this should work (at least it is very close to something that works for me)

```python
input_context = build_input_context(
      name="input_context",
      asset_key="some_asset",
      asset_partition_key_range=PartitionKeyRange(
          start=start_time, end=end_time
      ),
      asset_partitions_def=FIFTEEN_MINUTELY_PARTITION,
      upstream_output=OutputContext(
      ),
)
io_manager.load_input(input_context)
```

**Comment by C0DK** [comment]
I ended up makint it a bit more complex, however it does test the whole flow a bit better:

```python

def test_can_save_asset__partitioned():
    mock = MagicMock()

    class MockedSparkClient(SparkClient):
        def overwrite_partition(self, *args, **kwargs):
            mock(*args, **kwargs)

    partition_def = MonthlyPartitionsDefinition(
        start_date=datetime(2000, 1, 1), timezone=config.timezone
    )

    start = timezone.localize(datetime(2000, 6, 1))
    end = timezone.localize(datetime(2000, 7, 1))

    client = MockedSparkClient()

    @asset(
        name=table.table_name,
        key_prefix=table.as_key_prefix(),
        io_manager_def=DatabricksIOManager(client=client),
        partitions_def=partition_def,
    )
    def some_asset():
        return SOME_DATAFRAME

    materialize(
        assets=[some_asset],
        partition_key=partition_def.get_partition_key_for_timestamp(start.timestamp()),
    )
    assert (
        mock.call_count == 1
        and mock.call_args.kwargs["partition"]
        == Partition(
            column_name=column_name,
            start=start,
            end=end,
        )
    )
 ```

(the mock logic is a bit of an aside, but was due to issues with the ability to fully mock ConfigurableRessources combined with the need to easily test that the inner client got the correct request :)

**Comment by C0DK** [comment]
After updating dagster i also got the error with stepcontext

**Comment by ShootingStarD** [comment]
@C0DK yes I now remember that I had to revert back to dagster 1.5.9, maybe we should add a bug label to the issue or create a new issue to address specifically this issue with step_context?

**Comment by C0DK** [comment]
It might be two separate issues, yes; can you create the separate one (the bug one) and link them?

**Comment by ShootingStarD** [comment]
@C0DK  will do it after works ;)

**Comment by ShootingStarD** [comment]
@C0DK tried to do it but i do not manage to reproduce the code on a clean project

**Comment by matwasilewski** [comment]
Fixes

Thanks  @ShootingStarD, I tried your solution but unfortunately, it still doesn't work. My code and the full error are pasted below.

If we make a separate issue for the `step_context` problem, I'd be happy to look into it.

ERROR:
```
>           loaded_input = io_manager.load_input(input_context)

test_custom_io.py:86: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../ingest_dagster/utils/custom_io.py:57: in load_input
    partition_path = self._get_partition_path(asset_path, context)
../ingest_dagster/utils/custom_io.py:38: in _get_partition_path
    start, end = context.asset_partitions_time_window
../dagster-env/lib/python3.9/site-packages/dagster/_core/execution/context/input.py:408: in asset_partitions_time_window
    return self.step_context.asset_partitions_time_window_for_input(self.name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <dagster._core.execution.context.input.InputContext object at 0x16e953c70>

    @property
    def step_context(self) -> "StepExecutionContext":
        if self._step_context is None:
>           raise DagsterInvariantViolationError(
                "Attempting to access step_context, "
                "but it was not provided when constructing the InputContext"
            )
E           dagster._core.errors.DagsterInvariantViolationError: Attempting to access step_context, but it was not provided when constructing the InputContext

../dagster-env/lib/python3.9/site-packages/dagster/_core/execution/context/input.py:297: DagsterInvariantViolationError
Exception during reset or similar
Traceback (most recent call last):
  File "/Users/my_user/Code/dagster-ingest/dagster-env/lib/python3.9/site-packages/dagster/_core/execution/api.py", line 293, in ephemeral_instance_if_missing
    yield ephemeral_instance
  File "/Users/my_user/Code/dagster-ingest/dagster-env/lib/python3.9/site-packages/dagster/_core/execution/build_resources.py", line 108, in build_resources
    yield instantiated_resources.build(
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/my_user/Code/dagster-ingest/dagster-env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 763, in _finalize_fairy
    fairy._reset(pool, transaction_was_reset)
  File "/Users/my_user/Code/dagster-ingest/dagster-env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1038, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/my_user/Code/dagster-ingest/dagster-env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.
Exception during reset or similar
Traceback (most recent call last):
  File "/Users/my_user/Code/dagster-ingest/dagster-env/lib/python3.9/site-packages/dagster/_core/execution/api.py", line 293, in ephemeral_instance_if_missing
    yield ephemeral_instance
  File "/Users/my_user/Code/dagster-ingest/dagster-env/lib/python3.9/site-packages/dagster/_core/execution/build_resources.py", line 108, in build_resources
    yield instantiated_resources.build(
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/my_user/Code/dagster-ingest/dagster-env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 763, in _finalize_fairy
    fairy._reset(pool, transaction_was_reset)
  File "/Users/my_user/Code/dagster-ingest/dagster-env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1038, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/my_user/Code/dagster-ingest/dagster-env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

CODE, modified according to your suggestions:

```python
def test_partitioned_io_manager_with_non_zip_files():
    @asset(partitions_def=WEEKLY_PARTITION_DEF)
    def sample_asset(context: AssetExecutionContext):
        assets = []
        for idx in range(5):
            assets.append(
                DraftFileWithMetadata(
                    file_bytes=get_file_string(idx=idx, context=context).encode(
                        "utf-8"
                    ),
                    metadata={
                        "file_name": Path(f"element_{idx}.txt"),
                        "file_size": 10,
                        "file_uri": None,
                    },
                )
            )
        return assets

    with tempfile.TemporaryDirectory() as temp_dir:
        io_manager = PartitionedFilesIOManager(base_dir=temp_dir)
        dir_path = Path(temp_dir)

        res = materialize(
            assets=[sample_asset],
            resources={
                "io_manager": io_manager,
            },
            partition_key="2023-10-01",
        )
        expected_dir_path = dir_path / "sample_asset"

        assert res.success
        assert expected_dir_path.exists()
        assert expected_dir_path.is_dir()
        partition_dir_path = expected_dir_path / "2023-10-01_2023-10-08"
        assert partition_dir_path.exists()

        assert len(list(partition_dir_path.iterdir())) == 5
        assert all(
            [file_path.suffix == ".txt" for file_path in partition_dir_path.iterdir()]
        )

        input_context = build_input_context(
            name="input_context",
            asset_key=sample_asset.key,
            asset_partition_key_range=PartitionKeyRange(
                start="2023-10-01", end="2023-10-08"
            ),
            asset_partitions_def=WEEKLY_PARTITION_DEF,
            upstream_output=OutputContext(
            ),
        )
        loaded_input = io_manager.load_input(input_context)

        # loaded_input = io_manager.load_input(
        #     mock_input_context
        # )

        assert loaded_input
        assert len(loaded_input) == 5
        assert all([isinstance(element, DraftFileWithMetadata) for element in loaded_input])
        assert all(
            [
                element.file_bytes.decode('utf-8').startswith("Element no: ")
                for element in loaded_input
            ]
        )
        assert all(
            [
                element.file_bytes.decode('utf-8').endswith("From 2023-10-01 to 2023-10-08")
                for element in loaded_input
            ]
        )
        assert all(
            [
                element.metadata.file_name.name.startswith("element_")
                for element in loaded_input
            ]
        )
```

**Comment by geoHeil** [comment]
Any update on this? I am facing the same issue - even for a normal partition_key not the range
