### ISSUE TITLE
No check on "config" arg to @solid

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1873]
we should validate that `config` is a dict (might be worth seeing if other args are missing this check also)

**Comment by mgasner** [comment]
this is done in `resolve_config_field` -> `build_config_dict` -> `check_user_facing_fields_dict`

```
>>> from dagster import solid
>>> @solid(config='foo')
... def bar():
...     pass
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/decorators.py", line 349, in solid
    config_field=resolve_config_field(config_field, config, '@solid'),
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/config.py", line 20, in resolve_config_field
    return Field(Dict(config))
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/types/field_utils.py", line 229, in __call__
    return build_config_dict(fields)
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/types/field_utils.py", line 248, in build_config_dict
    check_user_facing_fields_dict(fields, 'Dict')
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/types/field_utils.py", line 191, in check_user_facing_fields_dict
    check.dict_param(fields, 'fields', key_type=str)
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/check/__init__.py", line 453, in dict_param
    raise_with_traceback(_param_type_mismatch_exception(obj, dict, param_name))
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
dagster.check.ParameterCheckError: Param "fields" is not a dict. Got 'foo' which is type <class 'str'>.
```

**Comment by natekupp** [comment]
Yeah my objection was that this is a confusing error for a first-time user of the system—as it happens a few layers down. Would be nice to tell someone what the issue is earlier in the process. Thoughts?
