### ISSUE TITLE
Build failure involving yarn?

### ISSUE THREAD

**Issue by TabLand** [dagster-io/dagster#18856]
### Dagster version

dagster, version 1!0+dev - 9406da52df3909c8f5b22f65100baf9a35b4dadb

### What's the issue?

Failed to build from source.

OS: Ubuntu 23.04
Python: 3.11.4
Yarn: 1.22.10

```
make rebuild_ui
...
/opt/source/dagster/js_modules/dagster-ui/.yarn/releases/yarn-4.0.2.cjs:4
...
SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
make: *** [Makefile:67: rebuild_ui] Error 1
```

Logs to be attached shortly...

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by TabLand** [comment]
[build.log](https://github.com/dagster-io/dagster/files/13742862/build.log)

**Comment by TabLand** [comment]
I've tried rolling back to a previous commit of .yarn: db18bc39a479b05469bb4523e053d7075f62b14c
Unfortunately, I get a different error:

```
SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.mod.require (/opt/source/dagster/js_modules/dagster-ui/node_modules/next/dist/server/require-hook.js:64:28)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/source/dagster/js_modules/dagster-ui/node_modules/next/dist/telemetry/post-payload.js:17:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
make: *** [Makefile:77: rebuild_ui] Error 1
```

I'll try reinstalling node and yarn before trying the build again...

**Comment by TabLand** [comment]
Interestingly enough, reinstalling nodejs + npm + yarn allowed me to build the webserver.
Node: v18.13.0
yarn: 1.22.10
