### ISSUE TITLE
UI error when viewing asset page of static partitioned asset after re-executing failed partitions

### ISSUE THREAD

**Issue by craustin** [dagster-io/dagster#19097]
### Dagster version

1.5.13

### What's the issue?

https://dagster/assets/partitioned_asset_name?status=FAILED&partition=static_partition_1&view=partitions

```
Unexpected undefined

Error: Unexpected undefined
    at notUndefined (https://dagster-macro.kobe.elementcapital.corp/_next/static/chunks/997.ed0daa79feb515f0.js:82:800)
    at Virtualizer.getOffsetForIndex (https://dagster-macro.kobe.elementcapital.corp/_next/static/chunks/997.ed0daa79feb515f0.js:91:8011)
    at Virtualizer.scrollToIndex (https://dagster-macro.kobe.elementcapital.corp/_next/static/chunks/997.ed0daa79feb515f0.js:91:9192)
    at https://dagster-macro.kobe.elementcapital.corp/_next/static/chunks/418.123b37924b9f5125.js:1:587918
    at Rj (https://dagster-macro.kobe.elementcapital.corp/_next/static/chunks/framework-d6095a5336d3e425.js:9:84179)
    at Ik (https://dagster-macro.kobe.elementcapital.corp/_next/static/chunks/framework-d6095a5336d3e425.js:9:113178)
    at Fk (https://dagster-macro.kobe.elementcapital.corp/_next/static/chunks/framework-d6095a5336d3e425.js:9:96035)
    at jg (https://dagster-macro.kobe.elementcapital.corp/_next/static/chunks/framework-d6095a5336d3e425.js:9:44900)
    at https://dagster-macro.kobe.elementcapital.corp/_next/static/chunks/framework-d6095a5336d3e425.js:9:111622
    at Qk (https://dagster-macro.kobe.elementcapital.corp/_next/static/chunks/framework-d6095a5336d3e425.js:9:111628)
```

Error persists after browser refresh. Switching to "Events" tab and back to "Partitions" causes the error to go away.

### How to reproduce?

1. Visit static partitioned asset page.
1. Filter to failed partitions only. (I had 3 failed partitions.)
1. Re-execute those failures by opening each in new tab and clicking "Re-execute"
1. Once those runs are enqueued, go back to partitioned asset page browser tab.
1. See UI error.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
This may be the same issue as https://github.com/dagster-io/dagster/pull/18772, which is resolved in 1.5.14.

Can you upgrade and see if the problem persists?

**Comment by craustin** [comment]
👍 Will test 1.5.14 as soon as it hits `conda-forge`.

**Comment by hellendag** [comment]
Thanks for verifying @craustin!
