### ISSUE TITLE
Passing hooks to `define_asset_job` yields an error

### ISSUE THREAD

**Issue by JasperHG90** [dagster-io/dagster#20416]
### Dagster version

1.6.5

### What's the issue?

I've copied the code from [this test](https://github.com/dagster-io/dagster/pull/14425/files#diff-060ba804a77599317147629aa0de87b7f26d12aa86e5a3cf0c5ef7a05d52fd3b) to see if hooks work for `define_asset_job`. This yields the following error:

```python
Traceback (most recent call last):
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/errors.py", line 287, in user_code_error_boundary
    yield
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_grpc/server.py", line 242, in __init__
    loadable_targets = get_loadable_targets(
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_grpc/utils.py", line 50, in get_loadable_targets
    else loadable_targets_from_python_module(module_name, working_directory)
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/workspace/autodiscovery.py", line 35, in loadable_targets_from_python_module
    module = load_python_module(
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/code_pointer.py", line 135, in load_python_module
    return importlib.import_module(module_name)
  File "/Users/jasperginn/.pyenv/versions/3.9.18/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/dags/luchtmeetnet_ingestion/src/luchtmeetnet_ingestion/__init__.py", line 21, in <module>
    definition = Definitions(
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/definitions/definitions_class.py", line 433, in __init__
    self._created_pending_or_normal_repo = _create_repository_using_definitions_args(
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/definitions/definitions_class.py", line 304, in _create_repository_using_definitions_args
    def created_repo():
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/definitions/decorators/repository_decorator.py", line 120, in __call__
    repository_definitions = fn()
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/definitions/definitions_class.py", line 306, in created_repo
    *with_resources(assets or [], resource_defs),
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/execution/with_resources.py", line 105, in with_resources
    transformed_defs.append(cast(T, definition.with_resources(resource_defs)))
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/definitions/assets.py", line 1405, in with_resources
    return self.__class__(**attributes_dict)
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/definitions/assets.py", line 337, in __init__
    if is_valid_email(owner):
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/utils.py", line 199, in is_valid_email
    return bool(re.fullmatch(regex, email))
  File "/Users/jasperginn/.pyenv/versions/3.9.18/lib/python3.9/re.py", line 196, in fullmatch
    return _compile(pattern, flags).fullmatch(string)
TypeError: expected string or bytes-like object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_grpc/server.py", line 408, in __init__
    self._loaded_repositories: Optional[LoadedRepositories] = LoadedRepositories(
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_grpc/server.py", line 242, in __init__
    loadable_targets = get_loadable_targets(
  File "/Users/jasperginn/.pyenv/versions/3.9.18/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/errors.py", line 297, in user_code_error_boundary
    raise new_error from e
dagster._core.errors.DagsterUserCodeLoadError: Error occurred during the loading of Dagster definitions in
executable_path=/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/bin/python, module_name=luchtmeetnet_ingestion, working_directory=/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/dags/luchtmeetnet_ingestion
/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/workspace/context.py:619: UserWarning: Error loading repository location luchtmeetnet_ingestion:dagster._core.errors.DagsterUserCodeLoadError: Error occurred during the loading of Dagster definitions in
executable_path=/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/bin/python, module_name=luchtmeetnet_ingestion, working_directory=/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/dags/luchtmeetnet_ingestion

Stack Trace:
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_grpc/server.py", line 408, in __init__
    self._loaded_repositories: Optional[LoadedRepositories] = LoadedRepositories(
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_grpc/server.py", line 242, in __init__
    loadable_targets = get_loadable_targets(
  File "/Users/jasperginn/.pyenv/versions/3.9.18/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/errors.py", line 297, in user_code_error_boundary
    raise new_error from e

The above exception was caused by the following exception:
TypeError: expected string or bytes-like object

Stack Trace:
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/errors.py", line 287, in user_code_error_boundary
    yield
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_grpc/server.py", line 242, in __init__
    loadable_targets = get_loadable_targets(
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_grpc/utils.py", line 50, in get_loadable_targets
    else loadable_targets_from_python_module(module_name, working_directory)
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/workspace/autodiscovery.py", line 35, in loadable_targets_from_python_module
    module = load_python_module(
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/code_pointer.py", line 135, in load_python_module
    return importlib.import_module(module_name)
  File "/Users/jasperginn/.pyenv/versions/3.9.18/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/dags/luchtmeetnet_ingestion/src/luchtmeetnet_ingestion/__init__.py", line 21, in <module>
    definition = Definitions(
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/definitions/definitions_class.py", line 433, in __init__
    self._created_pending_or_normal_repo = _create_repository_using_definitions_args(
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/definitions/definitions_class.py", line 304, in _create_repository_using_definitions_args
    def created_repo():
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/definitions/decorators/repository_decorator.py", line 120, in __call__
    repository_definitions = fn()
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/definitions/definitions_class.py", line 306, in created_repo
    *with_resources(assets or [], resource_defs),
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/execution/with_resources.py", line 105, in with_resources
    transformed_defs.append(cast(T, definition.with_resources(resource_defs)))
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/definitions/assets.py", line 1405, in with_resources
    return self.__class__(**attributes_dict)
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/definitions/assets.py", line 337, in __init__
    if is_valid_email(owner):
  File "/Users/jasperginn/Documents/code_projects/dagster/dagster-dags/shared/dagster_utils/.venv/lib/python3.9/site-packages/dagster/_core/utils.py", line 199, in is_valid_email
    return bool(re.fullmatch(regex, email))
  File "/Users/jasperginn/.pyenv/versions/3.9.18/lib/python3.9/re.py", line 196, in fullmatch
    return _compile(pattern, flags).fullmatch(string)

  warnings.warn(f"Error loading repository location {location_name}:{error.to_string()}")
```

### What did you expect to happen?

To be able to use hooks without an error

### How to reproduce?

I simply copied the code and added it to my repository. Not sure if the same thing happens in a clean repo.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Looks like the stack trace indicates that the error originates from the `is_valid_email` function in the dagster/_core/utils.py file. This function is being called with an argument email that is not a string or bytes-like object, which is causing the re.fullmatch function to fail.

**Comment by JasperHG90** [comment]
This is actually caused by another change in the code that I wasn't aware of (owners field in asset). Closing. Thanks for your quick reply!
