### ISSUE TITLE
alembic errors in dagstermill on fresh master in BK

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2085]
See https://dagster.phacility.com/D1884

https://buildkite.com/dagster/dagster/builds/9591#043856d4-6090-4d17-83a4-63db1b14bf9d

```

----------------------------- Captured stderr call -----------------------------
--
  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
  | 2020-01-27 16:14:40 - dagster - DEBUG - hello_logging_pipeline - c127bf51-753b-48af-9638-cff6029d11ee - PIPELINE_START - Started execution of pipeline "hello_logging_pipeline".
  | Exception in thread Thread-65:
  | Traceback (most recent call last):
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
  | cursor, statement, parameters, context
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
  | cursor.execute(statement, parameters)
  | sqlite3.OperationalError: no such table: event_logs
  |  
  | The above exception was the direct cause of the following exception:
  |  
  | Traceback (most recent call last):
  | File "/workdir/python_modules/dagster/dagster/core/storage/sql.py", line 53, in handle_schema_errors
  | yield
  | File "/workdir/python_modules/dagster/dagster/core/storage/event_log/sqlite/sqlite_event_log.py", line 108, in connect
  | yield conn
  | File "/workdir/python_modules/dagster/dagster/core/storage/event_log/sql_event_log.py", line 82, in get_logs_for_run
  | results = conn.execute(query).fetchall()
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
  | return meth(self, multiparams, params)
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
  | return connection._execute_clauseelement(self, multiparams, params)
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
  | distilled_params,
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
  | e, statement, parameters, cursor, context
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
  | util.raise_from_cause(sqlalchemy_exception, exc_info)
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
  | reraise(type(exception), exception, tb=exc_tb, cause=cause)
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
  | raise value.with_traceback(tb)
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
  | cursor, statement, parameters, context
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
  | cursor.execute(statement, parameters)
  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: event_logs
  | [SQL: SELECT event_logs.event
  | FROM event_logs
  | WHERE event_logs.run_id = ? AND event_logs.id >= ? ORDER BY event_logs.id ASC]
  | [parameters: ('c127bf51-753b-48af-9638-cff6029d11ee', -1)]
  | (Background on this error at: http://sqlalche.me/e/e3q8)
  |  
  | The above exception was the direct cause of the following exception:
  |  
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
  | self.run()
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/watchdog/observers/api.py", line 196, in run
  | self.dispatch_events(self.event_queue, self.timeout)
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/watchdog/observers/api.py", line 369, in dispatch_events
  | handler.dispatch(event)
  | File "/workdir/python_modules/dagstermill/.tox/py36/lib/python3.6/site-packages/watchdog/events.py", line 462, in dispatch
  | _method_map[event_type](event)
  | File "/workdir/python_modules/dagster/dagster/core/storage/event_log/sqlite/sqlite_event_log.py", line 156, in on_created
  | self._process_log()
  | File "/workdir/python_modules/dagster/dagster/core/storage/event_log/sqlite/sqlite_event_log.py", line 146, in _process_log
  | events = self._event_log_storage.get_logs_for_run(self._run_id, self._cursor)
  | File "/workdir/python_modules/dagster/dagster/core/storage/event_log/sql_event_log.py", line 82, in get_logs_for_run
  | results = conn.execute(query).fetchall()
  | File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
  | self.gen.throw(type, value, traceback)
  | File "/workdir/python_modules/dagster/dagster/core/storage/event_log/sqlite/sqlite_event_log.py", line 108, in connect
  | yield conn
  | File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
  | self.gen.throw(type, value, traceback)
  | File "/workdir/python_modules/dagster/dagster/core/storage/sql.py", line 70, in handle_schema_errors
  | exc,
  | File "<string>", line 3, in raise_from
  | dagster.core.errors.DagsterInstanceMigrationRequired: Instance is out of date and must be migrated (SqliteEventLogStorage for run c127bf51-753b-48af-9638-cff6029d11ee). Database is at revision None, head is 567bc23fd1ac. Please run `dagster instance migrate`.


```

**Comment by mgasner** [comment]
https://dagster.phacility.com/D1889
