### ISSUE TITLE
sqlite3.ProgrammingError: Cannot operate on a closed database.

### ISSUE THREAD

**Issue by marcilj** [dagster-io/dagster#21586]
### Dagster version

dagster, version 1.6.1

### What's the issue?

Everytime I run dagster locally I run into this error.

It doesn't affect dagster, like everything is working as expected, but I wonder why I see that error each time.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jacobmarcil/.local/share/virtualenvs/datateam-dagster-cloud-ln6uzjO0/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 763, in _finalize_fairy
    fairy._reset(pool, transaction_was_reset)
  File "/Users/jacobmarcil/.local/share/virtualenvs/datateam-dagster-cloud-ln6uzjO0/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1038, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/jacobmarcil/.local/share/virtualenvs/datateam-dagster-cloud-ln6uzjO0/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.
Exception during reset or similar
Traceback (most recent call last):
  File "/Users/jacobmarcil/.local/share/virtualenvs/datateam-dagster-cloud-ln6uzjO0/lib/python3.8/site-packages/dagster/_core/execution/api.py", line 293, in ephemeral_instance_if_missing
    yield ephemeral_instance
GeneratorExit
```

The same error is shown 9 times.

### What did you expect to happen?

Not showing any errors.

### How to reproduce?

For me it's running `dagster dev` or `pytest` on my dagster project.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by stevenmurphy12** [comment]
I see the same issue on Dagster `1.7.14` when deployed to Kubernetes. Functionally it seems fine, I don't get the same issue locally

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/api.py", line 290, in ephemeral_instance_if_missing
    yield ephemeral_instance
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 986, in _finalize_fairy
    fairy._reset(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1432, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 698, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.
Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/api.py", line 290, in ephemeral_instance_if_missing
    yield ephemeral_instance
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 986, in _finalize_fairy
    fairy._reset(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1432, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 698, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.
Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/api.py", line 290, in ephemeral_instance_if_missing
    yield ephemeral_instance
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 986, in _finalize_fairy
    fairy._reset(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1432, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 698, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.
Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/api.py", line 290, in ephemeral_instance_if_missing
    yield ephemeral_instance
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 986, in _finalize_fairy
    fairy._reset(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1432, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 698, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

**Comment by lydialimlh** [comment]
Is there any solution to this? It is still happening in Dagster 1.9.3. Doesn't affect functionality but it is annoying to see during `pytest`.

**Comment by Auric-Manteo** [comment]
Still happening in 2025. Is there a workaround?

**Comment by stevenmurphy12** [comment]
I haven't seen it recently. My guess is that there was a transitive dependency in our Docker image which is no longer being pulled in as part of our builds. We switched from using `pip` to `poetry` for dependency management which gives us more certainty in that regard.

**Comment by jessica18brooks** [comment]
In case it helps anyone, I came across this issue on `1.12.8` when running pytest locally. The fix that worked for me was using `build_asset_context()` within a context manager and using that as a fixture.
```
@pytest.fixture
def asset_context():
    with build_asset_context() as context:
        yield context
```
