### ISSUE TITLE
get_loadable_targets and LoadedRepositories errors in Dagster Univserity dbt

### ISSUE THREAD

**Issue by dbrtly** [dagster-io/dagster#21796]
### Dagster version

dagster, version 1.6.14

### What's the issue?

```

dagster-dbt) project-dagster-university[\w]\n$ dagster dev
2024-05-11 12:50:35 +1000 - dagster - INFO - Loaded environment variables from .env file: DUCKDB_DATABASE,DAGSTER_ENVIRONMENT
2024-05-11 12:50:35 +1000 - dagster - INFO - Using temporary directory /Users/danielbartley/code/project-dagster-university/tmpyry680ww for storage. This will be removed when dagster dev exits.
2024-05-11 12:50:35 +1000 - dagster - INFO - To persist information across sessions, set the environment variable DAGSTER_HOME to a directory to use.
2024-05-11 12:50:35 +1000 - dagster - INFO - Launching Dagster services...
2024-05-11 12:50:37 +1000 - dagster-webserver - INFO - Loaded environment variables from .env file: DUCKDB_DATABASE,DAGSTER_ENVIRONMENT
2024-05-11 12:51:05 +1000 - dagster.code_server - ERROR - Error while importing code
Traceback (most recent call last):
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/errors.py", line 287, in user_code_error_boundary
    yield
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 242, in __init__
    loadable_targets = get_loadable_targets(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/utils.py", line 50, in get_loadable_targets
    else loadable_targets_from_python_module(module_name, working_directory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/workspace/autodiscovery.py", line 35, in loadable_targets_from_python_module
    module = load_python_module(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/code_pointer.py", line 134, in load_python_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/.asdf/installs/python/3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/danielbartley/code/project-dagster-university/dagster_university/__init__.py", line 4, in <module>
    from .jobs import adhoc_request_job, trip_update_job, weekly_update_job
  File "/Users/danielbartley/code/project-dagster-university/dagster_university/jobs/__init__.py", line 5, in <module>
    trips_by_week = AssetSelection.assets("trips_by_week")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/definitions/asset_selection.py", line 108, in assets
    selected_keys=[key for assets_def in assets_defs for key in assets_def.keys]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/definitions/asset_selection.py", line 108, in <listcomp>
    selected_keys=[key for assets_def in assets_defs for key in assets_def.keys]
                                                                ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 408, in __init__
    self._loaded_repositories: Optional[LoadedRepositories] = LoadedRepositories(
                                                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 235, in __init__
    with user_code_error_boundary(
  File "/Users/danielbartley/.asdf/installs/python/3.11.9/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/errors.py", line 297, in user_code_error_boundary
    raise new_error from e
dagster._core.errors.DagsterUserCodeLoadError: Error occurred during the loading of Dagster definitions in
executable_path=/Users/danielbartley/code/project-dagster-university/.venv/bin/python, module_name=dagster_university, working_directory=/Users/danielbartley/code/project-dagster-university
2024-05-11 12:51:05 +1000 - dagster.code_server - ERROR - Error while importing code
Traceback (most recent call last):
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/errors.py", line 287, in user_code_error_boundary
    yield
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 242, in __init__
    loadable_targets = get_loadable_targets(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/utils.py", line 50, in get_loadable_targets
    else loadable_targets_from_python_module(module_name, working_directory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/workspace/autodiscovery.py", line 35, in loadable_targets_from_python_module
    module = load_python_module(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/code_pointer.py", line 134, in load_python_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/.asdf/installs/python/3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/danielbartley/code/project-dagster-university/dagster_university/__init__.py", line 4, in <module>
    from .jobs import adhoc_request_job, trip_update_job, weekly_update_job
  File "/Users/danielbartley/code/project-dagster-university/dagster_university/jobs/__init__.py", line 5, in <module>
    trips_by_week = AssetSelection.assets("trips_by_week")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/definitions/asset_selection.py", line 108, in assets
    selected_keys=[key for assets_def in assets_defs for key in assets_def.keys]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/definitions/asset_selection.py", line 108, in <listcomp>
    selected_keys=[key for assets_def in assets_defs for key in assets_def.keys]
                                                                ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 408, in __init__
    self._loaded_repositories: Optional[LoadedRepositories] = LoadedRepositories(
                                                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 235, in __init__
    with user_code_error_boundary(
  File "/Users/danielbartley/.asdf/installs/python/3.11.9/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/errors.py", line 297, in user_code_error_boundary
    raise new_error from e
dagster._core.errors.DagsterUserCodeLoadError: Error occurred during the loading of Dagster definitions in
executable_path=/Users/danielbartley/code/project-dagster-university/.venv/bin/python, module_name=dagster_university, working_directory=/Users/danielbartley/code/project-dagster-university
/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/workspace/context.py:622: UserWarning: Error loading repository location dagster_university:dagster._core.errors.DagsterUserCodeLoadError: Error occurred during the loading of Dagster definitions in
executable_path=/Users/danielbartley/code/project-dagster-university/.venv/bin/python, module_name=dagster_university, working_directory=/Users/danielbartley/code/project-dagster-university

Stack Trace:
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 408, in __init__
    self._loaded_repositories: Optional[LoadedRepositories] = LoadedRepositories(
                                                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 235, in __init__
    with user_code_error_boundary(
  File "/Users/danielbartley/.asdf/installs/python/3.11.9/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/errors.py", line 297, in user_code_error_boundary
    raise new_error from e

The above exception was caused by the following exception:
AttributeError: 'str' object has no attribute 'keys'

Stack Trace:
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/errors.py", line 287, in user_code_error_boundary
    yield
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 242, in __init__
    loadable_targets = get_loadable_targets(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/utils.py", line 50, in get_loadable_targets
    else loadable_targets_from_python_module(module_name, working_directory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/workspace/autodiscovery.py", line 35, in loadable_targets_from_python_module
    module = load_python_module(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/code_pointer.py", line 134, in load_python_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/.asdf/installs/python/3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/danielbartley/code/project-dagster-university/dagster_university/__init__.py", line 4, in <module>
    from .jobs import adhoc_request_job, trip_update_job, weekly_update_job
  File "/Users/danielbartley/code/project-dagster-university/dagster_university/jobs/__init__.py", line 5, in <module>
    trips_by_week = AssetSelection.assets("trips_by_week")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/definitions/asset_selection.py", line 108, in assets
    selected_keys=[key for assets_def in assets_defs for key in assets_def.keys]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/definitions/asset_selection.py", line 108, in <listcomp>
    selected_keys=[key for assets_def in assets_defs for key in assets_def.keys]
                                                                ^^^^^^^^^^^^^^^

  warnings.warn(f"Error loading repository location {location_name}:{error.to_string()}")
/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/workspace/context.py:622: UserWarning: Error loading repository location dagster_university:dagster._core.errors.DagsterUserCodeLoadError: Error occurred during the loading of Dagster definitions in
executable_path=/Users/danielbartley/code/project-dagster-university/.venv/bin/python, module_name=dagster_university, working_directory=/Users/danielbartley/code/project-dagster-university

Stack Trace:
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 408, in __init__
    self._loaded_repositories: Optional[LoadedRepositories] = LoadedRepositories(
                                                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 235, in __init__
    with user_code_error_boundary(
  File "/Users/danielbartley/.asdf/installs/python/3.11.9/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/errors.py", line 297, in user_code_error_boundary
    raise new_error from e

The above exception was caused by the following exception:
AttributeError: 'str' object has no attribute 'keys'

Stack Trace:
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/errors.py", line 287, in user_code_error_boundary
    yield
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 242, in __init__
    loadable_targets = get_loadable_targets(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/utils.py", line 50, in get_loadable_targets
    else loadable_targets_from_python_module(module_name, working_directory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/workspace/autodiscovery.py", line 35, in loadable_targets_from_python_module
    module = load_python_module(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/code_pointer.py", line 134, in load_python_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/.asdf/installs/python/3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/danielbartley/code/project-dagster-university/dagster_university/__init__.py", line 4, in <module>
    from .jobs import adhoc_request_job, trip_update_job, weekly_update_job
  File "/Users/danielbartley/code/project-dagster-university/dagster_university/jobs/__init__.py", line 5, in <module>
    trips_by_week = AssetSelection.assets("trips_by_week")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/definitions/asset_selection.py", line 108, in assets
    selected_keys=[key for assets_def in assets_defs for key in assets_def.keys]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/definitions/asset_selection.py", line 108, in <listcomp>
    selected_keys=[key for assets_def in assets_defs for key in assets_def.keys]
                                                                ^^^^^^^^^^^^^^^

  warnings.warn(f"Error loading repository location {location_name}:{error.to_string()}")
2024-05-11 12:51:05 +1000 - dagster.daemon - INFO - Instance is configured with the following daemons: ['AssetDaemon', 'BackfillDaemon', 'SchedulerDaemon', 'SensorDaemon']
2024-05-11 12:51:05 +1000 - dagster-webserver - INFO - Serving dagster-webserver on http://127.0.0.1:3000 in process 49268
```

===============================================================
error show in dagster web ui

```
dagster._core.errors.DagsterUserCodeLoadError: Error occurred during the loading of Dagster definitions in
executable_path=/Users/danielbartley/code/project-dagster-university/.venv/bin/python, module_name=dagster_university, working_directory=/Users/danielbartley/code/project-dagster-university

  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 408, in __init__
    self._loaded_repositories: Optional[LoadedRepositories] = LoadedRepositories(
                                                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 235, in __init__
    with user_code_error_boundary(
  File "/Users/danielbartley/.asdf/installs/python/3.11.9/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/errors.py", line 297, in user_code_error_boundary
    raise new_error from e

The above exception was caused by the following exception:
AttributeError: 'str' object has no attribute 'keys'

  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/errors.py", line 287, in user_code_error_boundary
    yield
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/server.py", line 242, in __init__
    loadable_targets = get_loadable_targets(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_grpc/utils.py", line 50, in get_loadable_targets
    else loadable_targets_from_python_module(module_name, working_directory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/workspace/autodiscovery.py", line 35, in loadable_targets_from_python_module
    module = load_python_module(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/code_pointer.py", line 134, in load_python_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/.asdf/installs/python/3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/danielbartley/code/project-dagster-university/dagster_university/__init__.py", line 4, in <module>
    from .jobs import adhoc_request_job, trip_update_job, weekly_update_job
  File "/Users/danielbartley/code/project-dagster-university/dagster_university/jobs/__init__.py", line 5, in <module>
    trips_by_week = AssetSelection.assets("trips_by_week")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/definitions/asset_selection.py", line 108, in assets
    selected_keys=[key for assets_def in assets_defs for key in assets_def.keys]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbartley/code/project-dagster-university/.venv/lib/python3.11/site-packages/dagster/_core/definitions/asset_selection.py", line 108, in <listcomp>
    selected_keys=[key for assets_def in assets_defs for key in assets_def.keys]
                                                                ^^^^^^^^^^^^^^^
```

### What did you expect to happen?

dagster should start without error

### How to reproduce?

macos 14.4.1 (23E224)
asdf local python 3.11.9
asdf install
pipx --version # got 1.5

# get repo
pipx install dagster
dagster project from-example --name project-dagster-university --example project_du_dbt_starter
pipx uninstall dagster

# start project
python -m venv .venv --prompt dagster-dbt
source .venv/bin/activate
pip install dagster-dbt dbt-duckdb
cp .env.example .env
pip install -e ".[dev]"

### Deployment type

None

### Additional information

The quickstart project at  https://github.com/dagster-io/dagster-quickstart does work for me without the error.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tacastillo** [comment]
Hey @dbrtly! Sorry to hear you've encountered this. What version of dbt are you using? Do you mind pushing up your code to a new repo and sharing your `pip freeze` output?

cc: @cmpadden who has seen this recently

**Comment by cmpadden** [comment]
For context, here is a recent discussion in the community Slack where someone experienced a similar issue.

https://dagster.slack.com/archives/C060X0EB7K4/p1714008685452319

<img width="656" alt="image" src="https://github.com/dagster-io/dagster/assets/5807118/bcd9ddd1-56dd-4cca-bc60-b6d2e25fb239">

**Comment by cmpadden** [comment]
Hi @dbrtly - wanted to follow up here to let you know that this was due to a change in Dagster v1.6.* and v1.7.*.

If you could please upgrade your project to 1.7, then you should be good to go.

We've updated the starter project to 1.7 here - https://github.com/dagster-io/project-dagster-university/pull/26.
