### ISSUE TITLE
make pyright error

### ISSUE THREAD

**Issue by dbrtly** [dagster-io/dagster#21800]
### Dagster version

dagster, version 1!0+dev

### What's the issue?

This is probably a me thing but I don't know what it is.

(dagster) [\w]\n$ make pyright 
python scripts/run-pyright.py --all
Creating virtualenv for pyright environment master...
Copying /Users/danielbartley/code/dagster-labs/dagster/pyright/master/requirements-pinned.txt to requirements-master.txt....
Using Python 3.10.14 interpreter at: /Users/danielbartley/code/dagster-labs/.venv/bin/python
Creating virtualenv at: pyright/master/.venv
 + pip==24.0
 + setuptools==69.5.1
 + wheel==0.43.0
Activate with: source pyright/master/.venv/bin/activate
Resolved 3 packages in 3ms
Audited 3 packages in 0.03ms
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labs
   Built file:///Users/danielbartley/code/dagster-labsBuilt 75 editables in 14.99s
  × No solution found when resolving
  │ dependencies:
  ╰─▶ Because torch==2.3.0 has no wheels
      are available with a matching Python
      implementation and you require
      torch==2.3.0, we can conclude that the
      requirements are unsatisfiable.
Partially built virtualenv for pyright environment master deleted.
Traceback (most recent call last):
  File "/Users/danielbartley/code/dagster-labs/dagster/scripts/run-pyright.py", line 524, in <module>
    normalize_env(env, params["rebuild"], params["update_pins"], params["venv_python"])
  File "/Users/danielbartley/code/dagster-labs/dagster/scripts/run-pyright.py", line 322, in normalize_env
    raise e
  File "/Users/danielbartley/code/dagster-labs/dagster/scripts/run-pyright.py", line 318, in normalize_env
    subprocess.run(build_venv_cmd, shell=True, check=True)
  File "/Users/danielbartley/.asdf/installs/python/3.10.14/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'uv venv --python=/Users/danielbartley/code/dagster-labs/.venv/bin/python --seed /Users/danielbartley/code/dagster-labs/dagster/pyright/master/.venv && uv pip install --python /Users/danielbartley/code/dagster-labs/dagster/pyright/master/.venv/bin/python -U pip setuptools wheel && uv pip install --python /Users/danielbartley/code/dagster-labs/dagster/pyright/master/.venv/bin/python -r requirements-master.txt --config-settings editable-mode=compat --no-deps' returned non-zero exit status 1.
make: *** [pyright] Error 1

### What did you expect to happen?

running on default branch should execute with no errors.

### How to reproduce?

git clone, install in contributing mode, `make pyright`

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by JPercivall** [comment]
@dbrtly I'm hitting this same issue. Did you find a fix or workaround?

**Comment by JPercivall** [comment]
For me at least, I believe this is because torch stopped supporting intel macs (what I have) with the 2.3.0  release: https://dev-discuss.pytorch.org/t/pytorch-macos-x86-builds-deprecation-starting-january-2024/1690

Not really an easy way to get around that without manually building torch.

**Comment by dbrtly** [comment]
> For me at least, I believe this is because torch stopped supporting intel macs (what I have) with the 2.3.0 release: https://dev-discuss.pytorch.org/t/pytorch-macos-x86-builds-deprecation-starting-january-2024/1690
> 
> Not really an easy way to get around that without manually building torch.

Plausible. I am indeed on an intel mac.
