### ISSUE TITLE
schedules shell files fail if $HOME != $DAGSTER_PATH

### ISSUE THREAD

**Issue by bobzoller** [dagster-io/dagster#2185]
dagster 0.7.0, debian buster, debian cron

we've got a schedule that generates this crontab:
```
1,11,21,31,41,51 * * * * /app/schedules/scripts/main_repository.gsheets_ingest_schedule.sh # dagster-schedule: main_repository.gsheets_ingest_schedule
```

and this is the generated script referenced above:
```

            #!/bin/bash
            export DAGSTER_HOME=/app
            export LANG=en_US.UTF-8
            

            export RUN_DATE=$(date "+%Y%m%dT%H%M%S")

            /home/docker/.local/share/virtualenvs/app-4PlAip0Q/bin/dagster-graphql -p startScheduledExecution -v '{"scheduleName": "gsheets_ingest_schedule"}' -y "/app/repository.yaml" --output "/app/schedules/logs/main_repository/gsheets_ingest_schedule/${RUN_DATE}_gsheets_ingest_schedule.result"
```

but when cron executes it (as our unprivileged docker user), the working directory is docker's home, `/home/docker`.  dagster-graphql barfs, not able to load the `repos` module.

```
/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/dagster/core/storage/sql.py:39: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got Engine(sqlite:////app/schedules/schedules.db)
  migration_context = MigrationContext.configure(conn)
Traceback (most recent call last):
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/bin/dagster-graphql", line 8, in <module>
    sys.exit(main())
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/dagster_graphql/cli.py", line 216, in main
    cli(obj={})  # pylint:disable=E1120
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/dagster_graphql/cli.py", line 208, in ui
    execute_query_from_cli(handle, query, variables, output)
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/dagster_graphql/cli.py", line 91, in execute_query_from_cli
    result_dict = execute_query(
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/dagster_graphql/cli.py", line 51, in execute_query
    context = DagsterGraphQLContext(
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/dagster_graphql/implementation/context.py", line 18, in __init__
    self.repository_definition = self.get_handle().build_repository_definition()
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/dagster/core/definitions/handle.py", line 495, in build_repository_definition
    obj = self.entrypoint.perform_load()
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/dagster/core/definitions/handle.py", line 552, in entrypoint
    return self.data.get_repository_entrypoint(from_handle=self)
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/dagster/core/definitions/handle.py", line 635, in get_repository_entrypoint
    return LoaderEntrypoint.from_yaml(self.repository_yaml, from_handle=from_handle)
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/dagster/core/definitions/handle.py", line 252, in from_yaml
    return LoaderEntrypoint.from_module_target(module_name, fn_name, from_handle)
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/dagster/core/definitions/handle.py", line 238, in from_module_target
    module = importlib.import_module(module_name)
  File "/home/docker/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'repos'
```

if I cd to $DAGSTER_HOME first and run the script again, it works as expected.

can we make something in that chain cd to $DAGSTER_HOME and/or make dagster_graphql run from anywhere?

**Comment by bobzoller** [comment]
also -- when cron tries to execute that script and it fails -- the output is swallowed because we're in a container without an MTA set up...  made debugging this harder, and I wonder if there's some output redirection that dagster could also include that might surface the error to us?

**Comment by alangenfeld** [comment]
how do you have `/app/repository.yaml` set up? is `repos` a module you have installed?

**Comment by bobzoller** [comment]
```
$ cd "$DAGSTER_HOME"
$ cat repository.yaml 
repository:
  module: repos.repos
  fn: define_repo
scheduler:
  module: schedules.schedules
  fn: define_scheduler
$ ls -l repos/
total 8
-rw-r--r--  1 bob  staff    0 Feb 10 14:34 __init__.py
-rw-r--r--  1 bob  staff  204 Feb 18 22:33 repos.py
```

/cc @dwallace0723 in case you're going to ask _why_ it is the way it is ;)

**Comment by alangenfeld** [comment]
I *think* if you make sure `repos` is appropriately `pip install`ed (potentially `-e`) in to the virtual environment or use the `file:` variant of specifying the target in `repository.yaml` it should work.

**Comment by bobzoller** [comment]
thanks!  you're right -- using `file:` resolved the immediate issue -- but now when it loads our repo.py file, it chokes on the next import:

```
$ grep pipelines repos/repos.py
from pipelines import gsheet_ingest_pipeline
$ ls "$DAGSTER_HOME/pipelines"
__init__.py  gsheet_ingest.py
$ cd /home/docker
$ /app/schedules/scripts/main_repository.gsheets_ingest_schedule.sh
[...snip...]
ModuleNotFoundError: No module named 'pipelines'
```

we tried making it a relative import (`from .pipelines`), but got _ImportError: attempted relative import with no known parent package_.

**Comment by alangenfeld** [comment]
hm - you could either make sure these modules are actually installed (likely with `pip install -e` or manipulate the path to allow the relative to imports to work anyway with something like:
```
SCRIPT_PATH = os.path.dirname(os.path.abspath(__file__))
sys.path.append(SCRIPT_PATH)
```

**Comment by bobzoller** [comment]
fair enough, we'll do this.  thanks!
