### ISSUE TITLE
dagster_pipes.DagsterPipesError: Cannot send message after pipes context is closed."

### ISSUE THREAD

**Issue by JasperHG90** [dagster-io/dagster#22094]
### Dagster version

1.7.7

### What's the issue?

I'm implementing 'dagster-pipes' for a GCP cloud function based on the [AWS Lambda example](https://docs.dagster.io/concepts/dagster-pipes/aws-lambda) and source code. 

The first time that I invoke the function using a dagster asset, everything is OK. I see the logs from the message writer in GCP:

<img width="1182" alt="image" src="https://github.com/dagster-io/dagster/assets/8079803/eecdff40-e8ff-4f5f-af7f-5a8fdc8f8eb0">

On subsequent invocations, however, the cloud function errors and I see:

```
textPayload: "Exception on / [POST]
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/functions_framework/execution_id.py", line 106, in wrapper
    return view_function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/functions_framework/__init__.py", line 142, in view_func
    return function(request._get_current_object())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/main.py", line 22, in main
    pipes.log.info(f"Version: {__version__}")
  File "/layers/google.python.runtime/python/lib/python3.11/logging/__init__.py", line 1489, in info
    self._log(INFO, msg, args, **kwargs)
  File "/layers/google.python.runtime/python/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/layers/google.python.runtime/python/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/layers/google.python.runtime/python/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/layers/google.python.runtime/python/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/dagster_pipes/__init__.py", line 424, in emit
    self._context._write_message(  # noqa: SLF001
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/dagster_pipes/__init__.py", line 1077, in _write_message
    raise DagsterPipesError("Cannot send message after pipes context is closed.")
```

When I redeploy the cloud function, I can call the function again without issue.

### What did you expect to happen?

I expect it to run on every invocation, and invocations of cloud functions to be independent of each other.

### How to reproduce?

Reproduce instructions can be found in comment below

### Deployment type

Local

### Deployment details

I run dagster locally and am using the lambda dagster-pipes example in a google cloud function.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by JasperHG90** [comment]
I have added a reproducible example [here](https://github.com/JasperHG90/dagster-pipes-gcp).

Turns out I'm getting the same error locally using the `functions-framework` library.

To reproduce:

1. Clone, set up and open in devcontainer
2. Execute `just install`
3. Execute `just serve` in one terminal
4. Execute `just dagster_dev` in another terminal
5. Go to local dagster webserver. Materialize asset. This should work and give you the logs that you expect.
6. Materialize the asset a second time. This yields the error "raise DagsterPipesError("Cannot send message after pipes context is closed.")"

**Comment by JasperHG90** [comment]
I've investigated this a little further, and what seems to happen is this:

- On the first call from dagster to the cloud function, context is passed and `open_dagster_pipes()` proceeds as expected. 
- On the second call, [these lines](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster-pipes/dagster_pipes/__init__.py#L977-L978) are hit and the pipescontext from the previous call is returned, which is indeed already closed.

I'm a little confused about how this works. Why is the pipescontext persisted like this? It's a singleton so there should be only one, but then how do I tell Dagster that the session is finished and closed and the context information from the first call should be wiped?

Perhaps I'm fundamentally misunderstanding what's going on here, but I'd love to hear how I can fix this!

**Comment by tanguylefloch-veesion** [comment]
I seem to have a very similar issue with a lambda function running in a docker so for now I can't use the lambda pipes. Not sure what debugging information would be useful.
My invocations tend to take a long time (several minutes) and hang a bit but every new materialization attempt ends up very quickly with the same erro as above.

**Comment by sofianelounici** [comment]
I have the same issues with lambda function (first invocation is OK, then it doesn't work with the same exact error. Only new deploy of the lambda function will reset the PipesContext).
The given fix (to add ```PipesContext._instance = None``` in the lambda code) works, I'm also curious on how we can fix this.

**Comment by tlongatalaya** [comment]
I had the same issue and created my own context manager which uses `open_dagster_pipes` but sets `PipesContext._instance = None` before calling `__exit__`. Seems like it might make sense to reset the `_instance` var when the context is closed to avoid this issue?

**Comment by dodofarm** [comment]
Just getting into Dagster and got the same error with this hello world function here:

```python

from typing import Any
from time import sleep

from dagster_pipes import (
    PipesMappingParamsLoader,
    open_dagster_pipes,
)


def lambda_handler(event: dict[str, Any], _lambda_context: object) -> dict[str, str]:
    """Lambda entry point invoked by Dagster Pipes."""
    with open_dagster_pipes(params_loader=PipesMappingParamsLoader(event)) as pipes:
        pipes.log.info(f"connector-example invoked {event}")
        sleep(2)
        pipes.report_asset_materialization(
            metadata={
                "row_count": 42,
                "example_value": 10
            },
        )
    return {"status": "ok"}
```
