### ISSUE TITLE
Problem finding datetime_ambiguous on EMR 

### ISSUE THREAD

**Issue by HPicatto** [dagster-io/dagster#22586]
### Dagster version

dagster, version 1.7.10

### What's the issue?

We had some assets that were working with no issues till may:
```
Traceback (most recent call last):
  File "/mnt/yarn/usercache/hadoop/appcache/application_1718696690706_0001/container_1718696690706_0001_02_000001/01_nodes.py", line 12, in <module>
    from ascii_library.orchestration.pipes.spark_pipes import Engine, ExecutionMode
  File "/usr/local/lib/python3.9/site-packages/ascii_library/orchestration/pipes/spark_pipes.py", line 5, in <module>
    from dagster import ConfigurableResource, ExperimentalWarning
  File "/usr/local/lib/python3.9/site-packages/dagster/__init__.py", line 99, in <module>
    from dagster._config.pythonic_config import (
  File "/usr/local/lib/python3.9/site-packages/dagster/_config/pythonic_config/__init__.py", line 1, in <module>
    from .config import (
  File "/usr/local/lib/python3.9/site-packages/dagster/_config/pythonic_config/config.py", line 14, in <module>
    from dagster._core.definitions.definition_config_schema import DefinitionConfigSchema
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/definitions/__init__.py", line 90, in <module>
    from .repository_definition import (
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/definitions/repository_definition/__init__.py", line 1, in <module>
    from .repository_definition import (
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/definitions/repository_definition/repository_definition.py", line 19, in <module>
    from dagster._core.definitions.asset_graph import AssetGraph
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/definitions/asset_graph.py", line 6, in <module>
    from dagster._core.definitions.asset_spec import (
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/definitions/asset_spec.py", line 12, in <module>
    from .freshness_policy import FreshnessPolicy
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/definitions/freshness_policy.py", line 9, in <module>
    from dagster._utils.schedules import is_valid_cron_schedule, reverse_cron_string_iterator
  File "/usr/local/lib/python3.9/site-packages/dagster/_utils/schedules.py", line 11, in <module>
    from dateutil.tz import datetime_ambiguous, datetime_exists
ImportError: cannot import name 'datetime_ambiguous' from 'dateutil.tz' (/usr/local/lib/python3.9/site-packages/dateutil/tz.py)
```

### What did you expect to happen?

execute print function without problem

### How to reproduce?
in an aws instance that has the latest EMR set it so that it uses this as task:
[test_date_ambiguous_emr.txt](https://github.com/user-attachments/files/15937967/test_date_ambiguous_emr.txt)
and this should be the boostrap file:
[test_bootstrap.txt](https://github.com/user-attachments/files/15937968/test_bootstrap.txt)
for the exact config, this is the file with the exact instance type:
[config.txt](https://github.com/user-attachments/files/15938033/config.txt)

_No response_

### Deployment type

local deployment submit task to EMR 

### Deployment details

It fails when using 
dagster_aws-0.23.10-py3-none-any.whl 
dagster-pipes==1.7.10

it was working on 
dagster_aws-0.23.3-py3-none-any.whl 
dagster-1.7.3-py3-none-any.whl

It runs on Amazon Linux release

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by HPicatto** [comment]
worth to add, we run the same asset on Databricks, that runs on EC2 instances under the hood, and it does work with no issue in the newer version... so the problem is in when we submit it directly using the dagster_aws

**Comment by gibsondan** [comment]
This is very odd. On a new EMR instance, running pip freeze shows:

```
python-dateutil==2.8.1
```

But going into python and checking dateutil's version gives

```
>>> import dateutil
>>> dateutil.__version__
'2.2'
```

**Comment by gibsondan** [comment]
Oh weird, are there two dateutils??

```
py-dateutil==2.2
python-dateutil==2.8.1
```

**Comment by gibsondan** [comment]
@HPicatto can you try pip uninstalling py-dateutil? That fixed the problem for me. Very odd that the default EMR environment includes both, py-dateutil has had a single 2.2 release almost a decade ago: https://pypi.org/project/py-dateutil/#history

**Comment by gibsondan** [comment]
Raised this with AWS here: https://repost.aws/questions/QUl4F36LBhQu-TPbgalNJ-sQ/default-emr-spark-python-environment-contains-two-different-versions-of-the-dateutil-package
