### ISSUE TITLE
slack_on_run_failure suddenly starts failing with `Expected non_None value`, possible run record

### ISSUE THREAD

**Issue by the4thamigo-uk** [dagster-io/dagster#22665]
### Dagster version

dagster, version 1.7.10

### What's the issue?

We are running dagster in k8s, and I have a slack run failure run status sensor that normally works fine. However, after sometime, at seemingly unpredictable moments, it suddenly starts to fail repeatedly with the following unrecoverable exception : 

https://github.com/dagster-io/dagster/blob/release-1.7.10/python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py#L819-L821

```
2024-06-24 08:38:25 +0000 - dagster.daemon.SensorDaemon - ERROR - Sensor daemon caught an error for sensor slack_on_run_failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dagster/_daemon/sensor.py", line 471, in _process_tick_generator
    yield from _evaluate_sensor(
  File "/usr/local/lib/python3.10/site-packages/dagster/_daemon/sensor.py", line 614, in _evaluate_sensor
    sensor_runtime_data = code_location.get_external_sensor_execution_data(
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/remote_representation/code_location.py", line 929, in get_external_sensor_execution_data
    return sync_get_external_sensor_execution_data_grpc(
  File "/usr/local/lib/python3.10/site-packages/dagster/_api/snapshot_sensor.py", line 87, in sync_get_external_sensor_execution_data_grpc
    raise DagsterUserCodeProcessError.from_error_info(result.error)
dagster._core.errors.DagsterUserCodeProcessError: dagster._core.errors.SensorExecutionError: Error occurred during the execution of evaluation_fn for sensor slack_on_run_failure

Stack Trace:
  File "/app/venv/lib/python3.10/site-packages/dagster/_grpc/impl.py", line 388, in get_external_sensor_execution
    with user_code_error_boundary(
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/app/venv/lib/python3.10/site-packages/dagster/_core/errors.py", line 297, in user_code_error_boundary
    raise new_error from e

The above exception was caused by the following exception:
dagster._check.CheckError: Expected non-None value: None

Stack Trace:
  File "/app/venv/lib/python3.10/site-packages/dagster/_core/errors.py", line 287, in user_code_error_boundary
    yield
  File "/app/venv/lib/python3.10/site-packages/dagster/_grpc/impl.py", line 394, in get_external_sensor_execution
    return sensor_def.evaluate_tick(sensor_context)
  File "/app/venv/lib/python3.10/site-packages/dagster/_core/definitions/sensor_definition.py", line 788, in evaluate_tick
    result = self._evaluation_fn(context)
  File "/app/venv/lib/python3.10/site-packages/dagster/_core/definitions/sensor_definition.py", line 1110, in _wrapped_fn
    result.append(next(raw_evaluation_result))
  File "/app/venv/lib/python3.10/site-packages/dagster/_core/definitions/run_status_sensor_definition.py", line 819, in _wrapped_fn
    external_repository_origin = check.not_none(
  File "/app/venv/lib/python3.10/site-packages/dagster/_check/__init__.py", line 1019, in not_none
    raise CheckError(f"Expected non-None value: {additional_message}")
```

I don't believe I am doing anything unusual with the sensor construction:

```
slack_on_run_failure = make_slack_on_run_failure_sensor(
    sensors_config.slack.channel,
    sensors_config.slack.token,
    default_status=sensors_config.default_status,
    webserver_base_url=sensors_config.slack.webserver_base_url,
)
```

Also, when considering the logic above the failing line I should point out that I have a single code repository and the sensor and all jobs/assets are all placed in that single repo. So this run ought to satisfy this `if` block, in theory: 

https://github.com/dagster-io/dagster/blob/release-1.7.10/python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py#L796-L814

Possible clue: It is very tentative but I noticed that sometimes this INFO message is a precursor to the above exception: 

```
INFO:dagster.daemon.MonitoringDaemon:Detected run worker status UNKNOWN: 'Job dagster-run-6b9cc016-c95c-4395-af87-9d4eef0533c4 could not be found'. Marking run 6b9cc016-c95c-4395-af87-9d4eef0533c4 as failed, because it has surpassed the configured maximum attempts to resume the run: 0.
```

### What did you expect to happen?

At least we should be able to rely on the run status sensor not to fail before it is even executed. Perhaps rather than an assertion on the validity of the `external_job_origin`, it should just use an `if` block to check the validity before checking the `JobSelector`... just a guess...

However, there is a possibility that there is an upstream issue causing a run to be lost.

### How to reproduce?

Unfortunately Im not sure what causes this.

### Deployment type

Dagster Helm chart

### Deployment details

1.7.10, I believe this was occurring at least since 1.7.6, possibly before but I cant really say for sure.

### Additional information

n/a

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by the4thamigo-uk** [comment]
Couple of updates on this : 

* Resetting the sensor status and restarting fixes the sensor. Simply restarting it does not fix it.
* The _possibly_ associated error messages above appear to be ephemeral asset jobs launched using the `materialize()` function, that failed. I suspect that the logic in the run status sensor doesnt appropriately handle ephemeral jobs that have failed.

**Comment by the4thamigo-uk** [comment]
cc @gibsondan @smackesey
