### ISSUE TITLE
Fix issue with Celery failing to start given incomplete config

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2289]
See: https://dagster.slack.com/archives/CCCR6P2UR/p1584427817311800

```
execution:
  celery:
      broker:  "pyamqp://test:test@dagster-rabbitmq:5672//"
      backend: 
      config_source:
```

results in 

```
Traceback (most recent call last):
  File "/usr/local/bin/dagster-celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dagster_celery/cli.py", line 159, in worker_start_command
    pythonpath = get_config_dir(config_yaml)
  File "/usr/local/lib/python3.7/site-packages/dagster_celery/cli.py", line 69, in get_config_dir
    if 'broker' in validated_config:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by natekupp** [comment]
https://dagster.phacility.com/D2277
