### ISSUE TITLE
Lesson 8: ImportError: cannot import name 'utc_datetime_from_timestamp' from 'dagster._utils'

### ISSUE THREAD

**Issue by EvanZ** [dagster-io/dagster#22999]
### What's the issue or suggestion?

I'm going through Lesson 8 of Dagster University and currently trying to complete the section titled "Partitions and Backfills in the Dagster UI". I've copied all the code from the lesson in the appropriate locations in my sample project but when I try to run `dagster dev` the following error is occurring and I'm not sure how to fix it:

```
(.env) ubuntu@ip-172-18-103-9:~/dagster_university$ dagster dev
/home/ubuntu/.env/lib/python3.12/site-packages/dagster/_core/utils.py:108: UserWarning: Found version mismatch between `dagster` (1.7.13)and `dagster-webserver` (1.7.12)
  warnings.warn(message)
2024-07-14 13:14:35 +0000 - dagster - INFO - Loaded environment variables from .env file: DUCKDB_DATABASE
2024-07-14 13:14:35 +0000 - dagster - INFO - Using temporary directory /home/ubuntu/dagster_university/tmpza6haipz for storage. This will be removed when dagster dev exits.
2024-07-14 13:14:35 +0000 - dagster - INFO - To persist information across sessions, set the environment variable DAGSTER_HOME to a directory to use.
2024-07-14 13:14:36 +0000 - dagster - INFO - Launching Dagster services...
/home/ubuntu/.env/lib/python3.12/site-packages/dagster/_core/utils.py:108: UserWarning: Found version mismatch between `dagster` (1.7.13)and `dagster-webserver` (1.7.12)
  warnings.warn(message)
/home/ubuntu/.env/lib/python3.12/site-packages/dagster/_core/utils.py:108: UserWarning: Found version mismatch between `dagster` (1.7.13)and `dagster-graphql` (1.7.12)
  warnings.warn(message)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ubuntu/.env/lib/python3.12/site-packages/dagster_webserver/__main__.py", line 1, in <module>
    from .cli import main  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.env/lib/python3.12/site-packages/dagster_webserver/cli.py", line 26, in <module>
    from .app import create_app_from_workspace_process_context
  File "/home/ubuntu/.env/lib/python3.12/site-packages/dagster_webserver/app.py", line 9, in <module>
    from .webserver import DagsterWebserver
  File "/home/ubuntu/.env/lib/python3.12/site-packages/dagster_webserver/webserver.py", line 20, in <module>
    from dagster_graphql.schema import create_schema
  File "/home/ubuntu/.env/lib/python3.12/site-packages/dagster_graphql/schema/__init__.py", line 3, in <module>
    from .roots.mutation import GrapheneMutation
  File "/home/ubuntu/.env/lib/python3.12/site-packages/dagster_graphql/schema/roots/mutation.py", line 11, in <module>
    from dagster_graphql.implementation.execution.backfill import (
  File "/home/ubuntu/.env/lib/python3.12/site-packages/dagster_graphql/implementation/execution/__init__.py", line 30, in <module>
    from .backfill import (
  File "/home/ubuntu/.env/lib/python3.12/site-packages/dagster_graphql/implementation/execution/backfill.py", line 19, in <module>
    from dagster._utils import utc_datetime_from_timestamp
ImportError: cannot import name 'utc_datetime_from_timestamp' from 'dagster._utils' (/home/ubuntu/.env/lib/python3.12/site-packages/dagster/_utils/__init__.py)
2024-07-14 13:14:39 +0000 - dagster.daemon - INFO - Instance is configured with the following daemons: ['AssetDaemon', 'BackfillDaemon', 'SchedulerDaemon', 'SensorDaemon']
2024-07-14 13:14:41 +0000 - dagster - ERROR - An unexpected exception has occurred
Traceback (most recent call last):
  File "/home/ubuntu/.env/lib/python3.12/site-packages/dagster/_cli/dev.py", line 207, in dev_command
    raise Exception(
Exception: dagster-webserver process shut down unexpectedly with return code 1
2024-07-14 13:14:41 +0000 - dagster - INFO - Shutting down Dagster services...
2024-07-14 13:14:41 +0000 - dagster.daemon - INFO - Received interrupt, shutting down daemon threads...
2024-07-14 13:14:41 +0000 - dagster.daemon - INFO - Daemon threads shut down.
2024-07-14 13:14:41 +0000 - dagster - INFO - Dagster services shut down.
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by EvanZ** [comment]
Sorry, I realized the problem is that I had not pip installed the proper way and while I was able to run every lesson up until this one, doing `pip install -e ".[dev]"` fixed the issue and it is now running.
