### ISSUE TITLE
UnicodeDecodeError in -w mode, versions 1.6.4 to 1.7.13

### ISSUE THREAD

**Issue by hanzch** [dagster-io/dagster#22998]
### Dagster version

1.6.4 ~ 1.7.13

### What's the issue?

Dear developer, this is a coding BUG based on -w mode.

![image](https://github.com/user-attachments/assets/90676a83-3551-40b7-98b3-bf5dc717c3c1)

### How to reproduce?

test_code:

f1.py
```python
import dagster
logger = dagster.get_dagster_logger()


@dagster.asset(description='f1', group_name='t_group')
def factory_f1():
    logger.debug("中文测试")
    logger.debug("111111111")


f1_every_day_job = dagster.define_asset_job("f1_every_day_job",
                                            selection=dagster.AssetSelection.groups("t_group"))
f2_schedule = dagster.ScheduleDefinition(
    job=f1_every_day_job,
    cron_schedule="0 1 * * 2-6",
    execution_timezone="Asia/Shanghai",
    default_status=dagster.DefaultScheduleStatus.RUNNING,
)

if __name__ == '__main__':
    logger.debug("中文测试")
```

### Deployment type

Local

### Deployment details

workspace.yaml
```yaml
load_from:
  - python_file: ./f2.py
```

start: `dagster dev -w workspace.yaml`

### Additional information

Note that the above code does not error through -f.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
If you remove the Chinese characters in the code, does the error still occur? I suspect those characters are not UTF-8 encodeable

**Comment by hanzch** [comment]
> If you remove the Chinese characters in the code, does the error still occur? I suspect those characters are not UTF-8 encodeable

Thank you for your reply. As you said, the encoding problem is indeed caused by Chinese characters. But I am more confused is that it can run normally in -f mode, is it because -w mode and -f processing of coding is not the same?

**Comment by raiAmagi** [comment]
Dagster: Ver. 1.10.2
Python: 3.12.9
OS: Windows11
Character encoding of the console running Dagster Daemon: UTF-8 with the command “chcp 65001” and execute the dagster dev command.
Change to UTF-8 with the command “chcp 65001” and run the dagster dev command

The same error occurs in the log displayed in the console by Dagster Daemon in the same way with both -f and -w as follows.
However, the executed process itself ends normally.

Error output:.
Traceback (most recent call last):
  File "D:\pg\workspace\dagstersample\.venv_dagster_latest\Lib\site-packages\dagster\_core\execution\scripts\poll_compute_logs.py", line 60, in <module>
    execute_polling(sys.argv[1:])
  File "D:\pg\workspace\dagstersample\.venv_dagster_latest\Lib\site-packages\dagster\_core\execution\scripts\poll_compute_logs.py", line 55, in execute_polling    
    tail_polling(filepath, sys.stdout, parent_pid)
  File "D:\pg\workspace\dagstersample\.venv_dagster_latest\Lib\site-packages\dagster\_core\execution\scripts\poll_compute_logs.py", line 31, in tail_polling       
    for block in iter(lambda: file.read(1024), None):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pg\workspace\dagstersample\.venv_dagster_latest\Lib\site-packages\dagster\_core\execution\scripts\poll_compute_logs.py", line 31, in <lambda>
    for block in iter(lambda: file.read(1024), None):
                              ^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 123: invalid start byte


Code built:.
test.py

from dagster import asset, AssetExecutionContext, Definitions

@asset
def test(context: AssetExecutionContext):
    context.log.info('日本語文')

defs = Definitions(
    assets=[test]
)


However, the above error is not output to Events on the Runs screen of the Dagster UI.

As you can see in the reply, it is caused by (in my case) Japanese characters.

In this case, I recognize that the Japanese characters are written in UTF-8 because they are written in Python code, so I believe that they are not something that cannot be converted to UTF-8.

The console running Dagster Daemon has also changed its settings to UTF-8, so
We do not think that the console is the cause of the problem.

(Dagster Daemon does not handle 2-byte characters well?)

1. Errors are written in the log.
2.GraphQL error occurs in stderr of Runs screen of Dagster UI.
3.I cannot exit Dagster Daemon with Ctrl+c.
I would be happy to solve these problems.
