### ISSUE TITLE
Attempting to show unified asset health for assets with dimension of different lengths

### ISSUE THREAD

**Issue by valentinedwv** [dagster-io/dagster#23654]
### Dagster version

1.7.12

### What's the issue?

UI [tossing error](https://sched.geocodes.ncsa.illinois.edu/locations/ingest/jobs/summon_and_release_job/partitions).
----
```
Please report this error to the Dagster team via GitHub or Slack. Refresh the page to try again.
Attempting to show unified asset health for assets with dimension of different lengths

Error: Attempting to show unified asset health for assets with dimension of different lengths
    at u (https://sched.geocodes.ncsa.illinois.edu/_next/static/chunks/557.b819bbd930dd71a2.js:1:760053)
    at https://sched.geocodes.ncsa.illinois.edu/_next/static/chunks/9212.67f78dadbb304de6.js:1:74443
    at Object.aq [as useMemo] (https://sched.geocodes.ncsa.illinois.edu/_next/static/chunks/framework-f499d8c0d67e5a59.js:9:65275)
    at n.useMemo (https://sched.geocodes.ncsa.illinois.edu/_next/static/chunks/framework-f499d8c0d67e5a59.js:25:5984)
    at t3 (https://sched.geocodes.ncsa.illinois.edu/_next/static/chunks/9212.67f78dadbb304de6.js:1:74422)
    at ak (https://sched.geocodes.ncsa.illinois.edu/_next/static/chunks/framework-f499d8c0d67e5a59.js:9:60902)
    at up (https://sched.geocodes.ncsa.illinois.edu/_next/static/chunks/framework-f499d8c0d67e5a59.js:9:72784)
    at i (https://sched.geocodes.ncsa.illinois.edu/_next/static/chunks/framework-f499d8c0d67e5a59.js:9:120316)
    at oD (https://sched.geocodes.ncsa.illinois.edu/_next/static/chunks/framework-f499d8c0d67e5a59.js:9:99072)
    at https://sched.geocodes.ncsa.illinois.edu/_next/static/chunks/framework-f499d8c0d67e5a59.js:9:98939
```
----

### What did you expect to happen?

Display page

### How to reproduce?

Shortened  a dynamic partition.
Had 'source'~partition causing failure, removed source from config being read

We have a [sensor](https://github.com/earthcube/scheduler/blob/54d404262397fa2a7bbdaa5530e067132ff992bf/dagster/implnets/workflows/ingest/ingest/sensors/s3_configs_sensor.py#L51) reads file, creates [asset](https://github.com/earthcube/scheduler/blob/54d404262397fa2a7bbdaa5530e067132ff992bf/dagster/implnets/workflows/ingest/ingest/assets/gleaner_sources.py#L113)
That asset is used a the [partition list](https://github.com/earthcube/scheduler/blob/54d404262397fa2a7bbdaa5530e067132ff992bf/dagster/implnets/workflows/ingest/ingest/assets/gleaner_sources.py#L10)

shortening that list caused this.

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by valentinedwv** [comment]
Looks like it resolved itself over time. 
closing
