### ISSUE TITLE
Strange output from Postgres storages

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2401]
```
Exception ignored in: <function PostgresEventLogStorage.__del__ at 0x10d939280>
Traceback (most recent call last):
  File "lib/python3.8/site-packages/dagster_postgres/event_log/event_log.py", line 133, in __del__
  File "lib/python3.8/site-packages/dagster_postgres/event_log/event_log.py", line 137, in dispose
  File "lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2039, in dispose
  File "lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 243, in recreate
  File "<string>", line 2, in __init__
  File "lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
  File "lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 221, in __init__
  File "lib/python3.8/site-packages/sqlalchemy/event/base.py", line 149, in _update
  File "lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 392, in _update
  File "lib/python3.8/site-packages/sqlalchemy/event/registry.py", line 115, in _stored_in_collection_multi
KeyError: <weakref at 0x126976720; to 'function' at 0x10d99da60 (on_connect)>
Exception ignored in: <function PostgresRunStorage.__del__ at 0x10d960430>
Traceback (most recent call last):
  File "lib/python3.8/site-packages/dagster_postgres/run_storage/run_storage.py", line 84, in __del__
  File "lib/python3.8/site-packages/dagster_postgres/run_storage/run_storage.py", line 87, in dispose
  File "lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2039, in dispose
  File "lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 243, in recreate
  File "<string>", line 2, in __init__
  File "lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
  File "lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 221, in __init__
  File "lib/python3.8/site-packages/sqlalchemy/event/base.py", line 149, in _update
  File "lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 392, in _update
  File "lib/python3.8/site-packages/sqlalchemy/event/registry.py", line 115, in _stored_in_collection_multi
KeyError: <weakref at 0x10d99a630; to 'function' at 0x10d99d1f0 (on_connect)>
```
maybe bc of https://dagster.phacility.com/D2599

**Comment by mgasner** [comment]
@alangenfeld @dwallace0723 I believe we have resolved this?

**Comment by alangenfeld** [comment]
ya dwall let me know its good now
