### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl' on Windows - dagster-postgres

### ISSUE THREAD

**Issue by nickfielding** [dagster-io/dagster#2419]
Hi,
Thanks for making this tool.  It is great, such a lot of potential.

The 'fcntl' module used in dagster-postgres isn't available on Windows machines.

Is it possible to use a module which is compatible with both linux and windows?

I really hope that windows support is maintained.  Windows Server 2016 is main platform in my company at the moment.

**Comment by natekupp** [comment]
@alangenfeld looks like we pull it in here: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-postgres/dagster_postgres/pynotify.py#L31

**Comment by nickfielding** [comment]
Hi, @natekupp is correct.  Stack trace below...


Traceback (most recent call last):
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster\serdes\__init__.py", line 298, in rehydrate
    module = importlib.import_module(self.module_name)
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster_postgres\__init__.py", line 1, in <module>
    from .event_log import PostgresEventLogStorage
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster_postgres\event_log\__init__.py", line 1, in <module>
    from .event_log import PostgresEventLogStorage
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster_postgres\event_log\event_log.py", line 24, in <module>
    from ..pynotify import await_pg_notifications
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster_postgres\pynotify.py", line 31, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\PycharmProjects\dagster\venv\Scripts\dagit.exe\__main__.py", line 7, in <module>
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagit\dagit.py", line 77, in main
    ui(command[1:])  # pylint: disable=no-value-for-parameter
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagit\cli.py", line 123, in ui
    host_dagit_ui(host, port, storage_fallback, reload_trigger, port_lookup, **kwargs)
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagit\cli.py", line 131, in host_dagit_ui
    return host_dagit_ui_with_execution_handle(
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagit\cli.py", line 149, in host_dagit_ui_with_execution_handle
    instance = DagsterInstance.get(storage_fallback)
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster\core\instance\__init__.py", line 256, in get
    return DagsterInstance.from_config(_dagster_home())
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster\core\instance\__init__.py", line 278, in from_config
    return DagsterInstance.from_ref(instance_ref)
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster\core\instance\__init__.py", line 286, in from_ref
    run_storage=instance_ref.run_storage,
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster\core\instance\ref.py", line 179, in run_storage
    return self.run_storage_data.rehydrate()
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster\serdes\__init__.py", line 300, in rehydrate
    check.failed(
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster\check\__init__.py", line 109, in failed
    raise_with_traceback(CheckError('Failure condition: {desc}'.format(desc=desc)))
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster\serdes\__init__.py", line 298, in rehydrate
    module = importlib.import_module(self.module_name)
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster_postgres\__init__.py", line 1, in <module>
    from .event_log import PostgresEventLogStorage
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster_postgres\event_log\__init__.py", line 1, in <module>
    from .event_log import PostgresEventLogStorage
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster_postgres\event_log\event_log.py", line 24, in <module>
    from ..pynotify import await_pg_notifications
  File "c:\users\xxx\pycharmprojects\dagster\venv\lib\site-packages\dagster_postgres\pynotify.py", line 31, in <module>
    import fcntl
dagster.check.CheckError: Failure condition: Couldn't import module dagster_postgres.run_storage when attempting to rehydrate the configurable class dagster_postgres.run_storage.PostgresRunStorage

**Comment by FishmanL** [comment]
Newest push eliminates the fcntl call on windows systems (as well as fixing a couple of broken tests)

**Comment by nickfielding** [comment]
Perfect.  Thanks.
