### ISSUE TITLE
dagster.core.errors.DagsterInvalidDefinitionError after 0.7.11 update 

### ISSUE THREAD

**Issue by b0nj0m0n** [dagster-io/dagster#2447]
Updated to 0.7.11 last night, and the same pipeline file that loaded into dagit previously now throws an error. Attached the pipeline file. I don't use any Path types, just strings that are converted to Path later. Only place I see "path" in the file (or other sourced modules) is in the context of the EventMetadataEntry.
```
        metadata_entries=[EventMetadataEntry.path(str(filepath), 
                'instore_impr_prt_red_dt_csv')])
```
[dagster_issue_20200510.zip](https://github.com/dagster-io/dagster/files/4606525/dagster_issue_20200510.zip)
```
(base) PS C:\Users\bsmith\OneDrive - Catalina Marketing\Python\catmktg\pipelines> dagit -f omni_measure_pipeline.py -n o
mni_measure
c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\core\execution\compute_logs.py:45: UserWarning: WARNING: Compute log capture is disabled for the current environment. Set the environment variable `PYTHONLEGACYWINDOWSSTDIO` to enable.

  warnings.warn(WIN_PY36_COMPUTE_LOG_DISABLED_MSG)
Loading repository...
Traceback (most recent call last):
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\bsmith\AppData\Local\Continuum\anaconda3\Scripts\dagit.exe\__main__.py", line 9, in <module>
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagit\dagit.py", line 77, in main
    ui(command[1:])  # pylint: disable=no-value-for-parameter
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagit\cli.py", line 123, in ui
    host_dagit_ui(host, port, storage_fallback, reload_trigger, port_lookup, **kwargs)
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagit\cli.py", line 132, in host_dagit_ui
    handle_for_repo_cli_args(kwargs), host, port, storage_fallback, reload_trigger, port_lookup
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagit\cli.py", line 154, in host_dagit_ui_with_execution_handle
    app = create_app_with_execution_handle(handle, instance, reloader)
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagit\app.py", line 228, in create_app_with_execution_handle
    version=__version__,
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster_graphql\implementation\context.py", line 113, in __init__
    self.repository_definition = handle.build_repository_definition()
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\core\definitions\handle.py", line 406, in build_repository_definition
    obj = self.entrypoint.perform_load()
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\core\definitions\handle.py", line 441, in entrypoint
    return self.data.get_repository_entrypoint(from_handle=self)
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\core\definitions\handle.py", line 551, in get_repository_entrypoint
    python_file=self.python_file, fn_name=self.fn_name, from_handle=from_handle
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\core\definitions\handle.py", line 161, in from_file_target
    module = import_module_from_path(module_name, os.path.abspath(python_file))
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\seven\__init__.py", line 75, in import_module_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\bsmith\OneDrive - Catalina Marketing\Python\catmktg\pipelines\omni_measure_pipeline.py", line 5, in <module>
    from catmktg.resources.yellowbrick_odbc_32 import yellowbrick_odbc_32
  File "C:\Users\bsmith\OneDrive - Catalina Marketing\Python\catmktg\resources\yellowbrick_odbc_32.py", line 4, in <module>
    from catmktg.pipelines.types import dataframes
  File "C:\Users\bsmith\OneDrive - Catalina Marketing\Python\catmktg\pipelines\types\dataframes.py", line 1, in <module>
    from dagster_pandas.data_frame import DataFrame, create_dagster_pandas_dataframe_type
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster_pandas\__init__.py", line 2, in <module>
    from .data_frame import DataFrame, create_dagster_pandas_dataframe_type
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster_pandas\data_frame.py", line 31, in <module>
    'table': {'path': Path},
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\config\field_utils.py", line 205, in __new__
    cls, Selector, _define_selector_key(expand_fields_dict(fields), description),
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\config\field_utils.py", line 238, in expand_fields_dict
    return _expand_fields_dict(fields, fields, [])
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\config\field_utils.py", line 245, in _expand_fields_dict
    for name, value in fields.items()
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\config\field_utils.py", line 245, in <dictcomp>
    for name, value in fields.items()
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\config\field_utils.py", line 301, in _convert_potential_field
    return Field(_convert_potential_type(original_root, potential_field, stack))
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\config\field_utils.py", line 279, in _convert_potential_type
    return Shape(_expand_fields_dict(original_root, potential_type, stack))
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\config\field_utils.py", line 245, in _expand_fields_dict
    for name, value in fields.items()
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\config\field_utils.py", line 245, in <dictcomp>
    for name, value in fields.items()
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\config\field_utils.py", line 295, in _convert_potential_field
    if not is_potential_field(potential_field):
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\config\field_utils.py", line 225, in is_potential_field
    potential_field
  File "c:\users\bsmith\appdata\local\continuum\anaconda3\lib\site-packages\dagster\config\field.py", line 117, in resolve_to_config_type
    desc=VALID_CONFIG_DESC,
dagster.core.errors.DagsterInvalidDefinitionError: You have passed an instance of DagsterType Path to the config system (Repr of type: <dagster.core.types.dagster_type._Path object at 0x0000019207D41F08>). The DagsterType and config schema systems are seperate. Valid config values are:

1. A Python primitive type that resolve to dagster config
   types: int, float, bool, str.

2. A dagster config type: Int, Float, Bool, String, StringSource, Path, Any,
   Array, Noneable, Selector, Shape, Permissive, etc.

3. A bare python dictionary, which is wrapped in Shape. Any
   values in the dictionary get resolved by the same rules, recursively.

4. A bare python list of length one which itself is config type.
   Becomes Array with list element as an argument.
```

**Comment by schrockn** [comment]
Hey Ben thanks for the report. Looks like you are using dagster-pandas and I suspect you are on an older version of dagster-pandas a new version of dagster. All dagster libraries need to be in lockstep. Thanks!

**Comment by schrockn** [comment]
Confirmed that this is issue
