### ISSUE TITLE
Rehydrating instance config requires cron installed

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2454]
It would be nice to not require cron installed when rehydrating scheduler config. I'm trying to set up a celery worker docker image with minimal dependencies installed, and getting this when running `dagster-celery worker start`:

```
Traceback (most recent call last):
  File "/usr/local/bin/dagster-celery", line 11, in <module>
    load_entry_point('dagster-celery', 'console_scripts', 'dagster-celery')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/dagster-celery/dagster_celery/cli.py", line 171, in worker_start_command
    pythonpath = get_config_dir(config_yaml)
  File "/dagster-celery/dagster_celery/cli.py", line 56, in get_config_dir
    instance = DagsterInstance.get()
  File "/dagster/dagster/core/instance/__init__.py", line 238, in get
    return DagsterInstance.from_config(_dagster_home())
  File "/dagster/dagster/core/instance/__init__.py", line 260, in from_config
    return DagsterInstance.from_ref(instance_ref)
  File "/dagster/dagster/core/instance/__init__.py", line 272, in from_ref
    scheduler=instance_ref.scheduler,
  File "/dagster/dagster/core/instance/ref.py", line 195, in scheduler
    return self.scheduler_data.rehydrate() if self.scheduler_data else None
  File "/dagster/dagster/serdes/__init__.py", line 335, in rehydrate
    return klass.from_config_value(self, result.value)
  File "/dagster-cron/dagster_cron/cron_scheduler.py", line 38, in from_config_value
    return SystemCronScheduler(inst_data=inst_data)
  File "/dagster-cron/dagster_cron/cron_scheduler.py", line 26, in __init__
    self._cron_tab = CronTab(user=True)
  File "/usr/local/lib/python3.7/site-packages/crontab.py", line 228, in __init__
    self.read(tabfile)
  File "/usr/local/lib/python3.7/site-packages/crontab.py", line 291, in read
    (out, err) = open_pipe(CRONCMD, l='', **self.user_opt).communicate()
  File "/usr/local/lib/python3.7/site-packages/crontab.py", line 190, in open_pipe
    return sp.Popen(args, stdout=sp.PIPE, stderr=sp.PIPE, env=env)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/crontab': '/usr/bin/crontab'
```

instance yaml is (with some fields redacted):

```
dagster.yaml:
----
scheduler:
  module: dagster_cron.cron_scheduler
  class: SystemCronScheduler

schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_db:
      username: dagster
      password:
        env: DAGSTER_PG_PASSWORD
      hostname: "..."
      db_name:  dagster
      port: 5432

run_launcher:
  module: dagster_k8s.launcher
  class: K8sRunLauncher
  config:
    service_account_name: nate-test-dagster
    job_image: "..."
    dagster_home: "/opt/dagster/dagster_home"
    instance_config_map: "nate-test-dagster-instance"
    postgres_password_secret: "nate-test-dagster-postgresql-secret"
    image_pull_policy: "Always"
    job_namespace: "default"
    env_config_maps:
    - "nate-test-dagster-pipeline-env"
    env_secrets:

run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      username: dagster
      password:
        env: DAGSTER_PG_PASSWORD
      hostname: "..."
      db_name:  dagster
      port: 5432

event_log_storage:
  module: dagster_postgres.event_log
  class: PostgresEventLogStorage
  config:
    postgres_db:
      username: dagster
      password:
        env: DAGSTER_PG_PASSWORD
      hostname: "...."
      db_name:  dagster
      port: 5432
```

**Comment by natekupp** [comment]
To clarify, only the actual node running the scheduler should require cron installed—other nodes that load this instance config should lazy-eval scheduler-specific stuff

**Comment by gibsondan** [comment]
'Fixed' due to new scheduler.
