### ISSUE TITLE
SQLAlchemy error during load testing

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2482]
Hit this during load testing:

```
Traceback (most recent call last):
  File "/usr/local/bin/dagster-graphql", line 11, in <module>
    load_entry_point('dagster-graphql', 'console_scripts', 'dagster-graphql')()
  File "/dagster-graphql/dagster_graphql/cli.py", line 228, in main
    cli(obj={})  # pylint:disable=E1120
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/dagster-graphql/dagster_graphql/cli.py", line 220, in ui
    execute_query_from_cli(recon_repo, query, variables, output)
  File "/dagster-graphql/dagster_graphql/cli.py", line 103, in execute_query_from_cli
    recon_repo, query, variables=seven.json.loads(variables) if variables else None
  File "/dagster-graphql/dagster_graphql/cli.py", line 49, in execute_query
    else DagsterInstance.get()
  File "/dagster/dagster/core/instance/__init__.py", line 238, in get
    return DagsterInstance.from_config(_dagster_home())
  File "/dagster/dagster/core/instance/__init__.py", line 260, in from_config
    return DagsterInstance.from_ref(instance_ref)
  File "/dagster/dagster/core/instance/__init__.py", line 268, in from_ref
    run_storage=instance_ref.run_storage,
  File "/dagster/dagster/core/instance/ref.py", line 179, in run_storage
    return self.run_storage_data.rehydrate()
  File "/dagster/dagster/serdes/__init__.py", line 345, in rehydrate
    return klass.from_config_value(self, result.value)
  File "/dagster-postgres/dagster_postgres/run_storage/run_storage.py", line 53, in from_config_value
    inst_data=inst_data, postgres_url=pg_url_from_config(config_value)
  File "/dagster-postgres/dagster_postgres/run_storage/run_storage.py", line 39, in __init__
    RunStorageSqlMetadata.create_all(self._engine)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4465, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2103, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2095, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2311, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2349, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1591, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 239, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "some-rds-host.amazonaws.com" to address: Temporary failure in name resolution
```

we should probably handle this more gracefully

**Comment by mgasner** [comment]
This is just a connection failure right?

**Comment by catherinewu** [comment]
@natekupp are you proposing adding retries here? 

going to close; feel free to to add more details and re-open

**Comment by natekupp** [comment]
yeah we have retries now so this issue is obsolete

**Comment by 123mw123** [comment]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.8/dist-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dagster_graphql/schema/external.py", line 183, in resolve_schedules
    [GrapheneSchedule(graphene_info, schedule) for schedule in schedules],
  File "/usr/local/lib/python3.8/dist-packages/dagster_graphql/schema/external.py", line 183, in <listcomp>
    [GrapheneSchedule(graphene_info, schedule) for schedule in schedules],
  File "/usr/local/lib/python3.8/dist-packages/dagster_graphql/schema/schedules/schedules.py", line 44, in __init__
    self._schedule_state = graphene_info.context.instance.get_job_state(
  File "/usr/local/lib/python3.8/dist-packages/dagster/core/instance/__init__.py", line 1507, in get_job_state
    return self._schedule_storage.get_job_state(job_origin_id)
  File "/usr/local/lib/python3.8/dist-packages/dagster/core/storage/schedules/sql_schedule_storage.py", line 65, in get_job_state
    rows = self.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/dagster/core/storage/schedules/sql_schedule_storage.py", line 30, in execute
    result_proxy = conn.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
graphql.error.located_error.GraphQLLocatedError: (psycopg2.DatabaseError) could not receive data from server: Connection timed out
`

@mgasner  @natekupp  I am using dagster=0.12.5 and still getting the same error. Any idea on which version of dagster this issue is fixed?
