### ISSUE TITLE
Rough error message when you return the wrong thing from @repository

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2538]
e.g.:

```
from dagster import repository, solid, pipeline


@solid
def conflicting_solid(_):
    pass


@pipeline
def conflicting_pipeline():
    conflicting_solid()


@repository
def repo_two():
    return [conflicting_solid] # should be conflicting_pipeline

```

error message:

```
Traceback (most recent call last):
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/bin/dagit", line 11, in <module>
    load_entry_point('dagit', 'console_scripts', 'dagit')()
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 207, in main
    cli(auto_envvar_prefix='DAGIT')  # pylint:disable=E1120
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 112, in ui
    host_dagit_ui(host, port, storage_fallback, port_lookup, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 116, in host_dagit_ui
    workspace = workspace_for_cli_args(kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 130, in workspace_for_cli_args
    return load_workspace_from_yaml_path(workspace_yaml)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/workspace.py", line 59, in load_workspace_from_yaml_path
    location_handles.append(_location_handle_from_location_config(location_config, yaml_path))
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/workspace.py", line 116, in _location_handle_from_location_config
    return _location_handle_from_python_file(location_config['python_file'], yaml_path)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/workspace.py", line 102, in _location_handle_from_python_file
    definition=definition if definition else loadable_target_from_python_file(absolute_path),
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/autodiscovery.py", line 9, in loadable_target_from_python_file
    loaded_module = load_python_file(python_file)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/code_pointer.py", line 73, in load_python_file
    return import_module_from_path(module_name, python_file)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/seven/__init__.py", line 82, in import_module_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/schrockn/code/dagster/examples/multi_location/repo_two.py", line 14, in <module>
    @repository
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/definitions/decorators/repository.py", line 217, in repository
    return _Repository()(name)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/definitions/decorators/repository.py", line 44, in __call__
    bad_definitions.append(i, type(definition))
TypeError: append() takes exactly one argument (2 given)
```

**Comment by natekupp** [comment]
This is fixed
