### ISSUE TITLE
`no such column: backfill_id` error when upgrading from 1.8.13 to 1.9.0

### ISSUE THREAD

**Issue by giovannipcarvalho** [dagster-io/dagster#25686]
### What's the issue?

I wanted to try the latest version (today's release) in an pre-existing project, however it fails to load the project.

### What did you expect to happen?

I expected dagster to successfully or instruct to run `dagster instance migrate`.

### How to reproduce?

setup

```python
# file: t.py
import dagster

@dagster.asset(partitions_def=dagster.DailyPartitionsDefinition(start_date="2024-10-30"))
def foo():
    return 1
```

```bash
# 1.8.13 is the latest release before 1.9.0, but this also happens with 1.7.x
uv venv && . .venv/bin/activate
uv pip install 'dagster==1.8.13' dagster-webserver
DAGSTER_HOME=$PWD dagster job backfill -f t.py --noprompt
```

after upgrading to 1.9.0 and attempting to load the project, it does not work:

```console
$ uv pip install dagster==1.9.0 dagster-webserver
$ DAGSTER_HOME=$PWD dagster dev -f t.py
[...]
Traceback (most recent call last):
  File "/tmp/dagster-migration/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/tmp/dagster-migration/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: backfill_id

The above exception was the direct cause of the following exception:

[...]
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: backfill_id
[SQL: UPDATE runs SET backfill_id=? WHERE runs.run_id = ? AND runs.backfill_id IS NULL]
[parameters: ('nkrgfmzo', '9b466728-bf4c-4003-81b9-89f669a996ee')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

migrating also fails with the same error

```console
$ DAGSTER_HOME=$PWD dagster instance migrate
[...]
Traceback (most recent call last):
  File "/tmp/dagster-migration/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/tmp/dagster-migration/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: backfill_id
```

### Dagster version

1.9.0

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by jamiedemaria** [comment]
hey @giovannipcarvalho could you share the full stack trace with us?

**Comment by prha** [comment]
Hi @giovannipcarvalho ... Apologies... we usually catch these types of errors with a prompt to run `dagster instance migrate`.  I'll look into why we're not catching this case.

Do you still run into issues after running the `migrate` command?

**Comment by giovannipcarvalho** [comment]
Sorry.  I wasn't clear in my original message, but neither do I get prompted to run the migration, nor running it fixes the problem.  It also crashes.

Here's the full stack trace:

```
λ DAGSTER_HOME=$PWD dagster dev -f t.py
2024-11-04 19:56:58 -0300 - dagster - WARNING - No dagster instance configuration file (dagster.yaml) found at /tmp/dagster-migration. Defaulting to loading and storing all metadata with /tmp/dagster-migration. If this is the desired behavior, create an empty dagster.yaml file in /tmp/dagster-migration.
Traceback (most recent call last):
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: backfill_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/dagster-migration/.venv/bin/dagster", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_cli/__init__.py", line 50, in main
    cli(auto_envvar_prefix=ENV_PREFIX)  # pylint:disable=E1123
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_cli/dev.py", line 142, in dev_command
    with get_possibly_temporary_instance_for_cli("dagster dev", logger=logger) as instance:
  File "/home/giovanni/micromamba/envs/gpsc/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_cli/utils.py", line 80, in get_possibly_temporary_instance_for_cli
    with DagsterInstance.get() as instance:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_core/instance/__init__.py", line 586, in get
    return DagsterInstance.from_config(dagster_home_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_core/instance/__init__.py", line 621, in from_config
    return DagsterInstance.from_ref(instance_ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_core/instance/__init__.py", line 633, in from_ref
    unified_storage = instance_ref.storage
                      ^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_core/instance/ref.py", line 498, in storage
    return self.storage_data.rehydrate(as_type=DagsterStorage) if self.storage_data else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_serdes/config_class.py", line 128, in rehydrate
    return klass.from_config_value(self, check.not_none(result.value))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_core/storage/sqlite_storage.py", line 80, in from_config_value
    return DagsterSqliteStorage.from_local(inst_data=inst_data, **config_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_core/storage/sqlite_storage.py", line 86, in from_local
    return cls(base_dir, inst_data=inst_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_core/storage/sqlite_storage.py", line 62, in __init__
    self._run_storage = SqliteRunStorage.from_local(_runs_directory(base_dir))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_core/storage/runs/sqlite/sqlite_run_storage.py", line 108, in from_local
    run_storage.migrate()
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_core/storage/runs/sql_run_storage.py", line 758, in migrate
    self._execute_data_migrations(REQUIRED_DATA_MIGRATIONS, print_fn, force_rebuild_all)
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_core/storage/runs/sql_run_storage.py", line 752, in _execute_data_migrations
    migration_fn()(self, print_fn)
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_core/storage/runs/migration.py", line 335, in migrate_run_backfill_id
    add_backfill_id(conn, run_id=run_id, backfill_id=backfill_id)
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/dagster/_core/storage/runs/migration.py", line 341, in add_backfill_id
    conn.execute(
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/tmp/dagster-migration/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: backfill_id
[SQL: UPDATE runs SET backfill_id=? WHERE runs.run_id = ? AND runs.backfill_id IS NULL]
[parameters: ('znzoknui', 'b2845db7-30fe-4c90-9cc0-3e1c258150cc')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by jkglasbrenner** [comment]
Not the original poster, but I'm encountering the same issue on an M1 Apple Silicon MacBook Pro. The stack trace still appears when I try running the `migrate` command. The full stack trace is copied below.

This is happening on my local development environment where I'm running `dagster dev` and using the default SQLite `runs.db`. Maybe its just affecting the SQLite migrations? From inspecting the stack trace, the migration that's failing is related to the `runs` table. There's this bit,

https://github.com/dagster-io/dagster/blob/c5944bda489a3bd7b815a300eedd1c99d4f6adeb/python_modules/dagster/dagster/_core/storage/runs/migration.py#L341-L348

which references a `backfill_id` column in `RunsTable`. However, it doesn't exist in the SQLite `runs.db` I have. Maybe it's supposed to be added first, but this operation is running out of order?

```
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/path/to/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: backfill_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/venv/bin/dagster", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_cli/__init__.py", line 50, in main
    cli(auto_envvar_prefix=ENV_PREFIX)  # pylint:disable=E1123
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_cli/instance.py", line 49, in migrate_command
    with get_instance_for_cli() as instance:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_cli/utils.py", line 107, in get_instance_for_cli
    with DagsterInstance.get() as instance:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_core/instance/__init__.py", line 586, in get
    return DagsterInstance.from_config(dagster_home_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_core/instance/__init__.py", line 621, in from_config
    return DagsterInstance.from_ref(instance_ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_core/instance/__init__.py", line 633, in from_ref
    unified_storage = instance_ref.storage
                      ^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_core/instance/ref.py", line 498, in storage
    return self.storage_data.rehydrate(as_type=DagsterStorage) if self.storage_data else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_serdes/config_class.py", line 128, in rehydrate
    return klass.from_config_value(self, check.not_none(result.value))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_core/storage/sqlite_storage.py", line 80, in from_config_value
    return DagsterSqliteStorage.from_local(inst_data=inst_data, **config_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_core/storage/sqlite_storage.py", line 86, in from_local
    return cls(base_dir, inst_data=inst_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_core/storage/sqlite_storage.py", line 62, in __init__
    self._run_storage = SqliteRunStorage.from_local(_runs_directory(base_dir))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_core/storage/runs/sqlite/sqlite_run_storage.py", line 108, in from_local
    run_storage.migrate()
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_core/storage/runs/sql_run_storage.py", line 758, in migrate
    self._execute_data_migrations(REQUIRED_DATA_MIGRATIONS, print_fn, force_rebuild_all)
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_core/storage/runs/sql_run_storage.py", line 752, in _execute_data_migrations
    migration_fn()(self, print_fn)
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_core/storage/runs/migration.py", line 335, in migrate_run_backfill_id
    add_backfill_id(conn, run_id=run_id, backfill_id=backfill_id)
  File "/path/to/venv/lib/python3.11/site-packages/dagster/_core/storage/runs/migration.py", line 341, in add_backfill_id
    conn.execute(
  File "/path/to/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/path/to/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/path/to/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/path/to/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: backfill_id
[SQL: UPDATE runs SET backfill_id=? WHERE runs.run_id = ? AND runs.backfill_id IS NULL]
[parameters: ('yshjmcpo', '49f8986c-8edd-47a8-8627-263ebadcd291')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by prha** [comment]
I can repro with a newly created sqlite file.  At some point (still not exactly sure when) we started allowing creation of sqlite run databases without an `alembic_version` correctly stamped.  This is preventing the new schema migration from being applied.  

I'm investigating how to get the alembic version to stamp correctly.  One workaround in the short term would be to find the alembic hash you most recently had applied and manually create an `alembic_version` table with the correct `version_num` hash set correctly.

**Comment by prha** [comment]
This will be resolved with the rollout of `1.9.1` in a couple days.  This affects all users upgrading to `1.9.0` with an existing SQLite-backed instance, that was created using SQLAlchemy 2.0 using a `dagster` version between `1.3.10` - `1.8.13`.

Downgrading to `1.8.13` should temporarily resolve the issue.

Another short-term workaround is to keep your package at `1.9.0` but manually stamp the alembic revision in the DB (first confirm that there are no rows in the `alembic_version` table:
```
sqlite3 $DAGSTER_HOME/history/runs.db
sqlite> select * from alembic_version;
sqlite> insert into alembic_version (version_num) VALUES ('284a732df317');
```

**Comment by rtol5** [comment]
> This will be resolved with the rollout of `1.9.1` in a couple days. This affects all users upgrading to `1.9.0` with an existing SQLite-backed instance, that was created using SQLAlchemy 2.0 using a `dagster` version between `1.3.10` - `1.8.13`.
> 
> Downgrading to `1.8.13` should temporarily resolve the issue.
> 
> Another short-term workaround is to keep your package at `1.9.0` but manually stamp the alembic revision in the DB (first confirm that there are no rows in the `alembic_version` table):
> 
> ```
> sqlite3 $DAGSTER_HOME/history/runs.db
> sqlite> select * from alembic_version;
> sqlite> insert into alembic_version (version_num) VALUES ('284a732df317');
> ```

I tried running this fix, I got the error message below with the main message `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) Expression tree is too large (maximum depth 1000)`. Is there a workaround to this? I can try increasing max_depth, but I don't really know how deep it'd need to be.
![image](https://github.com/user-attachments/assets/6d9592d6-c2db-4fda-a713-3686e7b14bc3)

**Comment by prha** [comment]
@rtol5 are you getting this error when running the alembic workaround, or when you are running `dagster instance migrate` or some other command?

Do you have the full log output?  Can you share in a gist / txt file?

**Comment by rtol5** [comment]
hi @prha – the sqlite commands worked perfectly fine! The issue was with running `dagster instance migrate`. I'm attaching the output: [instance_migration_output.txt](https://github.com/user-attachments/files/17653702/instance_migration_output.txt)

**Comment by prha** [comment]
Thanks for this... we see the issue and we'll also roll the fix for this out tomorrow with `1.9.1`

**Comment by rtol5** [comment]
hi @prha – how can I manually apply the fix while we wait for `1.9.1`? we've been Dagster-less for a couple days now and it's causing all sorts of mayhem :(

**Comment by prha** [comment]
Hi @rtol5 ... `1.9.1` was pushed yesterday (see [pypi](https://pypi.org/project/dagster/)).  I'm not sure why our GH releases page was not updated... looking into it.

The bugfix for the issue you're hitting is here: https://github.com/dagster-io/dagster/pull/25775

You could check out the `1.9.0` release branch, manually apply this PR, and then run `dagster instance migrate`.  This should run the migration successfully (which only needs to be run once), and then resume using the `1.9.0` package from pypi (instead of from source).
