### ISSUE TITLE
PR 25201 breaks the usage of cacheable assets that are depended on by other assets

### ISSUE THREAD

**Issue by cnogradi** [dagster-io/dagster#25924]
PR 25201 seems to break the usage of cacheable assets that are depended on by other assets since the new sensor is added using a graph that does not contain those cacheable assets and thus it fails to resolve those assets when trying to add the new sensor.  The code that seems to cause this is here:

https://github.com/dagster-io/dagster/blob/24729d953980788d7cab1117a4c8dc2644fc64f6/python_modules/dagster/dagster/_core/definitions/definitions_class.py#L280

We are seeing this because we use this:

airbyte.py:

airbyte_assets = load_assets_from_airbyte_instance()

__init__.py:

assets = load_assets_from_package_module(assets_, auto_materializePolicy.eager())
defs = Definitions( assets=assets, ...)

Yes we do have some sensors in there but if I comment them out, I still get the failure.  Also if I comment our the materialize policy failure still occurs.

The asset that is not found below does exist and is part of the cacheable assets created by airbyte above.

2024-11-14 18:28:41 +0000 - dagster.code_server - ERROR - Error while importing code

Traceback (most recent call last):

  File "/lib64/python3.11/site-packages/dagster/_grpc/server.py", line 421, in __init__

    self._loaded_repositories: Optional[LoadedRepositories] = LoadedRepositories(

                                                              ^^^^^^^^^^^^^^^^^^^

  File "/lib64/python3.11/site-packages/dagster/_grpc/server.py", line 275, in __init__

    repo_def = recon_repo.get_definition()

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lib64/python3.11/site-packages/dagster/_core/definitions/reconstruct.py", line 116, in get_definition

    return reconstruct_repository_def_from_pointer(self.pointer, self.repository_load_data)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lib64/python3.11/site-packages/dagster/_core/definitions/reconstruct.py", line 803, in reconstruct_repository_def_from_pointer

    repo_def = _repository_def_from_target_def_inner(

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lib64/python3.11/site-packages/dagster/_core/definitions/reconstruct.py", line 713, in _repository_def_from_target_def_inner

    return target.get_repository_def()

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lib64/python3.11/site-packages/dagster/_utils/cached_method.py", line 134, in _cached_method_wrapper

    result = method(self, *args, **kwargs)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lib64/python3.11/site-packages/dagster/_core/definitions/definitions_class.py", line 593, in get_repository_def

    return _create_repository_using_definitions_args(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lib64/python3.11/site-packages/dagster/_core/definitions/definitions_class.py", line 278, in _create_repository_using_definitions_args

    sensors = add_default_automation_condition_sensor(

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lib64/python3.11/site-packages/dagster/_core/definitions/utils.py", line 342, in add_default_automation_condition_sensor

    asset_graph = AssetGraph.from_assets([*assets, *asset_checks])

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lib64/python3.11/site-packages/dagster/_core/definitions/asset_graph.py", line 249, in from_assets

    assets_defs = cls.normalize_assets(assets)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lib64/python3.11/site-packages/dagster/_core/definitions/asset_graph.py", line 205, in normalize_assets

    resolved_deps = ResolvedAssetDependencies(assets_defs, [])

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lib64/python3.11/site-packages/dagster/_core/definitions/resolved_asset_deps.py", line 23, in __init__

    self._deps_by_assets_def_id = resolve_assets_def_deps(assets_defs, source_assets)

                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lib64/python3.11/site-packages/dagster/_core/definitions/resolved_asset_deps.py", line 206, in resolve_assets_def_deps

    raise DagsterInvalidDefinitionError(msg)

dagster._core.errors.DagsterInvalidDefinitionError: Input asset '["airbyte", "ingress", "public", "covid_data"]' for asset '["python_asset"]' is not produced by any of the provided asset ops and is not one of the provided sources.

/lib64/python3.11/site-packages/dagster/_core/workspace/context.py:771: UserWarning: Error loading repository location orch.instance:dagster._core.errors.DagsterInvalidDefinitionError: Input asset '["airbyte", "ingress", "public", "covid_data"]' for asset '["python_asset"]' is not produced by any of the provided asset ops and is not one of the provided sources.

_Originally posted by @cnogradi in https://github.com/dagster-io/dagster/issues/25201#issuecomment-2476901310_

**Comment by cnogradi** [comment]
Note that I am motivated to fix this and with proper direction could work the PR

**Comment by OwenKephart** [comment]
Hi @cnogradi ! Thanks for filing this -- this is definitely a legitimate bug, and I definitely appreciate the offer to help here. In this case this is actually a fairly simple fix (due to some framework-level improvements that happened soon after the original PR): https://github.com/dagster-io/dagster/pull/25929

**Comment by cnogradi** [comment]
Yay!  At least I was on the right path thinking about the solution ;)
