### ISSUE TITLE
Attempting to show unified asset health for assets with dimension of different lengths

### ISSUE THREAD

**Issue by brycelund** [dagster-io/dagster#26300]
### What's the issue?

```
Sorry, page can't be displayed.
Please report this error to the Dagster team via GitHub or Slack. Refresh the page to try again.
Attempting to show unified asset health for assets with dimension of different lengths

Error: Attempting to show unified asset health for assets with dimension of different lengths
    at u (https://xxxxxxx/_next/static/chunks/4363.a38da8e5aefd5254.js:1:813198)
    at https://xxxxxxx/_next/static/chunks/1190.9ee5bc5c5986451a.js:1:91373
    at Object.aV [as useMemo] (https://xxxxxxx/_next/static/chunks/framework-b0b93c41d6f05eda.js:1:62871)
    at n.useMemo (https://xxxxxxx/_next/static/chunks/framework-b0b93c41d6f05eda.js:1:135715)
    at rR (https://xxxxxxxv/_next/static/chunks/1190.9ee5bc5c5986451a.js:1:91352)
    at ad (https://xxxxxxx/_next/static/chunks/framework-b0b93c41d6f05eda.js:1:58498)
    at ud (https://xxxxxxx/_next/static/chunks/framework-b0b93c41d6f05eda.js:1:72828)
    at i (https://xxxxxxx/_next/static/chunks/framework-b0b93c41d6f05eda.js:1:120360)
    at oO (https://xxxxxxx/_next/static/chunks/framework-b0b93c41d6f05eda.js:1:99116)
    at https://xxxxxxx/_next/static/chunks/framework-b0b93c41d6f05eda.js:1:98983
```

### What did you expect to happen?

The new partition should be added without an error

### How to reproduce?

Jobs > Some job > Partitions > Materialize/Open launchpad > Add new partition

### Dagster version

dagster, version 1.9.3

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by easontm** [comment]
This error also occurs if you:
1. have a job with assets with different partitions definitions. I tried it with a job that has one non-partitioned asset and then some partitioned assets.
2. visit jobs/my_job/partitions
