### ISSUE TITLE
Getting gprc error during docs builds

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2662]
in dagster/docs

make buildnext

```
Traceback (most recent call last):
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/Users/schrockn/.pyenv/versions/3.7.6/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/schrockn/code/dagster/python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s/__init__.py", line 7, in <module>
    from .executor import celery_k8s_job_executor
  File "/Users/schrockn/code/dagster/python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s/executor.py", line 8, in <module>
    from dagster_graphql.client.mutations import handle_execute_plan_result, handle_execution_errors
  File "/Users/schrockn/code/dagster/python_modules/dagster-graphql/dagster_graphql/client/mutations.py", line 1, in <module>
    from dagster_graphql.cli import execute_query
  File "/Users/schrockn/code/dagster/python_modules/dagster-graphql/dagster_graphql/cli.py", line 189, in <module>
    help='A file path to store the GraphQL response to. This flag is useful when making pipeline '
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/workspace/cli_target.py", line 151, in workspace_target_argument
    from dagster.cli.pipeline import apply_click_params
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/__init__.py", line 8, in <module>
    from .api import api_cli
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/api.py", line 63, in <module>
    from dagster.grpc import DagsterGrpcServer
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/grpc/__init__.py", line 11, in <module>
    from .client import DagsterGrpcClient, ephemeral_grpc_api_client
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/grpc/client.py", line 12, in <module>
    from .__generated__ import DagsterApiStub, api_pb2
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/grpc/__generated__/__init__.py", line 6, in <module>
    from . import api_pb2
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/grpc/__generated__/api_pb2.py", line 28, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

**Comment by schrockn** [comment]
This appears to be because I had installed grpc prior the pins to my local setup was different than what setup.py specifies
