### ISSUE TITLE
database "migration_add_snapshot_db" does not exist on fresh postgress install

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2698]
I get this error when running dagit against a fresh postgres install. My workaround is to manually create the table but that is obviously not the greatest experience.

```
(dagster-dev-3.7.6) [schrockn@mbp ~/code/dagster (arcpatch-D3567)]$ dagit -f examples/docs_snippets/docs_snippets/introduction/intro.py
Traceback (most recent call last):
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 482, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/bin/dagit", line 11, in <module>
    load_entry_point('dagit', 'console_scripts', 'dagit')()
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 177, in main
    cli(auto_envvar_prefix='DAGIT')  # pylint:disable=E1120
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 85, in ui
    host_dagit_ui(host, port, storage_fallback, port_lookup, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 93, in host_dagit_ui
    return host_dagit_ui_with_workspace(workspace, host, port, storage_fallback, port_lookup)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 99, in host_dagit_ui_with_workspace
    instance = DagsterInstance.get(storage_fallback)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/instance/__init__.py", line 239, in get
    return DagsterInstance.from_config(_dagster_home())
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/instance/__init__.py", line 261, in from_config
    return DagsterInstance.from_ref(instance_ref)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/instance/__init__.py", line 269, in from_ref
    run_storage=instance_ref.run_storage,
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/instance/ref.py", line 185, in run_storage
    return self.run_storage_data.rehydrate()
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/serdes/__init__.py", line 353, in rehydrate
    return klass.from_config_value(self, result.value)
  File "/Users/schrockn/code/dagster/python_modules/libraries/dagster-postgres/dagster_postgres/run_storage/run_storage.py", line 56, in from_config_value
    inst_data=inst_data, postgres_url=pg_url_from_config(config_value)
  File "/Users/schrockn/code/dagster/python_modules/libraries/dagster-postgres/dagster_postgres/run_storage/run_storage.py", line 42, in __init__
    RunStorageSqlMetadata.create_all(self._engine)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4316, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2048, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/Users/schrockn/.pyenv/versions/3.7.6/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2040, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2242, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2280, in _wrap_pool_connect
    e, dialect, self
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1547, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 482, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/e3q8)
(dagster-dev-3.7.6) [schrockn@mbp ~/code/dagster (arcpatch-D3567)]$ dagit -f examples/docs_snippets/docs_snippets/introduction/intro.py
Traceback (most recent call last):
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 482, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "migration_add_snapshot_db" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/bin/dagit", line 11, in <module>
    load_entry_point('dagit', 'console_scripts', 'dagit')()
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 177, in main
    cli(auto_envvar_prefix='DAGIT')  # pylint:disable=E1120
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 85, in ui
    host_dagit_ui(host, port, storage_fallback, port_lookup, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 93, in host_dagit_ui
    return host_dagit_ui_with_workspace(workspace, host, port, storage_fallback, port_lookup)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/cli.py", line 99, in host_dagit_ui_with_workspace
    instance = DagsterInstance.get(storage_fallback)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/instance/__init__.py", line 239, in get
    return DagsterInstance.from_config(_dagster_home())
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/instance/__init__.py", line 261, in from_config
    return DagsterInstance.from_ref(instance_ref)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/instance/__init__.py", line 269, in from_ref
    run_storage=instance_ref.run_storage,
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/instance/ref.py", line 185, in run_storage
    return self.run_storage_data.rehydrate()
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/serdes/__init__.py", line 353, in rehydrate
    return klass.from_config_value(self, result.value)
  File "/Users/schrockn/code/dagster/python_modules/libraries/dagster-postgres/dagster_postgres/run_storage/run_storage.py", line 56, in from_config_value
    inst_data=inst_data, postgres_url=pg_url_from_config(config_value)
  File "/Users/schrockn/code/dagster/python_modules/libraries/dagster-postgres/dagster_postgres/run_storage/run_storage.py", line 42, in __init__
    RunStorageSqlMetadata.create_all(self._engine)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4316, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2048, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/Users/schrockn/.pyenv/versions/3.7.6/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2040, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2242, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2280, in _wrap_pool_connect
    e, dialect, self
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1547, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 482, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "migration_add_snapshot_db" does not exist

```

**Comment by alangenfeld** [comment]
what was your `dagster.yaml`? I don't think we can expect have the permissions to create databases can we?

**Comment by schrockn** [comment]
oh whoa you're right for some reason this was my dagster.yaml

```
run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      username: test
      password: test
      hostname: localhost
      db_name: migration_add_snapshot_db
      port: 5432
```
how strange. closing.
