### ISSUE TITLE
Reloading a repository that contains a loading error leaves dagit in bad state.

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2718]
Note infinite spinner:

![Screenshot 2020-07-14 13 37 31](https://user-images.githubusercontent.com/28738937/87474021-3ec59c80-c5d7-11ea-9cc7-c2b7b476f35c.png)

In console:

```
subprocess.CalledProcessError: Command '['/Users/schrockn/venvs/dagster-dev-3.7.6/bin/python', '-m', 'dagster', 'api', 'repository', '/var/folders/rf/6c_35yxs74j4v7_9w_4_p_wh0000gn/T/tmpebw73tcn', '/var/folders/rf/6c_35yxs74j4v7_9w_4_p_wh0000gn/T/tmp__y8_h6b']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagster-graphql/dagster_graphql/schema/roots.py", line 497, in mutate
    graphene_info.context.reload_repository_location(location_name)
  File "/Users/schrockn/code/dagster/python_modules/dagster-graphql/dagster_graphql/implementation/context.py", line 40, in reload_repository_location
    new_location = self._repository_locations[name].create_reloaded_repository_location()
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/host_representation/repository_location.py", line 250, in create_reloaded_repository_location
    return PythonEnvRepositoryLocation(self._handle)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/host_representation/repository_location.py", line 246, in __init__
    er.name: er for er in sync_get_external_repositories(self._handle)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/api/snapshot_repository.py", line 27, in sync_get_external_repositories
    RepositoryPythonOrigin(repository_location_handle.executable_path, pointer),
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/api/utils.py", line 32, in execute_unary_api_cli_command
    execute_command_in_subprocess(parts)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/api/utils.py", line 14, in execute_command_in_subprocess
    "Error when executing API command {cmd}: {output}".format(cmd=e.cmd, output=e.output)
dagster.serdes.ipc.DagsterIPCProtocolError: Error when executing API command ['/Users/schrockn/venvs/dagster-dev-3.7.6/bin/python', '-m', 'dagster', 'api', 'repository', '/var/folders/rf/6c_35yxs74j4v7_9w_4_p_wh0000gn/T/tmpebw73tcn', '/var/folders/rf/6c_35yxs74j4v7_9w_4_p_wh0000gn/T/tmp__y8_h6b']: b'Traceback (most recent call last):\n  File "/Users/schrockn/.pyenv/versions/3.7.6/lib/python3.7/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "/Users/schrockn/.pyenv/versions/3.7.6/lib/python3.7/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/__main__.py", line 3, in <module>\n    main()\n  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/__init__.py", line 38, in main\n    cli(obj={})  # pylint:disable=E1123\n  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 782, in main\n    rv = self.invoke(ctx)\n  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/Users/schrockn/venvs/dagster-dev-3.7.6/lib/python3.7/site-packages/click/core.py", line 610, in invoke\n    return callback(*args, **kwargs)\n  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/api.py", line 103, in command\n    output = check.inst(fn(args), output_cls)\n  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/cli/api.py", line 151, in repository_snapshot_command\n    return external_repository_data_from_def(recon_repo.get_definition())\n  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/definitions/reconstructable.py", line 35, in get_definition\n    return repository_def_from_pointer(self.pointer)\n  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/definitions/reconstructable.py", line 309, in repository_def_from_pointer\n    target = def_from_pointer(pointer)\n  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/definitions/reconstructable.py", line 272, in def_from_pointer\n    target = pointer.load_target()\n  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/code_pointer.py", line 178, in load_target\n    module = load_python_file(self.python_file, None)\n  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/code_pointer.py", line 95, in load_python_file\n    module = import_module_from_path(module_name, python_file)\n  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/seven/__init__.py", line 90, in import_module_from_path\n    spec.loader.exec_module(module)\n  File "<frozen importlib._bootstrap_external>", line 728, in exec_module\n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n  File "/Users/schrockn/code/dagster/examples/presentation/step_two.py", line 40, in <module>\n    @solid\n  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/definitions/decorators/solid.py", line 193, in solid\n    return _Solid()(name)\n  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/definitions/decorators/solid.py", line 68, in __call__\n    positional_inputs = validate_solid_fn(\'@solid\', self.name, fn, input_defs, [\'context\'])\n  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/definitions/decorators/solid.py", line 313, in validate_solid_fn\n    decorator_name=decorator_name, solid_name=fn_name, missing_param=missing_positional\ndagster.core.errors.DagsterInvalidDefinitionError: @solid \'write_sugariest_cereals\' decorated function does not have required positional parameter \'context\'. Solid functions should only have keyword arguments that match input names and a first positional parameter named \'context\'.\n'
```

**Comment by hellendag** [comment]
I think we can roll this into https://github.com/dagster-io/dagster/issues/2918, since the error UI should probably handle this as well.
