### ISSUE TITLE
Schedule config generation error 

### ISSUE THREAD

**Issue by szalai1** [dagster-io/dagster#2733]
When I tried to generate schedule config on Dagit, I got this error and it said I should file a bug report. 
```
Message: Error when executing API command ['/usr/local/bin/python', '-m', 'dagster', 'api', 'schedule_config', '/tmp/tmp0pdxmmnt', '/tmp/tmp6pjdvvi4']: b'Traceback (most recent call last):\n  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/usr/local/lib/python3.7/site-packages/dagster/__main__.py", line 3, in <module>\n    main()\n  File "/usr/local/lib/python3.7/site-packages/dagster/cli/__init__.py", line 38, in main\n    cli(obj={})  # pylint:disable=E1123\n  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main\n    rv = self.invoke(ctx)\n  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke\n    return callback(*args, **kwargs)\n  File "/usr/local/lib/python3.7/site-packages/dagster/cli/api.py", line 103, in command\n    output = check.inst(fn(args), output_cls)\n  File "/usr/local/lib/python3.7/site-packages/dagster/cli/api.py", line 298, in schedule_execution_data_command\n    return get_external_schedule_execution(args)\n  File "/usr/local/lib/python3.7/site-packages/dagster/grpc/impl.py", line 53, in get_external_schedule_execution\n    schedule_def = definition.get_schedule_def(external_schedule_execution_args.schedule_name)\n  File "/usr/local/lib/python3.7/site-packages/dagster/core/definitions/repository.py", line 566, in get_schedule_def\n    return self._repository_data.get_schedule(name)\n  File "/usr/local/lib/python3.7/site-packages/dagster/core/definitions/repository.py", line 396, in get_schedule\n    return self._schedules.get_definition(schedule_name)\n  File "/usr/local/lib/python3.7/site-packages/dagster/core/definitions/repository.py", line 75, in get_definition\n    for found_name in self.get_definition_names()\ndagster.core.errors.DagsterInvariantViolationError: Could not find schedule \'daily_answer_position_pipeline\'. Found: \'daily_maker_organisation_changes\', \'daily_events_rounds_loader\', \'daily_answer_positions_loader\'.\n'

Path: ["scheduleDefinitionOrError","runConfigOrError"]

Locations: [{"line":4,"column":7}]

Stack Trace:
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dagster_graphql/schema/schedules/schedule_definition.py", line 47, in resolve_runConfigOrError
    return get_schedule_config(graphene_info, self._external_schedule)
  File "/usr/local/lib/python3.7/site-packages/dagster_graphql/implementation/fetch_schedules.py", line 179, in get_schedule_config
    graphene_info.context.instance, handle, external_schedule.name
  File "/usr/local/lib/python3.7/site-packages/dagster/api/snapshot_schedule.py", line 27, in sync_get_external_schedule_execution_data
    schedule_name=schedule_name,
  File "/usr/local/lib/python3.7/site-packages/dagster/api/utils.py", line 32, in execute_unary_api_cli_command
    execute_command_in_subprocess(parts)
  File "/usr/local/lib/python3.7/site-packages/dagster/api/utils.py", line 14, in execute_command_in_subprocess
    "Error when executing API command {cmd}: {output}".format(cmd=e.cmd, output=e.output)
```

**Comment by gibsondan** [comment]
The relevant line here is "Could not find schedule \'daily_answer_position_pipeline\'" - @szalai1 are you still seeing this?

One possibility would be if the schedule was renamed in code while the page was still open?

Either way we should make the error message here more clear.

**Comment by szalai1** [comment]
Hey @gibsondan sorry for the late response. Not this has been resolved, thank you. Shall I close this issue?

**Comment by gibsondan** [comment]
no worries!
