### ISSUE TITLE
dagster-celery is failing if simplejson is installed

### ISSUE THREAD

**Issue by ofercaspi** [dagster-io/dagster#2745]
Hi all,

Following [this example](https://docs.dagster.io/deploying/celery) of using dagster-celery, it works out of the box.
However, once I install `simplejson` I get this error from the worker (which I couldn't extract valuable information from):

```shell
[2020-07-22 17:36:50,361: INFO/MainProcess] Received task: execute_plan[a833e3b9-3e70-4733-bc44-07b2eb611f2c]
[2020-07-22 17:36:50,425: ERROR/ForkPoolWorker-2] Task execute_plan[a833e3b9-3e70-4733-bc44-07b2eb611f2c] raised unexpected: CheckError("Failure condition: Couldn't import module module_name when attempting to rehydrate the configurable class module_name.class_name")
Traceback (most recent call last):
  File "/private/tmp/venv/lib/python3.8/site-packages/dagster/serdes/__init__.py", line 343, in rehydrate
    module = importlib.import_module(self.module_name)
  File "/Users/ofer/.pyenv/versions/3.8.3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'module_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/venv/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/private/tmp/venv/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/private/tmp/venv/lib/python3.8/site-packages/dagster_celery/tasks.py", line 23, in _execute_plan
    instance = DagsterInstance.from_ref(instance_ref)
  File "/private/tmp/venv/lib/python3.8/site-packages/dagster/core/instance/__init__.py", line 284, in from_ref
    local_artifact_storage=instance_ref.local_artifact_storage,
  File "/private/tmp/venv/lib/python3.8/site-packages/dagster/core/instance/ref.py", line 181, in local_artifact_storage
    return self.local_artifact_storage_data.rehydrate()
  File "/private/tmp/venv/lib/python3.8/site-packages/dagster/serdes/__init__.py", line 345, in rehydrate
    check.failed(
  File "/private/tmp/venv/lib/python3.8/site-packages/dagster/check/__init__.py", line 109, in failed
    raise_with_traceback(CheckError('Failure condition: {desc}'.format(desc=desc)))
  File "/private/tmp/venv/lib/python3.8/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/private/tmp/venv/lib/python3.8/site-packages/dagster/serdes/__init__.py", line 343, in rehydrate
    module = importlib.import_module(self.module_name)
  File "/Users/ofer/.pyenv/versions/3.8.3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
dagster.check.CheckError: Failure condition: Couldn't import module module_name when attempting to rehydrate the configurable class module_name.class_name
```

This is dagit's output:
```shell
2020-07-22 17:51:10 - dagster - DEBUG - parallel_pipeline - bce2bf81-8675-4865-b670-e12b020396f5 - PIPELINE_START - Started execution of pipeline "parallel_pipeline".
dagster/solid_selection = "*"
                 pid = 20266
2020-07-22 17:51:10 - dagster - DEBUG - parallel_pipeline - bce2bf81-8675-4865-b670-e12b020396f5 - ENGINE_EVENT - Submitting celery task for step "not_much_0.compute" to queue "dagster".
dagster/solid_selection = "*"
 event_specific_data = {"error": null, "marker_end": null, "marker_start": "celery_queue_wait", "metadata_entries": []}
                 pid = 20266
            step_key = "not_much_0.compute"
2020-07-22 17:51:12 - dagster - ERROR - system - bce2bf81-8675-4865-b670-e12b020396f5 - Step not_much_0.compute finished without success or failure event, assuming failure.
dagster/solid_selection = "*"
2020-07-22 17:51:12 - dagster - ERROR - parallel_pipeline - bce2bf81-8675-4865-b670-e12b020396f5 - PIPELINE_FAILURE - Execution of pipeline "parallel_pipeline" failed.
dagster/solid_selection = "*"
                 pid = 20266
```

**To reproduce:**
On a fresh virutalenv with python 3.8 (I'm on a MacOS Catalina 10.15.6):
```shell
pip install dagster dagit dagster-celery simplejson
```

The result of `pip freeze`:
```shell
alembic==1.4.2
amqp==2.6.0
aniso8601==7.0.0
attrs==19.3.0
billiard==3.6.3.0
bleach==3.1.5
celery==4.4.6
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
coloredlogs==14.0
contextlib2==0.6.0.post1
dagit==0.8.8
dagster==0.8.8
dagster-celery==0.8.8
dagster-graphql==0.8.8
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
Flask==1.1.2
Flask-Cors==3.0.8
Flask-GraphQL==2.0.1
Flask-Sockets==0.2.1
funcsigs==1.0.2
future==0.18.2
gevent==20.6.2
gevent-websocket==0.10.1
graphene==2.1.8
graphql-core==2.3.2
graphql-relay==2.0.1
graphql-server-core==1.2.0
graphql-ws==0.3.1
greenlet==0.4.16
grpcio==1.30.0
humanfriendly==8.2
idna==2.10
ipython-genutils==0.2.0
itsdangerous==1.1.0
Jinja2==2.11.2
jsonschema==3.2.0
jupyter-core==4.6.3
kombu==4.6.11
Mako==1.1.3
MarkupSafe==1.1.1
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.0.7
packaging==20.4
pandocfilters==1.4.2
pathtools==0.1.2
promise==2.3
protobuf==3.12.2
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
Rx==1.6.1
simplejson==3.17.2
six==1.15.0
SQLAlchemy==1.3.18
testpath==0.4.4
toposort==1.5
tqdm==4.48.0
traitlets==4.3.3
urllib3==1.25.9
vine==1.3.0
watchdog==0.10.3
webencodings==0.5.1
Werkzeug==1.0.1
zope.event==4.4
zope.interface==5.1.0
```
Then just follow the example in the [link](https://docs.dagster.io/deploying/celery) above.

**Comment by mrdrprofuroboros** [comment]
having the same issue currently

**Comment by natekupp** [comment]
we haven't seen any recent reports of this, closing—please reopen if you're still hitting this!

**Comment by szalai1** [comment]
This happend to us too. `simplejson` was an indirect dependency of a pkg and made all of our pipeliens break.

A bit hacky workouround: 
uninstalled the samplejson added the following where we import the pkg 
sys.modules['simplejson']

**Comment by johannkm** [comment]
Reopen if you're still hitting this!
