### ISSUE TITLE
it's not possible to use alias() and configured() together

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2795]

**Comment by mgasner** [comment]
also, unhelpful error messages for both `configured(solid.alias(...), ...)` and `configured(solid, ...).alias(...)`

**Comment by mgasner** [comment]
```
from dagster import Field, String, pipeline, solid, configured

@solid(config_schema=Field(String))
    def echo(context):
        return context.solid_config

@pipeline
def echo_pipeline():
    configured(echo)('foo').alias('bar')()
    configured(echo)('baz').alias('quux')()
```

gives: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/decorators/pipeline.py", line 91, in pipeline
    return _Pipeline()(name)
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/decorators/pipeline.py", line 29, in __call__
    context = exit_composition()
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/composition.py", line 21, in exit_composition
    return _composition_stack.pop().complete(output)
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/composition.py", line 77, in complete
    self.name, self._invocations, check.opt_dict_param(output, 'output')
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/composition.py", line 100, in __new__
    name=def_name
dagster.core.errors.DagsterInvalidDefinitionError: Detected conflicting solid definitions with the same name "echo"
```

**Comment by mgasner** [comment]
```
@pipeline
def echo_pipeline():
    configured(echo.alias('bar'), 'foo')()
```

gives:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/decorators/pipeline.py", line 91, in pipeline
    return _Pipeline()(name)
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/decorators/pipeline.py", line 27, in __call__
    fn()
  File "<stdin>", line 3, in echo_pipeline
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/config_mappable.py", line 143, in configured
    check.inst_param(configurable, 'configurable', IConfigMappable)
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/check/__init__.py", line 183, in inst_param
    obj, ttype, param_name, additional_message=additional_message
  File "/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/future/utils/__init__.py", line 472, in raise_with_traceback
    raise exc.with_traceback(traceback)
dagster.check.ParameterCheckError: Param "configurable" is not a IConfigMappable. Got <dagster.core.definitions.composition.CallableSolidNode object at 0x10a7de3c8> which is type <class 'dagster.core.definitions.composition.CallableSolidNode'>.```

**Comment by helloworld** [comment]
@ajnadel this is resolved, right?
