### ISSUE TITLE
':' is an acceptable character in pipeline names but breaks dagit

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2813]

**Comment by hellendag** [comment]
@mgasner Is this specifically a URL encoding problem, or does it surface in other ways as well?

**Comment by mgasner** [comment]
i'm not certain -- i think we would do well to define the acceptable alphabet for pipeline names (i haven't tested w/ unicode etc)

**Comment by alangenfeld** [comment]
pretty sure this has been fixed by enforcing pipeline name rules since this was first filed

**Comment by mgasner** [comment]
yep

```
>>> @pipeline(name='foo:bar')
... def foo_bar():
...     ...
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/decorators/pipeline.py", line 82, in __call__
    positional_inputs=positional_inputs,
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/pipeline.py", line 167, in __init__
    config_mapping=config_mapping,
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/graph.py", line 115, in __init__
    **kwargs,
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/i_solid_definition.py", line 17, in __init__
    self._name = check_valid_name(name)
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/definitions/utils.py", line 53, in check_valid_name
    "{name} must be in regex {regex}".format(name=name, regex=VALID_NAME_REGEX_STR)
dagster.core.errors.DagsterInvalidDefinitionError: foo:bar must be in regex ^[A-Za-z0-9_]+$
```
