### ISSUE TITLE
dagster-dask failure

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#2928]
```
Traceback (most recent call last):
--
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py36/lib/python3.6/site-packages/distributed/comm/tcp.py", line 186, in read
  | n_frames = await stream.read_bytes(8)
  | tornado.iostream.StreamClosedError: Stream is closed
  |  
  | The above exception was the direct cause of the following exception:
  |  
  | Traceback (most recent call last):
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py36/lib/python3.6/site-packages/distributed/client.py", line 1224, in _handle_report
  | msgs = await self.scheduler_comm.comm.read()
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py36/lib/python3.6/site-packages/distributed/comm/tcp.py", line 186, in read
  | n_frames = await stream.read_bytes(8)
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py36/lib/python3.6/site-packages/distributed/comm/tcp.py", line 125, in convert_stream_closed_error
  | raise CommClosedError("in %s: %s" % (obj, exc)) from exc
  | distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.6/logging/__init__.py", line 996, in emit
  | stream.write(msg)
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py36/lib/python3.6/site-packages/_pytest/capture.py", line 441, in write
  | self.buffer.write(obj)
  | ValueError: I/O operation on closed file
  | Call stack:
  | File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
  | self._bootstrap_inner()
  | File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
  | self.run()
  | File "/usr/local/lib/python3.6/threading.py", line 864, in run
  | self._target(*self._args, **self._kwargs)
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py36/lib/python3.6/site-packages/distributed/utils.py", line 418, in run_loop
  | loop.start()
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py36/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 149, in start
  | self.asyncio_loop.run_forever()
  | File "/usr/local/lib/python3.6/asyncio/base_events.py", line 442, in run_forever
  | self._run_once()
  | File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1462, in _run_once
  | handle._run()
  | File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
  | self._callback(*self._args)
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py36/lib/python3.6/site-packages/distributed/client.py", line 1224, in _handle_report
  | msgs = await self.scheduler_comm.comm.read()
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py36/lib/python3.6/site-packages/distributed/client.py", line 1081, in _reconnect
  | self._timeout,
  | Message: 'Failed to reconnect to scheduler after %.2f seconds, closing client'
  | Arguments: (10,)
  | _GatheringFuture exception was never retrieved
  | future: <_GatheringFuture finished exception=CancelledError()>
  | concurrent.futures._base.CancelledError
```

https://buildkite.com/dagster/dagster-diffs/builds/9097#ede0564d-27b4-405f-acd2-3330749f7334

**Comment by alangenfeld** [comment]
this isnt flake, straight break my be taking a PR 

fix in https://dagster.phacility.com/D4474
