### ISSUE TITLE
dagster-dask test failure

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#2948]
https://buildkite.com/dagster/dagster-diffs/builds/9271#f940f160-a128-47c4-97cb-37ef0869db60

```
Traceback (most recent call last):
--
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py37/lib/python3.7/site-packages/distributed/comm/tcp.py", line 186, in read
  | n_frames = await stream.read_bytes(8)
  | tornado.iostream.StreamClosedError: Stream is closed
  |  
  | The above exception was the direct cause of the following exception:
  |  
  | Traceback (most recent call last):
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py37/lib/python3.7/site-packages/distributed/client.py", line 1224, in _handle_report
  | msgs = await self.scheduler_comm.comm.read()
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py37/lib/python3.7/site-packages/distributed/comm/tcp.py", line 186, in read
  | n_frames = await stream.read_bytes(8)
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py37/lib/python3.7/site-packages/distributed/comm/tcp.py", line 125, in convert_stream_closed_error
  | raise CommClosedError("in %s: %s" % (obj, exc)) from exc
  | distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.7/logging/__init__.py", line 1028, in emit
  | stream.write(msg + self.terminator)
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py37/lib/python3.7/site-packages/_pytest/capture.py", line 441, in write
  | self.buffer.write(obj)
  | ValueError: I/O operation on closed file
  | Call stack:
  | File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
  | self._bootstrap_inner()
  | File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
  | self.run()
  | File "/usr/local/lib/python3.7/threading.py", line 870, in run
  | self._target(*self._args, **self._kwargs)
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py37/lib/python3.7/site-packages/distributed/utils.py", line 418, in run_loop
  | loop.start()
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py37/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 149, in start
  | self.asyncio_loop.run_forever()
  | File "/usr/local/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
  | self._run_once()
  | File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
  | handle._run()
  | File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
  | self._context.run(self._callback, *self._args)
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py37/lib/python3.7/site-packages/distributed/client.py", line 1224, in _handle_report
  | msgs = await self.scheduler_comm.comm.read()
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py37/lib/python3.7/site-packages/distributed/client.py", line 1081, in _reconnect
  | self._timeout,
  | Message: 'Failed to reconnect to scheduler after %.2f seconds, closing client'
  | Arguments: (10,)
  | _GatheringFuture exception was never retrieved
  | future: <_GatheringFuture finished exception=CancelledError()>
  | concurrent.futures._base.CancelledError
  | Exception in thread AsyncProcess Dask Worker process (from Nanny) watch process join:
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
  | self.run()
  | File "/usr/local/lib/python3.7/threading.py", line 870, in run
  | self._target(*self._args, **self._kwargs)
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py37/lib/python3.7/site-packages/distributed/process.py", line 234, in _watch_process
  | assert exitcode is not None
  | AssertionError
  | Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
  |  
```

**Comment by kinghuang** [comment]
I think this may have come from my implementation of the Dask resource, which didn't close the client and cluster after execution. I've submitted a PR to do so in #2970.
