### ISSUE TITLE
Space in path breaks the js build and the release process

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2959]
```
error Couldn't find a package.json file in "/Users/rexledesma/Dropbox (Personal)"
Traceback (most recent call last):
  File "/Users/rexledesma/.pyenv/versions/releases-0.9.10/bin/dagster-release", line 11, in <module>
    load_entry_point('automation', 'console_scripts', 'dagster-release')()
  File "/Users/rexledesma/Dropbox (Personal)/elementl/releases/0.9.10/dagster/python_modules/automation/automation/release/cli.py", line 268, in main
    click_cli()
  File "/Users/rexledesma/.pyenv/versions/3.7.4/envs/releases-0.9.10/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rexledesma/.pyenv/versions/3.7.4/envs/releases-0.9.10/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/rexledesma/.pyenv/versions/3.7.4/envs/releases-0.9.10/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rexledesma/.pyenv/versions/3.7.4/envs/releases-0.9.10/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rexledesma/.pyenv/versions/3.7.4/envs/releases-0.9.10/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/rexledesma/Dropbox (Personal)/elementl/releases/0.9.10/dagster/python_modules/automation/automation/release/cli.py", line 114, in publish
    dmp.publish_all(dry_run=dry_run)
  File "/Users/rexledesma/Dropbox (Personal)/elementl/releases/0.9.10/dagster/python_modules/automation/automation/release/dagster_module_publisher.py", line 284, in publish_all
    module.publish(dry_run=dry_run)
  File "/Users/rexledesma/Dropbox (Personal)/elementl/releases/0.9.10/dagster/python_modules/automation/automation/release/dagster_module.py", line 154, in publish
    module_name=self.name, code=process.returncode, command=command, cwd=cwd
AssertionError: Something went wrong while attempting to publish module dagit! Got code 1 from command "./build_js.sh" in cwd /Users/rexledesma/Dropbox (Personal)/elementl/releases/0.9.10/dagster/python_modules/dagit
```

this is from `python_modules/dagit/build_js.sh`

**Comment by natekupp** [comment]
This was fixed by https://dagster.phacility.com/D4543
