### ISSUE TITLE
Fix doc build instructions

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2997]
im trying to build the docs and hitting this
4:23
FileNotFoundError: [Errno 2] No such file or directory: '/Users/max/dev/dagster-release/dagster/docs/out'
New

sashank  4:23 PM
try mkdir -p that and running again

max  4:23 PM
ok
4:24
also getting
Traceback (most recent call last):
  File "/Users/max/.pyenv/versions/3.7.2/lib/python3.7/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/max/.pyenv/versions/3.7.2/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/Users/max/dev/dagster-release/dagster/docs/conf.py", line 24, in <module>
    from dagster.utils import script_relative_path
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/__init__.py", line 110, in <module>
    from dagster.core.launcher import DefaultRunLauncher
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/launcher/__init__.py", line 2, in <module>
    from .cli_api_run_launcher import CliApiRunLauncher
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/launcher/cli_api_run_launcher.py", line 6, in <module>
    from dagster.api.execute_run import cli_api_launch_run
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/api/execute_run.py", line 2, in <module>
    from dagster.cli.api import ExecuteRunArgsLoadComplete
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/cli/__init__.py", line 8, in <module>
    from .api import api_cli
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/cli/api.py", line 13, in <module>
    from dagster.cli.workspace.cli_target import (
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/cli/workspace/__init__.py", line 1, in <module>
    from .cli_target import get_workspace_from_kwargs, workspace_target_argument
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/cli/workspace/cli_target.py", line 13, in <module>
    from dagster.core.host_representation import ExternalRepository, RepositoryLocation
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/host_representation/__init__.py", line 48, in <module>
    from .repository_location import (
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/host_representation/repository_location.py", line 7, in <module>
    from dagster.api.snapshot_executable import (
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/api/snapshot_executable.py", line 8, in <module>
    from dagster.grpc.types import ExternalExecutableArgs
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/grpc/__init__.py", line 11, in <module>
    from .client import DagsterGrpcClient, ephemeral_grpc_api_client
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/grpc/client.py", line 7, in <module>
    import grpc
ModuleNotFoundError: No module named 'grpc'

sashank  4:24 PM
u need to do a make dev_install

**Comment by yuhan** [comment]
@helloworld have we fixed it?

**Comment by helloworld** [comment]
Yeah I believe they were already correct
