### ISSUE TITLE
Dagit exits if grpc_server is not reachable

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#3001]
I converted an existing project to have Dagit use [grpc_server](https://docs.dagster.io/overview/repositories-workspaces/workspaces#grpc-server) configs to load repositories. However, Dagit does a hard exit if any of the servers are unreachable.

<details><summary>Stack Trace</summary>

```
Traceback (most recent call last):
  File "/usr/local/bin/dagit", line 33, in <module>
    sys.exit(load_entry_point('dagit', 'console_scripts', 'dagit')())
  File "/usr/local/lib/python3.8/site-packages/dagit/cli.py", line 198, in main
    cli(auto_envvar_prefix="DAGIT")  # pylint:disable=E1120
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dagit/cli.py", line 91, in ui
    host_dagit_ui(host, port, path_prefix, storage_fallback, port_lookup, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dagit/cli.py", line 98, in host_dagit_ui
    with get_workspace_from_kwargs(kwargs, instance) as workspace:
  File "/usr/local/lib/python3.8/site-packages/dagster/cli/workspace/cli_target.py", line 213, in get_workspace_from_kwargs
    return workspace_from_load_target(created_workspace_load_target(kwargs), instance)
  File "/usr/local/lib/python3.8/site-packages/dagster/cli/workspace/cli_target.py", line 173, in workspace_from_load_target
    return load_workspace_from_yaml_paths(
  File "/usr/local/lib/python3.8/site-packages/dagster/cli/workspace/load.py", line 22, in load_workspace_from_yaml_paths
    workspaces = [
  File "/usr/local/lib/python3.8/site-packages/dagster/cli/workspace/load.py", line 23, in <listcomp>
    load_workspace_from_config(workspace_config, yaml_path, python_user_process_api)
  File "/usr/local/lib/python3.8/site-packages/dagster/cli/workspace/load.py", line 60, in load_workspace_from_config
    _location_handle_from_location_config(
  File "/usr/local/lib/python3.8/site-packages/dagster/cli/workspace/load.py", line 287, in _location_handle_from_location_config
    return _location_handle_from_grpc_server_config(location_config["grpc_server"], yaml_path)
  File "/usr/local/lib/python3.8/site-packages/dagster/cli/workspace/load.py", line 235, in _location_handle_from_grpc_server_config
    return RepositoryLocationHandle.create_grpc_server_location(
  File "/usr/local/lib/python3.8/site-packages/dagster/core/host_representation/handle.py", line 219, in create_grpc_server_location
    list_repositories_response = sync_list_repositories_grpc(client)
  File "/usr/local/lib/python3.8/site-packages/dagster/api/list_repositories.py", line 39, in sync_list_repositories_grpc
    api_client.list_repositories(), (ListRepositoriesResponse, SerializableErrorInfo)
  File "/usr/local/lib/python3.8/site-packages/dagster/grpc/client.py", line 123, in list_repositories
    res = self._query("ListRepositories", api_pb2.ListRepositoriesRequest)
  File "/usr/local/lib/python3.8/site-packages/dagster/grpc/client.py", line 72, in _query
    response = getattr(stub, method)(request_type(**kwargs), timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1601737254.860446185","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3948,"referenced_errors":[{"created":"@1601737254.860399119","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}"
```
</details>

This is annoying during development when I start a Dagit container and a Dagster gRPC server container at the same time, and Dagit launches faster than the gRPC server. I imagine this will also be a problem in deployment if any of the target gRPC servers are unavailable for any reason.

I think Dagit should gracefully handle unavailable gRPC servers by continuing to launch and trying to fetch repository information again with a delay.

**Comment by gibsondan** [comment]
Good point and agreed - I think this is functionally the same as issue #2918, which we should prioritize.

**Comment by kinghuang** [comment]
Ah, yes, this does look like a dupe of that one. I'll close this one in favour of #2918.
