### ISSUE TITLE
Dagster dask flakey test

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3170]
https://buildkite.com/dagster/dagster-diffs/builds/10966#a3cc8827-e120-41c2-b076-9f084702e87e

```

[183] /workdir/python_modules/libraries/dagster-dask$ /bin/echo -e '--- \033[0;32m:pytest: Running tox tests\033[0m'
--
  | Running tox tests | 4m 9s
  | Logging error --- | 0s
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.8/logging/__init__.py", line 1084, in emit
  | stream.write(msg + self.terminator)
  | ValueError: I/O operation on closed file.
  | Call stack:
  | File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
  | self._bootstrap_inner()
  | File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  | self.run()
  | File "/usr/local/lib/python3.8/threading.py", line 870, in run
  | self._target(*self._args, **self._kwargs)
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py38/lib/python3.8/site-packages/distributed/utils.py", line 417, in run_loop
  | loop.start()
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py38/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 149, in start
  | self.asyncio_loop.run_forever()
  | File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
  | self._run_once()
  | File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
  | handle._run()
  | File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
  | self._context.run(self._callback, *self._args)
  | File "/workdir/python_modules/libraries/dagster-dask/.tox/py38/lib/python3.8/site-packages/distributed/nanny.py", line 456, in _on_exit
  | logger.warning("Restarting worker")
  | Message: 'Restarting worker'
``

**Comment by gibsondan** [comment]
still seeing teardown issues after fixing the test failure: https://buildkite.com/dagster/dagster-diffs/builds/11094#9206ab03-62a7-44f4-a99c-05577a78aad7

**Comment by sryza** [comment]
Haven't seen this flake in a long while, so closing
