### ISSUE TITLE
[core] fan-in does not support input mappings

### ISSUE THREAD

**Issue by nancydyc** [dagster-io/dagster#3176]
**Summary**
```
def example_computation(num1, num2):
    res1 = operate_two_nums.alias("res1")
    res2 = operate_two_nums.alias("res2")
    return combine(res1([num1, num2]), res2([num1, num2]))
```
When providing inputs for solid res1 and res2 within a composite solid, got invalid type error message like below. The input should be a list for the solid operate_two_nums/res1/res2, but I was not sure if I should redefine the input for the composite solid or the solids res1 and res2.

```(dagster-3.7.4) ➜  elementl git:(myexpl) ✗ python3 config_mapping_and_expectation_result.py
Invalid -W option ignored: unknown warning category: 'ExperimentalWarning'
/Users/a16502/dagster/python_modules/dagster/dagster/core/definitions/composition.py:39: UserWarning: While in @composite_solid context 'example_computation', received an uninvoked solid 'operate_two_nums'.
'operate_two_nums' was aliased as 'res1'.
  warnings.warn(warning_message.strip())
/Users/a16502/dagster/python_modules/dagster/dagster/core/definitions/composition.py:39: UserWarning: While in @composite_solid context 'example_computation', received an uninvoked solid 'operate_two_nums'.
'operate_two_nums' was aliased as 'res2'.
  warnings.warn(warning_message.strip())
Traceback (most recent call last):
  File "config_mapping_and_expectation_result.py", line 76, in <module>
    config_schema={"operator": Field(str, is_required=False, default_value="divide")}
  File "/Users/a16502/dagster/python_modules/dagster/dagster/core/definitions/decorators/composite_solid.py", line 75, in __call__
    output = fn(**kwargs)
  File "config_mapping_and_expectation_result.py", line 81, in example_computation
    return combine(res1([num1, num2]), res2([num1, num2])) # pylint: disable=no-value-for-parameter
  File "/Users/a16502/dagster/python_modules/dagster/dagster/core/definitions/composition.py", line 235, in __call__
    "(at position {idx})".format(idx=idx),
  File "/Users/a16502/dagster/python_modules/dagster/dagster/core/definitions/composition.py", line 291, in _process_argument_node
    solid_name=solid_name,
dagster.core.errors.DagsterInvalidDefinitionError: In @composite_solid example_computation, received a list containing invalid types for input "nums" (at position 0) in solid invocation res1. Lists can only contain the output from previous solid invocations.
```

**Repro**
The original codes:

```
@solid(
    config_schema={
        "cluster_cfg": Shape(
            {
                "%": int,
                "ave": int
            }
        ),
        "operator": Field(str, is_required=False, default_value="ave")
    }
)
def operate_two_nums(context, nums: list):
    if context.solid_config["operator"] == "ave":
        x = context.solid_config["cluster_cfg"]["ave"]
        print(x)
        return (nums[1] + nums[0]) / x # 150
    elif context.solid_config["operator"] == "subtract":
        return nums[1] - nums[0]
    elif context.solid_config["operator"] == "divide":
        y = context.solid_config["cluster_cfg"]["%"]
        print(y)
        return (nums[1] / nums[0]) * y # 200
    elif context.solid_config["operator"] == "multiply":
        return nums[1] * nums[0]


@solid
def combine(_context, num1, num2):
    result = num2 + num1
    yield ExpectationResult(
        success=result > 0, 
        description="ensure positive result",
        metadata_entries=[
            EventMetadataEntry.text("{result}".format(result=result), label="combine result")
        ])
    yield Output(result)


def config_mapping_fn(cfg):
    return {
        "res1": {
            "config": {
                "cluster_cfg": {
                    "%": 100,
                    "ave": 2
                },
                # "operator": "ave" # (by default, operator will be "ave")
            }
        },
        "res2": {
            "config": {
                "cluster_cfg": {
                    "%": 100,
                    "ave": 2
                },
                "operator": "ave" # can hard code value "divide" or "ave"
            }
        }
    }

@composite_solid(
    config_fn=config_mapping_fn,
    config_schema={"operator": Field(str, is_required=False, default_value="divide")}
)
def example_computation(num1, num2):
    res1 = operate_two_nums.alias("res1")
    res2 = operate_two_nums.alias("res2")
    return combine(res1([num1, num2]), res2([num1, num2])) # pylint: disable=no-value-for-parameter`
    

@pipeline
def example_computation_pipeline():
    example_computation() # pylint: disable=no-value-for-parameter
```

**Comment by alangenfeld** [comment]
You actually just hit on a lacking feature of support for input mappings in to fan-ins
