### ISSUE TITLE
AttributeError: 'ManagedGrpcPythonEnvRepositoryLocationHandle' object has no attribute 'client'

### ISSUE THREAD

**Issue by JBrVJxsc** [dagster-io/dagster#3229]
## Summary
```
Traceback (most recent call last):
  File "/export/content/lid/apps/dagster-web/i001/libexec/dagster-web_c0ef7b83c436eed3e1fde58bf84f5616e03c48d7605c710cc48b8158b3748442/site-packages/dagster/core/host_representation/handle.py", line 245, in __del__
    self.is_cleaned_up,
  File "/export/content/lid/apps/dagster-web/i001/libexec/dagster-web_c0ef7b83c436eed3e1fde58bf84f5616e03c48d7605c710cc48b8158b3748442/site-packages/dagster/core/host_representation/handle.py", line 241, in is_cleaned_up
    return not self.client
AttributeError: 'ManagedGrpcPythonEnvRepositoryLocationHandle' object has no attribute 'client'
```

## Reproduction
Call `is_cleaned_up` without a client.

**Comment by gibsondan** [comment]
Thanks for the report - this is fixed in https://github.com/dagster-io/dagster/commit/66497ad90d60c75ea9a355dabbc9ee5dbae80ab0
