### ISSUE TITLE
Support datetime in AssetMaterialization with JsonMetadataEntryData

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#3480]
## Use Case

When yielding an AssetMaterialization, if the content of the dict in JsonMetadataEntryData is a datetime, the job fails complaining that datetime is not serializable.  

What do you think about handling datetimes like [Pydantic](https://pydantic-docs.helpmanual.io/usage/types/#datetime-types) does? It's not strictly necessary (the user can always convert the dictionary manually), but I feel like it would be nice to have.

Expand to see the error trace:
<details>
```
Traceback (most recent call last):
  File "/usr/local/bin/dagster", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/dagster/cli/__init__.py", line 41, in main
    cli(auto_envvar_prefix=ENV_PREFIX)  # pylint:disable=E1123
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dagster/cli/api.py", line 251, in execute_step_with_structured_logs_command
    execution_plan, pipeline_run, instance, run_config=args.run_config, retries=retries,
  File "/usr/local/lib/python3.7/site-packages/dagster/core/execution/api.py", line 728, in __iter__
    execution_plan=self.execution_plan, pipeline_context=self.pipeline_context,
  File "/usr/local/lib/python3.7/site-packages/dagster/core/execution/plan/execute_plan.py", line 78, in inner_plan_execution_iterator
    _dagster_event_sequence_for_step(step_context, retries)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/execution/plan/execute_plan.py", line 284, in _dagster_event_sequence_for_step
    raise unexpected_exception
  File "/usr/local/lib/python3.7/site-packages/dagster/core/execution/plan/execute_plan.py", line 212, in _dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.7/site-packages/dagster/core/execution/plan/execute_step.py", line 291, in core_dagster_event_sequence_for_step
    for evt in _create_step_events_for_output(step_context, user_event):
  File "/usr/local/lib/python3.7/site-packages/dagster/core/execution/plan/execute_step.py", line 328, in _create_step_events_for_output
    for evt in _create_output_materializations(step_context, output.output_name, output.value):
  File "/usr/local/lib/python3.7/site-packages/dagster/core/execution/plan/execute_step.py", line 447, in _create_output_materializations
    yield DagsterEvent.step_materialization(step_context, materialization)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/events/__init__.py", line 574, in step_materialization
    else ""
  File "/usr/local/lib/python3.7/site-packages/dagster/core/events/__init__.py", line 215, in from_step
    log_step_event(step_context, event)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/events/__init__.py", line 143, in log_step_event
    pipeline_name=step_context.pipeline_def.name,
  File "/usr/local/lib/python3.7/site-packages/dagster/core/log_manager.py", line 237, in debug
    return self._log(logging.DEBUG, msg, kwargs)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/log_manager.py", line 207, in _log
    logger_.log(level, message, extra=extra)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1444, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/instance/__init__.py", line 137, in emit
    self._instance.handle_new_event(event)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/instance/__init__.py", line 997, in handle_new_event
    self._event_storage.store_event(event)
  File "/usr/local/lib/python3.7/site-packages/dagster_postgres/event_log/event_log.py", line 102, in store_event
    insert_event_statement = self.prepare_insert_event(event)  # from SqlEventLogStorage.py
  File "/usr/local/lib/python3.7/site-packages/dagster/core/storage/event_log/sql_event_log.py", line 84, in prepare_insert_event
    event=serialize_dagster_namedtuple(event),
  File "/usr/local/lib/python3.7/site-packages/dagster/serdes/__init__.py", line 228, in serialize_dagster_namedtuple
    check.tuple_param(nt, "nt"), whitelist_map=_WHITELIST_MAP, **json_kwargs
  File "/usr/local/lib/python3.7/site-packages/dagster/serdes/__init__.py", line 213, in _serialize_dagster_namedtuple
    return seven.json.dumps(_pack_value(nt, whitelist_map), **json_kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```
</details>

## Ideas of Implementation

I think the change should probably be in https://github.com/dagster-io/dagster/blob/662c076b088e480066c4a5957ebd2cca599e0884/python_modules/dagster/dagster/serdes/__init__.py#L212 
and could probably borrow from Pydantic the datetime logic.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by GKTheOne** [comment]
Using `datetime.isoformat` is a "good enough" work around for me at the moment.
Mainly because I don't use the datetime once it's in the dictionary used to set the metadata, so I can stringify the value on assignment to the dictionary.

**Comment by sryza** [comment]
This is related to (or possible the same as) https://github.com/dagster-io/dagster/issues/13344

**Comment by CarlyAThomas** [comment]
Hi team! 👋

@amarrella I believe this issue may now be resolved with the merge of [PR #20328](https://github.com/dagster-io/dagster/pull/20328), which introduced the TimestampMetadataValue class and updated MetadataValue.from_python_value() to support datetime objects.

This issue also appears to be related to [#13344](https://github.com/dagster-io/dagster/issues/13344), which focused on JSON serialization of datetime values in metadata. Based on the comments and test references in that thread, it seems both issues may be addressed by the same PR.

While testing locally, I found that passing a datetime object directly to JsonMetadataValue still raises a DagsterInvalidMetadata error — which I believe is expected behavior now that users are encouraged to use TimestampMetadataValue instead for that data type.

If that's the case, perhaps both of these issues could be closed.
@alangenfeld since you helped guide the related PR, would you mind confirming if this now fully resolves the concerns raised here?

One remaining note: if someone still passes a datetime into JsonMetadataValue, it fails silently unless the user explicitly tries to serialize it with json.dumps(). It might be helpful to raise a more visible warning or error in such cases to make this failure mode more obvious, or even suggest using TimestampMetadataValue instead.

Thanks so much to the team for your great work on this!
