### ISSUE TITLE
0.10.0 Instance Migration

### ISSUE THREAD

**Issue by dehume-drizly** [dagster-io/dagster#3606]
## Summary
First time doing a Dagster instance migration (going from 0.9.15 to 0.10.0). We have Dagster running on ECS and the RDS instance is on private subnets so executing the migration dagster instance migration by running an ECS task on the cluster. Getting this error
```
2021-01-26T06:53:01.365-06:00 | $DAGSTER_HOME: /opt/dagster/dagster_home/
-- | --
  | 2021-01-26T06:53:03.000-06:00 | Updating run storage...
  | 2021-01-26T06:53:03.059-06:00 | INFO [alembic.runtime.migration] Context impl PostgresqlImpl.
  | 2021-01-26T06:53:03.059-06:00 | INFO [alembic.runtime.migration] Will assume transactional DDL.
  | 2021-01-26T06:53:03.067-06:00 | INFO [alembic.runtime.migration] Running upgrade 567bc23fd1ac -> 8f8dba68fd3b, cascade run deletion
  | 2021-01-26T06:53:03.072-06:00 | Traceback (most recent call last):
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/bin/dagster", line 8, in <module>
  | 2021-01-26T06:53:03.072-06:00 | sys.exit(main())
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/dagster/cli/__init__.py", line 43, in main
  | 2021-01-26T06:53:03.072-06:00 | cli(auto_envvar_prefix=ENV_PREFIX) # pylint:disable=E1123
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
  | 2021-01-26T06:53:03.072-06:00 | return self.main(*args, **kwargs)
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
  | 2021-01-26T06:53:03.072-06:00 | rv = self.invoke(ctx)
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
  | 2021-01-26T06:53:03.072-06:00 | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
  | 2021-01-26T06:53:03.072-06:00 | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
  | 2021-01-26T06:53:03.072-06:00 | return ctx.invoke(self.callback, **ctx.params)
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
  | 2021-01-26T06:53:03.072-06:00 | return callback(*args, **kwargs)
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/dagster/cli/instance.py", line 47, in migrate_command
  | 2021-01-26T06:53:03.072-06:00 | instance.upgrade(click.echo)
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/dagster/core/instance/__init__.py", line 482, in upgrade
  | 2021-01-26T06:53:03.072-06:00 | self._run_storage.upgrade()
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/dagster_postgres/run_storage/run_storage.py", line 102, in upgrade
  | 2021-01-26T06:53:03.072-06:00 | run_alembic_upgrade(alembic_config, self._engine)
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/dagster/core/storage/sql.py", line 28, in run_alembic_upgrade
  | 2021-01-26T06:53:03.072-06:00 | upgrade(alembic_config, rev)
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 294, in upgrade
  | 2021-01-26T06:53:03.072-06:00 | script.run_env()
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 481, in run_env
  | 2021-01-26T06:53:03.072-06:00 | util.load_python_file(self.dir, "env.py")
  | 2021-01-26T06:53:03.072-06:00 | File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
  | 2021-01-26T06:53:03.072-06:00 | module = load_module_py(module_id, path)
  | 2021-01-26T06:53:03.073-06:00 | File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 182, in load_module_py
  | 2021-01-26T06:53:03.073-06:00 | spec.loader.exec_module(module)
  | 2021-01-26T06:53:03.073-06:00 | File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  | 2021-01-26T06:53:03.073-06:00 | File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  | 2021-01-26T06:53:03.073-06:00 | File "/usr/local/lib/python3.7/site-packages/dagster_postgres/run_storage/alembic/env.py", line 72, in <module>
  | 2021-01-26T06:53:03.073-06:00 | run_migrations_online()
  | 2021-01-26T06:53:03.073-06:00 | File "/usr/local/lib/python3.7/site-packages/dagster_postgres/run_storage/alembic/env.py", line 66, in run_migrations_online
  | 2021-01-26T06:53:03.073-06:00 | context.run_migrations()
  | 2021-01-26T06:53:03.073-06:00 | File "<string>", line 8, in run_migrations
  | 2021-01-26T06:53:03.073-06:00 | File "/usr/local/lib/python3.7/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
  | 2021-01-26T06:53:03.073-06:00 | self.get_context().run_migrations(**kw)
  | 2021-01-26T06:53:03.073-06:00 | File "/usr/local/lib/python3.7/site-packages/alembic/runtime/migration.py", line 560, in run_migrations
  | 2021-01-26T06:53:03.073-06:00 | step.migration_fn(**kw)
  | 2021-01-26T06:53:03.073-06:00 | File "/usr/local/lib/python3.7/site-packages/dagster_postgres/run_storage/alembic/versions/8f8dba68fd3b_cascade_run_deletion.py", line 27, in upgrade
  | 2021-01-26T06:53:03.073-06:00 | op.drop_constraint("run_tags_run_id_fkey", table_name="run_tags", type="foreignkey")
  | 2021-01-26T06:53:03.073-06:00 | File "<string>", line 8, in drop_constraint
  | 2021-01-26T06:53:03.073-06:00 | TypeError: drop_constraint() got an unexpected keyword argument 'type'
```

## Reproduction
Running 0.9.15 and trying to migrate the instance database

## Additional Info about Your Environment
Running dagit service on ECS
---
#### Message from the maintainers:
Cannot upgrade to 0.10.0 without manually deleting database

**Comment by schrockn** [comment]
Thanks!

**Comment by schrockn** [comment]
Assigned to dan because of commentary around type param in this diff https://dagster.phacility.com/D6040

**Comment by gibsondan** [comment]
Hi @dehume-drizly, sorry for the trouble here. While we fix this on our side, is it an option for you to run a pip command on the machine that’s doing the upgrade?

I think pip uninstalling alembic and re-installing it at version 1.4.3 (the previous version) is likely to make the upgrade work as a temporary workaround (there was a breaking change in the alembic 1.5.0 release). In the meantime we’ll get this fixed on the dagster side too ASAP.

**Comment by gibsondan** [comment]
Er acctually, looking closer now - are you sure that the box that you're running the migrate command on has actually installed dagster 0.10.0? The line in the error message says

"op.drop_constraint("run_tags_run_id_fkey", table_name="run_tags", type="foreignkey")"

but I'm fairly confident that the code in the 0.10.0 release has been updated since then.

**Comment by gibsondan** [comment]
Update: I believe that upgrading to dagster 0.10.1 rather than 0.10.0 will fix this problem - we added code to account for the latest alembic update as part of that release.

**Comment by dehume-drizly** [comment]
Sounds good. I changed to alembic to 1.4.3 (while still using 0.10.0) and the migration was successful. Longer term I'll update to 0.10.1

**Comment by gibsondan** [comment]
Great! Just let us know if anything else comes up.
