### ISSUE TITLE
Unable to use schedules with GRPC server

### ISSUE THREAD

**Issue by amillette** [dagster-io/dagster#3650]
## Summary
Dagit crash when using schedules in a GRPC server since version 0.10.3

```
Traceback (most recent call last):
  File "/usr/local/bin/dagit", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/dagit/cli.py", line 212, in main
    cli(auto_envvar_prefix="DAGIT")  # pylint:disable=E1120
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dagit/cli.py", line 107, in ui
    host_dagit_ui(
  File "/usr/local/lib/python3.8/site-packages/dagit/cli.py", line 133, in host_dagit_ui
    host_dagit_ui_with_workspace(instance, workspace, host, port, path_prefix, port_lookup)
  File "/usr/local/lib/python3.8/site-packages/dagit/cli.py", line 140, in host_dagit_ui_with_workspace
    log_workspace_stats(instance, workspace)
  File "/usr/local/lib/python3.8/site-packages/dagster/core/telemetry.py", line 417, in log_workspace_stats
    repo_location = RepositoryLocation.from_handle(repository_location_handle)
  File "/usr/local/lib/python3.8/site-packages/dagster/core/host_representation/repository_location.py", line 143, in from_handle
    return GrpcServerRepositoryLocation(repository_location_handle)
  File "/usr/local/lib/python3.8/site-packages/dagster/core/host_representation/repository_location.py", line 315, in __init__
    external_repositories_list = sync_get_streaming_external_repositories_grpc(
  File "/usr/local/lib/python3.8/site-packages/dagster/api/snapshot_repository.py", line 54, in sync_get_streaming_external_repositories_grpc
    external_repository_data = deserialize_json_to_dagster_namedtuple(
  File "/usr/local/lib/python3.8/site-packages/dagster/serdes/__init__.py", line 265, in deserialize_json_to_dagster_namedtuple
    dagster_namedtuple = _deserialize_json_to_dagster_namedtuple(
  File "/usr/local/lib/python3.8/site-packages/dagster/serdes/__init__.py", line 278, in _deserialize_json_to_dagster_namedtuple
    return _unpack_value(seven.json.loads(json_str), whitelist_map=whitelist_map)
  File "/usr/local/lib/python3.8/site-packages/dagster/serdes/__init__.py", line 250, in _unpack_value
    return klass(**filtered_val)
  File "/usr/local/lib/python3.8/site-packages/dagster/core/host_representation/external_data.py", line 60, in __new__
    external_job_datas=check.opt_list_param(
  File "/usr/local/lib/python3.8/site-packages/dagster/check/__init__.py", line 482, in opt_list_param
    return _check_list_items(obj_list, of_type)
  File "/usr/local/lib/python3.8/site-packages/dagster/check/__init__.py", line 369, in _check_list_items
    raise_with_traceback(
  File "/usr/local/lib/python3.8/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
dagster.check.CheckError: Member of list mismatches type. Expected <class 'dagster.core.host_representation.external_data.ExternalJobData'>. Got ExternalScheduleData(name='my_schedule', cron_schedule='* * * * *', pipeline_name='my_pipeline', solid_selection=None, mode='default', environment_vars={}, partition_set_name=None, execution_timezone='America/Toronto') of type <class 'dagster.core.host_representation.external_data.ExternalScheduleData'>.
```

## Reproduction
```
from dagster import pipeline, repository, schedule, solid


@solid
def hello(_):
    return 1


@pipeline
def my_pipeline():
    hello()


@schedule(cron_schedule="* * * * *", pipeline_name="my_pipeline", execution_timezone="America/Toronto")
def my_schedule(_context):
    return {}


@repository
def my_repository():
    return [my_pipeline, my_schedule]
```

## Additional Info about Your Environment
```
# ==================================================================================================
# Run Storage
# ==================================================================================================
# Controls how the history of runs is persisted. Can be set to SqliteRunStorage (default) or
# PostgresRunStorage.
run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      username:
        env: DAGSTER_POSTGRES_USERNAME
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      hostname:
        env: DAGSTER_POSTGRES_HOSTNAME
      db_name:
        env: DAGSTER_POSTGRES_DATABASE
      port: 5432

# ==================================================================================================
# Event Log Storage
# ==================================================================================================
# Controls how the structured event logs produced by each run are persisted. Can be set to
# SqliteEventLogStorage (default) or PostgresEventLogStorage.
event_log_storage:
  module: dagster_postgres.event_log
  class: PostgresEventLogStorage
  config:
    postgres_db:
      username:
        env: DAGSTER_POSTGRES_USERNAME
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      hostname:
        env: DAGSTER_POSTGRES_HOSTNAME
      db_name:
        env: DAGSTER_POSTGRES_DATABASE
      port: 5432

# ==================================================================================================
# Scheduler
# ==================================================================================================
# Provides an optional scheduler which controls execution of pipeline runs at regular intervals.
# We recommend using the default DagsterDaemonScheduler - SystemCronScheduler and K8sScheduler are
# also available but are deprecated.
scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

# ==================================================================================================
# Schedule Storage
# ==================================================================================================
# Controls the backing storage used by the scheduler to manage the state of schedules and persist
# records of attempts.
schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_db:
      username:
        env: DAGSTER_POSTGRES_USERNAME
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      hostname:
        env: DAGSTER_POSTGRES_HOSTNAME
      db_name:
        env: DAGSTER_POSTGRES_DATABASE
      port: 5432

# ==================================================================================================
# Run Launcher
# ==================================================================================================
# Component that determines where runs are executed.
run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
  config:
    env_vars:
      - DAGSTER_POSTGRES_USERNAME
      - DAGSTER_POSTGRES_PASSWORD
      - DAGSTER_POSTGRES_HOSTNAME
      - DAGSTER_POSTGRES_DATABASE
      - AWS_ENDPOINT_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DAGSTER_BUCKET
    network: host

# ==================================================================================================
# Run Coordinator
# ==================================================================================================
# Determines the policy used to determine the prioritization rules and concurrency limits for runs.
# Can be set to DefaultRunCoordinator (default) or QueuedRunCoordinator when you want to maintain
# limits on the number of runs that can be executing at once.
run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator

# ==================================================================================================
# Compute Log Storage
# ==================================================================================================
# Controls the capture and persistence of raw stdout & stderr text logs.
#
# Currently supported:
# - LocalComputeLogManager (default)
# - AzureBlobComputeLogManager
# - S3ComputeLogManager
compute_logs:
  module: dagster_aws.s3.compute_log_manager
  class: S3ComputeLogManager
  config:
    endpoint_url:
      env: AWS_ENDPOINT_URL
    bucket:
      env: AWS_DAGSTER_BUCKET
    prefix: "logs"

# ==================================================================================================
# Local Artifact Storage
# ==================================================================================================
# Controls where to store data on the local disk. Primarily used for storing schedule metadata.
#
# Currently only supports LocalArtifactStorage.
local_artifact_storage:
  module: dagster.core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: "/var/shared/dagster"

# ==================================================================================================
# Telemetry
# ==================================================================================================
# Allows opting out of Dagster collecting usage statistics. See
# https://docs.dagster.io/install#telemetry for more details.
telemetry:
  enabled: false
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @amillette - sorry for the trouble here. A couple of follow-up questions: Can I ask what your workspace.yaml setup is, are you running your own gRPC server with the 'dagster api grpc' command? 

If so, when you updated dagit to 0.10.3, did you also update your gRPC server as well to use the new release?

**Comment by gibsondan** [comment]
Er, I had that reversed actually.  Is it possible that you updated your gRPC server to 0.10.3 but didn't update dagit? The stack trace there looks like it's from 0.10.2.

We'd like to be able to guarantee more backwards/forwards compatibility between the gRPC servers and dagit in the future, but at the moment the best bet is to update them both after a new release.

**Comment by amillette** [comment]
You're right @gibsondan, my gRPC server container was on version 0.10.3 but not the Dagit container. I had to rebuild each stages of my Dockerfile since it only detected changes from the Pipfile and Pipfile.lock

```
# Dockerfile
FROM python:3.8 AS dagster

RUN pip install \
    dagster \
    dagit \
    dagster-aws \
    dagster-docker \
    dagster-postgres

ENV DAGSTER_APP=/opt/dagster/dagster_app/

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_APP $DAGSTER_HOME

COPY config/dagster.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_APP


FROM dagster AS pipelines

RUN pip install pipenv

COPY Pipfile Pipfile.lock $DAGSTER_APP

RUN pipenv install --system

COPY . $DAGSTER_APP

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "repository.py"]
```

Thanks for your help :)
