### ISSUE TITLE
Inconsistent treatment of Enum when doing composition, parse not idempotent

### ISSUE THREAD

**Issue by antonl** [dagster-io/dagster#3663]
## Summary

When declaring a field as an enum, the configuration system expects one to pass the field name of the enum as a string instead of the enum value. When writing a composite solid, this means that the config coercion isn't idempotent. This is because after the first parse of the config for the composite solid, the inner solid will not accept an enum type as input.

The workaround is to extract the field name and pass that in, but this results in double enum conversion. I expected that the config system would take either the enum value itself or a string representing the name.

## Reproduction

```python
import enum
from dagster import (
    solid,
composite_solid,
execute_solid,
    Field, Enum
)

class CaseTypes(enum.Enum):
    lower = "lower"
    upper = "upper"
    preserve = "preserve"


ingest_schema = {
    "column_case": Field(Enum.from_python_enum(CaseTypes),
                         default_value=CaseTypes.preserve.name),
}

def ingest_config_fn(cfg):
    cfg = {
        "ingest": {
            "config": {
                "column_case": cfg.get("column_case"),
            }
        }
    }

    return cfg

@solid(
    config_schema=ingest_schema
)
def ingest(_):
    ...

@composite_solid(config_schema=ingest_schema,
                 config_fn=ingest_config_fn,
                 )
def curried():
    return ingest()


runtime = execute_solid(curried)

```

This results in a traceback:
```python-traceback
Traceback (most recent call last):
  File "[...snip..]/enum_solid.py", line 45, in <module>
    runtime = execute_solid(curried)
  File "/opt/miniconda3/envs/dp-dagster/lib/python3.8/site-packages/dagster/utils/test/__init__.py", line 309, in execute_solid
    result = execute_pipeline(
  File "/opt/miniconda3/envs/dp-dagster/lib/python3.8/site-packages/dagster/core/execution/api.py", line 356, in execute_pipeline
    return _logged_execute_pipeline(
  File "/opt/miniconda3/envs/dp-dagster/lib/python3.8/site-packages/dagster/core/telemetry.py", line 88, in wrap
    result = f(*args, **kwargs)
  File "/opt/miniconda3/envs/dp-dagster/lib/python3.8/site-packages/dagster/core/execution/api.py", line 398, in _logged_execute_pipeline
    pipeline_run = instance.create_run_for_pipeline(
  File "/opt/miniconda3/envs/dp-dagster/lib/python3.8/site-packages/dagster/core/instance/__init__.py", line 599, in create_run_for_pipeline
    full_execution_plan = execution_plan or create_execution_plan(
  File "/opt/miniconda3/envs/dp-dagster/lib/python3.8/site-packages/dagster/core/execution/api.py", line 668, in create_execution_plan
    environment_config = EnvironmentConfig.build(pipeline_def, run_config, mode=mode)
  File "/opt/miniconda3/envs/dp-dagster/lib/python3.8/site-packages/dagster/core/system_config/objects.py", line 153, in build
    solid_config_dict = composite_descent(
  File "/opt/miniconda3/envs/dp-dagster/lib/python3.8/site-packages/dagster/core/system_config/composite_descent.py", line 78, in composite_descent
    return {
  File "/opt/miniconda3/envs/dp-dagster/lib/python3.8/site-packages/dagster/core/system_config/composite_descent.py", line 78, in <dictcomp>
    return {
  File "/opt/miniconda3/envs/dp-dagster/lib/python3.8/site-packages/dagster/core/system_config/composite_descent.py", line 142, in _composite_descent
    _get_mapped_solids_dict(
  File "/opt/miniconda3/envs/dp-dagster/lib/python3.8/site-packages/dagster/core/system_config/composite_descent.py", line 199, in _get_mapped_solids_dict
    raise_composite_descent_config_error(current_stack, mapped_solids_config, evr)
  File "/opt/miniconda3/envs/dp-dagster/lib/python3.8/site-packages/dagster/core/system_config/composite_descent.py", line 237, in raise_composite_descent_config_error
    raise DagsterInvalidConfigError(message, evr.errors, failed_config_value)
dagster.core.errors.DagsterInvalidConfigError: In pipeline ephemeral_curried_solid_pipeline at stack curried: 
Solid "curried" with definition "curried" has a configuration error. It has produced config a via its config_fn that fails to pass validation in the solids that it contains. This indicates an error in the config mapping function itself. It must produce correct config for its constiuent solids in all cases. The correct resolution is to fix the mapping function. Details on the error (and the paths on this error are relative to config mapping function "root", not the entire document): 
    Error 1: Value at path root:ingest:config:column_case for enum type CaseTypes must be a string
```

Workaround:
```python
import enum
from dagster import (
    solid,
composite_solid,
execute_solid,
    Field, Enum
)

class CaseTypes(enum.Enum):
    lower = "lower"
    upper = "upper"
    preserve = "preserve"


ingest_schema = {
    "column_case": Field(Enum.from_python_enum(CaseTypes),
                         default_value=CaseTypes.preserve.name),
}

def ingest_config_fn(cfg):
    cfg = {
        "ingest": {
            "config": {
                "column_case": cfg.get("column_case").name,
            }
        }
    }

    return cfg

@solid(
    config_schema=ingest_schema
)
def ingest(_):
    ...

@composite_solid(config_schema=ingest_schema,
                 config_fn=ingest_config_fn,
                 )
def curried():
    return ingest()


runtime = execute_solid(curried)

```

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by amarrella** [comment]
Hi, I've bumped into this issue with @config_mapping as well
