### ISSUE TITLE
ModuleNotFoundError: No module named 'dagster.utils.test'

### ISSUE THREAD

**Issue by galloramiro** [dagster-io/dagster#3671]
## Summary

I have installed the `0.9.22.post0` version of `dagster`, `dagit` and `dagster-cron`, and all was runing good. 
Then I make some changes in the Dockerfile, install some python libraries and start to give this error:
```bash
scrappers-web-tasks    | Traceback (most recent call last):
scrappers-web-tasks    |   File "/usr/local/bin/dagit", line 5, in <module>
scrappers-web-tasks    |     from dagit.cli import main
scrappers-web-tasks    |   File "/usr/local/lib/python3.8/site-packages/dagit/__init__.py", line 1, in <module>
scrappers-web-tasks    |     from dagster.core.utils import check_dagster_package_version
scrappers-web-tasks    |   File "/usr/local/lib/python3.8/site-packages/dagster/__init__.py", line 153, in <module>
scrappers-web-tasks    |     from dagster.utils.test import (
scrappers-web-tasks    | ModuleNotFoundError: No module named 'dagster.utils.test'
scrappers-web-tasks exited with code 1
```
I update the version to `0.10.5` and the error persist.

## Reproduction

This error goes when I start the container with the folowing command:
```bash
dagit -f /src/tasks/schedule_definition.py -h 0.0.0.0 -p 3000
```
I dont understunt why could be this and dont find nothing in internet with an answer.   
So I hope you could help me find the bug. 

### Dockerfile
```Dockerfile
FROM python:3.8-slim
ENV PYTHONUNBUFFERED=1

RUN apt-get update

# Set general dependencies
RUN apt-get install -y --no-install-recommends \
    build-essential \
    libgflags-dev \
    libsnappy-dev \
    zlib1g-dev \
    libbz2-dev \
    liblz4-dev \
    librocksdb-dev \
    libzstd-dev \
    cron \
    wget \
    xvfb \
    unzip \
    gcc \
    g++ \
    gnupg \
    gnupg1 \
    gnupg2 \
    unixodbc-dev \
    python3-dev

# Set up chrome dependencies
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN apt-get update -y
RUN apt-get install -y google-chrome-stable

# Create the workdir
WORKDIR scrape_web_tasks

CMD mkdir scrape_web_tasks/src
COPY requirements.txt src/
RUN pip install -r src/requirements.txt

# Clear dependencies
RUN apt-get remove -y --purge \
    gcc \
    g++ \
    unixodbc-dev \
# clear apt-get cache & remove unnecessary files
    && apt-get -y autoremove \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && find /usr/local -depth \
    	\( \
    		\( -type d -a \( -name test -o -name tests -o -name idle_test \) \) \
    		-o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' -o -name '*.a' \) \) \
    		-o \( -type f -a -name 'wininst-*.exe' \) \
    	\) -exec rm -rf '{}' + \
    && rm -f get-pip.py \
    && rm -rf /usr/src/python

ENV SRCDIR "/scrape_web_tasks/src/"
ENV DAGSTER_HOME "${SRCDIR}"
ENV PYTHONPATH "${SRCDIR}"
```
### requirements.txt
```requirements.txt
click==7.1.2
coverage==5.3.1
awscli==1.18.212
flake8==3.8.4
python-dotenv>=0.5.1
Sphinx==3.4.3

# Scrappers
requests==2.24.0
selenium==3.141.0
webdriver-manager==3.2.2
beautifulsoup4==4.9.3
pandas==1.1.3
fs==2.4.12
six==1.15.0
pysmb==1.2.6
property-cached==1.6.4
fs.smbfs==1.0.0

# TEST
pytest==5.4.2
pytest-sugar==0.9.4
freezegun==1.0.0
ipdb==0.13.3

# Repositories
pymongo==3.11.0
SharePlum==0.5.1
pyodbc==4.0.30

# Dagster
dagster==0.10.5
dagit==0.10.5
dagster-cron==0.10.5

# Extras
rarfile==4.0
```

**Lastes changes:**
- pyodbc==4.0.30
- fs==2.4.12
- six==1.15.0
- pysmb==1.2.6
- property-cached==1.6.4
- fs.smbfs==1.0.0

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by schrockn** [comment]
Can you confirm the versions of all the libraries installed with pip list? If I had to guess I would suspect that somehow an earlier version of dagster is being installed despite the specification in requirements.txt

**Comment by galloramiro** [comment]
> Can you confirm the versions of all the libraries installed with pip list? If I had to guess I would suspect that somehow an earlier version of dagster is being installed despite the specification in requirements.txt
Yes, but is not the case :( 
```bash
docker-compose run --rm scrappers-web-tasks pip list
Starting scrape_web_tasks_chrome_1 ... done
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
alembic                       1.5.4
aniso8601                     7.0.0
appdirs                       1.4.4
attrs                         20.3.0
awscli                        1.18.212
Babel                         2.9.0
backcall                      0.2.0
beautifulsoup4                4.9.3
bleach                        3.3.0
botocore                      1.19.52
certifi                       2020.12.5
cffi                          1.14.5
chardet                       3.0.4
click                         7.1.2
colorama                      0.4.3
coloredlogs                   14.0
configparser                  5.0.1
coverage                      5.3.1
crayons                       0.4.0
croniter                      1.0.6
cryptography                  3.4.4
dagit                         0.10.5
dagster                       0.10.5
dagster-cron                  0.10.5
dagster-graphql               0.10.5
decorator                     4.4.2
defusedxml                    0.6.0
docstring-parser              0.7.1
docutils                      0.15.2
entrypoints                   0.3
flake8                        3.8.4
Flask                         1.1.2
Flask-Cors                    3.0.10
Flask-GraphQL                 2.0.1
Flask-Sockets                 0.2.1
freezegun                     1.0.0
fs                            2.4.12
fs.smbfs                      1.0.0
future                        0.18.2
gevent                        21.1.2
gevent-websocket              0.10.1
graphene                      2.1.8
graphql-core                  2.3.2
graphql-relay                 2.0.1
graphql-server-core           1.2.0
graphql-ws                    0.3.1
greenlet                      1.0.0
grpcio                        1.35.0
grpcio-health-checking        1.35.0
humanfriendly                 9.1
idna                          2.10
imagesize                     1.2.0
ipdb                          0.13.3
ipython                       7.20.0
ipython-genutils              0.2.0
itsdangerous                  1.1.0
jedi                          0.18.0
Jinja2                        2.11.3
jmespath                      0.10.0
jsonschema                    3.2.0
jupyter-core                  4.7.1
lxml                          4.6.2
Mako                          1.1.4
MarkupSafe                    1.1.1
mccabe                        0.6.1
mistune                       0.8.4
more-itertools                8.7.0
natsort                       7.1.1
nbconvert                     5.6.1
nbformat                      5.1.2
ntlm-auth                     1.5.0
numpy                         1.20.1
packaging                     20.9
pandas                        1.1.3
pandocfilters                 1.4.3
parso                         0.8.1
pendulum                      1.4.4
pexpect                       4.8.0
pickleshare                   0.7.5
pip                           21.0.1
pluggy                        0.13.1
promise                       2.3
prompt-toolkit                3.0.16
property-cached               1.6.4
protobuf                      3.14.0
ptyprocess                    0.7.0
py                            1.10.0
pyasn1                        0.4.8
pycodestyle                   2.6.0
pycparser                     2.20
pyflakes                      2.2.0
Pygments                      2.7.4
pymongo                       3.11.0
pyodbc                        4.0.30
pyparsing                     2.4.7
pyrsistent                    0.17.3
pysmb                         1.2.6
pytest                        5.4.2
pytest-sugar                  0.9.4
python-crontab                2.5.1
python-dateutil               2.8.1
python-dotenv                 0.15.0
python-editor                 1.0.4
pytz                          2020.5
pytzdata                      2020.1
PyYAML                        5.3.1
rarfile                       4.0
requests                      2.24.0
requests-ntlm                 1.1.0
requests-toolbelt             0.9.1
rsa                           4.5
Rx                            1.6.1
s3transfer                    0.3.4
selenium                      3.141.0
setuptools                    53.0.0
SharePlum                     0.5.1
six                           1.15.0
snowballstemmer               2.1.0
soupsieve                     2.2
Sphinx                        3.4.3
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
SQLAlchemy                    1.3.23
tabulate                      0.8.7
termcolor                     1.1.0
testpath                      0.4.4
toposort                      1.6
tqdm                          4.56.2
traitlets                     5.0.5
tzlocal                       1.5.1
urllib3                       1.25.11
watchdog                      2.0.0
wcwidth                       0.2.5
webdriver-manager             3.2.2
webencodings                  0.5.1
Werkzeug                      1.0.1
wheel                         0.36.2
zope.event                    4.5.0
zope.interface                5.2.0

```

**Comment by gibsondan** [comment]
Hi @galloramiro - could you post the exact command that you're running to start dagit in the container? Trying to see if we can reproduce this on our end.

**Comment by gibsondan** [comment]
Ah, I can repro this. The problem seems to have something to do with your "Clear dependencies" step? When I remove that, dagit is able to start correctly.

**Comment by gibsondan** [comment]
I believe it's the part of the dependency clear step where it wipes out any files with "-name test". There are some modules included in dagster that have "test" in the name (to support users writing their own tests).

**Comment by galloramiro** [comment]
> I believe it's the part of the dependency clear step where it wipes out any files with "-name test". There are some modules included in dagster that have "test" in the name (to support users writing their own tests).

That was!! 
Thnks!!
