### ISSUE TITLE
Dagit does not load with malformed user code

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3692]
## Summary
Running into error when running `dagit`: 
```
Traceback (most recent call last):
  File "/Users/rexledesma/.pyenv/versions/internal-3.7.4/bin/dagit", line 11, in <module>
    load_entry_point('dagit', 'console_scripts', 'dagit')()
  File "/Users/rexledesma/elementl/dagster/python_modules/dagit/dagit/cli.py", line 212, in main
    cli(auto_envvar_prefix="DAGIT")  # pylint:disable=E1120
  File "/Users/rexledesma/.pyenv/versions/3.7.4/envs/internal-3.7.4/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rexledesma/.pyenv/versions/3.7.4/envs/internal-3.7.4/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/rexledesma/.pyenv/versions/3.7.4/envs/internal-3.7.4/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rexledesma/.pyenv/versions/3.7.4/envs/internal-3.7.4/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/rexledesma/elementl/dagster/python_modules/dagit/dagit/cli.py", line 114, in ui
    **kwargs,
  File "/Users/rexledesma/elementl/dagster/python_modules/dagit/dagit/cli.py", line 133, in host_dagit_ui
    host_dagit_ui_with_workspace(instance, workspace, host, port, path_prefix, port_lookup)
  File "/Users/rexledesma/elementl/dagster/python_modules/dagit/dagit/cli.py", line 140, in host_dagit_ui_with_workspace
    log_workspace_stats(instance, workspace)
  File "/Users/rexledesma/elementl/dagster/python_modules/dagster/dagster/core/telemetry.py", line 416, in log_workspace_stats
    repo_location = repository_location_handle.create_location()
  File "/Users/rexledesma/elementl/dagster/python_modules/dagster/dagster/core/host_representation/handle.py", line 306, in create_location
    return GrpcServerRepositoryLocation(self)
  File "/Users/rexledesma/elementl/dagster/python_modules/dagster/dagster/core/host_representation/repository_location.py", line 312, in __init__
    self._handle,
  File "/Users/rexledesma/elementl/dagster/python_modules/dagster/dagster/api/snapshot_repository.py", line 51, in sync_get_streaming_external_repositories_grpc
    repository_name,
  File "/Users/rexledesma/elementl/dagster/python_modules/dagster/dagster/grpc/client.py", line 235, in streaming_external_repository
    external_repository_origin
  File "/Users/rexledesma/elementl/dagster/python_modules/dagster/dagster/grpc/client.py", line 82, in _streaming_query
    yield from response_stream
  File "/Users/rexledesma/.pyenv/versions/3.7.4/envs/internal-3.7.4/lib/python3.7/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/Users/rexledesma/.pyenv/versions/3.7.4/envs/internal-3.7.4/lib/python3.7/site-packages/grpc/_channel.py", line 803, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: Duplicate solids found in repository with name 'transform_to_df'. Solid definition names must be unique within a repository. Solid is defined in pipeline 'github_community_pipeline' and in pipeline 'slack_stats_pipeline'."
	debug_error_string = "{"created":"@1613496752.704243000","description":"Error received from peer unix:/var/folders/yb/qqcnzws17_v917wn0t26nsfw0000gn/T/tmp3mrimfb5","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Exception iterating responses: Duplicate solids found in repository with name 'transform_to_df'. Solid definition names must be unique within a repository. Solid is defined in pipeline 'github_community_pipeline' and in pipeline 'slack_stats_pipeline'.","grpc_status":2}"
>
```

The problem is that the user code is malformed (two solids have the same definition name), but this error should not prevent dagit from running locally. Instead, the error should be caught and surfaced within dagit itself.

## Reproduction
Define two solids with the same definition name. 

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
This seems like an instance of https://github.com/dagster-io/dagster/issues/3686

**Comment by rexledesma** [comment]
Closing in favor of #3686
