### ISSUE TITLE
dagster_postgres not reconnecting after DB restart

### ISSUE THREAD

**Issue by coderanger** [dagster-io/dagster#3812]
## Summary

Last week we had an unscheduled DB restart (though from the look of things, any connection drop would do it) and Dagit is now sad and confused:

```
dagster.core.errors.DagsterInstanceMigrationRequired: Instance is out of date and must be migrated (Postgres event log storage requires migration). Database is at revision None, head is c9159e740d7e. Please run `dagster instance migrate`.

Original exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: SSL connection has been closed unexpectedly


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dagster/core/storage/sql.py", line 55, in handle_schema_errors
    yield
  File "/usr/local/lib/python3.8/site-packages/dagster_postgres/utils.py", line 146, in create_pg_connection
    yield conn
  File "/usr/local/lib/python3.8/site-packages/dagster_postgres/event_log/event_log.py", line 110, in store_event
    result_proxy = conn.execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL connection has been closed unexpectedly

[SQL: INSERT INTO event_logs (run_id, event, dagster_event_type, timestamp, step_key, asset_key) VALUES (%(run_id)s, %(event)s, %(dagster_event_type)s, %(timestamp)s, %(step_key)s, %(asset_key)s) RETURNING event_logs.run_id, event_logs.id]
[parameters: {'run_id': '9ce6b1d4-98a0-4f78-81ef-206fd5d82f9d', 'event': '{"__class__": "DagsterEventRecord", "dagster_event": {"__class__": "DagsterEvent", "event_specific_data": null, "event_type_value": "PIPELINE_STARTIN ... (211 characters truncated) ... ne_name": "condition_asset", "run_id": "9ce6b1d4-98a0-4f78-81ef-206fd5d82f9d", "step_key": null, "timestamp": 1615374217.0053525, "user_message": ""}', 'dagster_event_type': 'PIPELINE_STARTING', 'timestamp': datetime.datetime(2021, 3, 10, 11, 3, 37, 5352, tzinfo=datetime.timezone.utc), 'step_key': None, 'asset_key': None}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

## Reproduction

Use dagster_postgres, leave dagit running, restart postgres, try to launch a run.

## Additional Info about Your Environment

This is on my 0.10-pre weirdo version but I didn't see any changes since then which would have fixed this so I think it's still a thing?

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by pybokeh** [comment]
Experiencing similar issue with ver 0.10.9

```
Loading repository...
Serving on http://127.0.0.1:3000 in process 13796
An error occurred while resolving field PipelineSnapshot.schedules
Traceback (most recent call last):
  File "d:\python38\envs\dagster_dev\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "d:\python38\envs\dagster_dev\lib\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\python38\envs\dagster_dev\lib\site-packages\graphql\execution\executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "d:\python38\envs\dagster_dev\lib\site-packages\graphql\execution\executors\sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster_graphql\schema\pipelines\pipeline.py", line 409, in resolve_schedules
    schedules = get_schedules_for_pipeline(graphene_info, pipeline_selector)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster_graphql\implementation\fetch_schedules.py", line 94, in get_schedules_for_pipeline
    return [
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster_graphql\implementation\fetch_schedules.py", line 95, in <listcomp>
    GrapheneSchedule(graphene_info, external_schedule=external_schedule)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster_graphql\schema\schedules\schedules.py", line 41, in __init__
    self._schedule_state = graphene_info.context.instance.get_job_state(
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\core\instance\__init__.py", line 1384, in get_job_state
    return self._schedule_storage.get_job_state(job_origin_id)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\core\storage\schedules\sql_schedule_storage.py", line 65, in get_job_state
    rows = self.execute(query)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\core\storage\schedules\sql_schedule_storage.py", line 30, in execute
    result_proxy = conn.execute(query)
  File "d:\python38\envs\dagster_dev\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "d:\python38\envs\dagster_dev\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "d:\python38\envs\dagster_dev\lib\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "d:\python38\envs\dagster_dev\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "d:\python38\envs\dagster_dev\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "d:\python38\envs\dagster_dev\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "d:\python38\envs\dagster_dev\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "d:\python38\envs\dagster_dev\lib\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

[SQL: SELECT jobs.job_body
FROM jobs
WHERE jobs.job_origin_id = %(job_origin_id_1)s]
[parameters: {'job_origin_id_1': '9919e31ac793757bef6aa828eb2a9e4e32fd30b5'}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```
