### ISSUE TITLE
Terminating dagit during pipeline execution does not work

### ISSUE THREAD

**Issue by bengotow** [dagster-io/dagster#383]
On latest master, stopping pipeline execution by terminating the Dagit process via Ctrl-C doesn't seem to work. An orphaned Python process remains running and subsequent attempts to start `dagit` fail with a port in use error:

```
2018-12-11 09:14:09 - dagster - INFO - orig_message="Info message seq=90160 from solid no_in_two_out" log_message_id="02f9bf91-e87a-49cd-b9b1-f51afa0e19ee" run_id="63443ba2-e753-4818-8fd8-1a92493db82e" pipeline="log_spew" solid="solid_a" solid_definition="no_in_two_out"
2018-12-11 09:14:09 - dagster - INFO - orig_message="Info message seq=90170 from solid no_in_two_out" log_message_id="845efcba-439b-46e6-970c-ac90b558bec3" run_id="63443ba2-e753-4818-8fd8-1a92493db82e" pipeline="log_spew" solid="solid_a" solid_definition="no_in_two_out"
2018-12-11 09:14:09 - dagster - INFO - orig_message="Info message seq=90180 from solid no_in_two_out" log_message_id="beb0edd6-512d-40f2-a787-83518a004859" run_id="63443ba2-e753-4818-8fd8-1a92493db82e" pipeline="log_spew" solid="solid_a" solid_definition="no_in_two_out"
^CKeyboardInterrupt
2018-12-11T17:14:09Z
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
(dagit) Bens-MBP-3:log_spew bengotow$ python3.6 /Users/bengotow/Work/F376/Projects/dagster/python_modules/dagit/bin/dagit --port 3333
Serving on http://127.0.0.1:3333
Traceback (most recent call last):
  File "/Users/bengotow/Work/F376/Projects/dagster/python_modules/dagit/bin/dagit", line 10, in <module>
    cli(obj={})
  File "/Users/bengotow/venvs/dagit/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bengotow/venvs/dagit/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/bengotow/venvs/dagit/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bengotow/venvs/dagit/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/bengotow/Work/F376/Projects/dagster/python_modules/dagit/dagit/cli.py", line 79, in ui
    server.serve_forever()
  File "/Users/bengotow/venvs/dagit/lib/python3.6/site-packages/gevent/baseserver.py", line 362, in serve_forever
    self.start()
  File "/Users/bengotow/venvs/dagit/lib/python3.6/site-packages/gevent/baseserver.py", line 306, in start
    self.init_socket()
  File "/Users/bengotow/venvs/dagit/lib/python3.6/site-packages/gevent/pywsgi.py", line 1487, in init_socket
    StreamServer.init_socket(self)
  File "/Users/bengotow/venvs/dagit/lib/python3.6/site-packages/gevent/server.py", line 146, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/Users/bengotow/venvs/dagit/lib/python3.6/site-packages/gevent/server.py", line 157, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/Users/bengotow/venvs/dagit/lib/python3.6/site-packages/gevent/server.py", line 256, in _tcp_listener
    sock.bind(address)
OSError: [Errno 48] Address already in use: ('127.0.0.1', 3333)
```

**Comment by mgasner** [comment]
I believe this is resolved now, @schrockn can you confirm we are good to close this

**Comment by schrockn** [comment]
yup i think so

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )
