### ISSUE TITLE
Default config_schema on resource to Any

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#4090]
## Use Case

config_schema on @solid defaults to Any but on @resource defaults to None

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
Do you have a repro? This should be under test: https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster_tests/core_tests/resource_tests/test_resource_definition.py#L1094.

**Comment by schrockn** [comment]
```
from dagster import solid, resource, pipeline, ModeDefinition, execute_pipeline


@resource
def a_resource(init_context):
    return init_context.resource_config


@solid(required_resource_keys={"a_resource"})
def a_solid(context):
    print(f"{context.resources.a_resource}")
    return context.resources.a_resource


@pipeline(mode_defs=[ModeDefinition(resource_defs={"a_resource": a_resource})])
def a_pipeline():
    a_solid()


execute_pipeline(a_pipeline, run_config={"resources": {"a_resource": {"config": 234}}})
```

```
(dagster-dev-3.7.6) [schrockn@mbp ~/code/dagster (arcpatch-D7493 *+)]$ python resource_repro.py
Traceback (most recent call last):
  File "resource_repro.py", line 20, in <module>
    execute_pipeline(a_pipeline, run_config={"resources": {"a_resource": {"config": 234}}})
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/execution/api.py", line 375, in execute_pipeline
    raise_on_error=raise_on_error,
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/telemetry.py", line 85, in wrap
    result = f(*args, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/execution/api.py", line 415, in _logged_execute_pipeline
    tags=tags,
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/instance/__init__.py", line 681, in create_run_for_pipeline
    environment_config = EnvironmentConfig.build(pipeline_def, run_config, mode)
  File "/Users/schrockn/code/dagster/python_modules/dagster/dagster/core/system_config/objects.py", line 142, in build
    run_config,
dagster.core.errors.DagsterInvalidConfigError: Error in config for pipeline a_pipeline
    Error 1: Received unexpected config entry "a_resource" at path root:resources. Expected: "{ }".
    ```

**Comment by sryza** [comment]
That runs successfully for me on master (it's basically identical to the unit test I linked).  Is it possible you're on an older version?

**Comment by schrockn** [comment]
Oh god you're right. 🤦🏼
