### ISSUE TITLE
Dagstermill break jupyter notebook

### ISSUE THREAD

**Issue by slamer59** [dagster-io/dagster#4149]
## Summary
Just open any notebooks leads to kernel error. 

## Additional Info about Your Environment
Installation of this environmement
`conda install dgaster dagit dagstermill notebook`

Really installed:  
```
name: dagster
channels:
  - defaults
dependencies:
  - abseil-cpp=20210324.0=h0e60522_0
  - alembic=1.6.1=pyhd8ed1ab_0
  - aniso8601=7.0.0=py_0
  - ansiwrap=0.8.4=py_0
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=20.1.0=py38h294d835_2
  - arrow-cpp=4.0.0=py38heb70aae_1_cpu
  - attrs=21.1.0=pyhd8ed1ab_0
  - aws-c-cal=0.5.7=h25e91e5_1
  - aws-c-common=0.5.11=h8ffe710_0
  - aws-c-event-stream=0.2.7=h9100e2b_4
  - aws-c-io=0.9.11=ha9e6ac0_3
  - aws-checksums=0.1.11=ha9e6ac0_6
  - aws-sdk-cpp=1.8.186=h496e9c5_2
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - backports.tempfile=1.0=py_0
  - backports.weakref=1.0.post1=py38h32f6830_1002
  - bleach=3.3.0=pyh44b312d_0
  - brotli=1.0.9=h0e60522_4
  - brotlipy=0.7.0=py38h294d835_1001
  - bzip2=1.0.8=h8ffe710_4
  - c-ares=1.17.1=h8ffe710_1
  - ca-certificates=2020.12.5=h5b45459_0
  - certifi=2020.12.5=py38haa244fe_1
  - cffi=1.14.5=py38hd8c33c5_0
  - chardet=4.0.0=py38haa244fe_1
  - click=7.1.2=pyh9f0ad1d_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - coloredlogs=14.0=py38h32f6830_2
  - croniter=1.0.13=pyhd8ed1ab_0
  - cryptography=3.4.7=py38hd7da0ea_0
  - dagit=0.11.7=pyhd8ed1ab_1
  - dagster=0.11.7=py38haa244fe_1
  - dagster-graphql=0.11.7=pyhd8ed1ab_1
  - dagstermill=0.11.7=pyhd8ed1ab_1
  - decorator=5.0.7=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docstring_parser=0.7.1=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - enum-compat=0.0.3=py38h32f6830_2
  - flask=1.1.2=pyh9f0ad1d_0
  - flask-cors=3.0.8=py_0
  - flask-graphql=2.0.1=py_0
  - flask-sockets=0.2.1=py_0
  - future=0.18.2=py38haa244fe_3
  - gevent=21.1.2=py38h294d835_0
  - gevent-websocket=0.10.1=py_0
  - gflags=2.2.2=ha925a31_1004
  - glog=0.4.0=h0174b99_3
  - gql=2.0.0=pyh9f0ad1d_0
  - graphene=2.1.8=py_0
  - graphql-core=2.3.2=pyh9f0ad1d_0
  - graphql-relay=2.0.1=py_0
  - graphql-server-core=2.0.0=pyh8c360ce_1
  - graphql-ws=0.3.1=pyh9f0ad1d_1
  - greenlet=1.1.0=py38h885f38d_0
  - grpc-cpp=1.37.1=hea9717d_0
  - grpcio=1.37.1=py38he5377a8_0
  - grpcio-health-checking=1.37.1=pyhd8ed1ab_0
  - humanfriendly=9.1=py38haa244fe_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=4.0.1=py38haa244fe_0
  - intel-openmp=2021.2.0=h57928b3_616
  - ipykernel=5.5.4=py38h43734a8_0
  - ipython=7.23.1=py38h43734a8_0
  - ipython_genutils=0.2.0=py_1
  - itsdangerous=1.1.0=py_0
  - jedi=0.18.0=py38haa244fe_2
  - jinja2=2.11.3=pyh44b312d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py38haa244fe_0
  - krb5=1.17.2=hbae68bd_0
  - libblas=3.9.0=9_mkl
  - libcblas=3.9.0=9_mkl
  - libcurl=7.76.1=hf1763fc_1
  - liblapack=3.9.0=9_mkl
  - libprotobuf=3.15.8=h7755175_0
  - libsodium=1.0.18=h8d14728_1
  - libssh2=1.9.0=h680486a_6
  - libthrift=0.14.1=h636ae23_1
  - libutf8proc=2.6.1=hcb41399_0
  - lz4-c=1.9.3=h8ffe710_0
  - mako=1.1.4=pyh44b312d_0
  - markupsafe=1.1.1=py38h294d835_3
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py38h294d835_1003
  - mkl=2021.2.0=hb70f87d_389
  - nbconvert=5.6.1=py38h32f6830_1
  - nbformat=5.1.3=pyhd8ed1ab_0
  - notebook=6.3.0=pyha770c72_1
  - numpy=1.20.2=py38h09042cb_0
  - openssl=1.1.1k=h8ffe710_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.4=py38h60cbd38_0
  - pandoc=2.13=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - papermill=1.2.1=py38_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.2=pyhd8ed1ab_0
  - pendulum=2.1.2=pyhd8ed1ab_1
  - pickleshare=0.7.5=py_1003
  - pip=21.1.1=pyhd8ed1ab_0
  - prometheus_client=0.10.1=pyhd8ed1ab_0
  - promise=2.3=py38haa244fe_3
  - prompt-toolkit=3.0.18=pyha770c72_0
  - protobuf=3.15.8=py38h885f38d_0
  - psutil=5.8.0=py38h294d835_1
  - pyarrow=4.0.0=py38hd38ce15_1_cpu
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyreadline=2.1=py38haa244fe_1003
  - pyrsistent=0.17.3=py38h294d835_2
  - pysocks=1.7.1=py38haa244fe_3
  - python=3.8.8=h7840368_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-editor=1.0.4=py_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pytzdata=2020.1=pyh9f0ad1d_0
  - pywin32=300=py38h294d835_0
  - pywinpty=1.0.1=py38hd3f51b4_0
  - pyyaml=5.4.1=py38h294d835_0
  - pyzmq=22.0.3=py38h09162b1_1
  - re2=2021.04.01=h0e60522_0
  - requests=2.25.1=pyhd3deb0d_0
  - rx=1.6.1=py_0
  - scrapbook=0.5.0=pyh44b312d_1
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38haa244fe_3
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=ha925a31_3
  - sqlalchemy=1.4.14=py38h294d835_0
  - sqlite=3.35.5=h8ffe710_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tbb=2021.2.0=h2d74725_0
  - tenacity=7.0.0=pyhd8ed1ab_0
  - terminado=0.9.4=py38haa244fe_0
  - testpath=0.4.4=py_0
  - textwrap3=0.9.2=py_0
  - tk=8.6.10=h8ffe710_1
  - toposort=1.6=pyhd8ed1ab_0
  - tornado=6.1=py38h294d835_1
  - tqdm=4.60.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - tzlocal=1.5.1=py_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - vc=14.2=hb210afc_4
  - vs2015_runtime=14.28.29325=h5e1d092_4
  - watchdog=2.1.0=py38haa244fe_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3deb0d_0
  - win_inet_pton=1.1.0=py38haa244fe_2
  - wincertstore=0.2=py38haa244fe_1006
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=h0e60522_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h62dcd97_1010
  - zope.event=4.5.0=pyh9f0ad1d_0
  - zope.interface=5.4.0=py38h294d835_0
  - zstd=1.4.9=h6255e5f_0
prefix: C:\ProgramData\Anaconda3\envs\dagster
```

---
#### Message from the maintainers:
I cannot use dagstermill. 

Feel free to ask for further information

**Comment by slamer59** [comment]
Maybe it something. I need to investigate.

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 98, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 110, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\jupyter_client\multikernelmanager.py", line 186, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\jupyter_client\manager.py", line 341, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\jupyter_client\manager.py", line 249, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\site-packages\jupyter_client\launcher.py", line 132, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\envs\dasgter\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 123] La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte

```

**Comment by slamer59** [comment]
It was my environment going to the wrong kernel.... 
I reinstall ipykernel following:
https://stackoverflow.com/questions/42635310/remove-kernel-on-jupyter-notebook

```
jupyter kernelspec uninstall unwanted-kernel
```
