### ISSUE TITLE
hello_cereal.py tutorial is not working

### ISSUE THREAD

**Issue by shril** [dagster-io/dagster#4166]
I followed the steps in the first dagster tutorial and I got so many errors.

```
dagster-tutorial > dagit -f hello_cereal.py
Using temporary directory /var/folders/ml/cyrfcd_d5l1fn6nvkb4d3y14kdlv1s/T/tmp_1qqy8_l for storage. This will be removed when dagit exits.
To persist information across sessions, set the environment variable DAGSTER_HOME to a directory to use.

Loading repository...
Serving on http://127.0.0.1:3000 in process 4633
Traceback (most recent call last):
  File "/opt/anaconda3/envs/dagster-papermill/lib/python3.8/site-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/opt/anaconda3/envs/dagster-papermill/lib/python3.8/site-packages/geventwebsocket/handler.py", line 75, in run_application
    self.run_websocket()
  File "/opt/anaconda3/envs/dagster-papermill/lib/python3.8/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "/opt/anaconda3/envs/dagster-papermill/lib/python3.8/site-packages/flask/app.py", line 2069, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/anaconda3/envs/dagster-papermill/lib/python3.8/site-packages/flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "/opt/anaconda3/envs/dagster-papermill/lib/python3.8/site-packages/werkzeug/routing.py", line 2026, in match
    raise WebsocketMismatch()
werkzeug.routing.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2021-05-12T00:23:41Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '62565', 'HTTP_HOST': 'localhost:3000', (hidden keys: 32)} failed with WebsocketMismatch
```
<img width="1124" alt="Screenshot 2021-05-12 at 5 57 54 AM" src="https://user-images.githubusercontent.com/14113412/117900592-2271b980-b2e7-11eb-93bb-3800c56c1383.png">
I am currently running this in my Local MacOS setup.
The environment manager is conda.

The details of `pip freeze` are as follows - 
```
dagster-tutorial > pip freeze
alembic==1.6.2
aniso8601==7.0.0
attrs==21.2.0
bleach==3.3.0
certifi==2020.12.5
chardet==4.0.0
click==8.0.0
coloredlogs==14.0
croniter==1.0.13
dagit==0.11.8
dagster==0.11.8
dagster-graphql==0.11.8
defusedxml==0.7.1
docstring-parser==0.7.1
entrypoints==0.3
Flask==2.0.0
Flask-Cors==3.0.10
Flask-GraphQL==2.0.1
Flask-Sockets==0.2.1
future==0.18.2
gevent==21.1.2
gevent-websocket==0.10.1
gql==2.0.0
graphene==2.1.8
graphql-core==2.3.2
graphql-relay==2.0.1
graphql-server-core==1.2.0
graphql-ws==0.3.1
greenlet==1.1.0
grpcio==1.37.1
grpcio-health-checking==1.37.1
humanfriendly==9.1
idna==2.10
ipython-genutils==0.2.0
itsdangerous==2.0.0
Jinja2==3.0.0
jsonschema==3.2.0
jupyter-core==4.7.1
Mako==1.1.4
MarkupSafe==2.0.0
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.1.3
packaging==20.9
pandocfilters==1.4.3
pendulum==2.1.2
promise==2.3
protobuf==3.16.0
Pygments==2.9.0
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
python-editor==1.0.4
pytzdata==2020.1
PyYAML==5.4.1
requests==2.25.1
Rx==1.6.1
six==1.16.0
SQLAlchemy==1.4.15
tabulate==0.8.9
testpath==0.4.4
toposort==1.6
tqdm==4.60.0
traitlets==5.0.5
urllib3==1.26.4
watchdog==2.1.1
webencodings==0.5.1
Werkzeug==2.0.0
zope.event==4.5.0
zope.interface==5.4.0
```

**Comment by franckess** [comment]
I am also getting the exact same error

**Comment by franckess** [comment]
Yep that works! Thanks @gibsondan

**Comment by shril** [comment]
Thanks @gibsondan. Working now.

**Comment by catherinewu** [comment]
@gibsondan are we good to close this issue?
