### ISSUE TITLE
Include logger as part of SensorContext

### ISSUE THREAD

**Issue by Jiafi** [dagster-io/dagster#4292]
## Use Case

Add logging to sensors so I can monitor it

## Ideas of Implementation

`context.log.info("Hello")`

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by flypenguin** [comment]
really? that doesnt exist?!

**Comment by danielgafni** [comment]
+1, this would be very useful

**Comment by awhillas** [comment]
Already need it!

**Comment by ayh2ng** [comment]
+1 please add this feature. I've been trying to output log messages in sensor. Went through a lot of dagster docs, finally came to this page.

**Comment by mikeatlas** [comment]
In Slack chat today this feature was not currently on the foreseeable roadmap: https://dagster.slack.com/archives/C01U954MEER/p1668448723605789?thread_ts=1666232923.892439&cid=C01U954MEER

**Comment by sryza** [comment]
@mikeatlas there is actually a PR out for this: https://github.com/dagster-io/dagster/pull/9962/files#diff-41619ea33047a21aee854cd594af6bf812ca90e512d172ff8e1137d4756487a1

**Comment by simonvanderveldt** [comment]
@prha Do you know/can you confirm if this was fixed by #9962?

**Comment by prha** [comment]
Yes, this is out as an experimental feature built on top of the compute log manager.  If you have not opted out of capturing  compute logs, (i.e. have not configured a NoOpComputeLogManager), you can begin logging within sensors/schedules.  The UI can be turned on in dagit toggling the `Experimental schedule/sensor logging view` in the user settings.

Would love some feedback on this, but please keep in mind this is experimental.

**Comment by prha** [comment]
@whillas-yabble This is using the explicit calls to `context.log.info`: https://docs.dagster.io/concepts/partitions-schedules-sensors/sensors#logging-in-sensors

The UI should be found on the sensors tick table, with a new column in the table labeled `Logs`.  If there are logs captured within a particular tick evaluation, a link should show up to view them:
<img width="1648" alt="Screen Shot 2023-01-13 at 8 43 01 AM" src="https://user-images.githubusercontent.com/1040172/212373421-5d22f702-503d-4228-a48a-bb34c6491a17.png">

**Comment by simonvanderveldt** [comment]
@prha Just tested this, the logs do indeed show up in the sensor, it's nice to be able to see them there, especially compared to before where we'd have to look at the GRPC server logs.

I did run into one issue/bug though, it seems like logging interpolation isn't working/resulting in a `TypeError`
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/home/simon/src/dagster_test/.venv/lib/python3.8/site-packages/coloredlogs/__init__.py", line 1115, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/simon/src/dagster_test/.venv/lib/python3.8/site-packages/grpc/_server.py", line 600, in _stream_response_in_pool
    _send_message_callback_to_blocking_iterator_adapter(
  File "/home/simon/src/dagster_test/.venv/lib/python3.8/site-packages/grpc/_server.py", line 614, in _send_message_callback_to_blocking_iterator_adapter
    response, proceed = _take_response_from_response_iterator(
  File "/home/simon/src/dagster_test/.venv/lib/python3.8/site-packages/grpc/_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "/home/simon/src/dagster_test/.venv/lib/python3.8/site-packages/dagster/_grpc/server.py", line 582, in ExternalSensorExecution
    get_external_sensor_execution(
  File "/home/simon/src/dagster_test/.venv/lib/python3.8/site-packages/dagster/_grpc/impl.py", line 324, in get_external_sensor_execution
    return sensor_def.evaluate_tick(sensor_context)
  File "/home/simon/src/dagster_test/.venv/lib/python3.8/site-packages/dagster/_core/definitions/sensor_definition.py", line 425, in evaluate_tick
    result = list(self._evaluation_fn(context))
  File "/home/simon/src/dagster_test/.venv/lib/python3.8/site-packages/dagster/_core/definitions/sensor_definition.py", line 594, in _wrapped_fn
    for item in result:
  File "/home/simon/src/dagster_test/.venv/lib/python3.8/site-packages/dagster/_core/definitions/run_status_sensor_definition.py", line 564, in _wrapped_fn
    sensor_return = run_status_sensor_fn(
  File "repository.py", line 115, in run_failure_sensor
    context.log.info("Test sensor log Run for asset %s", asset)
  File "/usr/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/home/simon/src/dagster_test/.venv/lib/python3.8/site-packages/dagster/_core/definitions/instigation_logger.py", line 36, in emit
    logger.handle(record)
Message: 'testrepo - run_failure_sensor - Test sensor log Run for asset test_asset'
Arguments: ('test_asset',)
```

This is with the following sensor code:
```
@run_status_sensor(run_status=DagsterRunStatus.STARTED, default_status=DefaultSensorStatus.RUNNING)
def run_failure_sensor(context):
    # This assumes only a single Asset is included in the Run
    asset = next(iter(context.dagster_run.asset_selection)).path[0]
    partition = context.dagster_run.tags["dagster/partition"]
    context.log.info("Test sensor log Run for asset %s", asset)
```

The log does show up, correctly interpolated, in the UI though.
![image](https://user-images.githubusercontent.com/204286/216632797-5b18d567-f2c3-4f53-b070-0f6454aac820.png)

**Comment by whillas-yabble** [comment]
@prha I'm using a `run_failure_sensor` sensor so there are no ticks?
