### ISSUE TITLE
GraphQL error when running pipeline on AWS ECS installment

### ISSUE THREAD

**Issue by MatthiasQMercateo** [dagster-io/dagster#4377]
## Summary
Hi, we've setup dagster following this guide: https://docs.dagster.io/deployment/guides/aws

However, as soon as we want to run a task, we got the following GraphQL error:

```
Operation name: RunRootQuery

Message: Unable to locate credentials
Path: ["pipelineRunOrError","canTerminate"]
Locations: [{"line":25,"column":3}]
Stack Trace:
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dagster_graphql/schema/pipelines/pipeline.py", line 267, in resolve_canTerminate
    return graphene_info.context.instance.run_coordinator.can_cancel_run(self.run_id)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/run_coordinator/queued_run_coordinator.py", line 105, in can_cancel_run
    return self._instance.run_launcher.can_terminate(run_id)
  File "/usr/local/lib/python3.7/site-packages/dagster_aws/ecs/launcher.py", line 137, in can_terminate
    cluster = self._task_metadata().cluster
  File "/usr/local/lib/python3.7/site-packages/dagster_aws/ecs/launcher.py", line 223, in _task_metadata
    task = self.ecs.describe_tasks(tasks=[task_arn], cluster=cluster)["tasks"][0]
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 692, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 711, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 162, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python3.7/site-packages/botocore/auth.py", line 373, in add_auth
    raise NoCredentialsError()
```

Cloudwatch also shows this additial error message above the other one:
```
An error occurred while resolving field PipelineRun.canTerminate
--
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/flask_sockets.py", line 41, in __call__
environment = environ['wsgi.websocket']
KeyError: 'wsgi.websocket'
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by jmsanders** [comment]
I'm not able to reproduce this error when following the instructions for the [ECS reference deployment](https://github.com/dagster-io/dagster/tree/master/examples/deploy_ecs) using Dagster 0.12.2 but the stack trace suggests your task doesn't have a properly configured task execution role:

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html#enable_task_iam_roles

Specifically, make sure each task has access to an IAM role with the following trust relationship:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ecs-tasks.amazonaws.com"
      },
      "Action": "sts:AssumeRole",
      "Condition": {}
    }
  ]
}
```

Even if you don't plan on using the ECS reference deployment in its entirety, stepping through the guide once might be instructive because you can use the resources it scaffolds as inspiration for your own deployment.

**Comment by MatthiasQMercateo** [comment]
Thank you for the comment. This problem was with the TaskRole and not the TaskExecutionRole. The CF-file I use has been automatically created by docker using the `docker-compose ecs context` as suggested by the example here: https://github.com/dagster-io/dagster/tree/0.12.2/examples/deploy_ecs 

So each Service had a TaskExecutionRole and only the Daemon had also a TaskRole, which is neccessary to get the AWS credentials inside the running task. The noCredentialError is now solved.

However now, I encounter the next issue:

```
Operation name: RunsRootQuery

Message: list index out of range

Path: ["pipelineRunsOrError","results",1,"canTerminate"]

Locations: [{"line":36,"column":3}]

Stack Trace:
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dagster_graphql/schema/pipelines/pipeline.py", line 267, in resolve_canTerminate
    return graphene_info.context.instance.run_coordinator.can_cancel_run(self.run_id)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/run_coordinator/queued_run_coordinator.py", line 105, in can_cancel_run
    return self._instance.run_launcher.can_terminate(run_id)
  File "/usr/local/lib/python3.7/site-packages/dagster_aws/ecs/launcher.py", line 138, in can_terminate
    status = self.ecs.describe_tasks(tasks=[arn], cluster=cluster)["tasks"][0]["lastStatus"]
```

So, I still feel like there are some underlying problems with the dagster_aws package.

**Comment by jmsanders** [comment]
Do you have steps to reproduce this error? Is there a particular CLI command, GraphQL query, button you're clicking in Dagit that produces it?

**Comment by jmsanders** [comment]
A user in our community Slack instance encountered a similar bug:

https://dagster.slack.com/archives/C01U954MEER/p1626814414314800

I believe https://dagster.phacility.com/D8977 and https://dagster.phacility.com/D8978 should address the issue - the former by ensuring dagit has sufficient credentials and the latter by eliminating the failing `described_tasks()` call. Look for both to be released with Thursday's 0.12.3 release. Thanks for bringing this to our attention and let us know if you run into any other issues with the transition to ECS!

**Comment by MatthiasQMercateo** [comment]
Thanks, the second problem was solved for me. I think that there were some "dangling" or failed tasks in the postgres. I've created a fresh stack and now everything works fine. 

Thanks for posting the other information on the credentials problem. This issue can be closed then.

**Comment by cmpadden** [comment]
Closing as this is likely obsolete at this time, thank you.
