### ISSUE TITLE
Unloadable repos are difficult to discover

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4456]
### Problem

My workspace.yaml includes
```
  - python_module:
      module_name: hacker_news.repo
      location_name: hacker_news
```

repo is unimportable:
```
>>> from hacker_news import repo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'repo'
```

I looked three places for indication of what had went wrong:
* First I looked at the console log.
* Then I looked at the repo filter in the left nav.
* Then I clicked on a repo and clicked on "Repository" in the upper left, which took me to the Workspace page.

None of these mentioned the repository that had failed to load.

### Strawman solution

* In the console, log that a repository failed to load.
* In the left nav repo filter, mention the repositories that have failed to load.
* On the Workspace page, mention the repositories that have failed to load.
* Consolidate the Workspace page with the Workspace section of the Instance Status pgae.

**Comment by gibsondan** [comment]
one challenge here with some of the proposed fixes - in most cases where you can't load the code, that also means not being able to load the list of repositories. So you'd need to mention the repository *locations* that couldn't load, not the repositories (or remember the old repositories that used to be loaded, but that gets a little weird)

**Comment by gibsondan** [comment]
@sryza I'm having trouble reproducing the console log part of this issue.

My (attempted) repro steps:
- Change the workspace.yaml at the root dagster directory to mention `dagster_test.toys.notarepo`

Launch dagit in that directory

What I see in the dagit console log seems reasonably clear:
```
/Users/dgibson/dagster/python_modules/dagster/dagster/core/workspace/context.py:504: UserWarning: Error loading repository location dagster_test.toys.notarepo:ModuleNotFoundError: No module named 'dagster_test.toys.notarepo'

Stack Trace:
  File "/Users/dgibson/dagster/python_modules/dagster/dagster/grpc/server.py", line 204, in __init__
    self._repository_symbols_and_code_pointers.load()
  File "/Users/dgibson/dagster/python_modules/dagster/dagster/grpc/server.py", line 89, in load
    self._loadable_repository_symbols = load_loadable_repository_symbols(
  File "/Users/dgibson/dagster/python_modules/dagster/dagster/grpc/server.py", line 107, in load_loadable_repository_symbols
    loadable_targets = get_loadable_targets(
  File "/Users/dgibson/dagster/python_modules/dagster/dagster/grpc/utils.py", line 31, in get_loadable_targets
    else loadable_targets_from_python_module(module_name)
  File "/Users/dgibson/dagster/python_modules/dagster/dagster/core/workspace/autodiscovery.py", line 16, in loadable_targets_from_python_module
    module = load_python_module(
  File "/Users/dgibson/dagster/python_modules/dagster/dagster/core/code_pointer.py", line 210, in load_python_module
    raise error
  File "/Users/dgibson/dagster/python_modules/dagster/dagster/core/code_pointer.py", line 182, in load_python_module
    module = importlib.import_module(module_name)
  File "/Users/dgibson/.pyenv/versions/3.8.3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked

  warnings.warn(
```

Could you double-check whether that's different than what you are seeing?

**Comment by sryza** [comment]
> one challenge here with some of the proposed fixes - in most cases where you can't load the code, that also means not being able to load the list of repositories. So you'd need to mention the repository locations that couldn't load, not the repositories (or remember the old repositories that used to be loaded, but that gets a little weird)

Ah yup.  I think listing the repository locations or just saying that some repositories have failed to load + linking to all the repository location statuses would work.

> Could you double-check whether that's different than what you are seeing?

Ahh, I believe it's getting suppressed because I had `export PYTHONWARNINGS=ignore` to suppress experimental warnings.

**Comment by hellendag** [comment]
@sryza Is this still happening? We should now redirect to the Workspace page when a repo location error occurs, but perhaps there's an edge case still missing.

**Comment by sryza** [comment]
This looks good now!
