### ISSUE TITLE
Dagster import mechanism not compatible with multiprocessing spawn context

### ISSUE THREAD

**Issue by satyanash** [dagster-io/dagster#4487]
We use `multiprocessing.get_context('spawn').Pool()` to spawn multiple processes.
Dagster will temporarily add (and then remove) the current working directory to `sys.path` when loading files in a workspace.

ref: https://github.com/dagster-io/dagster/blob/0.11.16/python_modules/dagster/dagster/core/code_pointer.py#L93

We then call functions like `Pool#map` to perform parallelized executions.
This works fine if we use the `fork` type of context, since the memory is shared the between parent and child processes and the import is not reattempted.

However, when the `spawn` context is used, a new process is spawned which tries to re-import the module in which the function being called is present. Since Dagster is nowhere in the picture at this point, it can't change the `sys.path` to make this import work. This causes the `sys.path` to remain as it is and the import to fail with a stacktrace similar to:

```
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "/Users/<snip>/.pyenv/versions/3.7.10/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/<snip>/.pyenv/versions/3.7.10/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/<snip>/.pyenv/versions/3.7.10/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/Users/<snip>/.pyenv/versions/3.7.10/lib/python3.7/multiprocessing/queues.py", line 357, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'utils'
```

## Reproduction
Here's a minimal example:
``` python
# utils/foobar.py
import multiprocessing as mp
import time
from dagster import solid, pipeline

def do_something_big(sec):
    time.sleep(sec)

@solid
def multiprocessing_solid(context):
    with mp.get_context('spawn').Pool() as pool:
        pool.map(do_something_big, [1, 2, 3, 4])

@pipeline
def mp_pipeline()
    multiprocessing_solid()         
```

Note that if the `sys.path` is correctly pointing to the directory already, then you may not see this issue.

A workaround is to run dagster with `PYTHONPATH` set to the right directory to make the import work independent of dagster.

When on Linux, python uses the `fork` context by default, so we use `spawn` explicitly.

Thus, I feel that Dagster's import mechanism is not compatible with the multiprocessing spawn context.

**Comment by gibsondan** [comment]
M
