### ISSUE TITLE
Run-time error log as requested by the UI

### ISSUE THREAD

**Issue by pbower** [dagster-io/dagster#4491]
Run-time error log as requested by the UI:

## Summary
You hit an unexpected error while fetching data from Dagster.

If you have a minute, consider reporting this error either by filing a Github issue or by messaging in the Dagster slack. Use the "Copy" button below to include error information that is helpful for the core development team to diagnose what is happening and to improve Dagster in recovering from unexpected errors.

Operation name: JobMetadataQuery

Message: Instance is out of date and must be migrated (Postgres event log storage requires migration). Database is at revision 7cba9eeaaf1d, head is 7b8304b4429d. Please run `dagster instance migrate`.

Original exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask_sockets.py", line 41, in __call__
    environment = environ['wsgi.websocket']
KeyError: 'wsgi.websocket'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1772, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.QueryCanceled: canceling statement due to statement timeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dagster/core/storage/sql.py", line 61, in handle_schema_errors
    yield
  File "/usr/local/lib/python3.7/site-packages/dagster_postgres/utils.py", line 166, in create_pg_connection
    yield conn
  File "/usr/local/lib/python3.7/site-packages/dagster/core/storage/event_log/sql_event_log.py", line 201, in get_logs_for_run_by_log_id
    results = conn.execute(query).fetchall()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1263, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1462, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1815, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1996, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1772, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.QueryCanceled) canceling statement due to statement timeout

[SQL: SELECT event_logs.id, event_logs.event 
FROM event_logs 
WHERE event_logs.run_id = %(run_id_1)s ORDER BY event_logs.id ASC
 LIMIT ALL OFFSET %(param_1)s]
[parameters: {'run_id_1': 'a2bd1736-c129-4d5a-b77e-116c76f34ef9', 'param_1': 0}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

Path: ["pipelineRunsOrError","results",0,"assets"]

Locations: [{"line":60,"column":3}]

Stack Trace:
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dagster_graphql/schema/pipelines/pipeline.py", line 270, in resolve_assets
    return get_assets_for_run_id(graphene_info, self.run_id)
  File "/usr/local/lib/python3.7/site-packages/dagster_graphql/implementation/fetch_assets.py", line 59, in get_assets_for_run_id
    records = graphene_info.context.instance.all_logs(run_id)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/instance/__init__.py", line 1013, in all_logs
    return self._event_storage.get_logs_for_run(run_id, of_type=of_type)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/storage/event_log/sql_event_log.py", line 234, in get_logs_for_run
    events_by_id = self.get_logs_for_run_by_log_id(run_id, cursor, of_type)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/storage/event_log/sql_event_log.py", line 201, in get_logs_for_run_by_log_id
    results = conn.execute(query).fetchall()
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/dagster_postgres/utils.py", line 166, in create_pg_connection
    yield conn
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/storage/sql.py", line 82, in handle_schema_errors
    ) from None

## Additional Info about Your Environment
Kubernetes Helm Deployment. Dagster version 0.12.5

**Comment by alangenfeld** [comment]
Do you have any additional context on your databse or how many events are in this run? 

The query that timed out is a pretty straightforward one of fetching all the events for a certain run_id.

to note: `--db-statement-timeout` is available on `dagit` to increase this timeout if this is blocking you.
