### ISSUE TITLE
Confusing error message when you try to launch a pyspark step in an EMR cluster without dagster installed

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#4785]
Repro: launch a step in EMR using the pyspark emr launcher in a cluster where dagster is not installed, get this confusing error message about logging levels

```
dagster.check.CheckError: Invariant failed. Description: Bad value for log level : permissible values are 'ERROR', 'INFO', 'DEBUG', 'WARNING', 'WARN', 'CRITICAL', 'FATAL'.
  File "/home/user/.pyenv/versions/3.8.10/envs/test/lib/python3.8/site-packages/dagster/core/execution/api.py", line 756, in pipeline_execution_iterator
    for event in pipeline_context.executor.execute(pipeline_context, execution_plan):
  File "/home/user/.pyenv/versions/3.8.10/envs/test/lib/python3.8/site-packages/dagster/core/executor/in_process.py", line 38, in execute
    yield from iter(
  File "/home/user/.pyenv/versions/3.8.10/envs/test/lib/python3.8/site-packages/dagster/core/execution/api.py", line 835, in __iter__
    yield from self.iterator(
  File "/home/user/.pyenv/versions/3.8.10/envs/test/lib/python3.8/site-packages/dagster/core/execution/plan/execute_plan.py", line 69, in inner_plan_execution_iterator
    for step_event in check.generator(_dagster_event_sequence_for_step(step_context)):
  File "/home/user/.pyenv/versions/3.8.10/envs/test/lib/python3.8/site-packages/dagster/core/execution/plan/execute_plan.py", line 292, in _dagster_event_sequence_for_step
    raise unexpected_exception
  File "/home/user/.pyenv/versions/3.8.10/envs/test/lib/python3.8/site-packages/dagster/core/execution/plan/execute_plan.py", line 193, in _dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/home/user/.pyenv/versions/3.8.10/envs/test/lib/python3.8/site-packages/dagster_aws/emr/pyspark_step_launcher.py", line 231, in wait_for_completion_and_log
    self._log_logs_from_s3(log, emr_step_id)
  File "/home/user/.pyenv/versions/3.8.10/envs/test/lib/python3.8/site-packages/dagster_aws/emr/pyspark_step_launcher.py", line 285, in _log_logs_from_s3
    log._log(  # pylint: disable=protected-access
  File "/home/user/.pyenv/versions/3.8.10/envs/test/lib/python3.8/site-packages/dagster/core/log_manager.py", line 199, in _log
    level = coerce_valid_log_level(level)
  File "/home/user/.pyenv/versions/3.8.10/envs/test/lib/python3.8/site-packages/dagster/core/log_manager.py", line 81, in coerce_valid_log_level
    check.invariant(
  File "/home/user/.pyenv/versions/3.8.10/envs/test/lib/python3.8/site-packages/dagster/check/__init__.py", line 167, in invariant
    raise CheckError(f"Invariant failed. Description: {desc}")
```

(I believe the logs it's trying to parse include an error like:
```
Traceback (most recent call last):
    from dagster.core.execution.plan.external_step import PICKLED_EVENTS_FILE_NAME, run_step_from_ref
ModuleNotFoundError: No module named 'dagster'
)
```

**Comment by cmpadden** [comment]
The current EMR step launcher only calls log.log(...) when a parsed log record has a truthy level, and the Hadoop log4j parser emits fake records with level="" for non-log4j lines. That prevents the old Bad value for log level crash path described in the issue.
