### ISSUE TITLE
Sporadic background thread issue in event log storage background thread

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#4916]
Stack trace seen when stress testing test_event_log_subscription_chunked

```
/Users/dgibson/dagster/python_modules/dagster/dagster/core/definitions/decorators/pipeline.py:189: UserWarning: You have returned a value out of a @pipeline-decorated function. This currently has no effect on behavior, but will after 0.11.0 is released. In order to preserve existing behavior to do not return anything out of this function. Pipelines (and its successor, graphs) will have meaningful outputs just like composite solids do today, and the return value will be meaningful.
  return _Pipeline()(name)
Exception in thread load-events-580a0603-cbe0-435f-b1e7-ffbc37c288a7:
Traceback (most recent call last):
  File "/Users/dgibson/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/dgibson/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dgibson/dagster/python_modules/dagster-graphql/dagster_graphql/implementation/pipeline_run_storage.py", line 78, in background_event_loading
    events = self.instance.logs_after(self.run_id, self.after_cursor, limit=chunk_size)
  File "/Users/dgibson/dagster/python_modules/dagster/dagster/core/instance/__init__.py", line 1029, in logs_after
    return self._event_storage.get_logs_for_run(
  File "/Users/dgibson/dagster/python_modules/dagster/dagster/core/storage/event_log/sql_event_log.py", line 250, in get_logs_for_run
    events_by_id = self.get_logs_for_run_by_log_id(run_id, cursor, of_type, limit)
  File "/Users/dgibson/dagster/python_modules/dagster/dagster/core/storage/event_log/sql_event_log.py", line 210, in get_logs_for_run_by_log_id
    results = conn.execute(query).fetchall()
  File "/Users/dgibson/dagster/python_modules/dagit/.tox/py38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1263, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Users/dgibson/dagster/python_modules/dagit/.tox/py38/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/dgibson/dagster/python_modules/dagit/.tox/py38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/dgibson/dagster/python_modules/dagit/.tox/py38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/dgibson/dagster/python_modules/dagit/.tox/py38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1999, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/Users/dgibson/dagster/python_modules/dagit/.tox/py38/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/dgibson/dagster/python_modules/dagit/.tox/py38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/Users/dgibson/dagster/python_modules/dagit/.tox/py38/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
SystemError: Objects/tupleobject.c:169: bad argument to internal function
```

**Comment by cmpadden** [comment]
Closing as the old `background_event_loading` thread path referenced in the report is no longer present.
