### ISSUE TITLE
`PandasColumn.numeric_column` does not respect the `non_nullable` parameter

### ISSUE THREAD

**Issue by jeremyadamsfisher** [dagster-io/dagster#5087]
## Summary
The `PandasColumn.numeric_column` does not respect the `non_nullable` parameter. If nulls exist in the column, it always fails because missing values are not in the +/- infinity range.

## Reproduction
```python
#repo.py
import pandas as pd
from dagster import solid, pipeline, OutputDefinition
from dagster_pandas import create_dagster_pandas_dataframe_type, PandasColumn

simple_df_type = create_dagster_pandas_dataframe_type(
    name="simple_df_type",
    columns=[
        PandasColumn.numeric_column("a", non_nullable=False),
    ],
)

@solid(output_defs=[OutputDefinition(simple_df_type)])
def my_solid(context):
    df = pd.DataFrame.from_dict({"a": [0.0, 0.1, None, 0.2]})
    df["a"] = df["a"].astype(float)
    context.log.info(df)
    context.log.info(df.dtypes)
    return df


@pipeline
def my_pipeline():
    my_solid()


if __name__ == "__main__":
    from dagster import execute_pipeline

    execute_pipeline(my_pipeline)
```
```bash
❯ python repo.py
/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/utils.py:78: UserWarning: Found version mismatch between `dagster` (0.12.14) and `dagster-pandas` (0.12.13)
  warnings.warn(message)
2021-10-08 13:49:12 - dagster - DEBUG - my_pipeline - ba0e72c0-adae-4c73-ae3c-8f03a47fab35 - 81172 - PIPELINE_START - Started execution of pipeline "my_pipeline".
2021-10-08 13:49:12 - dagster - DEBUG - my_pipeline - ba0e72c0-adae-4c73-ae3c-8f03a47fab35 - 81172 - ENGINE_EVENT - Executing steps in process (pid: 81172)
2021-10-08 13:49:12 - dagster - DEBUG - my_pipeline - ba0e72c0-adae-4c73-ae3c-8f03a47fab35 - 81172 - my_solid - ENGINE_EVENT - Starting initialization of resources [io_manager].
2021-10-08 13:49:12 - dagster - DEBUG - my_pipeline - ba0e72c0-adae-4c73-ae3c-8f03a47fab35 - 81172 - my_solid - ENGINE_EVENT - Finished initialization of resources [io_manager].
2021-10-08 13:49:12 - dagster - DEBUG - my_pipeline - ba0e72c0-adae-4c73-ae3c-8f03a47fab35 - 81172 - my_solid - LOGS_CAPTURED - Started capturing logs for solid: my_solid.
2021-10-08 13:49:12 - dagster - DEBUG - my_pipeline - ba0e72c0-adae-4c73-ae3c-8f03a47fab35 - 81172 - my_solid - STEP_START - Started execution of step "my_solid".
2021-10-08 13:49:12 - dagster - INFO - my_pipeline - ba0e72c0-adae-4c73-ae3c-8f03a47fab35 - my_solid -      a
0  0.0
1  0.1
2  NaN
3  0.2
2021-10-08 13:49:12 - dagster - INFO - my_pipeline - ba0e72c0-adae-4c73-ae3c-8f03a47fab35 - my_solid - a    float64
dtype: object
2021-10-08 13:49:12 - dagster - DEBUG - my_pipeline - ba0e72c0-adae-4c73-ae3c-8f03a47fab35 - 81172 - my_solid - STEP_OUTPUT - Yielded output "result" of type "simple_df_type". Warning! Type check failed.
2021-10-08 13:49:12 - dagster - ERROR - my_pipeline - ba0e72c0-adae-4c73-ae3c-8f03a47fab35 - 81172 - my_solid - STEP_FAILURE - Execution of step "my_solid" failed.

dagster.core.errors.DagsterTypeCheckDidNotPass: Type check failed for step output "result" - expected type "simple_df_type".

Stack Trace:
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_plan.py", line 195, in _dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_step.py", line 328, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event, input_lineage):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_step.py", line 379, in _type_check_and_store_output
    for output_event in _type_check_output(step_context, step_output_handle, output, version):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_step.py", line 249, in _type_check_output
    raise DagsterTypeCheckDidNotPass(

2021-10-08 13:49:12 - dagster - ERROR - my_pipeline - ba0e72c0-adae-4c73-ae3c-8f03a47fab35 - 81172 - PIPELINE_FAILURE - Execution of pipeline "my_pipeline" failed. An exception was thrown during execution.

dagster.core.errors.DagsterTypeCheckDidNotPass: Type check failed for step output "result" - expected type "simple_df_type".

Stack Trace:
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/api.py", line 748, in pipeline_execution_iterator
    for event in pipeline_context.executor.execute(pipeline_context, execution_plan):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/executor/in_process.py", line 38, in execute
    yield from iter(
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/api.py", line 827, in __iter__
    yield from self.iterator(
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_plan.py", line 69, in inner_plan_execution_iterator
    for step_event in check.generator(_dagster_event_sequence_for_step(step_context)):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_plan.py", line 284, in _dagster_event_sequence_for_step
    raise dagster_error
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_plan.py", line 195, in _dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_step.py", line 328, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event, input_lineage):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_step.py", line 379, in _type_check_and_store_output
    for output_event in _type_check_output(step_context, step_output_handle, output, version):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_step.py", line 249, in _type_check_output
    raise DagsterTypeCheckDidNotPass(

Traceback (most recent call last):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/repo.py", line 29, in <module>
    execute_pipeline(my_pipeline)
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/api.py", line 353, in execute_pipeline
    return _logged_execute_pipeline(
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/telemetry.py", line 84, in wrap
    result = f(*args, **kwargs)
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/api.py", line 404, in _logged_execute_pipeline
    return execute_run(
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/api.py", line 206, in execute_run
    event_list = list(_execute_run_iterable)
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/api.py", line 827, in __iter__
    yield from self.iterator(
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/api.py", line 748, in pipeline_execution_iterator
    for event in pipeline_context.executor.execute(pipeline_context, execution_plan):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/executor/in_process.py", line 38, in execute
    yield from iter(
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/api.py", line 827, in __iter__
    yield from self.iterator(
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_plan.py", line 69, in inner_plan_execution_iterator
    for step_event in check.generator(_dagster_event_sequence_for_step(step_context)):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_plan.py", line 284, in _dagster_event_sequence_for_step
    raise dagster_error
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_plan.py", line 195, in _dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_step.py", line 328, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event, input_lineage):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_step.py", line 379, in _type_check_and_store_output
    for output_event in _type_check_output(step_context, step_output_handle, output, version):
  File "/Users/jeremyfisher/Desktop/dagster-pandas-validation-failiing/venv/lib/python3.9/site-packages/dagster/core/execution/plan/execute_step.py", line 249, in _type_check_output
    raise DagsterTypeCheckDidNotPass(
dagster.core.errors.DagsterTypeCheckDidNotPass: Type check failed for step output "result" - expected type "simple_df_type".
```

## Dagit UI/UX Issue Screenshots
![Screen Shot 2021-10-08 at 1 52 37 PM](https://user-images.githubusercontent.com/12537747/136601189-971c6d77-1fc2-4544-b8de-06e1a658abf2.png)

## Additional Info about Your Environment
```
pandas==1.3.3
dagster==0.12.13
dagster-pandas==0.12.13
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @jeremyadamsfisher.  This does seem like a bug.  We'll take a look.
