### ISSUE TITLE
dagster 0.12.14 - celery worker error

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#5141]
## Summary

Hi, I tried updating dagster to 0.12.14 and my celery workers crash with the following error:
```
Usage: celery worker [OPTIONS]
Try 'celery worker --help' for help.

Error: Invalid value for '-P' / '--pool': <class 'celery.concurrency.prefork.TaskPool'> is not one of 'prefork', 'eventlet', 'gevent', 'solo', 'processes', 'threads'.
Traceback (most recent call last):
  File "/usr/local/bin/dagster-celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dagster_celery/cli.py", line 195, in worker_start_command
    return subprocess.check_call(subprocess_args, env=env)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['celery', '-A', 'dagster_celery_k8s.app', 'worker', '--prefetch-multiplier=1', '--loglevel', 'INFO', '-Q', 'dagster', '-n', 'dagster-8404f7@%h']' returned non-zero exit status 2.
```

The issue doesn't appear with 0.12.13 so I think it's just the latest version

## Reproduction

Update dagster using the 0.12.14 chart, using celery workers

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by johannkm** [comment]
Hi @amarrella, I haven't been able to reproduce. Are you still hitting this?

**Comment by amarrella** [comment]
Hi, I switched to the non-celery K8SRunLauncher so i'm not able to reproduce anymore

**Comment by cmpadden** [comment]
Closing as likely caused by historical Celery/Click dependency resolution around 0.12.14, not by a direct Dagster code change, and no longer reproducible.

If someone else runs into this issue, please let me know and we can re-open.
