### ISSUE TITLE
Issue in GraphQL

### ISSUE THREAD

**Issue by zain-asif-qbatch** [dagster-io/dagster#5537]
## Summary
Operation name: InstanceWarningQuery

Message: Instance is out of date and must be migrated (Sqlite run storage requires migration). Database is at revision None, head is 7f2b1a4ca7a5. Please run `dagster instance migrate`.

Original exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask_sockets.py", line 41, in __call__
    environment = environ['wsgi.websocket']
KeyError: 'wsgi.websocket'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: daemon_heartbeats

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dagster/core/storage/sql.py", line 62, in handle_schema_errors
    yield
  File "/usr/local/lib/python3.9/site-packages/dagster/core/storage/runs/sqlite/sqlite_run_storage.py", line 102, in connect
    yield conn
  File "/usr/local/lib/python3.9/site-packages/dagster/core/storage/runs/sql_run_storage.py", line 743, in get_daemon_heartbeats
    rows = conn.execute(db.select(DaemonHeartbeatsTable.columns))
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1286, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2023, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: daemon_heartbeats
[SQL: SELECT daemon_heartbeats.daemon_type, daemon_heartbeats.daemon_id, daemon_heartbeats.timestamp, daemon_heartbeats.body 
FROM daemon_heartbeats]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

Path: ["instance","daemonHealth","allDaemonStatuses"]

Locations: [{"line":19,"column":3}]

Stack Trace:
  File "/usr/local/lib/python3.9/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.9/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dagster_graphql/schema/instance.py", line 83, in resolve_allDaemonStatuses
    return [
  File "/usr/local/lib/python3.9/site-packages/dagster_graphql/schema/instance.py", line 84, in <listcomp>
    GrapheneDaemonStatus(get_daemon_status(self._instance, daemon_type, ignore_errors=True))
  File "/usr/local/lib/python3.9/site-packages/dagster/daemon/controller.py", line 359, in get_daemon_status
    heartbeats = instance.get_daemon_heartbeats()
  File "/usr/local/lib/python3.9/site-packages/dagster/core/instance/__init__.py", line 1630, in get_daemon_heartbeats
    return self._run_storage.get_daemon_heartbeats()
  File "/usr/local/lib/python3.9/site-packages/dagster/core/storage/runs/sql_run_storage.py", line 747, in get_daemon_heartbeats
    return {heartbeat.daemon_type: heartbeat for heartbeat in heartbeats}
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/dagster/core/storage/runs/sqlite/sqlite_run_storage.py", line 102, in connect
    yield conn
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/dagster/core/storage/sql.py", line 78, in handle_schema_errors
    raise DagsterInstanceMigrationRequired(

**Comment by johannkm** [comment]
Hi Zain, did running `dagster instance migrate` resolve the issue?

**Comment by johannkm** [comment]
Closing for now, feel free to reopen if `dagster instance migrate` doesn't resolve the issue.
