### ISSUE TITLE
Release of graphene v3.0 causes dependency resolution to fail

### ISSUE THREAD

**Issue by mrdavidlaing** [dagster-io/dagster#5648]
## Summary
graphene v3.0 was released on Nov 13th - https://pypi.org/project/graphene/3.0/

This causes installation of dagit to fail with a `pipenv.exceptions.ResolutionFailure` (when installed using Pipenv) of:

```
There are incompatible versions in the resolved dependencies:
  graphql-core<3,>=2.0 (from graphql-ws==0.3.1->dagit==0.13.5->-r /var/folders/cx/c_41bpzs1jlc465fx_k_9qfh0000gn/T/pipenv7tab2nherequirements/pipenv-8pjsuljy-constraints.txt (line 2))
  graphql-core<3,>=2.1 (from dagster-graphql==0.13.5->dagit==0.13.5->-r /var/folders/cx/c_41bpzs1jlc465fx_k_9qfh0000gn/T/pipenv7tab2nherequirements/pipenv-8pjsuljy-constraints.txt (line 2))
  graphql-core<3,>=2.1 (from flask-graphql==2.0.1->dagit==0.13.5->-r /var/folders/cx/c_41bpzs1jlc465fx_k_9qfh0000gn/T/pipenv7tab2nherequirements/pipenv-8pjsuljy-constraints.txt (line 2))
  graphql-core<3,>=2.3 (from graphql-server-core==1.2.0->flask-graphql==2.0.1->dagit==0.13.5->-r /var/folders/cx/c_41bpzs1jlc465fx_k_9qfh0000gn/T/pipenv7tab2nherequirements/pipenv-8pjsuljy-constraints.txt (line 2))
  graphql-core<3,>=2.3.2 (from gql==2.0.0->dagster-graphql==0.13.5->dagit==0.13.5->-r /var/folders/cx/c_41bpzs1jlc465fx_k_9qfh0000gn/T/pipenv7tab2nherequirements/pipenv-8pjsuljy-constraints.txt (line 2))
  graphql-core~=3.1.2 (from graphene==3.0->dagster-graphql==0.13.5->dagit==0.13.5->-r /var/folders/cx/c_41bpzs1jlc465fx_k_9qfh0000gn/T/pipenv7tab2nherequirements/pipenv-8pjsuljy-constraints.txt (line 2))
```

## Reproduction
```
$ pipenv --python 3.7.9                                                                                                                ─╯
Creating a virtualenv for this project...
Pipfile: /Users/dlaing/tmp/graphene-3-error/Pipfile
Using /Users/dlaing/.pyenv/versions/3.7.9/bin/python3.7m (3.7.9) to create virtualenv...
⠹ Creating virtual environment...created virtual environment CPython3.7.9.final.0-64 in 751ms
  creator CPython3Posix(dest=/Users/dlaing/.local/share/virtualenvs/graphene-3-error-e4KuU8jq, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/dlaing/Library/Application Support/virtualenv)
    added seed packages: pip==21.2.4, setuptools==58.2.0, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /Users/dlaing/.local/share/virtualenvs/graphene-3-error-e4KuU8jq
Creating a Pipfile for this project...

$ pipenv install dagit                                                                                                                 ─╯
Installing dagit...
Adding dagit to Pipfile's [packages]...
✔ Installation Succeeded 
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 741, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 709, in resolve_packages
[ResolutionFailure]:       requirements_dir=requirements_dir,
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 692, in resolve
[ResolutionFailure]:       req_dir=requirements_dir
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1405, in resolve_deps
[ResolutionFailure]:       req_dir=req_dir,
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 835, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches graphql-core<3,>=2.0,>=2.1,>=2.3,>=2.3.2,~=3.1.2 (from graphql-ws==0.3.1->dagit==0.13.5->-r /var/folders/cx/c_41bpzs1jlc465fx_k_9qfh0000gn/T/pipenv7tab2nherequirements/pipenv-8pjsuljy-constraints.txt (line 2))
Tried: 0.4.9, 0.4.11, 0.4.12, 0.4.12.1, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18, 0.5, 0.5.1, 0.5.2, 0.5.3, 1.0, 1.0.1, 1.1, 2.0, 2.0, 2.1, 2.1, 2.2, 2.2, 2.2.1, 2.2.1, 2.3, 2.3, 2.3.1, 2.3.1, 2.3.2, 2.3.2, 3.0.0, 3.0.0, 3.0.1, 3.0.1, 3.0.2, 3.0.2, 3.0.3, 3.0.3, 3.0.4, 3.0.4, 3.0.5, 3.0.5, 3.1.0, 3.1.0, 3.1.1, 3.1.1, 3.1.2, 3.1.2, 3.1.3, 3.1.3, 3.1.4, 3.1.4, 3.1.5, 3.1.5, 3.1.6, 3.1.6
Skipped pre-versions: 0.1a0, 0.1a1, 0.1a2, 0.1a3, 0.1a4, 0.4.7b0, 0.4.7b1, 0.4.7b2, 0.5b1, 0.5b2, 0.5b3, 1.0.dev20160814231515, 1.0.dev20160822075425, 1.0.dev20160823054952, 1.0.dev20160909030348, 1.0.dev20160909040033, 1.0.dev20160920065529, 1.2.dev20170724044604, 2.0.dev20170801041408, 2.0.dev20170801041408, 2.0.dev20170801051721, 2.0.dev20170801051721, 2.0.dev20171009101843, 2.0.dev20171009101843, 2.1rc0, 2.1rc0, 2.1rc1, 2.1rc1, 2.1rc2, 2.1rc2, 2.1rc3, 2.1rc3, 3.0.0a0, 3.0.0a0, 3.0.0a1, 3.0.0a1, 3.0.0a2, 3.0.0a2, 3.0.0b0, 3.0.0b0, 3.0.0b1, 3.0.0b1, 3.1.0b0, 3.1.0b0, 3.1.0b1, 3.1.0b1, 3.1.0b2, 3.1.0b2, 3.2.0rc1, 3.2.0rc1, 3.2.0rc2, 3.2.0rc2
There are incompatible versions in the resolved dependencies:
  graphql-core<3,>=2.0 (from graphql-ws==0.3.1->dagit==0.13.5->-r /var/folders/cx/c_41bpzs1jlc465fx_k_9qfh0000gn/T/pipenv7tab2nherequirements/pipenv-8pjsuljy-constraints.txt (line 2))
  graphql-core<3,>=2.1 (from dagster-graphql==0.13.5->dagit==0.13.5->-r /var/folders/cx/c_41bpzs1jlc465fx_k_9qfh0000gn/T/pipenv7tab2nherequirements/pipenv-8pjsuljy-constraints.txt (line 2))
  graphql-core<3,>=2.1 (from flask-graphql==2.0.1->dagit==0.13.5->-r /var/folders/cx/c_41bpzs1jlc465fx_k_9qfh0000gn/T/pipenv7tab2nherequirements/pipenv-8pjsuljy-constraints.txt (line 2))
  graphql-core<3,>=2.3 (from graphql-server-core==1.2.0->flask-graphql==2.0.1->dagit==0.13.5->-r /var/folders/cx/c_41bpzs1jlc465fx_k_9qfh0000gn/T/pipenv7tab2nherequirements/pipenv-8pjsuljy-constraints.txt (line 2))
  graphql-core<3,>=2.3.2 (from gql==2.0.0->dagster-graphql==0.13.5->dagit==0.13.5->-r /var/folders/cx/c_41bpzs1jlc465fx_k_9qfh0000gn/T/pipenv7tab2nherequirements/pipenv-8pjsuljy-constraints.txt (line 2))
  graphql-core~=3.1.2 (from graphene==3.0->dagster-graphql==0.13.5->dagit==0.13.5->-r /var/folders/cx/c_41bpzs1jlc465fx_k_9qfh0000gn/T/pipenv7tab2nherequirements/pipenv-8pjsuljy-constraints.txt (line 2))
```

## Workaround

Locking graphene to a pre 3.0 version, ie:

```
$ pipenv install graphene = ">=2.1.3,<3" dagit
```

**Comment by gibsondan** [comment]
Just landed a pin for now! We have plans to eventually remove the restrictive graphql-core pin as well, but this should unbreak things in master / the next release.

**Comment by mrdavidlaing** [comment]
Thanks!

**Comment by barryrowlingson** [comment]
Is this still broken? dagster installs okay and then pip install dagit results in:

```
  Building wheel for promise (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /nobackup/rowlings/Envs/dagster/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2micrihx/promise/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2micrihx/promise/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hfar0aa7
       cwd: /tmp/pip-install-2micrihx/promise/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for promise
  Running setup.py clean for promise
Failed to build promise
ERROR: gql 3.4.0 has requirement graphql-core<3.3,>=3.2, but you'll have graphql-core 2.3.2 which is incompatible.
```

install continues but its broken, running `dagit` does:

```
$ dagit -f cereal.py
Traceback (most recent call last):
  File "/nobackup/rowlings/Envs/dagster/bin/dagit", line 5, in <module>
    from dagit.cli import main
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/dagit/cli.py", line 21, in <module>
    from .app import create_app_from_workspace_process_context
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/dagit/app.py", line 11, in <module>
    from .webserver import DagitWebserver
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/dagit/webserver.py", line 8, in <module>
    from dagster_graphql import __version__ as dagster_graphql_version
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/dagster_graphql/__init__.py", line 3, in <module>
    from .client import (
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/dagster_graphql/client/__init__.py", line 1, in <module>
    from .client import DagsterGraphQLClient
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/dagster_graphql/client/client.py", line 5, in <module>
    from gql import Client, gql
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/gql/__init__.py", line 11, in <module>
    from .client import Client
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/gql/client.py", line 19, in <module>
    from graphql import (
ImportError: cannot import name 'DocumentNode' from 'graphql' (/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/graphql/__init__.py)
```

python 3.8.10, clean virtual env, on Ubuntu 20.04

**Comment by dannyp** [comment]
@barryrowlingson I get the same thing - might be worth adding another issue, considering this one is closed? 

In case it helps, installing `gql<3` seemed to get things running (at least for the tutorial that you also seem to be doing 😃)
