### ISSUE TITLE
`DynamicOut.collect` result is not treated like other op outputs when in list of inputs 

### ISSUE THREAD

**Issue by cvb** [dagster-io/dagster#5649]
## Summary

When trying to use something like `some_solid([some_other_solid(), solid_yielding().collect()])` it fails with error below. It works fine if you run result of `collect` thru some other proxy solid (something like `tst` proxy in the example).

## Reproduction

```
$ cat tst_d.py
# flake8: noqa
from typing import List, Any
from dagster import (
    DagsterInstance,
    DynamicOutput,
    DynamicOutputDefinition,
    ModeDefinition,
    Output,
    OutputDefinition,
    composite_solid,
    execute_pipeline,
    fs_io_manager,
    pipeline,
    reconstructable,
    reexecute_pipeline,
    solid
)


@solid(output_defs=[DynamicOutputDefinition(int)])
def producer(context):
    for i in range(10):
        yield DynamicOutput(i, mapping_key=str(i))


@solid
def consumer(context, vals: Any):
    context.log.info(f'vals: {vals}')


@solid
def tst(context, v: Any) -> Any:
    return v

@pipeline(
    mode_defs=[
        ModeDefinition(
            "default",
            resource_defs={"io_manager": fs_io_manager},
        )
    ]
)
def pipe():
    data = producer()
    # consumer([tst(data.collect())])
    consumer([data.collect()])



run_config = {
    'execution': {'multiprocess': {'config': {'max_concurrent': 8}}},
    'loggers': {'console': {'config': {'log_level': 'INFO'}}}
}
if __name__ == '__main__':
    instance = DagsterInstance.get()
    instance

    run = execute_pipeline(
        reconstructable(pipe),
        instance=instance,
        run_config=run_config,
    )
```
```
$ python tst_d.py
/home/cvb/.cache/pypoetry/virtualenvs/***-QiXA0H0F-py3.8/lib/python3.8/site-packages/dagster/core/definitions/composition.py:89: UserWarning: While in @pipeline context 'pipe', received an uninvoked solid 'consumer'.
  warnings.warn(warning_message.strip())
Traceback (most recent call last):
  File "tst_d.py", line 43, in <module>
    def pipe():
  File "/home/cvb/.cache/pypoetry/virtualenvs/***-QiXA0H0F-py3.8/lib/python3.8/site-packages/dagster/core/definitions/decorators/pipeline.py", line 77, in __call__
    ) = do_composition(
  File "/home/cvb/.cache/pypoetry/virtualenvs/***-QiXA0H0F-py3.8/lib/python3.8/site-packages/dagster/core/definitions/composition.py", line 1002, in do_composition
    output = fn(**kwargs)
  File "tst_d.py", line 46, in pipe
    consumer([data.collect()])
  File "/home/cvb/.cache/pypoetry/virtualenvs/***-QiXA0H0F-py3.8/lib/python3.8/site-packages/dagster/core/definitions/solid.py", line 145, in __call__
    return super(SolidDefinition, self).__call__(*args, **kwargs)
  File "/home/cvb/.cache/pypoetry/virtualenvs/***-QiXA0H0F-py3.8/lib/python3.8/site-packages/dagster/core/definitions/node.py", line 158, in __call__
    return PendingNodeInvocation(
  File "/home/cvb/.cache/pypoetry/virtualenvs/***-QiXA0H0F-py3.8/lib/python3.8/site-packages/dagster/core/definitions/composition.py", line 373, in __call__
    self._process_argument_node(
  File "/home/cvb/.cache/pypoetry/virtualenvs/***-QiXA0H0F-py3.8/lib/python3.8/site-packages/dagster/core/definitions/composition.py", line 448, in _process_argument_node
    raise DagsterInvalidDefinitionError(
dagster.core.errors.DagsterInvalidDefinitionError: In @pipeline pipe, received a list containing an invalid type at index 0 for input "vals" (at position 0) in solid invocation consumer. Lists can only contain the output from previous solid invocations or input mappings, received <class 'list'>
```

## Additional Info about Your Environment

```
$ pip list | grep dagster
dagster                0.13.5
dagster-graphql        0.13.5
dagster-k8s            0.12.12
dagster-postgres       0.12.12
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @cvb - seems like a real issue.

**Comment by jamiedemaria** [comment]
Hey @cvb I just took a look at reproducing the bug here. I think the issue is wrapping `data.collect()` in a list before passing to `consumer`. If you change your pipeline to look like this
```
def pipe():
    data = producer()
    consumer(data.collect())
```
It runs as expected for me. Let me know if this change doesn't work for you and I can investigate further
