### ISSUE TITLE
dagster-databricks - improved logging / permission handling

### ISSUE THREAD

**Issue by Phazure** [dagster-io/dagster#6156]
## Use Case
When running ops using databricks_pyspark_step_launcher from the dagster_databricks package, if the submitted Databricks job run fails, the resulting error message is rather generic and unhelpful in diagnosing the root cause of error. It typically looks as follows:
```
dagster.core.errors.DagsterSubprocessError: During multiprocess execution errors occurred in child processes:
In process 8: dagster_databricks.databricks.DatabricksError: Run 2506004 failed with result state: DatabricksRunResultState.Failed. Message:

Stack Trace:
File "/usr/local/lib/python3.8/site-packages/dagster/core/executor/child_process_executor.py", line 65, in _execute_command_in_child_process
for step_event in command.execute():
File "/usr/local/lib/python3.8/site-packages/dagster/core/executor/multiprocess.py", line 77, in execute
yield from execute_plan_iterator(
File "/usr/local/lib/python3.8/site-packages/dagster/core/execution/api.py", line 861, in __iter__
yield from self.iterator(
File "/usr/local/lib/python3.8/site-packages/dagster/core/execution/plan/execute_plan.py", line 69, in inner_plan_execution_iterator
for step_event in check.generator(_dagster_event_sequence_for_step(step_context)):
File "/usr/local/lib/python3.8/site-packages/dagster/core/execution/plan/execute_plan.py", line 294, in _dagster_event_sequence_for_step
raise unexpected_exception
File "/usr/local/lib/python3.8/site-packages/dagster/core/execution/plan/execute_plan.py", line 195, in _dagster_event_sequence_for_step
for step_event in check.generator(step_events):
File "/usr/local/lib/python3.8/site-packages/dagster_databricks/databricks_pyspark_step_launcher.py", line 165, in launch_step
self.databricks_runner.wait_for_run_to_complete(log, databricks_run_id)
File "/usr/local/lib/python3.8/site-packages/dagster_databricks/databricks.py", line 245, in wait_for_run_to_complete
return wait_for_run_to_complete(
File "/usr/local/lib/python3.8/site-packages/dagster_databricks/databricks.py", line 270, in wait_for_run_to_complete
raise DatabricksError(error_message)

  File "/usr/local/lib/python3.8/site-packages/dagster/core/execution/api.py", line 774, in pipeline_execution_iterator
    for event in pipeline_context.executor.execute(pipeline_context, execution_plan):
  File "/usr/local/lib/python3.8/site-packages/dagster/core/executor/multiprocess.py", line 227, in execute
    raise DagsterSubprocessError(
```

## Ideas of Implementation
It would be optimal if dagster were able to retrieve and log out the job run's output as if we were looking in the job run itself in Databricks' workspace. One can access the job run itself by running the following script and going into the printed run_page_url to diagnose the root error:
```
from databricks_api import DatabricksAPI
client = DatabricksAPI(host="...", token="...")
run_info = client.jobs.get_run("2506004")
print(run_info["run_page_url"])  # typically looks like 'https://{databricks_host}/?o=2480071277909477#job/2506004/run/1'
```
This is fine for localized debugging. However, if the production Dagster deployment leverages a different production Databricks service principal / token that users do not (and should not) have access to, they would be unable to view the job run due to job permission errors, thus making it difficult diagnose the underlying issue.
```
Traceback (most recent call last):
  File "/home/user.name/miniconda3/envs/dagster/lib/python3.8/site-packages/databricks_cli/sdk/api_client.py", line 138, in perform_query
    resp.raise_for_status()
  File "/home/user.name/miniconda3/envs/dagster/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://{databricks_host}/api/2.0/jobs/runs/get?run_id=2506004

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user.name/miniconda3/envs/dagster/lib/python3.8/site-packages/databricks_cli/sdk/service.py", line 193, in get_run
    return self.client.perform_query('GET', '/jobs/runs/get', data=_data, headers=headers, version=version)
  File "/home/user.name/miniconda3/envs/dagster/lib/python3.8/site-packages/databricks_cli/sdk/api_client.py", line 146, in perform_query
    raise requests.exceptions.HTTPError(message, response=e.response)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://{databricks_host}/api/2.0/jobs/runs/get?run_id=2506004
 Response from server:
 { 'error_code': 'PERMISSION_DENIED',
  'message': 'User {user.name} does not have Admin or Manage '
             'Run or Owner or View permissions on job 2506004'}. # because this is owned by the production service principal
```
If logging the underlying job run logs to dagster's context is particularly difficult / infeasible, a nice middle ground may be to:
1. Provide support for an `access_control_list` field when defining the pyspark_step_launcher. This would allow developers to configure job run permissions to allow end users to view the job run page. From the Databricks side, this should theoretically be possible based on their Jobs API 2.1: https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsRunsSubmit.
```
step_launcher = databricks_pyspark_step_launcher.configured(
        {
            "run_config": {
               ...
            },
            "databricks_host": ...,
            "databricks_token": {"env": "DATABRICKS_TOKEN"},
            "local_pipeline_package_path": ...,
            "secrets_to_env_variables": [],
            "storage": {
                ...
            },
            "access_control_list": [{"user_name": ..., "permission_level": "CAN_VIEW"}, ...]
        }
    )
```
2. Have Dagster log the associated run_page_url for end users to click into manually.
```
dagster_databricks.databricks.DatabricksError: Run 2506004 failed with result state: DatabricksRunResultState.Failed. Job run url: {run_page_url}. Message: ...
```
Together, these two improvements should sufficiently empower developers to diagnose Databricks job run errors in production dagster deployments.
## Additional Info
I have been running with dagster 0.13.8 package versions.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
cc @OwenKephart - I think you're the right point of contact on this one

**Comment by OwenKephart** [comment]
Hi @Phazure ! Your suggestions make sense, but I think something in the previous set of changes might actually do what you're looking for here. It's kind of an ugly implementation at the moment, but as of the last release, once a databricks job completes, the stdout / stderr from databricks will be captured and sent back immediately to dagster (and be logged to the event log). Formatting isn't the greatest (just prints a raw string), but should be good enough for debugging in many cases.

Happy to talk more on improving that feature (if it doesn't entirely cover what you need)!

**Comment by Phazure** [comment]
@OwenKephart Gotcha, have taken a look at the 0.13.14 release - these are exactly the logs we wanted to be exposed. Thanks for adding this!
