### ISSUE TITLE
Dagster pyspark example throws errors for both local/prod mode

### ISSUE THREAD

**Issue by npow** [dagster-io/dagster#6187]
## Summary
I tried running the [EMR example](https://github.com/dagster-io/dagster/tree/0.13.13/examples/emr_pyspark) in local mode and am getting the following error:

```
2022-01-11 15:46:40 -0700 - dagster - ERROR - local - 1c6fe175-e16d-4af6-b083-604e54b54dab - 33633 - make_people - STEP_FAILURE - Execution of step "make_people" failed.

dagster.core.errors.DagsterExecutionHandleOutputError: Error occurred while handling output "result" of step "make_people"::

TypeError: can't pickle _thread.RLock objects

Stack Trace:
  File "/Users/pownissa/code/dagster/python_modules/dagster/dagster/core/execution/plan/utils.py", line 47, in solid_execution_error_boundary
    yield
  File "/Users/pownissa/code/dagster/python_modules/dagster/dagster/utils/__init__.py", line 387, in iterate_with_context
    next_output = next(iterator)
  File "/Users/pownissa/code/dagster/python_modules/dagster/dagster/core/execution/plan/execute_step.py", line 504, in _gen_fn
    gen_output = output_manager.handle_output(output_context, output.value)
  File "/Users/pownissa/code/dagster/python_modules/dagster/dagster/core/storage/fs_io_manager.py", line 122, in handle_output
    pickle.dump(obj, write_obj, PICKLE_PROTOCOL)
```

## Reproduction
1. Clone the dagster repo (I'm on commit 4a84ac4a3b5c0c6831eec1ae71c3d7de46aec045)
2. Run `make dev_install` 
3. Run `cd dagster/examples/emr_pyspark; dagster job execute -f  repo.py --job local`

Also tried running the job on an EMR cluster (production mode) via `dagster job execute -f  repo.py --job prod` and am getting the following error:
```
22/01/11 22:52:14 INFO VirtualEnvFactory: Start to setup virtualenv...
Exception in thread "main" java.util.NoSuchElementException: spark.app.id
	at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:246)
	at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:246)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.SparkConf.get(SparkConf.scala:246)
	at org.apache.spark.SparkConf.getAppId(SparkConf.scala:452)
	at org.apache.spark.api.python.VirtualEnvFactory.setupVirtualEnv(VirtualEnvFactory.scala:73)
	at org.apache.spark.deploy.PythonRunner$.main(PythonRunner.scala:53)
	at org.apache.spark.deploy.PythonRunner.main(PythonRunner.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:863)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:938)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:947)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
22/01/11 22:52:14 INFO ShutdownHookManager: Shutdown hook called
22/01/11 22:52:14 INFO ShutdownHookManager: Deleting directory /mnt/tmp/spark-dfcdecf3-9d52-40f1-8c21-8617013b0e21
Command exiting with ret '1'
```

## Additional Info about Your Environment
Python: 3.7.11
OS: macOS Catalina 10.15.7
EMR: 5.34.0

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
cc @sryza

**Comment by sryza** [comment]
Thanks for reporting this @npow . This PR should address it: https://github.com/dagster-io/dagster/pull/6196.

**Comment by npow** [comment]
Thanks @sryza, I checked out the `emr-example` branch and confirmed that both local/prod mode works there!
