### ISSUE TITLE
On restart dagit cannot find run id

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#673]
Dagit can often get into the state where we are querying for a run id that doesn't exist and it throws a raw Exception. 

```
Serving on http://127.0.0.1:3000
An error occurred while resolving field Subscription.pipelineRunLogs
Traceback (most recent call last):
  File "/Users/schrockn/code/venvs/sun_basket/lib/python3.6/site-packages/graphql/execution/executor.py", line 447, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/schrockn/code/venvs/sun_basket/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/schema/roots.py", line 105, in resolve_pipelineRunLogs
    return model.get_pipeline_run_observable(info, runId, after)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/schema/model.py", line 163, in get_pipeline_run_observable
    raise Exception('No run with such id: {run_id}'.format(run_id=run_id))
Exception: No run with such id: fd4c6e79-a240-4675-a569-f6d5909818f5
```

**Comment by mgasner** [comment]
Is the fix to this to persist to disk?

**Comment by schrockn** [comment]
Yeah we need to persist to disk to make this work.
