### ISSUE TITLE
'Select' object has no attribute 'filter' when using SQLAlchemy v1.3.x

### ISSUE THREAD

**Issue by mrdavidlaing** [dagster-io/dagster#6964]
## Summary
When using Dagit/Dagster v1.14.3 with SQLAlchemy v1.3.24 a `'Select' object has no attribute 'filter'` 

## Reproduction
Given the following set of packages:

```
dagit = "==0.14.3"
sqlalchemy = "==1.3.24"
```

A simple job:

```
from dagster import job, op, repository


@op
def hello():
    return "Hello"

@op
def world(greeting):
    return f"{greeting} World"


@job
def hello_world_job():
    world(hello())


@repository
def hello_world_repository():
    return [hello_world_job]
```

1. Run a local dagit instance - `dagit -f repository.py`
2. Run the job once
3. Navigate back to the Job Overview page - http://127.0.0.1:3000/workspace/hello_world_repository@repository.py/jobs/hello_world_job/

The following `Unexpected GraphQL error` is shown 
```
Operation name: JobMetadataQuery

Message: 'Select' object has no attribute 'filter'

Path: ["pipelineRunsOrError","results",0,"assets"]

Locations: [{"line":73,"column":3}]
```

Following error details are logged to the console: 
```
An error occurred while resolving field Run.assets
Traceback (most recent call last):
  File "/Users/dlaing/.local/share/virtualenvs/dagster-run-config-failure-test-G3ZLspwL/lib/python3.7/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/dlaing/.local/share/virtualenvs/dagster-run-config-failure-test-G3ZLspwL/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/dlaing/.local/share/virtualenvs/dagster-run-config-failure-test-G3ZLspwL/lib/python3.7/site-packages/dagster_graphql/schema/pipelines/pipeline.py", line 357, in resolve_assets
    return get_assets_for_run_id(graphene_info, self.run_id)
  File "/Users/dlaing/.local/share/virtualenvs/dagster-run-config-failure-test-G3ZLspwL/lib/python3.7/site-packages/dagster_graphql/implementation/fetch_assets.py", line 175, in get_assets_for_run_id
    records = graphene_info.context.instance.all_logs(run_id, of_type=ASSET_EVENTS)
  File "/Users/dlaing/.local/share/virtualenvs/dagster-run-config-failure-test-G3ZLspwL/lib/python3.7/site-packages/dagster/utils/__init__.py", line 608, in inner
    return func(*args, **kwargs)
  File "/Users/dlaing/.local/share/virtualenvs/dagster-run-config-failure-test-G3ZLspwL/lib/python3.7/site-packages/dagster/core/instance/__init__.py", line 1138, in all_logs
    return self._event_storage.get_logs_for_run(run_id, of_type=of_type)
  File "/Users/dlaing/.local/share/virtualenvs/dagster-run-config-failure-test-G3ZLspwL/lib/python3.7/site-packages/dagster/core/storage/event_log/sql_event_log.py", line 279, in get_logs_for_run
    events_by_id = self.get_logs_for_run_by_log_id(run_id, cursor, of_type, limit)
  File "/Users/dlaing/.local/share/virtualenvs/dagster-run-config-failure-test-G3ZLspwL/lib/python3.7/site-packages/dagster/core/storage/event_log/sql_event_log.py", line 221, in get_logs_for_run_by_log_id
    query = query.filter(
AttributeError: 'Select' object has no attribute 'filter'
```

## Remediation
Install SQLALchemy >= v1.4.0

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by prha** [comment]
Thanks @mrdavidlaing...

For now we're committed to supporting SQLAlchemy < 1.4.0.   I just added a tox env to run our core storage tests using SQLAlchemy 1.3.  Should get pushed out with our next release: https://github.com/dagster-io/dagster/pull/6930
