### ISSUE TITLE
Fresh installs of dagit fail due to a missing upstream dependency

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#7023]
## Summary
Doing a fresh pip install of dagster and dagit causes dagit to fail on startup with the following error:
```
(dagster-fresh) dgibson@Daniels-MacBook-Pro dagster % dagit
Traceback (most recent call last):
  File "/Users/dgibson/.pyenv/versions/dagster-fresh/bin/dagit", line 5, in <module>
    from dagit.cli import main
  File "/Users/dgibson/.pyenv/versions/3.8.9/envs/dagster-fresh/lib/python3.8/site-packages/dagit/cli.py", line 21, in <module>
    from .app import create_app_from_workspace_process_context
  File "/Users/dgibson/.pyenv/versions/3.8.9/envs/dagster-fresh/lib/python3.8/site-packages/dagit/app.py", line 10, in <module>
    from .webserver import DagitWebserver
  File "/Users/dgibson/.pyenv/versions/3.8.9/envs/dagster-fresh/lib/python3.8/site-packages/dagit/webserver.py", line 11, in <module>
    from nbconvert import HTMLExporter
  File "/Users/dgibson/.pyenv/versions/3.8.9/envs/dagster-fresh/lib/python3.8/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/Users/dgibson/.pyenv/versions/3.8.9/envs/dagster-fresh/lib/python3.8/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
    from .base import (export, get_exporter, 
  File "/Users/dgibson/.pyenv/versions/3.8.9/envs/dagster-fresh/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 14, in <module>
    from ipython_genutils.py3compat import string_types
ModuleNotFoundError: No module named 'ipython_genutils'
```

Luckily the workaround is straightforward: pip install that missing dependency (ipython_genutils) and dagit will load without issues.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by shaheedebrahim** [comment]
👍

**Comment by nbrons** [comment]
Fixed by the WeMeta team: https://github.com/dagster-io/dagster/pull/7034/commits/94d5f22541e1053fbabb37a3456e74851524346e
