### ISSUE TITLE
weakref key error

### ISSUE THREAD

**Issue by CheckHarry** [dagster-io/dagster#7100]
## Summary
Got this issue when trying to call engine.dispose() when using a engine in a class 

Exception ignored in: <function DBData.__del__ at 0x7fd4f4de3680>
Traceback (most recent call last):
  File "/home/ec2-user/Github/simba/lib/webdb/data_db.py", line 19, in __del__
  File "/home/ec2-user/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2076, in dispose
  File "/home/ec2-user/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 255, in recreate
  File "<string>", line 2, in __init__
  File "/home/ec2-user/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
  File "/home/ec2-user/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 221, in __init__
  File "/home/ec2-user/.local/lib/python3.7/site-packages/sqlalchemy/event/base.py", line 150, in _update
  File "/home/ec2-user/.local/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 392, in _update
  File "/home/ec2-user/.local/lib/python3.7/site-packages/sqlalchemy/event/registry.py", line 115, in _stored_in_collection_multi
KeyError: (<weakref at 0x7fd4e42fe650; to 'function' at 0x7fd4e462be60 (on_connect)>,)

**Comment by alangenfeld** [comment]
> Got this issue when trying to call engine.dispose() when using a engine in a class

can you add some more detail / context? I am not sure where in dagster you are getting an "engine" from

**Comment by CheckHarry** [comment]
> > Got this issue when trying to call engine.dispose() when using a engine in a class
> 
> can you add some more detail / context? I am not sure where in dagster you are getting an "engine" from

Actually i am creating the engine with this method:
`def create_engine(self):
        self.engine = sqlalchemy.create_engine(f"mysql+pymysql://{self.credentials['user']}:{self.credentials['pwd']}@{self.credentials['host']}/{self.credentials['db']}?charset=utf8" , poolclass = NullPool) `


My class is defined by following code:
`class DBData:

    def __init__(self, host, db, user, pwd, auto_conn = True):
        self.credentials = {"host": host, "db": db, "user": user, "pwd": pwd}
        self.engine = None
        self.conn = None
        self.engine = None
    
        if auto_conn:
            self.connect()       

    def __del__(self):
        if self.conn:
            self.conn.close()
        self.engine.dispose()


    def create_engine(self):
        self.engine = sqlalchemy.create_engine(f"mysql+pymysql://{self.credentials['user']}:{self.credentials['pwd']}@{self.credentials['host']}/{self.credentials['db']}?charset=utf8" , poolclass = NullPool) 
    
    def connect(self):
        if not self.engine:
            self.create_engine()
        self.conn = self.engine.connect()
        
    def commit(self):
        if self.conn is not None:
            self.conn.commit()

    def sql_cmd(self, cmd):
        if self.conn is None:
            self.connect()

        df = pd.read_sql(cmd, self.conn)
        return df

    def close_connection(self):
        if self.conn is not None:
            print("now is closing")
            self.conn.close()

    def check_connected(self):
        if self.conn is not None:
            return True
        else:
            return False
`

and this is how i call it:
`
d = DBData(host , db , user , pwd, auto_conn=False)
 print(d.sql_cmd("show tables;"))
`
