### ISSUE TITLE
Cannot read properties of undefined (reading 'name') during asset graph search

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#7301]
```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'name')
    at :8080/static/js/265.dcb11d72.chunk.js:1:317529
    at Hs (main.da643899.js:2:1533895)
    at t.unstable_runWithPriority (main.da643899.js:2:1612165)
    at Go (main.da643899.js:2:1474214)
    at Rs (main.da643899.js:2:1533356)
    at bs (main.da643899.js:2:1524846)
    at main.da643899.js:2:1474437
    at t.unstable_runWithPriority (main.da643899.js:2:1612165)
    at Go (main.da643899.js:2:1474214)
    at Qo (main.da643899.js:2:1474382)
uc @ react-dom.production.min.js:216

react-dom.production.min.js:123 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at :8080/static/js/265.dcb11d72.chunk.js:1:317529
    at Hs (main.da643899.js:2:1533895)
    at t.unstable_runWithPriority (main.da643899.js:2:1612165)
    at Go (main.da643899.js:2:1474214)
    at Rs (main.da643899.js:2:1533356)
    at bs (main.da643899.js:2:1524846)
    at main.da643899.js:2:1474437
    at t.unstable_runWithPriority (main.da643899.js:2:1612165)
    at Go (main.da643899.js:2:1474214)
    at Qo (main.da643899.js:2:1474382)
```

Dagster 0.14.2

Occurred along with https://github.com/dagster-io/dagster/issues/7300

**Comment by hellendag** [comment]
@johannkm Can you repro this in Cloud or in a dev build so that we can get sourcemaps on the trace?

**Comment by hellendag** [comment]
Oh, is this the same issue as #7300?

**Comment by hellendag** [comment]
This has been fixed!
