### ISSUE TITLE
Display a helpful error message when jupyter_client.kernelspec.NoSuchKernel is raised

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#839]
This is going to be a relatively common error when notebooks are passed around between users.

Right now the top-level error message is `dagstermill.DagstermillError: There was an error when Papermill tried to execute the notebook. The process stderr is None` and the logs read, e.g.:

```
2019-02-15 13:24:45 - dagster - DEBUG - orig_message="Executing core transform for solid delays_by_geo." log_message_id="6b096dc8-8b61-41f1-ace0-b4403a86ad41" run_id="ea2911d8-9886-4140-85df-779b12c2353c" pipeline="airline_demo_warehouse_pipeline" step_key="delays_by_geo.transform" solid="delays_by_geo" solid_definition="delays_by_geo"
Input Notebook:  /tmp/dagstermill/ea2911d8-9886-4140-85df-779b12c2353c/output_notebooks/51a3eaf9-a932-4a08-99d2-98d045000903-inter.ipynb
Output Notebook: /tmp/dagstermill/ea2911d8-9886-4140-85df-779b12c2353c/output_notebooks/455f8128-fe58-4de4-a789-45affd2a21e7-out.ipynb
  0%|                                                                                                    | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/max/.virtualenvs/dagster/bin/papermill", line 11, in <module>
    sys.exit(papermill())
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/papermill/cli.py", line 165, in papermill
    cwd=cwd,
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/papermill/execute.py", line 90, in execute_notebook
    start_timeout=start_timeout,
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/papermill/engines.py", line 56, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/papermill/engines.py", line 296, in execute_notebook
    nb = cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/papermill/engines.py", line 352, in execute_managed_notebook
    preprocessor.preprocess(nb_man, kwargs)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/papermill/preprocess.py", line 24, in preprocess
    with self.setup_preprocessor(nb_man.nb, resources, km=km):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 304, in setup_preprocessor
    self.km, self.kc = self.start_new_kernel(cwd=path)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/papermill/preprocess.py", line 37, in start_new_kernel
    km, kc = super(PapermillExecutePreprocessor, self).start_new_kernel(**kwargs)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 253, in start_new_kernel
    km.start_kernel(extra_arguments=self.extra_arguments, **kwargs)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/jupyter_client/manager.py", line 246, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 236, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named dagster
2019-02-15 13:24:54 - dagster - INFO - orig_message="Execution of delays_by_geo.transform failed" log_message_id="c955c077-77ec-4a05-8a8b-7b40dda4b44a" run_id="ea2911d8-9886-4140-85df-779b12c2353c" pipeline="airline_demo_warehouse_pipeline" step_key="delays_by_geo.transform" solid="delays_by_geo" solid_definition="delays_by_geo" event_type="EXECUTION_PLAN_STEP_FAILURE" error_info="[\"dagstermill.DagstermillError: There was an error when Papermill tried to execute the notebook. The process stderr is None\\n\", [\"  File \\\"/Users/max/dev/dagster/python_modules/dagster/dagster/core/execution_plan/simple_engine.py\\\", line 251, in _execution_step_error_boundary\\n    yield\\n\", \"  File \\\"/Users/max/dev/dagster/python_modules/dagster/dagster/core/execution_plan/simple_engine.py\\\", line 230, in _iterate_step_output_values_within_boundary\\n    for step_output_value in gen:\\n\", \"  File \\\"/Users/max/dev/dagster/python_modules/dagster/dagster/core/execution_plan/transform.py\\\", line 80, in _execute_core_transform\\n    for step_output_value in _yield_transform_results(transform_context, inputs):\\n\", \"  File \\\"/Users/max/dev/dagster/python_modules/dagster/dagster/core/execution_plan/transform.py\\\", line 47, in _yield_transform_results\\n    for result in gen:\\n\", \"  File \\\"/Users/max/dev/dagster/python_modules/dagstermill/dagstermill/__init__.py\\\", line 457, in _t_fn\\n    'The process stderr is {stderr}'.format(stderr=process.stderr)\\n\"]]"
2019-02-15 13:24:54 - dagster - ERROR - orig_message="There was an error when Papermill tried to execute the notebook. The process stderr is None" log_message_id="a731a171-811e-4b55-a70a-18d3cbb64258" run_id="ea2911d8-9886-4140-85df-779b12c2353c" pipeline="airline_demo_warehouse_pipeline" step_key="delays_by_geo.transform" solid="delays_by_geo" solid_definition="delays_by_geo" stack_trace="  File \"/Users/max/dev/dagster/python_modules/dagster/dagster/core/execution_plan/simple_engine.py\", line 251, in _execution_step_error_boundary\n    yield\n  File \"/Users/max/dev/dagster/python_modules/dagster/dagster/core/execution_plan/simple_engine.py\", line 230, in _iterate_step_output_values_within_boundary\n    for step_output_value in gen:\n  File \"/Users/max/dev/dagster/python_modules/dagster/dagster/core/execution_plan/transform.py\", line 80, in _execute_core_transform\n    for step_output_value in _yield_transform_results(transform_context, inputs):\n  File \"/Users/max/dev/dagster/python_modules/dagster/dagster/core/execution_plan/transform.py\", line 47, in _yield_transform_results\n    for result in gen:\n  File \"/Users/max/dev/dagster/python_modules/dagstermill/dagstermill/__init__.py\", line 457, in _t_fn\n    'The process stderr is {stderr}'.format(stderr=process.stderr)\n"
2019-02-15 13:24:54 - dagster - ERROR - orig_message="Error occured during step delays_by_geo.transform" log_message_id="bce74fb1-b54f-44b4-8643-abfe43ae9f4e" run_id="ea2911d8-9886-4140-85df-779b12c2353c" pipeline="airline_demo_warehouse_pipeline" step_key="delays_by_geo.transform" solid="delays_by_geo" solid_definition="delays_by_geo"
```

**Comment by mgasner** [comment]
I think this is likely to be an issue when users are running Anaconda

**Comment by mgasner** [comment]
Properly speaking, this is probably an issue for papermill.
