### ISSUE TITLE
dagit installation fails with graphql version error.

### ISSUE THREAD

**Issue by barryrowlingson** [dagster-io/dagster#9036]
### Dagster version

dagster, version 0.15.7

### What's the issue?

install dagit via pip to a clean venv on ubuntu 20.04 results in:

ERROR: gql 3.4.0 has requirement graphql-core<3.3,>=3.2, but you'll have graphql-core 2.3.2 which is incompatible.

and a broken dagit:

```
$ dagit -f cereal.py
Traceback (most recent call last):
  File "/nobackup/rowlings/Envs/dagster/bin/dagit", line 5, in <module>
    from dagit.cli import main
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/dagit/cli.py", line 21, in <module>
    from .app import create_app_from_workspace_process_context
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/dagit/app.py", line 11, in <module>
    from .webserver import DagitWebserver
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/dagit/webserver.py", line 8, in <module>
    from dagster_graphql import __version__ as dagster_graphql_version
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/dagster_graphql/__init__.py", line 3, in <module>
    from .client import (
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/dagster_graphql/client/__init__.py", line 1, in <module>
    from .client import DagsterGraphQLClient
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/dagster_graphql/client/client.py", line 5, in <module>
    from gql import Client, gql
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/gql/__init__.py", line 11, in <module>
    from .client import Client
  File "/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/gql/client.py", line 19, in <module>
    from graphql import (
ImportError: cannot import name 'DocumentNode' from 'graphql' (/nobackup/rowlings/Envs/dagster/lib/python3.8/site-packages/graphql/__init__.py)
```

### What did you expect to happen?

Expected dagit to run.

### How to reproduce?

Create new virtual env, activate, install, run:

```
python -m venv /tmp/dagster
. /tmp/dagster/bin/activate
python -m pip install dagit
dagit
[error]
```

### Deployment type

Local

### Deployment details

Ubuntu 20.04 focal

### Additional information

Can be fixed by pushing `gql` back to a version 2.x release:

```
python -m pip install "gql<3"
dagit
[runs ok]
```

but don't know what other impact this might have.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @barryrowlingson - we just landed a gql pin for this that should go out in the next release. There should be enough information in the setup.py for pip to figure out what to do, but it looks like certain versions of pip still need the pin. Thanks for the report!
