### ISSUE TITLE
Run_id exception on process reload when using in-memory run storage

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#957]
```
on_any_event(self=<watchdog.tricks.AutoRestartTrick object at 0x10ffc8f98>, event=<FileDeletedEvent: src_path='./pandas_hello_world/pipeline.py.fea67d04942549f1eff043712418bdad.py'>)
on_any_event(self=<watchdog.tricks.AutoRestartTrick object at 0x10ffc8f98>, event=<FileModifiedEvent: src_path='./pandas_hello_world/pipeline.py'>)
Serving on http://127.0.0.1:3000
An error occurred while resolving field Subscription.pipelineRunLogs
Traceback (most recent call last):
  File "/Users/schrockn/code/venvs/dagster-3.7.1/lib/python3.7/site-packages/graphql/execution/executor.py", line 447, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/schrockn/code/venvs/dagster-3.7.1/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/schema/roots.py", line 203, in resolve_pipelineRunLogs
    return model.get_pipeline_run_observable(graphene_info, runId, after)
  File "/Users/schrockn/code/dagster/python_modules/dagit/dagit/schema/model.py", line 242, in get_pipeline_run_observable
    raise Exception('No run with such id: {run_id}'.format(run_id=run_id))
Exception: No run with such id: 8d03bd13-642c-408e-8220-a2d96e27db63
```

**Comment by schrockn** [comment]
Fixed by https://github.com/dagster-io/dagster/pull/1044
