### ISSUE TITLE
dagster-k8s/k8s_job_op throws TypeError when a non-zero `timeout` is used.

### ISSUE THREAD

**Issue by mlarose** [dagster-io/dagster#9584]
### Dagster version

1.0.4

### What's the issue?

When a timeout configuration is provided on k8s_job_op, the op will error out with a TypeError.

The root cause seems to be that the `start` parameter is not provided in calling code and defaults to None, resulting in TypeError in the substraction.

https://github.com/dagster-io/dagster/blob/1.0.7/python_modules/libraries/dagster-k8s/dagster_k8s/client.py#L271-L280

#### Partial relevant trace

This trace was produced with the code sample below.

```
[...]
dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing solid "test_timeout":

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

 [...]
  File "/path/to/virtualenv//lib/python3.10/site-packages/dagster_k8s/ops/k8s_job_op.py", line 216, in k8s_job_op
    wait_for_running_job_to_succeed(
  File "/path/to/virtualenv/lib/python3.10/site-packages/dagster_k8s/utils.py", line 78, in wait_for_running_job_to_succeed
    return DagsterKubernetesClient.production_client().wait_for_running_job_to_succeed(
  File "/path/to/virtualenv/lib/python3.10/site-packages/dagster_k8s/client.py", line 276, in wait_for_running_job_to_succeed
    if wait_timeout and (self.timer() - start > wait_timeout):
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

### What did you expect to happen?

The k8s_job_op should wait for the job completion or until the timeout is reached and report job status.

A successful run should look like this if the job completes before the timeout:

```
/path/to/virtualenv/bin/python /path/to/code/issue.py 
2022-09-02 08:56:16 -0400 - dagster - DEBUG - test_with_timeout - 8ca5e0bf-7db5-42fb-98df-15e41d694fae - 18946 - RUN_START - Started execution of run for "test_with_timeout".
2022-09-02 08:56:16 -0400 - dagster - DEBUG - test_with_timeout - 8ca5e0bf-7db5-42fb-98df-15e41d694fae - 18946 - ENGINE_EVENT - Executing steps in process (pid: 18946)
2022-09-02 08:56:16 -0400 - dagster - DEBUG - test_with_timeout - 8ca5e0bf-7db5-42fb-98df-15e41d694fae - 18946 - test_timeout - RESOURCE_INIT_STARTED - Starting initialization of resources [io_manager].
2022-09-02 08:56:16 -0400 - dagster - DEBUG - test_with_timeout - 8ca5e0bf-7db5-42fb-98df-15e41d694fae - 18946 - test_timeout - RESOURCE_INIT_SUCCESS - Finished initialization of resources [io_manager].
2022-09-02 08:56:16 -0400 - dagster - DEBUG - test_with_timeout - 8ca5e0bf-7db5-42fb-98df-15e41d694fae - 18946 - test_timeout - LOGS_CAPTURED - Started capturing logs for step: test_timeout.
2022-09-02 08:56:16 -0400 - dagster - DEBUG - test_with_timeout - 8ca5e0bf-7db5-42fb-98df-15e41d694fae - 18946 - test_timeout - STEP_START - Started execution of step "test_timeout".
/path/to/virtualenv/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py:73: ExperimentalWarning: "k8s_job_op" is an experimental function. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
2022-09-02 08:56:17 -0400 - dagster - INFO - test_with_timeout - 8ca5e0bf-7db5-42fb-98df-15e41d694fae - test_timeout - Creating Kubernetes job 4749d9f89460a3c65b8d388c251d2090 in namespace orchestrator...
2022-09-02 08:56:18 -0400 - dagster - INFO - test_with_timeout - 8ca5e0bf-7db5-42fb-98df-15e41d694fae - test_timeout - Waiting for Kubernetes job to finish...
2022-09-02 08:56:39 -0400 - dagster - DEBUG - test_with_timeout - 8ca5e0bf-7db5-42fb-98df-15e41d694fae - 18946 - test_timeout - STEP_OUTPUT - Yielded output "result" of type "Any". (Type check passed).
2022-09-02 08:56:39 -0400 - dagster - DEBUG - test_with_timeout - 8ca5e0bf-7db5-42fb-98df-15e41d694fae - 18946 - test_timeout - HANDLED_OUTPUT - Handled output "result" using IO manager "io_manager"
2022-09-02 08:56:39 -0400 - dagster - DEBUG - test_with_timeout - 8ca5e0bf-7db5-42fb-98df-15e41d694fae - 18946 - test_timeout - STEP_SUCCESS - Finished execution of step "test_timeout" in 22.56s.
2022-09-02 08:56:39 -0400 - dagster - DEBUG - test_with_timeout - 8ca5e0bf-7db5-42fb-98df-15e41d694fae - 18946 - ENGINE_EVENT - Finished steps in process (pid: 18946) in 22.56s
2022-09-02 08:56:39 -0400 - dagster - DEBUG - test_with_timeout - 8ca5e0bf-7db5-42fb-98df-15e41d694fae - 18946 - RUN_SUCCESS - Finished execution of run for "test_with_timeout".

Process finished with exit code 0
```

### How to reproduce?

This code sample reproduces the error.

```
from dagster import graph
import dagster_k8s


@graph
def test_with_timeout() -> None:
    op = dagster_k8s.k8s_job_op.configured({
            "image": "debian:buster-slim",
            "args": ["sleep", "5"],
             "timeout": 30,

            # configure as needed for your k8s setup
            "namespace": "<your namespace>",
            "service_account_name": "<your service account>",
            "load_incluster_config": False,
        },
        name="test_timeout",
    )

    op()


if __name__ == "__main__":
    j = test_with_timeout.to_job(name="test_with_timeout")
    j.execute_in_process()
```

The same code, with timeout set to 0, will work normally, because the condition will exit on wait_timeout evaluating as falsy.

### Deployment type

Local

### Deployment details

This error was reproduced running dagster locally (using an .kubeconfig pointed at an EKS dev cluster 1.22)

dagster = "==1.0.4"
dagster-cloud = "==1.0.4"
dagster-dbt = "~=0.16.4"
dagster-k8s = "~=0.16.4"

python 3.10.x

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by johannkm** [comment]
Thanks for the report! This is fixed in 1.0.9 (core) / 0.16.9 (libraries)
