### ISSUE TITLE
dagster-postgresql inconsistently uses `psycopg2.connect` and SQLAlchemy's connect

### ISSUE THREAD

**Issue by peay** [dagster-io/dagster#9661]
### Dagster version

0.15.8

### What's the issue?

`dagster-postgresql` relies on a SQLAlchemy engine to create a connection to PostgreSQL in `PostgresEventLogStorage` and other components.

In principle, it means that [SQLAlchemy dialects](https://docs.sqlalchemy.org/en/14/core/engines.html#postgresql) can be used, to use other libraries than the default (e.g., `postgresql+pg8000://`). Custom dialects are also easy to write (e.g., to support token authentication methods for [Cloud SQL IAM authentication](https://cloud.google.com/sql/docs/postgres/authentication) or [Amazon RDS IAM authentication](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html)).

However, today, using a custom dialect can breaj live streaming events in the Dagit UI, because the event watch thread directly calls `psycopg2.connect` (which ignores dialect and scheme in general) instead of using a SQLAlchemy engine to create a connection in `await_pg_notifications`. For instance, with options specific to a dialect and unknown to `psycopg2`, the thread dies with the following exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/pipelines/.venv/lib/python3.10/site-packages/dagster_postgres/event_log/event_watcher.py", line 25, in watcher_thread
    for notif in await_pg_notifications(
  File "/opt/pipelines/.venv/lib/python3.10/site-packages/dagster_postgres/pynotify.py", line 106, in await_pg_notifications
    conn = get_conn(conn_string)
  File "/opt/pipelines/.venv/lib/python3.10/site-packages/dagster_postgres/utils.py", line 21, in get_conn
    conn = psycopg2.connect(conn_string)  <----------- HERE
  File "/opt/pipelines/.venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 121, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "/opt/pipelines/.venv/lib/python3.10/site-packages/psycopg2/extensions.py", line 145, in make_dsn
    parse_dsn(dsn)
psycopg2.ProgrammingError: invalid dsn: invalid connection option "..."
```

Would it make sense to replace the `psycopg2.connect` call by a call to the existing utility [`create_pg_connection`](
https://github.com/dagster-io/dagster/blob/e1adadd33cecf01474ec1c232b5b52b68ab1210a/python_modules/libraries/dagster-postgres/dagster_postgres/utils.py#L140)? This would require creating an engine in the thread, but it would ensure that SQLAlchemy is used consistently everywhere a connection is needed.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by peay** [comment]
@rexledesma this is related to https://github.com/dagster-io/dagster/pull/8126 which added support for passing custom schemes with the Helm chart, but unfortunately did not take care of making sure SQLAlchemy is also used for the event watcher.
