### ISSUE TITLE
Protobuf `3.20.2` crashes grpc server. ImportError: symbol not found in flat namespace

### ISSUE THREAD

**Issue by Modjular** [dagster-io/dagster#9728]
### Dagster version

0.14.20

### NOTE
The root problem is `protobuf` and downgrading from `"3.20.2"` to `"3.20.1"` fixed the problem for me. The fix was found in the following thread:
https://github.com/protocolbuffers/protobuf/issues/10571

Anyways, attempting to run `dagster api grpc` causes a crash.

```
(tttk-repo-wDQRTDsS-py3.10) tony@Tonys-MacBook-Pro tttk-repo % dagster api grpc --python-file /Users/tony/Documents/Github/tttk-repo/tttk-repo/repo.py --working-directory /Users/tony/Documents/Github/tttk-repo --host 0.0.0.0 --port 4266
Traceback (most recent call last):
  File "/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/bin/dagster", line 5, in <module>
    from dagster.cli import main
  File "/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/lib/python3.10/site-packages/dagster/__init__.py", line 227, in <module>
    from dagster.core.launcher import DefaultRunLauncher
  File "/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/lib/python3.10/site-packages/dagster/core/launcher/__init__.py", line 1, in <module>
    from .base import (
  File "/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/lib/python3.10/site-packages/dagster/core/launcher/base.py", line 8, in <module>
    from dagster.core.workspace.workspace import IWorkspace
  File "/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/lib/python3.10/site-packages/dagster/core/workspace/__init__.py", line 1, in <module>
    from .context import IWorkspaceProcessContext, WorkspaceProcessContext
  File "/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/lib/python3.10/site-packages/dagster/core/workspace/context.py", line 16, in <module>
    from dagster.core.host_representation import (
  File "/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/lib/python3.10/site-packages/dagster/core/host_representation/__init__.py", line 50, in <module>
    from .repository_location import (
  File "/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/lib/python3.10/site-packages/dagster/core/host_representation/repository_location.py", line 9, in <module>
    from dagster.api.list_repositories import sync_list_repositories_grpc
  File "/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/lib/python3.10/site-packages/dagster/api/list_repositories.py", line 6, in <module>
    from dagster.grpc.types import ListRepositoriesResponse
  File "/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/lib/python3.10/site-packages/dagster/grpc/__init__.py", line 11, in <module>
    from .client import DagsterGrpcClient, ephemeral_grpc_api_client
  File "/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/lib/python3.10/site-packages/dagster/grpc/client.py", line 9, in <module>
    from grpc_health.v1 import health_pb2
  File "/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/lib/python3.10/site-packages/grpc_health/v1/health_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: dlopen(/Users/tony/Library/Caches/pypoetry/virtualenvs/tttk-repo-wDQRTDsS-py3.10/lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (__ZN6google8protobuf15FieldDescriptor12TypeOnceInitEPKS1_)
```

Specifically, `protobuf` seems to be missing a symbol. 

### What did you expect to happen?

I expected the grpc server to spin up without problem

### How to reproduce?

Use `dagster` with `protobuf` version `3.20.2` and attempt to spin up a grpc server

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by yuhan** [comment]
pinning protobuf should help. slack convo: https://dagster.slack.com/archives/C01U954MEER/p1663960677291959?thread_ts=1663881876.905199&cid=C01U954MEER
