### ISSUE TITLE
DagsterInvariantViolationError when creating asset from tutorial

### ISSUE THREAD

**Issue by alefer559** [dagster-io/dagster#9877]
### Dagster version

1.0.11

### What's the issue?

I'm just getting started with dagster and I'm trying to run a simple asset from the tutorial:

import csv
import requests
from dagster import asset

@asset
def cereals():
    response = requests.get("https://docs.dagster.io/assets/cereal.csv")
    lines = response.text.split("\n")
    cereal_rows = [row for row in csv.DictReader(lines)]

    return cereal_rows

I am able run dagit -f cereal.py and go on Dagit but I get the following error: 

![Screenshot 2022-10-04 033407](https://user-images.githubusercontent.com/59588130/193798138-992a150f-e037-43df-9231-4414ad5145d9.png)

I've tried using other examples from the tutorial but the same problem occurs. Any help is appreciated.

### What did you expect to happen?

I expect the asset to run successfully. I am new to this so it is most likely something simple since I can't seem to find anyone else with the same issue. 

### How to reproduce?

dagit -f cereal.py

### Deployment type

Local

### Additional information

Here is the error message from terminal when I run dagster api grpc -p 4000 -f cereal.py

(base) PS C:\Users\boblo\Downloads\test_python\Project_Microscopy> dagster api grpc -p 4000 -f cereal.py
Traceback (most recent call last):
  File "C:\Users\boblo\anaconda3\Scripts\dagster-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\boblo\anaconda3\lib\site-packages\dagster\_cli\__init__.py", line 48, in main
    cli(auto_envvar_prefix=ENV_PREFIX)  # pylint:disable=E1123
  File "C:\Users\boblo\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\boblo\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\boblo\anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\boblo\anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\boblo\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\boblo\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\boblo\anaconda3\lib\site-packages\dagster\_cli\api.py", line 613, in grpc_command
    server = DagsterGrpcServer(
  File "C:\Users\boblo\anaconda3\lib\site-packages\dagster\_grpc\server.py", line 855, in __init__
    self._api_servicer = DagsterApiServer(
  File "C:\Users\boblo\anaconda3\lib\site-packages\dagster\_grpc\server.py", line 230, in __init__
    self._loaded_repositories: Optional[LoadedRepositories] = LoadedRepositories(
  File "C:\Users\boblo\anaconda3\lib\site-packages\dagster\_grpc\server.py", line 104, in __init__
    loadable_targets = get_loadable_targets(
  File "C:\Users\boblo\anaconda3\lib\site-packages\dagster\_grpc\utils.py", line 33, in get_loadable_targets
    else loadable_targets_from_python_file(python_file, working_directory)
  File "C:\Users\boblo\anaconda3\lib\site-packages\dagster\_core\workspace\autodiscovery.py", line 27, in loadable_targets_from_python_file      
    return loadable_targets_from_loaded_module(loaded_module)
  File "C:\Users\boblo\anaconda3\lib\site-packages\dagster\_core\workspace\autodiscovery.py", line 120, in loadable_targets_from_loaded_module   
    raise DagsterInvariantViolationError(
dagster._core.errors.DagsterInvariantViolationError: No repositories, jobs, pipelines, graphs, asset groups, or asset definitions found in "cereal".

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hey @alefer559 - I just tried copy/pasting the code you listed here into a file and running `dagit -f` on it and got it to load successfully.

Is it possible that the file is empty and you put the code in a different file?

**Comment by BluejacketScott** [comment]
Late reply but just ran into this issue and discovered why: pasted hello-dagster.py into a fresh vs instance after the usual 'conda - dance' and simply forgot to save the file before trying it out! - Naturally we cannot hold dagster to blame for being unable to render files that only exist in our imaginations, can we? 
Hope this helps someone late at night and too bleary eyed to pay proper mind and create errors associated with deviating from tutorials - even those we've done thousands of times! Best wishes fellow coders!

**Comment by cmpadden** [comment]
Thank you, closing as the current autodiscovery explicitly loads module-scoped assets and only raises when it finds no Definitions. If someone finds it necessary to re-open the issue, then please let me know.
