### ISSUE TITLE
If dagit is already running, trying to start dagit again on the same port gives a strange error

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#992]
cc @alangenfeld 

```14:17 $ dagit
Watching for file changes...
Serving on http://127.0.0.1:3000
Traceback (most recent call last):
  File "/Users/max/.virtualenvs/dagster/bin/dagit-cli", line 11, in <module>
    load_entry_point('dagit', 'console_scripts', 'dagit-cli')()
  File "/Users/max/dev/dagster/python_modules/dagit/dagit/cli.py", line 129, in main
    cli(obj={})  # pylint:disable=E1120
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/max/dev/dagster/python_modules/dagit/dagit/cli.py", line 104, in ui
    host_dagit_ui(log, log_dir, repository_container, sync, host, port)
  File "/Users/max/dev/dagster/python_modules/dagit/dagit/cli.py", line 123, in host_dagit_ui
    server.serve_forever()
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/gevent/baseserver.py", line 362, in serve_forever
    self.start()
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/gevent/baseserver.py", line 306, in start
    self.init_socket()
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/gevent/pywsgi.py", line 1487, in init_socket
    StreamServer.init_socket(self)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/gevent/server.py", line 146, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/gevent/server.py", line 157, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/Users/max/.virtualenvs/dagster/lib/python3.6/site-packages/gevent/server.py", line 256, in _tcp_listener
    sock.bind(address)
OSError: [Errno 48] Address already in use: ('127.0.0.1', 3000)
on_any_event(self=<watchdog.tricks.AutoRestartTrick object at 0x101933a20>, event=<FileCreatedEvent: src_path='./airline_demo/pipelines.py.e0425ff9610eb5e1be597fa05ba7e595.py'>)
on_any_event(self=<watchdog.tricks.AutoRestartTrick object at 0x101933a20>, event=<FileDeletedEvent: src_path='./airline_demo/pipelines.py.e0425ff9610eb5e1be597fa05ba7e595.py'>)```

**Comment by schrockn** [comment]
other solution here would be to do what jupyter does and assign new ports for you

**Comment by mgasner** [comment]
at the very least, i'd like dagit to bail harder
